### PR TITLE
Replay PR24 - Qt5/5.14.1 with GCCcore-9.3.0 to NESSI/2022.11

### PR DESCRIPTION
**Pull request by trz42**
Added option `--generic` when running `install_software_layer.sh`

Hopefully this fixes the builds which are off for `generic` builds (it wasn't building for `generic` but for the architecture on the host).

### CODE REVIEW

**Comment by trz42** [comment]
Reset `bot:build` label.

**Comment by trz42** [comment]
Once more resetting label `bot:build`

**Comment by trz42** [comment]
Tarball sizes are still off. Trying to keep tmp dirs to inspect parameters passed to eb, make and compilers.

**Comment by trz42** [comment]
- [x] did the builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
  - the tarballs for `x86_64/generic` differ in size $\longrightarrow$ investigate during deployment and approve only the one built on the oldest CPU architecture
- [x] is the PR up-to-date with the target branch `nessi.no-2022.11-dev` in the repository (if not what are the differences)
  - only difference was that changes due to merged [Nextflow PR#34](https://github.com/NorESSI/software-layer/pull/34) were not included (should have no impact on builds)
- [x] are all requested changes sound (checking files changed on GitHub.com)
- [x] is/are the easyconfig/s being built included with the EB version used (if not why not)
- [x] were any changes needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)
  - added support for `generic` architecture and used flag terminator (`--`) when calling `install_software_layer.sh`
  - these changes will be included when pulling in changes from EESSI/software-layer (incl [PR#233](https://github.com/EESSI/software-layer/pull/233))
  - might be good to merge these as soon as possible or all GENERIC builds may be faulty

**Comment by trz42** [comment]
Checklist for deployment
- [x] was at least one tarball for each architecture uploaded
- [x] was at least one tarball for each architecture staged
- [ ] for each architecture **one and only one** tarball was approved (for `generic` the tarball built on the oldest architecture shall be ingested ... lower risk that `generic` build is not really `generic`)
  - the tarballs for `x86_64/generic` differ in size $\longrightarrow$ investigate during deployment and approve the correct build only
- [ ] was at least one tarball for each architecture ingested
- [ ] has the package become available via CernVM-FS for all architectures ingested
  ```
  [EESSI pilot 2022.11] $ ls /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/x86_64/{generic,amd/zen2,intel/[bsc]*}/modules/all/Qt5/5.14.1*
  ```

**Review by poksumdo — APPROVED** [review]
Looks good. Everything ingested once. Despite the build on the oldest architecture for `generic` has been ingested we may wish to rebuild it nevertheless to avoid any potential problems caused by faulty dependencies.

**Pull request merged**
