### PR TITLE
pull in fixes from EESSI/software-layer PR238 and PR239

### PR DESCRIPTION
**Pull request by trz42**
- https://github.com/EESSI/software-layer/pull/238 fixes the issue that `eb` cannot be found
- https://github.com/EESSI/software-layer/pull/239 fixes the issue that packages that already existed are included in a tarball when some file was added to the writable overlay (e.g., a `*.pyc`)

### CODE REVIEW

**Comment by trz42** [comment]
Fails across the board because `module_file_list` was empty / non-existing, hence could be `cat`ed.

**Review by poksumdo — APPROVED** [review]
Looks good (after fixing issue discovered with first batch of tests).

**Comment by trz42** [comment]
Should be in sync with EESSI/main now too. Rerun build jobs to see if it still works.

**Review by poksumdo — APPROVED** [review]
- all GHA succeeded
- builds for `generic` failed, same problem as for #61 (CMake fails at sanity check)
- all other builds succeeded (except for pending jobs on `eX3-NESSI`)

**Pull request merged**
