### PR TITLE
{2023.06}[foss/2022a] add Xvfb

### PR DESCRIPTION
**Pull request by trz42**
Will install the following packages (incl dependencies):

* libxslt/1.1.34-GCCcore-11.3.0 (libxslt-1.1.34-GCCcore-11.3.0.eb)
* pixman/0.40.0-GCCcore-11.3.0 (pixman-0.40.0-GCCcore-11.3.0.eb)
* Meson/0.62.1-GCCcore-11.3.0 (Meson-0.62.1-GCCcore-11.3.0.eb)
* nettle/3.8-GCCcore-11.3.0 (nettle-3.8-GCCcore-11.3.0.eb)
* Mako/1.2.0-GCCcore-11.3.0 (Mako-1.2.0-GCCcore-11.3.0.eb)
* libpng/1.6.37-GCCcore-11.3.0 (libpng-1.6.37-GCCcore-11.3.0.eb)
* libunwind/1.6.2-GCCcore-11.3.0 (libunwind-1.6.2-GCCcore-11.3.0.eb)
* Brotli/1.0.9-GCCcore-11.3.0 (Brotli-1.0.9-GCCcore-11.3.0.eb)
* freetype/2.12.1-GCCcore-11.3.0 (freetype-2.12.1-GCCcore-11.3.0.eb)
* fontconfig/2.14.0-GCCcore-11.3.0 (fontconfig-2.14.0-GCCcore-11.3.0.eb)
* X11/20220504-GCCcore-11.3.0 (X11-20220504-GCCcore-11.3.0.eb)
* libdrm/2.4.110-GCCcore-11.3.0 (libdrm-2.4.110-GCCcore-11.3.0.eb)
* libglvnd/1.4.0-GCCcore-11.3.0 (libglvnd-1.4.0-GCCcore-11.3.0.eb)
* LLVM/14.0.3-GCCcore-11.3.0 (LLVM-14.0.3-GCCcore-11.3.0.eb)
* Mesa/22.0.3-GCCcore-11.3.0 (Mesa-22.0.3-GCCcore-11.3.0.eb)
* Xvfb/21.1.3-GCCcore-11.3.0 (Xvfb-21.1.3-GCCcore-11.3.0.eb)

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:AWS arch:x86_64/generic repo:nessi-2023.06-swl-deb11
bot: build inst:AWS arch:x86_64/amd/zen2 repo:nessi-2023.06-swl-deb11
bot: build inst:eX3 arch:aarch64/generic repo:nessi-2023.06-swl-deb11
bot: build inst:Fram arch:x86_64/intel/broadwell repo:nessi-2023.06-swl-deb10
bot: build inst:AWS arch:x86_64/intel/cascadelake repo:nessi-2023.06-swl-deb11
bot: build inst:AWS arch:x86_64/intel/skylake repo:nessi-2023.06-swl-deb11

**Comment by trz42** [comment]
Build for `aarch64/generic` failed with `deb11` container. Trying `deb10` container.

bot: build inst:eX3 arch:aarch64/generic repo:nessi-2023.06-swl-deb10

**Comment by trz42** [comment]
Checklist for building: 

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
  - we need to include an updated easyconfig for `Xvfb`, see https://github.com/easybuilders/easybuild-easyconfigs/pull/18834
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-intel-cascadelake`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/Xvfb/* \
        aarch64/generic/{software,modules/all}/Xvfb/*
  ```
  **log**
```
-rw-r--r-- 1 cvmfs cvmfs 2169 Oct  8 00:38 aarch64/generic/modules/all/Xvfb/21.1.3-GCCcore-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 2169 Oct  7 23:02 x86_64/amd/zen2/modules/all/Xvfb/21.1.3-GCCcore-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 2168 Oct  7 22:58 x86_64/generic/modules/all/Xvfb/21.1.3-GCCcore-11.3.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 2176 Oct  7 23:14 x86_64/intel/broadwell/modules/all/Xvfb/21.1.3-GCCcore-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 2178 Oct  7 22:51 x86_64/intel/cascadelake/modules/all/Xvfb/21.1.3-GCCcore-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 2181 Oct  7 22:46 x86_64/intel/skylake_avx512/modules/all/Xvfb/21.1.3-GCCcore-11.3.0.lua

aarch64/generic/software/Xvfb/21.1.3-GCCcore-11.3.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  8 00:38 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  8 00:38 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  8 00:33 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  8 00:38 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  8 00:38 lib64 -> lib
dr-xr-xr-x 8 cvmfs cvmfs 4096 Oct  8 00:32 share

x86_64/amd/zen2/software/Xvfb/21.1.3-GCCcore-11.3.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  7 23:02 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  7 23:02 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  7 23:00 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  7 23:02 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  7 23:02 lib64 -> lib
dr-xr-xr-x 8 cvmfs cvmfs 4096 Oct  7 23:00 share

x86_64/generic/software/Xvfb/21.1.3-GCCcore-11.3.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  7 22:58 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  7 22:58 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  7 22:56 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  7 22:58 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  7 22:58 lib64 -> lib
dr-xr-xr-x 8 cvmfs cvmfs 4096 Oct  7 22:55 share

x86_64/intel/broadwell/software/Xvfb/21.1.3-GCCcore-11.3.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  7 23:14 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  7 23:14 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  7 23:10 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  7 23:14 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  7 23:14 lib64 -> lib
dr-xr-xr-x 8 cvmfs cvmfs 4096 Oct  7 23:09 share

x86_64/intel/cascadelake/software/Xvfb/21.1.3-GCCcore-11.3.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  7 22:50 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  7 22:51 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  7 22:49 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  7 22:50 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  7 22:50 lib64 -> lib
dr-xr-xr-x 8 cvmfs cvmfs 4096 Oct  7 22:49 share

x86_64/intel/skylake_avx512/software/Xvfb/21.1.3-GCCcore-11.3.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  7 22:46 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  7 22:46 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  7 22:44 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  7 22:46 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  7 22:46 lib64 -> lib
dr-xr-xr-x 8 cvmfs cvmfs 4096 Oct  7 22:44 share 
```
</details>

**Review by poksumdo — APPROVED** [review]
All good.

**Pull request merged**
