### PR TITLE
{2023.06}[foss/2022a] add NCO/5.1.0

### PR DESCRIPTION
**Pull request by trz42**
Will install the following packages (including dependencies):

* ANTLR/2.7.7-GCCcore-11.3.0-Java-11 (ANTLR-2.7.7-GCCcore-11.3.0-Java-11.eb)
* Bison/3.8.2-GCCcore-11.3.0 (Bison-3.8.2-GCCcore-11.3.0.eb)
* Doxygen/1.9.4-GCCcore-11.3.0 (Doxygen-1.9.4-GCCcore-11.3.0.eb)
* ESMF/8.3.0-foss-2022a (ESMF-8.3.0-foss-2022a.eb)
* HDF5/1.12.2-gompi-2022a (HDF5-1.12.2-gompi-2022a.eb)
* libdap/3.20.11-GCCcore-11.3.0 (libdap-3.20.11-GCCcore-11.3.0.eb)
* libiconv/1.17-GCCcore-11.3.0 (libiconv-1.17-GCCcore-11.3.0.eb)
* libtirpc/1.3.2-GCCcore-11.3.0 (libtirpc-1.3.2-GCCcore-11.3.0.eb)
* NCO/5.1.0-foss-2022a (NCO-5.1.0-foss-2022a.eb)
* netCDF/4.9.0-gompi-2022a (netCDF-4.9.0-gompi-2022a.eb)
* netCDF-C++4/4.3.1-gompi-2022a (netCDF-C++4-4.3.1-gompi-2022a.eb)
* netCDF-Fortran/4.6.0-gompi-2022a (netCDF-Fortran-4.6.0-gompi-2022a.eb)
* PCRE/8.45-GCCcore-11.3.0 (PCRE-8.45-GCCcore-11.3.0.eb)
* Szip/2.1.1-GCCcore-11.3.0 (Szip-2.1.1-GCCcore-11.3.0.eb)
* UDUNITS/2.2.28-GCCcore-11.3.0 (UDUNITS-2.2.28-GCCcore-11.3.0.eb)

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:AWS arch:x86_64/generic repo:nessi-2023.06-swl-deb11
bot: build inst:eX3 arch:x86_64/amd/zen2 repo:nessi-2023.06-swl-deb11
bot: build inst:eX3 arch:aarch64/generic repo:nessi-2023.06-swl-deb11
bot: build inst:Fram arch:x86_64/intel/broadwell repo:nessi-2023.06-swl-deb10
bot: build inst:AWS arch:x86_64/intel/cascadelake repo:nessi-2023.06-swl-deb11
bot: build inst:AWS arch:x86_64/intel/skylake repo:nessi-2023.06-swl-deb11

**Comment by trz42** [comment]
Try using `deb10` container on `eX3`.

bot: build inst:eX3 arch:x86_64/amd/zen2 repo:nessi-2023.06-swl-deb10
bot: build inst:eX3 arch:aarch64/generic repo:nessi-2023.06-swl-deb10

**Comment by trz42** [comment]
Rebuild after using updated CMakeMake easyblock for netCDF.

bot: build inst:AWS arch:x86_64/generic repo:nessi-2023.06-swl-deb11
bot: build inst:eX3 arch:x86_64/amd/zen2 repo:nessi-2023.06-swl-deb11
bot: build inst:eX3 arch:aarch64/generic repo:nessi-2023.06-swl-deb11
bot: build inst:Fram arch:x86_64/intel/broadwell repo:nessi-2023.06-swl-deb10
bot: build inst:AWS arch:x86_64/intel/cascadelake repo:nessi-2023.06-swl-deb11
bot: build inst:AWS arch:x86_64/intel/skylake repo:nessi-2023.06-swl-deb11

**Comment by trz42** [comment]
Small typo in easystack file caused building of netCDF for 2022b.

bot: build inst:AWS arch:x86_64/generic repo:nessi-2023.06-swl-deb11
bot: build inst:eX3 arch:x86_64/amd/zen2 repo:nessi-2023.06-swl-deb11
bot: build inst:eX3 arch:aarch64/generic repo:nessi-2023.06-swl-deb10
bot: build inst:Fram arch:x86_64/intel/broadwell repo:nessi-2023.06-swl-deb10
bot: build inst:AWS arch:x86_64/intel/cascadelake repo:nessi-2023.06-swl-deb11
bot: build inst:AWS arch:x86_64/intel/skylake repo:nessi-2023.06-swl-deb11

**Comment by trz42** [comment]
Checklist for building: 

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)
  - building `netCDF` required an updated `CMakeMake` easyblock (https://github.com/easybuilders/easybuild-easyblocks/pull/3012)

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-intel-cascadelake`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [ ] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/NCO/* \
        aarch64/generic/{software,modules/all}/NCO/*
  ```
  **log**
```
-rw-r--r--. 1 cvmfs cvmfs 1847 Oct  7 07:58 aarch64/generic/modules/all/NCO/5.1.0-foss-2022a.lua
-rw-r--r--. 1 cvmfs cvmfs 1847 Oct  7 06:46 x86_64/amd/zen2/modules/all/NCO/5.1.0-foss-2022a.lua
-rw-r--r--. 1 cvmfs cvmfs 1846 Oct  7 07:02 x86_64/generic/modules/all/NCO/5.1.0-foss-2022a.lua
-rw-rw-r--. 1 cvmfs cvmfs 1854 Oct  7 07:19 x86_64/intel/broadwell/modules/all/NCO/5.1.0-foss-2022a.lua
-rw-r--r--. 1 cvmfs cvmfs 1856 Oct  7 06:54 x86_64/intel/cascadelake/modules/all/NCO/5.1.0-foss-2022a.lua
-rw-r--r--. 1 cvmfs cvmfs 1859 Oct  7 06:54 x86_64/intel/skylake_avx512/modules/all/NCO/5.1.0-foss-2022a.lua

aarch64/generic/software/NCO/5.1.0-foss-2022a:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct  7 07:58 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct  7 07:58 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct  7 07:58 include
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct  7 07:58 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct  7 07:58 lib64 -> lib
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Oct  7 07:58 share

x86_64/amd/zen2/software/NCO/5.1.0-foss-2022a:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct  7 06:46 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct  7 06:46 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct  7 06:46 include
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct  7 06:46 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct  7 06:46 lib64 -> lib
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Oct  7 06:46 share

x86_64/generic/software/NCO/5.1.0-foss-2022a:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct  7 07:02 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct  7 07:02 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct  7 07:02 include
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct  7 07:02 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct  7 07:02 lib64 -> lib
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Oct  7 07:02 share

x86_64/intel/broadwell/software/NCO/5.1.0-foss-2022a:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct  7 07:19 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct  7 07:20 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct  7 07:19 include
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct  7 07:19 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct  7 07:19 lib64 -> lib
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Oct  7 07:19 share

x86_64/intel/cascadelake/software/NCO/5.1.0-foss-2022a:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct  7 06:54 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct  7 06:54 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct  7 06:54 include
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct  7 06:54 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct  7 06:54 lib64 -> lib
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Oct  7 06:54 share

x86_64/intel/skylake_avx512/software/NCO/5.1.0-foss-2022a:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct  7 06:54 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct  7 06:54 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct  7 06:54 include
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct  7 06:54 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct  7 06:54 lib64 -> lib
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Oct  7 06:54 share 
```
</details>

**Review by poksumdo — APPROVED** [review]
Progress :tada:

**Pull request merged**
