### PR TITLE
add OpenSSL/1.1 to NESSI/2023.04

### PR DESCRIPTION
**Pull request by trz42**
This pull request mainly serves as a test to verify if and how OpenSSL/1.1 can be built. OpenSSL/1.1 is a dependency of `CMake-3.20.1-GCCcore-10.3.0.eb` (and potentially others).

1. We just add `OpenSS-1.1.eb` to the easystack file and submit a single job for each bot instance (Fram, AWS and eX3). We expect it to work on AWS and eX3, but not on Fram. Particularly, we expect it to fail in the sanity-check step when a connection to GitHub.com is tried. This should not work out of the box because on Fram, compute nodes are not directly connected to the internet.
2. We try to fix the issue by letting `openssl` use the argument `-proxy` when the environment variable `https_proxy` is defined. We adjust the easyblock `EB_OpenSSL_wrapper` (implemented in `openssl_wrapper.py`) for this and provide the necessary option in the easystack file. We submit jobs on all three bot instances as in (1).
3. If all works well, we open a PR for the updated easyblock and build OpenSSL using that.

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:Fram repo:nessi.no-2023.04 arch:x86_64/generic
bot: build inst:AWS repo:nessi.no-2023.04 arch:x86_64/generic
bot: build inst:eX3 repo:nessi.no-2023.04 arch:aarch64/generic
- received bot command `build inst:Fram repo:nessi.no-2023.04 arch:x86_64/generic` from `trz42` (expanded command format: `build instance:Fram repository:nessi.no-2023.04 architecture:x86_64/generic`)
- received bot command `build inst:AWS repo:nessi.no-2023.04 arch:x86_64/generic` from `trz42` (expanded command format: `build instance:AWS repository:nessi.no-2023.04 architecture:x86_64/generic`)
- received bot command `build inst:eX3 repo:nessi.no-2023.04 arch:aarch64/generic` from `trz42` (expanded command format: `build instance:eX3 repository:nessi.no-2023.04 architecture:aarch64/generic`)

**Comment by trz42** [comment]
bot: build inst:Fram repo:nessi.no-2023.04 arch:x86_64/generic
bot: build inst:AWS repo:nessi.no-2023.04 arch:x86_64/generic
bot: build inst:eX3 repo:nessi.no-2023.04 arch:aarch64/generic
- received bot command `build inst:Fram repo:nessi.no-2023.04 arch:x86_64/generic` from `trz42` (expanded command format: `build instance:Fram repository:nessi.no-2023.04 architecture:x86_64/generic`)
- received bot command `build inst:AWS repo:nessi.no-2023.04 arch:x86_64/generic` from `trz42` (expanded command format: `build instance:AWS repository:nessi.no-2023.04 architecture:x86_64/generic`)
- received bot command `build inst:eX3 repo:nessi.no-2023.04 arch:aarch64/generic` from `trz42` (expanded command format: `build instance:eX3 repository:nessi.no-2023.04 architecture:aarch64/generic`)

**Comment by trz42** [comment]
bot: build inst:Fram repo:nessi.no-2023.04 arch:x86_64/generic
bot: build inst:AWS repo:nessi.no-2023.04 arch:x86_64/generic
bot: build inst:eX3 repo:nessi.no-2023.04 arch:aarch64/generic
- received bot command `build inst:Fram repo:nessi.no-2023.04 arch:x86_64/generic` from `trz42` (expanded command format: `build instance:Fram repository:nessi.no-2023.04 architecture:x86_64/generic`)
- received bot command `build inst:AWS repo:nessi.no-2023.04 arch:x86_64/generic` from `trz42` (expanded command format: `build instance:AWS repository:nessi.no-2023.04 architecture:x86_64/generic`)
- received bot command `build inst:eX3 repo:nessi.no-2023.04 arch:aarch64/generic` from `trz42` (expanded command format: `build instance:eX3 repository:nessi.no-2023.04 architecture:aarch64/generic`)

**Comment by trz42** [comment]
bot: build repo:nessi.no-2023.04
- received bot command `build repo:nessi.no-2023.04` from `trz42` (expanded command format: `build repository:nessi.no-2023.04`)

**Comment by trz42** [comment]
Checklist for building: 

- [x]  did the builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  is the PR up-to-date with the target branch nessi.no-2023.04-dev in the repository (if not what are the differences)
  - [PR#2922](https://github.com/easybuilders/easybuild-easyblocks/pull/2922) may not be final, but the change needed for building OpenSSL/1.1 here will be kept in place one way or the other
  - the temporarily used custom OpenSSL_wrapper easyblock has been moved to to that PR (it's not part of this PR here any longer) 
- [x]  are all requested changes sound (checking files changed on GitHub.com)
- [x]  is/are the easyconfig/s being built included with the EB version used (if not why not)
  - only the easyblock is not yet part (because a PR needed to be used)
- [x]  were any changes needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)
  - yes, see [PR#2922](https://github.com/easybuilders/easybuild-easyblocks/pull/2922)

**Comment by trz42** [comment]
Checklist for deployment/ingestion

- [x] at least one tarball for each architecture has been uploaded
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512`
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] at least one tarball for each architecture has been staged
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512`
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] for each architecture **one and only one** tarball has been approved
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512`
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] for each architecture **one and only one** tarball was ingested
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512` 
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
  **command**
  ```
  ls -l /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/OpenSSL/*
  ls -l /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/aarch64/generic/{software,modules/all}/OpenSSL/*
  ```
  **log**
```
-rw-r--r-- 1 cvmfs cvmfs 1497 Apr 23 14:40 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/amd/zen2/modules/all/OpenSSL/1.1.lua
-rw-r--r-- 1 cvmfs cvmfs 1496 Apr 23 14:45 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/generic/modules/all/OpenSSL/1.1.lua
-rw-rw-r-- 1 cvmfs cvmfs 1504 Apr 23 14:40 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/broadwell/modules/all/OpenSSL/1.1.lua
-rw-r--r-- 1 cvmfs cvmfs 1506 Apr 23 14:44 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/cascadelake/modules/all/OpenSSL/1.1.lua
-rw-r--r-- 1 cvmfs cvmfs 1509 Apr 23 14:44 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/skylake_avx512/modules/all/OpenSSL/1.1.lua

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/amd/zen2/software/OpenSSL/1.1:
total 28
drwxr-xr-x 2 cvmfs cvmfs 4096 Apr 23 14:39 bin
drwxr-xr-x 3 cvmfs cvmfs 4096 Apr 23 14:40 easybuild
drwxr-xr-x 3 cvmfs cvmfs 4096 Apr 23 14:39 include
drwxr-xr-x 4 cvmfs cvmfs 4096 Apr 23 14:39 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Apr 23 14:40 lib64 -> lib
drwxr-xr-x 4 cvmfs cvmfs 4096 Apr 23 14:39 share
drwxr-xr-x 4 cvmfs cvmfs 4096 Apr 23 14:40 ssl

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/generic/software/OpenSSL/1.1:
total 28
drwxr-xr-x 2 cvmfs cvmfs 4096 Apr 23 14:43 bin
drwxr-xr-x 3 cvmfs cvmfs 4096 Apr 23 14:45 easybuild
drwxr-xr-x 3 cvmfs cvmfs 4096 Apr 23 14:43 include
drwxr-xr-x 4 cvmfs cvmfs 4096 Apr 23 14:43 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Apr 23 14:45 lib64 -> lib
drwxr-xr-x 4 cvmfs cvmfs 4096 Apr 23 14:44 share
drwxr-xr-x 4 cvmfs cvmfs 4096 Apr 23 14:45 ssl

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/broadwell/software/OpenSSL/1.1:
total 28
drwxr-xr-x 2 cvmfs cvmfs 4096 Apr 23 14:39 bin
drwxr-xr-x 3 cvmfs cvmfs 4096 Apr 23 14:41 easybuild
drwxr-xr-x 3 cvmfs cvmfs 4096 Apr 23 14:39 include
drwxr-xr-x 4 cvmfs cvmfs 4096 Apr 23 14:39 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Apr 23 14:40 lib64 -> lib
drwxr-xr-x 4 cvmfs cvmfs 4096 Apr 23 14:40 share
drwxr-xr-x 4 cvmfs cvmfs 4096 Apr 23 14:40 ssl

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/cascadelake/software/OpenSSL/1.1:
total 28
drwxr-xr-x 2 cvmfs cvmfs 4096 Apr 23 14:43 bin
drwxr-xr-x 3 cvmfs cvmfs 4096 Apr 23 14:44 easybuild
drwxr-xr-x 3 cvmfs cvmfs 4096 Apr 23 14:43 include
drwxr-xr-x 4 cvmfs cvmfs 4096 Apr 23 14:43 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Apr 23 14:44 lib64 -> lib
drwxr-xr-x 4 cvmfs cvmfs 4096 Apr 23 14:43 share
drwxr-xr-x 4 cvmfs cvmfs 4096 Apr 23 14:44 ssl

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/skylake_avx512/software/OpenSSL/1.1:
total 28
drwxr-xr-x 2 cvmfs cvmfs 4096 Apr 23 14:43 bin
drwxr-xr-x 3 cvmfs cvmfs 4096 Apr 23 14:44 easybuild
drwxr-xr-x 3 cvmfs cvmfs 4096 Apr 23 14:43 include
drwxr-xr-x 4 cvmfs cvmfs 4096 Apr 23 14:43 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Apr 23 14:44 lib64 -> lib
drwxr-xr-x 4 cvmfs cvmfs 4096 Apr 23 14:43 share
drwxr-xr-x 4 cvmfs cvmfs 4096 Apr 23 14:44 ssl

-rw-r--r-- 1 cvmfs cvmfs 1497 Apr 23 14:43 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/aarch64/generic/modules/all/OpenSSL/1.1.lua

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/aarch64/generic/software/OpenSSL/1.1:
total 28
drwxr-xr-x 2 cvmfs cvmfs 4096 Apr 23 14:40 bin
drwxr-xr-x 3 cvmfs cvmfs 4096 Apr 23 14:43 easybuild
drwxr-xr-x 3 cvmfs cvmfs 4096 Apr 23 14:40 include
drwxr-xr-x 4 cvmfs cvmfs 4096 Apr 23 14:40 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Apr 23 14:43 lib64 -> lib
drwxr-xr-x 4 cvmfs cvmfs 4096 Apr 23 14:42 share
drwxr-xr-x 4 cvmfs cvmfs 4096 Apr 23 14:43 ssl 
```

**Review by poksumdo — APPROVED** [review]
All looking good.

**Pull request merged**
