### PR TITLE
{2023.06}[system] EasyBuild V4.9.0

### PR DESCRIPTION
**Pull request by TopRichard**
Adding EasyBuild V4.9.0

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
The build is successful but reports as FAILED!

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
Applied archdetect changes in https://github.com/EESSI/software-layer/pull/397/files BUT ONLY FOR THE SOFTWARE-LAYER , thus skipped the CI changes for now.

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
It builds EasyBuild but fails while trying to install CUDA using the bot, as interactively all is seems good!
Will be troubleshooting in #233

**Comment by TopRichard** [comment]
After #233 was built successfully, the reason behind the failure was the missing CUDA configuration in bot/build.sh.
Will make a PR and merge it, after that will try to build this again.

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb10 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake

**Comment by TopRichard** [comment]
These Builds are before the last commit with the use of archdetect.

**Comment by TopRichard** [comment]
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb10 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by trz42** [comment]
Checklist before deploying: 

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
  - all built successfully
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
  - using the easystack file for eb v4.9.0 to install eb v4.9.0 is weird because we cannot use something that isn't available yet to install something
  - it only works because `load_easybuild_module.sh <VERSION>` not just loads easybuild with the given `<VERSION>` it also attempts to install it if it is not yet available from NESSI
  - here we follow what EESSI has done for `software.eessi.io` 
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
  - uses `--from-pr` because v4.9.0 is the newest version, hence it cannot be included
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)
  - no changes needed

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb10 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by trz42** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - ~`x86_64-intel-cascadelake`~
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/EasyBuild/4.9.0* \
        aarch64/generic/{software,modules/all}/EasyBuild/4.9.0*
  ```
  **log**
```
[@login-5.SAGA ~]$ cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
ls -l \
      x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/EasyBuild/4.9.0* \
      aarch64/generic/{software,modules/all}/EasyBuild/4.9.0*
-rw-r--r-- 1 cvmfs cvmfs 1223 Jan 26 06:06 aarch64/generic/modules/all/EasyBuild/4.9.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 1222 Jan 26 13:00 x86_64/amd/zen2/modules/all/EasyBuild/4.9.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 1221 Jan 26 07:12 x86_64/generic/modules/all/EasyBuild/4.9.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 1229 Jan 26 06:07 x86_64/intel/broadwell/modules/all/EasyBuild/4.9.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 1234 Jan 26 06:07 x86_64/intel/skylake_avx512/modules/all/EasyBuild/4.9.0.lua

aarch64/generic/software/EasyBuild/4.9.0:
total 23
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 26 06:05 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 26 06:05 contrib
dr-xr-xr-x 5 cvmfs cvmfs 4096 Jan 26 06:08 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 26 06:05 etc
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 26 06:05 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jan 26 06:06 lib64 -> lib

x86_64/amd/zen2/software/EasyBuild/4.9.0:
total 23
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 26 13:00 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 26 13:00 contrib
dr-xr-xr-x 5 cvmfs cvmfs 4096 Jan 26 13:01 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 26 13:00 etc
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 26 12:59 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jan 26 13:00 lib64 -> lib

x86_64/generic/software/EasyBuild/4.9.0:
total 23
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 26 07:11 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 26 07:11 contrib
dr-xr-xr-x 5 cvmfs cvmfs 4096 Jan 26 07:13 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 26 07:11 etc
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 26 07:11 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jan 26 07:12 lib64 -> lib

x86_64/intel/broadwell/software/EasyBuild/4.9.0:
total 23
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 26 06:06 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 26 06:06 contrib
dr-xr-xr-x 5 cvmfs cvmfs 4096 Jan 26 06:09 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 26 06:06 etc
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 26 06:06 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jan 26 06:07 lib64 -> lib

x86_64/intel/skylake_avx512/software/EasyBuild/4.9.0:
total 23
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 26 06:06 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 26 06:06 contrib
dr-xr-xr-x 5 cvmfs cvmfs 4096 Jan 26 06:08 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 26 06:06 etc
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 26 06:06 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jan 26 06:07 lib64 -> lib 
```
</details>

**Review by trz42 — APPROVED** [review]
looks good.

**Pull request merged**
