### PR TITLE
Add Qt5/5.14.1 with GCCcore-9.3.0 to NESSI/2022.11

### PR DESCRIPTION
**Pull request by dajon**

### CODE REVIEW

**Review by trz42 — COMMENTED** [review]
Looks good. Building Qt5 is known to be problematic. Will see how it goes.

**Comment by dajon** [comment]
Looks good on Fram and Saga with reasonably sized tarball. I have checked one tarball in more detail. Looks good to me.

**Comment by trz42** [comment]
- [ ] did the builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
  - succeeded for `x86_64/generic`, `x86_64/intel/{broadwell,skylake_avx512,cascadelake}`
  - the tarballs for `x86_64/generic` differ in size
  - did NOT succeed for `x86_64/amd/zen2`, maybe a temporary issue?
  - suggest to retrigger all builds
- [x] is the PR up-to-date with the target branch `nessi.no-2022.11-dev` in the repository (if not what are the differences)
- [x] are all requested changes sound (checking files changed on GitHub.com)
- [x] is/are the easyconfig/s being built included with the EB version used (if not why not)
  - included with EB v4.7.0
- [ ] were any changes needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)
  - no changes were needed

@dajon I suggest to retrigger all builds to try again building for `x86_64/amd/zen2` and also the see if builds for `x86_64/generic` continue to differ in size.

**Comment by trz42** [comment]
- [x] did the builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
  - the tarballs for `x86_64/generic` differ in size $\longrightarrow$ investigate during deployment and approve the correct build only
- [x] is the PR up-to-date with the target branch `nessi.no-2022.11-dev` in the repository (if not what are the differences)
- [x] are all requested changes sound (checking files changed on GitHub.com)
- [x] is/are the easyconfig/s being built included with the EB version used (if not why not)
- [x] were any changes needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Checklist for deployment
- [ ] was at least one tarball for each architecture uploaded
- [ ] was at least one tarball for each architecture staged
- [ ] was at least one tarball for each architecture approved
- [ ] was at least one tarball for each architecture ingested
- [ ] has the package become available via CernVM-FS for all architectures ingested
  ```
  [EESSI pilot 2022.11] $ ls /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/x86_64/{generic,amd/zen2,intel/[bsc]*}/modules/all/Qt5/5.14.1*
  ```

**Comment by trz42** [comment]
The size differences are weird. I think it's best to retrigger a complete build across all architectures.

**Pull request merged**
