### PR TITLE
{2023.06}[GCCcore/12.3.0] Perl-bundle-CPAN V5.36.1

### PR DESCRIPTION
**Pull request by TopRichard**
PLUMED is found on Fram, will try to build it on NESSI:
license  -->https://spdx.org/licenses/GPL-1.0-or-later.html

 ```

2 out of 7 required modules missing:

* groff/1.22.4-GCCcore-12.3.0 (groff-1.22.4-GCCcore-12.3.0.eb)
* Perl-bundle-CPAN/5.36.1-GCCcore-12.3.0 (Perl-bundle-CPAN-5.36.1-GCCcore-12.3.0.eb)
 ```

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb10 arch:x86_64/generic

**Comment by trz42** [comment]
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb10 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
Checklist before starting deployment (setting bot:deploy label):

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by TopRichard** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x]  Check if the _SPDX license identifier_ is provided 
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI for the ingested tarballs have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)

<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; 
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/Perl-bundle-CPAN/5.36.1-GCCcore-12.3.0* \
        aarch64/generic/{software,modules/all}/Perl-bundle-CPAN/5.36.1-GCCcore-12.3.0*
  ```
  **log** 
```
-rw-r--r--. 1 cvmfs cvmfs 36457 May 23 09:05 aarch64/generic/modules/all/Perl-bundle-CPAN/5.36.1-GCCcore-12.3.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 36457 May 23 08:36 x86_64/amd/zen2/modules/all/Perl-bundle-CPAN/5.36.1-GCCcore-12.3.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 36456 May 23 09:57 x86_64/generic/modules/all/Perl-bundle-CPAN/5.36.1-GCCcore-12.3.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 36464 May 23 09:15 x86_64/intel/broadwell/modules/all/Perl-bundle-CPAN/5.36.1-GCCcore-12.3.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 36469 May 23 09:04 x86_64/intel/skylake_avx512/modules/all/Perl-bundle-CPAN/5.36.1-GCCcore-12.3.0.lua

aarch64/generic/software/Perl-bundle-CPAN/5.36.1-GCCcore-12.3.0:
total 19
dr-xr-xr-x. 2 cvmfs cvmfs 4096 May 23 09:03 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May 23 09:08 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May 23 07:57 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 May 23 09:05 lib64 -> lib
dr-xr-xr-x. 4 cvmfs cvmfs 4096 May 23 07:58 man

x86_64/amd/zen2/software/Perl-bundle-CPAN/5.36.1-GCCcore-12.3.0:
total 19
dr-xr-xr-x. 2 cvmfs cvmfs 4096 May 23 08:35 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May 23 08:38 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May 23 07:59 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 May 23 08:36 lib64 -> lib
dr-xr-xr-x. 4 cvmfs cvmfs 4096 May 23 07:59 man

x86_64/generic/software/Perl-bundle-CPAN/5.36.1-GCCcore-12.3.0:
total 19
dr-xr-xr-x. 2 cvmfs cvmfs 4096 May 23 09:56 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May 23 09:58 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May 23 09:23 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 May 23 09:57 lib64 -> lib
dr-xr-xr-x. 4 cvmfs cvmfs 4096 May 23 09:23 man

x86_64/intel/broadwell/software/Perl-bundle-CPAN/5.36.1-GCCcore-12.3.0:
total 19
dr-xr-xr-x. 2 cvmfs cvmfs 4096 May 23 09:13 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May 23 09:18 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May 23 08:01 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 May 23 09:15 lib64 -> lib
dr-xr-xr-x. 4 cvmfs cvmfs 4096 May 23 08:02 man

x86_64/intel/skylake_avx512/software/Perl-bundle-CPAN/5.36.1-GCCcore-12.3.0:
total 19
dr-xr-xr-x. 2 cvmfs cvmfs 4096 May 23 09:02 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May 23 09:06 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May 23 07:59 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 May 23 09:03 lib64 -> lib
dr-xr-xr-x. 4 cvmfs cvmfs 4096 May 23 08:00 man

```
</details>

**Review by justadejavu — APPROVED** [review]
looks good

**Pull request merged**
