### PR TITLE
{2023.06}[foss/2022b] R v4.2.2

### PR DESCRIPTION
**Pull request by trz42**
Sync NESSI with EESSI (PR 452).

SPDX license identifier: `GPL-2.0-or-later`

Missing packages:
```
20 out of 140 required modules missing:

* libxslt/1.1.37-GCCcore-12.2.0 (libxslt-1.1.37-GCCcore-12.2.0.eb)
* nettle/3.8.1-GCCcore-12.2.0 (nettle-3.8.1-GCCcore-12.2.0.eb)
* Xvfb/21.1.6-GCCcore-12.2.0 (Xvfb-21.1.6-GCCcore-12.2.0.eb)
* Tk/8.6.12-GCCcore-12.2.0 (Tk-8.6.12-GCCcore-12.2.0.eb)
* NLopt/2.7.1-GCCcore-12.2.0 (NLopt-2.7.1-GCCcore-12.2.0.eb)
* libogg/1.3.5-GCCcore-12.2.0 (libogg-1.3.5-GCCcore-12.2.0.eb)
* FLAC/1.4.2-GCCcore-12.2.0 (FLAC-1.4.2-GCCcore-12.2.0.eb)
* libvorbis/1.3.7-GCCcore-12.2.0 (libvorbis-1.3.7-GCCcore-12.2.0.eb)
* UDUNITS/2.2.28-GCCcore-12.2.0 (UDUNITS-2.2.28-GCCcore-12.2.0.eb)
* libopus/1.3.1-GCCcore-12.2.0 (libopus-1.3.1-GCCcore-12.2.0.eb)
* GSL/2.7-GCC-12.2.0 (GSL-2.7-GCC-12.2.0.eb)
* LAME/3.100-GCCcore-12.2.0 (LAME-3.100-GCCcore-12.2.0.eb)
* libsndfile/1.2.0-GCCcore-12.2.0 (libsndfile-1.2.0-GCCcore-12.2.0.eb)
* GLPK/5.0-GCCcore-12.2.0 (GLPK-5.0-GCCcore-12.2.0.eb)
* MPFR/4.2.0-GCCcore-12.2.0 (MPFR-4.2.0-GCCcore-12.2.0.eb)
* libgit2/1.5.0-GCCcore-12.2.0 (libgit2-1.5.0-GCCcore-12.2.0.eb)
* jq/1.6-GCCcore-12.2.0 (jq-1.6-GCCcore-12.2.0.eb)
* Abseil/20230125.2-GCCcore-12.2.0 (Abseil-20230125.2-GCCcore-12.2.0.eb)
* protobuf/23.0-GCCcore-12.2.0 (protobuf-23.0-GCCcore-12.2.0.eb)
* R/4.2.2-foss-2022b (R-4.2.2-foss-2022b.eb)
```

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb10 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
Repeat builds for `zen2`

bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2

**Comment by trz42** [comment]
Repeat builds for `zen2` after fixing conflict

bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2

**Comment by trz42** [comment]
Checklist before starting deployment (setting `bot:deploy` label): 

- [x]  Check if the _SPDX license identifier_ is provided 
- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
  - quite a lot of rebuilds needed, often downloads of some package failed
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each staged tarball was a PR for approval/rejection opened
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/R/4.2.2-foss-2022b* \
        aarch64/generic/{software,modules/all}/R/4.2.2-foss-2022b*
  ```
  **log**
```
-rw-r--r--. 1 cvmfs cvmfs 76180 Apr 16 03:59 aarch64/generic/modules/all/R/4.2.2-foss-2022b.lua
-rw-rw-r--. 1 cvmfs cvmfs 76180 Apr 15 22:24 x86_64/amd/zen2/modules/all/R/4.2.2-foss-2022b.lua
-rw-rw-r--. 1 cvmfs cvmfs 76178 Apr 15 19:30 x86_64/generic/modules/all/R/4.2.2-foss-2022b.lua
-rw-rw-r--. 1 cvmfs cvmfs 76194 Apr 16 06:34 x86_64/intel/broadwell/modules/all/R/4.2.2-foss-2022b.lua
-rw-rw-r--. 1 cvmfs cvmfs 76204 Apr 16 01:34 x86_64/intel/skylake_avx512/modules/all/R/4.2.2-foss-2022b.lua

aarch64/generic/software/R/4.2.2-foss-2022b:
total 19
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Apr 15 12:06 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 16 04:14 easybuild
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Apr 15 12:06 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 16 03:31 lib64 -> lib
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 15 12:06 share

x86_64/amd/zen2/software/R/4.2.2-foss-2022b:
total 19
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Apr 15 14:01 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 15 22:31 easybuild
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Apr 15 14:01 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 15 22:07 lib64 -> lib
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 15 14:01 share

x86_64/generic/software/R/4.2.2-foss-2022b:
total 19
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Apr 15 11:29 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 15 19:39 easybuild
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Apr 15 11:29 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 15 19:14 lib64 -> lib
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 15 11:29 share

x86_64/intel/broadwell/software/R/4.2.2-foss-2022b:
total 19
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Apr 15 12:10 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 16 06:55 easybuild
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Apr 15 12:10 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 16 05:59 lib64 -> lib
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 15 12:10 share

x86_64/intel/skylake_avx512/software/R/4.2.2-foss-2022b:
total 19
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Apr 15 12:32 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 16 01:46 easybuild
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Apr 15 12:32 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 16 01:05 lib64 -> lib
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 15 12:32 share 
```
</details>

**Review by poksumdo — APPROVED** [review]
Finally.

**Pull request merged**
