### PR TITLE
{2023.06}[foss/2023a] TensorFlow v2.13.0

### PR DESCRIPTION
**Pull request by trz42**
SPDX license identifier: `Apache-2.0`

Missing modules:

```
20 out of 81 required modules missing:

* Zip/3.0-GCCcore-12.3.0 (Zip-3.0-GCCcore-12.3.0.eb)
* dill/0.3.7-GCCcore-12.3.0 (dill-0.3.7-GCCcore-12.3.0.eb)
* Bazel/6.3.1-GCCcore-12.3.0 (Bazel-6.3.1-GCCcore-12.3.0.eb)
* double-conversion/3.3.0-GCCcore-12.3.0 (double-conversion-3.3.0-GCCcore-12.3.0.eb)
* flatbuffers-python/23.5.26-GCCcore-12.3.0 (flatbuffers-python-23.5.26-GCCcore-12.3.0.eb)
* flatbuffers/23.5.26-GCCcore-12.3.0 (flatbuffers-23.5.26-GCCcore-12.3.0.eb)
* giflib/5.2.1-GCCcore-12.3.0 (giflib-5.2.1-GCCcore-12.3.0.eb)
* pkgconfig/1.5.5-GCCcore-12.3.0-python (pkgconfig-1.5.5-GCCcore-12.3.0-python.eb)
* JsonCpp/1.9.5-GCCcore-12.3.0 (JsonCpp-1.9.5-GCCcore-12.3.0.eb)
* NASM/2.16.01-GCCcore-12.3.0 (NASM-2.16.01-GCCcore-12.3.0.eb)
* libjpeg-turbo/2.1.5.1-GCCcore-12.3.0 (libjpeg-turbo-2.1.5.1-GCCcore-12.3.0.eb)
* nsync/1.26.0-GCCcore-12.3.0 (nsync-1.26.0-GCCcore-12.3.0.eb)
* mpi4py/3.1.4-gompi-2023a (mpi4py-3.1.4-gompi-2023a.eb)
* h5py/3.9.0-foss-2023a (h5py-3.9.0-foss-2023a.eb)
* snappy/1.1.10-GCCcore-12.3.0 (snappy-1.1.10-GCCcore-12.3.0.eb)
* Abseil/20230125.3-GCCcore-12.3.0 (Abseil-20230125.3-GCCcore-12.3.0.eb)
* protobuf/24.0-GCCcore-12.3.0 (protobuf-24.0-GCCcore-12.3.0.eb)
* protobuf-python/4.24.0-GCCcore-12.3.0 (protobuf-python-4.24.0-GCCcore-12.3.0.eb)
* RE2/2023-08-01-GCCcore-12.3.0 (RE2-2023-08-01-GCCcore-12.3.0.eb)
* TensorFlow/2.13.0-foss-2023a (TensorFlow-2.13.0-foss-2023a.eb)
```

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by trz42** [comment]
bot: build inst:eX3 repo:nessi-2023.06-swl-deb10 arch:aarch64/generic

**Comment by trz42** [comment]
Checklist before starting deployment (setting `bot:deploy` label): 

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)
  - needed to use `deb10` container on `eX3` for `aarch64/generic`

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each staged tarball was a PR for approval/rejection opened
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/TensorFlow/2.13.0* \
        aarch64/generic/{software,modules/all}/TensorFlow/2.13.0*
  ```
  **log**
```
-rw-r--r-- 1 cvmfs cvmfs 5438 Feb  3 00:55 aarch64/generic/modules/all/TensorFlow/2.13.0-foss-2023a.lua
-rw-rw-r-- 1 cvmfs cvmfs 5438 Feb  3 00:17 x86_64/amd/zen2/modules/all/TensorFlow/2.13.0-foss-2023a.lua
-rw-rw-r-- 1 cvmfs cvmfs 5437 Feb  3 00:34 x86_64/generic/modules/all/TensorFlow/2.13.0-foss-2023a.lua
-rw-rw-r-- 1 cvmfs cvmfs 5445 Feb  3 04:27 x86_64/intel/broadwell/modules/all/TensorFlow/2.13.0-foss-2023a.lua
-rw-rw-r-- 1 cvmfs cvmfs 5450 Feb  3 03:01 x86_64/intel/skylake_avx512/modules/all/TensorFlow/2.13.0-foss-2023a.lua

aarch64/generic/software/TensorFlow/2.13.0-foss-2023a:
total 14
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  3 00:46 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  3 01:01 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  2 21:19 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Feb  3 00:46 lib64 -> lib

x86_64/amd/zen2/software/TensorFlow/2.13.0-foss-2023a:
total 14
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  3 00:13 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  3 00:20 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  2 20:38 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Feb  3 00:13 lib64 -> lib

x86_64/generic/software/TensorFlow/2.13.0-foss-2023a:
total 14
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  3 00:27 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  3 00:39 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  2 20:36 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Feb  3 00:27 lib64 -> lib

x86_64/intel/broadwell/software/TensorFlow/2.13.0-foss-2023a:
total 14
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  3 04:20 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  3 04:34 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  2 20:45 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Feb  3 04:20 lib64 -> lib

x86_64/intel/skylake_avx512/software/TensorFlow/2.13.0-foss-2023a:
total 14
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  3 02:53 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  3 03:06 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  2 20:44 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Feb  3 02:53 lib64 -> lib 
```
</details>

**Review by poksumdo — APPROVED** [review]
Done. :tada:

**Pull request merged**
