### PR TITLE
{2023.06}[system] GPAW-setups V24.1.0

### PR DESCRIPTION
**Pull request by TopRichard**
Required for CI tests in #292 
 license --> https://spdx.org/licenses/GPL-3.0-or-later.html

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:zen2

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
Checklist before starting deployment (setting bot:deploy label):

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by TopRichard** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  -  `aarch64-generic`

Checklist for deployment/ingestion
- [x]  Check if the _SPDX license identifier_ is provided 
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [] encountered issues in the ingestion, likely related to troubles interacting with GitHub via PyGithub … 
- [x] all tests in the CI for the ingested tarballs have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)

<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; 
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/GPAW-setups/24.1.0.* \
        aarch64/generic/{software,modules/all}/GPAW-setups/24.1.0*
  ```
  **log** (note, output includes `-bare` modules)
```
-rw-r--r-- 1 cvmfs cvmfs 1503 Apr  3 09:38 aarch64/generic/modules/all/GPAW-setups/24.1.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1503 Apr  3 10:39 x86_64/amd/zen2/modules/all/GPAW-setups/24.1.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 1502 Apr  3 19:57 x86_64/generic/modules/all/GPAW-setups/24.1.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 1510 Apr  3 08:39 x86_64/intel/broadwell/modules/all/GPAW-setups/24.1.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 1515 Apr  3 08:39 x86_64/intel/skylake_avx512/modules/all/GPAW-setups/24.1.0.lua

 The log below shows only some files/architecture as the list is too long
 
aarch64/generic/software/GPAW-setups/24.1.0:
total 52531
-r--r--r-- 1 cvmfs cvmfs  17824 Apr 19  2010 Ag.11.dzp.basis.gz
-r--r--r-- 1 cvmfs cvmfs 138218 Apr 13  2011 Ag.11.GLLBSC.gz
-r--r--r-- 1 cvmfs cvmfs 131465 Jun 17  2008 Ag.11.LDA.gz
-r--r--r-- 1 cvmfs cvmfs 131492 Jun 17  2008 Ag.11.PBE.gz
-r--r--r-- 1 cvmfs cvmfs 131645 Apr 19  2010 Ag.11.revPBE.gz
-r--r--r-- 1 cvmfs cvmfs 131527 Jun 17  2008 Ag.11.RPBE.gz
-r--r--r-- 1 cvmfs cvmfs  32404 Mar 31  2014 Ag.dzp.basis.gz
-r--r--r-- 1 cvmfs cvmfs 165187 Oct 26  2012 Ag.GLLBSC.gz
-r--r--r-- 1 cvmfs cvmfs 150974 Oct 26  2012 Ag.LDA.gz
-r--r--r-- 1 cvmfs cvmfs 150887 Oct 26  2012 Ag.PBE.gz

x86_64/amd/zen2/software/GPAW-setups/24.1.0:
total 52531
-r--r--r-- 1 cvmfs cvmfs  17824 Apr 19  2010 Ag.11.dzp.basis.gz
-r--r--r-- 1 cvmfs cvmfs 138218 Apr 13  2011 Ag.11.GLLBSC.gz
-r--r--r-- 1 cvmfs cvmfs 131465 Jun 17  2008 Ag.11.LDA.gz
-r--r--r-- 1 cvmfs cvmfs 131492 Jun 17  2008 Ag.11.PBE.gz
-r--r--r-- 1 cvmfs cvmfs 131645 Apr 19  2010 Ag.11.revPBE.gz
-r--r--r-- 1 cvmfs cvmfs 131527 Jun 17  2008 Ag.11.RPBE.gz
-r--r--r-- 1 cvmfs cvmfs  32404 Mar 31  2014 Ag.dzp.basis.gz
-r--r--r-- 1 cvmfs cvmfs 165187 Oct 26  2012 Ag.GLLBSC.gz
-r--r--r-- 1 cvmfs cvmfs 150974 Oct 26  2012 Ag.LDA.gz
-r--r--r-- 1 cvmfs cvmfs 150887 Oct 26  2012 Ag.PBE.gz

x86_64/generic/software/GPAW-setups/24.1.0:
total 52531
-r--r--r-- 1 cvmfs cvmfs  17824 Apr 19  2010 Ag.11.dzp.basis.gz
-r--r--r-- 1 cvmfs cvmfs 138218 Apr 13  2011 Ag.11.GLLBSC.gz
-r--r--r-- 1 cvmfs cvmfs 131465 Jun 17  2008 Ag.11.LDA.gz
-r--r--r-- 1 cvmfs cvmfs 131492 Jun 17  2008 Ag.11.PBE.gz
-r--r--r-- 1 cvmfs cvmfs 131645 Apr 19  2010 Ag.11.revPBE.gz
-r--r--r-- 1 cvmfs cvmfs 131527 Jun 17  2008 Ag.11.RPBE.gz
-r--r--r-- 1 cvmfs cvmfs  32404 Mar 31  2014 Ag.dzp.basis.gz
-r--r--r-- 1 cvmfs cvmfs 165187 Oct 26  2012 Ag.GLLBSC.gz
-r--r--r-- 1 cvmfs cvmfs 150974 Oct 26  2012 Ag.LDA.gz
-r--r--r-- 1 cvmfs cvmfs 150887 Oct 26  2012 Ag.PBE.gz

x86_64/intel/broadwell/software/GPAW-setups/24.1.0:
total 52531
-r--r--r-- 1 cvmfs cvmfs  17824 Apr 19  2010 Ag.11.dzp.basis.gz
-r--r--r-- 1 cvmfs cvmfs 138218 Apr 13  2011 Ag.11.GLLBSC.gz
-r--r--r-- 1 cvmfs cvmfs 131465 Jun 17  2008 Ag.11.LDA.gz
-r--r--r-- 1 cvmfs cvmfs 131492 Jun 17  2008 Ag.11.PBE.gz
-r--r--r-- 1 cvmfs cvmfs 131645 Apr 19  2010 Ag.11.revPBE.gz
-r--r--r-- 1 cvmfs cvmfs 131527 Jun 17  2008 Ag.11.RPBE.gz
-r--r--r-- 1 cvmfs cvmfs  32404 Mar 31  2014 Ag.dzp.basis.gz
-r--r--r-- 1 cvmfs cvmfs 165187 Oct 26  2012 Ag.GLLBSC.gz
-r--r--r-- 1 cvmfs cvmfs 150974 Oct 26  2012 Ag.LDA.gz
-r--r--r-- 1 cvmfs cvmfs 150887 Oct 26  2012 Ag.PBE.gz

x86_64/intel/skylake_avx512/software/GPAW-setups/24.1.0:
total 52531
-r--r--r-- 1 cvmfs cvmfs  17824 Apr 19  2010 Ag.11.dzp.basis.gz
-r--r--r-- 1 cvmfs cvmfs 138218 Apr 13  2011 Ag.11.GLLBSC.gz
-r--r--r-- 1 cvmfs cvmfs 131465 Jun 17  2008 Ag.11.LDA.gz
-r--r--r-- 1 cvmfs cvmfs 131492 Jun 17  2008 Ag.11.PBE.gz
-r--r--r-- 1 cvmfs cvmfs 131645 Apr 19  2010 Ag.11.revPBE.gz
-r--r--r-- 1 cvmfs cvmfs 131527 Jun 17  2008 Ag.11.RPBE.gz
-r--r--r-- 1 cvmfs cvmfs  32404 Mar 31  2014 Ag.dzp.basis.gz
-r--r--r-- 1 cvmfs cvmfs 165187 Oct 26  2012 Ag.GLLBSC.gz
-r--r--r-- 1 cvmfs cvmfs 150974 Oct 26  2012 Ag.LDA.gz
-r--r--r-- 1 cvmfs cvmfs 150887 Oct 26  2012 Ag.PBE.gz

```
</details>

**Review by justadejavu — APPROVED** [review]
lgtm

**Pull request merged**
