### PR TITLE
{2023.06}[foss/2022a] ASE V3.22.1

### PR DESCRIPTION
**Pull request by TopRichard**
Trying to build ASE/3.22.1-foss/2022a as a step forward for getting closer to the current available HPC software stack.
License: https://spdx.org/licenses/LGPL-3.0-only.html
Will install the following packages:
```
*ASE/3.22.1-foss-2022a.lua
*cppy/1.2.1-GCCcore-11.3.0.lua
*Flask/2.2.2-GCCcore-11.3.0.lua
*matplotlib/3.5.2-foss-2022a.lua
*Qhull/2020.2-GCCcore-11.3.0.lua
*spglib-python/2.0.0-foss-2022a.lua
*Tkinter/3.10.4-GCCcore-11.3.0.lua
```

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS repo nessi-2023.06-swl-deb10 arch:zen2

**Comment by TopRichard** [comment]
bot: build inst:AWS repo nessi-2023.06-swl-deb10 arch:x86_64/amd/zen2

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi-2023.06-swl-deb10 arch:zen2

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi-2023.06-swl-deb10 arch:zen2

**Comment by TopRichard** [comment]
Built Pillow/9.1.1/GCCcore-11.3.0 separately, check : #202

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS repo:nessi-2023.06-swl-deb10 arch:zen2
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb10 arch:x86_64/intel/broadwell
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/cascadelake
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake

**Comment by TopRichard** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/cascadelake

**Comment by TopRichard** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb10 arch:x86_64/intel/cascadelake

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake 
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb10 arch:zen2

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2

**Comment by TopRichard** [comment]
Checklist for building ASE V3.22.1 : 

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)
      - Excluded aarch64 and Cascadelake regardless of the build status.

**Comment by TopRichard** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [] encountered issues in the ingestion, likely related to troubles interacting with GitHub via PyGithub … 
- [x] all tests in the CI for the ingested tarballs have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] the PR has a license info for the ingested software
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)

<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; 
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/ASE/3.22.1-foss-2022a* \
        aarch64/generic/{software,modules/all}/ASE/3.22.1-foss-2022a*

-rw-rw-r--. 1 cvmfs cvmfs 2414 Oct 18 18:17 x86_64/amd/zen2/modules/all/ASE/3.22.1-foss-2022a.lua
-rw-rw-r--. 1 cvmfs cvmfs 2413 Oct 18 13:36 x86_64/generic/modules/all/ASE/3.22.1-foss-2022a.lua
-rw-rw-r--. 1 cvmfs cvmfs 2421 Oct 18 13:26 x86_64/intel/broadwell/modules/all/ASE/3.22.1-foss-2022a.lua
-rw-rw-r--. 1 cvmfs cvmfs 2426 Oct 18 13:34 x86_64/intel/skylake_avx512/modules/all/ASE/3.22.1-foss-2022a.lua

x86_64/amd/zen2/software/ASE/3.22.1-foss-2022a:
total 14
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct 18 18:17 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 18 18:17 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 18 18:17 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct 18 18:17 lib64 -> lib

x86_64/generic/software/ASE/3.22.1-foss-2022a:
total 14
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct 18 13:36 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 18 13:36 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 18 13:36 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct 18 13:36 lib64 -> lib

x86_64/intel/broadwell/software/ASE/3.22.1-foss-2022a:
total 14
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct 18 13:26 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 18 13:26 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 18 13:25 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct 18 13:26 lib64 -> lib

x86_64/intel/skylake_avx512/software/ASE/3.22.1-foss-2022a:
total 14
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct 18 13:33 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 18 13:34 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 18 13:33 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct 18 13:33 lib64 -> lib


```
</details>

**Review by justadejavu — APPROVED** [review]
Okay

**Pull request merged**
