### PR TITLE
{2023.06}[foss/2023a] SciPy-bundle/2023.07

### PR DESCRIPTION
**Pull request by trz42**
Add SciPy-bundle/2023.07.

Missing modules:

```
21 out of 40 required modules missing:

* expat/2.5.0-GCCcore-12.3.0 (expat-2.5.0-GCCcore-12.3.0.eb)
* Ninja/1.11.1-GCCcore-12.3.0 (Ninja-1.11.1-GCCcore-12.3.0.eb)
* hatchling/1.18.0-GCCcore-12.3.0 (hatchling-1.18.0-GCCcore-12.3.0.eb)
* scikit-build/0.17.6-GCCcore-12.3.0 (scikit-build-0.17.6-GCCcore-12.3.0.eb)
* Eigen/3.4.0-GCCcore-12.3.0 (Eigen-3.4.0-GCCcore-12.3.0.eb)
* Meson/1.1.1-GCCcore-12.3.0 (Meson-1.1.1-GCCcore-12.3.0.eb)
* git/2.41.0-GCCcore-12.3.0-nodocs (git-2.41.0-GCCcore-12.3.0-nodocs.eb)
* flit/3.9.0-GCCcore-12.3.0 (flit-3.9.0-GCCcore-12.3.0.eb)
* Catch2/2.13.9-GCCcore-12.3.0 (Catch2-2.13.9-GCCcore-12.3.0.eb)
* virtualenv/20.23.1-GCCcore-12.3.0 (virtualenv-20.23.1-GCCcore-12.3.0.eb)
* setuptools-rust/1.6.0-GCCcore-12.3.0 (setuptools-rust-1.6.0-GCCcore-12.3.0.eb)
* patchelf/0.18.0-GCCcore-12.3.0 (patchelf-0.18.0-GCCcore-12.3.0.eb)
* Rust/1.70.0-GCCcore-12.3.0 (Rust-1.70.0-GCCcore-12.3.0.eb)
* cffi/1.15.1-GCCcore-12.3.0 (cffi-1.15.1-GCCcore-12.3.0.eb)
* cryptography/41.0.1-GCCcore-12.3.0 (cryptography-41.0.1-GCCcore-12.3.0.eb)
* poetry/1.5.1-GCCcore-12.3.0 (poetry-1.5.1-GCCcore-12.3.0.eb)
* Python-bundle-PyPI/2023.06-GCCcore-12.3.0 (Python-bundle-PyPI-2023.06-GCCcore-12.3.0.eb)
* pybind11/2.11.1-GCCcore-12.3.0 (pybind11-2.11.1-GCCcore-12.3.0.eb)
* gfbf/2023a (gfbf-2023a.eb)
* hypothesis/6.82.0-GCCcore-12.3.0 (hypothesis-6.82.0-GCCcore-12.3.0.eb)
* SciPy-bundle/2023.07-gfbf-2023a (SciPy-bundle-2023.07-gfbf-2023a.eb)
```

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/generic
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:eX3 repo:nessi-2023.06-swl-deb10 arch:aarch64/generic

**Comment by trz42** [comment]
bot: show_config

**Comment by trz42** [comment]
bot: show_config

**Comment by trz42** [comment]
Launch two more jobs just in case the other fails.

bot: build inst:eX3 repo:nessi-2023.06-swl-deb10 arch:aarch64/generic
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by trz42** [comment]
Checklist before starting deployment: 

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by TopRichard** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI for the ingested tarballs have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)

<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; 
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/SciPy-bundle/2023** \
        aarch64/generic/{software,modules/all}/SciPy-bundle/2023*
  ```
  **log** (note, output includes `-bare` modules)
```
-rw-r--r-- 1 cvmfs cvmfs 2430 Jan 29 02:13 aarch64/generic/modules/all/SciPy-bundle/2023.07-gfbf-2023a.lua
-rw-r--r-- 1 cvmfs cvmfs 2430 Jan 28 18:31 x86_64/amd/zen2/modules/all/SciPy-bundle/2023.07-gfbf-2023a.lua
-rw-rw-r-- 1 cvmfs cvmfs 2429 Jan 28 17:23 x86_64/generic/modules/all/SciPy-bundle/2023.07-gfbf-2023a.lua
-rw-rw-r-- 1 cvmfs cvmfs 2437 Jan 28 18:54 x86_64/intel/broadwell/modules/all/SciPy-bundle/2023.07-gfbf-2023a.lua
-rw-rw-r-- 1 cvmfs cvmfs 2442 Jan 28 18:43 x86_64/intel/skylake_avx512/modules/all/SciPy-bundle/2023.07-gfbf-2023a.lua

aarch64/generic/software/SciPy-bundle/2023.07-gfbf-2023a:
total 14
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 28 23:12 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 29 02:14 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 28 23:10 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jan 29 02:12 lib64 -> lib

x86_64/amd/zen2/software/SciPy-bundle/2023.07-gfbf-2023a:
total 14
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 28 17:44 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 28 18:31 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 28 17:44 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jan 28 18:31 lib64 -> lib

x86_64/generic/software/SciPy-bundle/2023.07-gfbf-2023a:
total 14
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 28 16:44 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 28 17:24 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 28 16:43 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jan 28 17:23 lib64 -> lib

x86_64/intel/broadwell/software/SciPy-bundle/2023.07-gfbf-2023a:
total 14
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 28 17:41 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 28 18:55 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 28 17:40 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jan 28 18:53 lib64 -> lib

x86_64/intel/skylake_avx512/software/SciPy-bundle/2023.07-gfbf-2023a:
total 14
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 28 17:24 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 28 18:44 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 28 17:23 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jan 28 18:42 lib64 -> lib

```
</details>

**Review by justadejavu — APPROVED** [review]
Looks good

**Pull request merged**
