### PR TITLE
{2023.06}[foss/2023a] MetalWalls V21.06.1

### PR DESCRIPTION
**Pull request by TopRichard**
Lic --> MIT
```
missing packages:

f90wrap/0.2.13-foss-2023a
Meson/1.3.1-GCCcore-12.3.0
meson-python/0.15.0-GCCcore-12.3.0
MetalWalls/21.06.1-foss-2023a
```

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
Checklist before starting deployment (setting bot:deploy label):

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by TopRichard** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x]  Check if the _SPDX license identifier_ is provided 
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI for the ingested tarballs have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)

<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; 
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/MetalWalls/21.06.1-foss-2023a* \
        aarch64/generic/{software,modules/all}/MetalWalls/21.06.1-foss-2023a*
  ```
  **log** 
```
-rw-rw-r--. 1 cvmfs cvmfs 1600 Jul 19 13:38 aarch64/generic/modules/all/MetalWalls/21.06.1-foss-2023a.lua
-rw-rw-r--. 1 cvmfs cvmfs 1600 Jul 19 13:41 x86_64/amd/zen2/modules/all/MetalWalls/21.06.1-foss-2023a.lua
-rw-rw-r--. 1 cvmfs cvmfs 1599 Jul 19 13:43 x86_64/generic/modules/all/MetalWalls/21.06.1-foss-2023a.lua
-rw-rw-r--. 1 cvmfs cvmfs 1607 Jul 19 13:53 x86_64/intel/broadwell/modules/all/MetalWalls/21.06.1-foss-2023a.lua
-rw-rw-r--. 1 cvmfs cvmfs 1612 Jul 19 14:02 x86_64/intel/skylake_avx512/modules/all/MetalWalls/21.06.1-foss-2023a.lua

aarch64/generic/software/MetalWalls/21.06.1-foss-2023a:
total 14
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 19 13:38 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 19 13:38 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 19 13:37 python

x86_64/amd/zen2/software/MetalWalls/21.06.1-foss-2023a:
total 14
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 19 13:41 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 19 13:41 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 19 13:40 python

x86_64/generic/software/MetalWalls/21.06.1-foss-2023a:
total 14
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 19 13:43 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 19 13:43 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 19 13:43 python

x86_64/intel/broadwell/software/MetalWalls/21.06.1-foss-2023a:
total 14
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 19 13:53 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 19 13:53 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 19 13:53 python

x86_64/intel/skylake_avx512/software/MetalWalls/21.06.1-foss-2023a:
total 14
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 19 14:02 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 19 14:02 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 19 14:02 python
```
</details>

**Review by justadejavu — APPROVED** [review]
lgtm

**Pull request merged**
