### PR TITLE
{23.06}[foss/2022a] Python/3.10.4

### PR DESCRIPTION
**Pull request by trz42**
Secondary objective is to update lmod cache for foss/2021b and foss/2022b.

### CODE REVIEW

**Comment by trz42** [comment]
bot: build repo:nessi.no-2023.06-software inst:eX3 arch:aarch64/generic
bot: build repo:nessi.no-2023.06-software inst:eX3 arch:zen2
bot: build repo:nessi.no-2023.06-software inst:Fram arch:broadwell
bot: build repo:nessi.no-2023.06-software inst:AWS arch:x86_64/generic
bot: build repo:nessi.no-2023.06-software inst:AWS arch:cascade
bot: build repo:nessi.no-2023.06-software inst:AWS arch:skylake

**Comment by trz42** [comment]
Checklist for building: 

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-intel-cascadelake`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/Python/3.10.4-GCCcore-11.3.0* \
        aarch64/generic/{software,modules/all}/Python/3.10.4-GCCcore-11.3.0*
  ```
  **log** (note, output includes `-bare` modules)
```
-rw-r--r--. 1 cvmfs cvmfs  1673 Jun 28 20:38 aarch64/generic/modules/all/Python/3.10.4-GCCcore-11.3.0-bare.lua
-rw-r--r--. 1 cvmfs cvmfs 10831 Jun 30 22:34 aarch64/generic/modules/all/Python/3.10.4-GCCcore-11.3.0.lua
-rw-r--r--. 1 cvmfs cvmfs  1673 Jun 28 19:54 x86_64/amd/zen2/modules/all/Python/3.10.4-GCCcore-11.3.0-bare.lua
-rw-r--r--. 1 cvmfs cvmfs 10831 Jun 30 21:46 x86_64/amd/zen2/modules/all/Python/3.10.4-GCCcore-11.3.0.lua
-rw-r--r--. 1 cvmfs cvmfs  1672 Jun 28 20:25 x86_64/generic/modules/all/Python/3.10.4-GCCcore-11.3.0-bare.lua
-rw-r--r--. 1 cvmfs cvmfs 10830 Jun 30 22:52 x86_64/generic/modules/all/Python/3.10.4-GCCcore-11.3.0.lua
-rw-rw-r--. 1 cvmfs cvmfs  1680 Jun 28 20:01 x86_64/intel/broadwell/modules/all/Python/3.10.4-GCCcore-11.3.0-bare.lua
-rw-rw-r--. 1 cvmfs cvmfs 10838 Jun 30 21:34 x86_64/intel/broadwell/modules/all/Python/3.10.4-GCCcore-11.3.0.lua
-rw-r--r--. 1 cvmfs cvmfs  1682 Jun 28 23:53 x86_64/intel/cascadelake/modules/all/Python/3.10.4-GCCcore-11.3.0-bare.lua
-rw-r--r--. 1 cvmfs cvmfs 10840 Jun 30 21:58 x86_64/intel/cascadelake/modules/all/Python/3.10.4-GCCcore-11.3.0.lua
-rw-r--r--. 1 cvmfs cvmfs  1685 Jun 28 20:07 x86_64/intel/skylake_avx512/modules/all/Python/3.10.4-GCCcore-11.3.0-bare.lua
-rw-r--r--. 1 cvmfs cvmfs 10843 Jun 30 22:13 x86_64/intel/skylake_avx512/modules/all/Python/3.10.4-GCCcore-11.3.0.lua

aarch64/generic/software/Python/3.10.4-GCCcore-11.3.0:
total 23
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 30 22:24 bin
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 30 22:35 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 30 21:52 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 30 21:52 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 30 22:25 lib64 -> lib
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 30 21:52 share

aarch64/generic/software/Python/3.10.4-GCCcore-11.3.0-bare:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 20:37 bin
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 20:38 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 20:37 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 20:37 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 28 20:37 lib64 -> lib
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 20:37 share

x86_64/amd/zen2/software/Python/3.10.4-GCCcore-11.3.0:
total 23
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 30 21:42 bin
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 30 21:47 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 30 21:26 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 30 21:26 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 30 21:42 lib64 -> lib
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 30 21:26 share

x86_64/amd/zen2/software/Python/3.10.4-GCCcore-11.3.0-bare:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 19:54 bin
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 19:54 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 19:54 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 19:54 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 28 19:54 lib64 -> lib
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 19:54 share

x86_64/generic/software/Python/3.10.4-GCCcore-11.3.0:
total 23
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 30 22:45 bin
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 30 22:53 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 30 22:22 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 30 22:22 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 30 22:46 lib64 -> lib
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 30 22:22 share

x86_64/generic/software/Python/3.10.4-GCCcore-11.3.0-bare:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 20:25 bin
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 20:26 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 20:25 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 20:25 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 28 20:25 lib64 -> lib
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 20:25 share

x86_64/intel/broadwell/software/Python/3.10.4-GCCcore-11.3.0:
total 23
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 30 21:28 bin
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 30 21:35 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 30 21:06 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 30 21:06 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 30 21:28 lib64 -> lib
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 30 21:06 share

x86_64/intel/broadwell/software/Python/3.10.4-GCCcore-11.3.0-bare:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 20:01 bin
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 20:01 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 20:01 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 20:01 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 28 20:01 lib64 -> lib
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 20:01 share

x86_64/intel/cascadelake/software/Python/3.10.4-GCCcore-11.3.0:
total 23
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 30 21:53 bin
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 30 21:58 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 30 21:38 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 30 21:38 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 30 21:53 lib64 -> lib
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 30 21:38 share

x86_64/intel/cascadelake/software/Python/3.10.4-GCCcore-11.3.0-bare:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 23:53 bin
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 23:53 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 23:53 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 23:53 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 28 23:53 lib64 -> lib
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 23:53 share

x86_64/intel/skylake_avx512/software/Python/3.10.4-GCCcore-11.3.0:
total 23
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 30 22:08 bin
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 30 22:14 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 30 21:51 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 30 21:51 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 30 22:09 lib64 -> lib
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 30 21:51 share

x86_64/intel/skylake_avx512/software/Python/3.10.4-GCCcore-11.3.0-bare:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 20:07 bin
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 20:07 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 20:07 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 20:07 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 28 20:07 lib64 -> lib
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 20:07 share 
```
</details>

**Review by poksumdo — APPROVED** [review]
Worked out nicely.

**Pull request merged**
