### PR TITLE
{2023.06}[foss/2023b] SciPy-bundle/2023.11, netCDF/4.9.2 and matplotlib/3.8.2

### PR DESCRIPTION
**Pull request by trz42**
SPDX license identifiers:
- SciPy-bundle/2023.11 $\rightarrow$ `BSD-3-Clause` for SciPy
- netCDF/4.9.2 $\rightarrow$ `NetCDF` (https://www.unidata.ucar.edu/software/netcdf/copyright.html)
- matplotlib/3.8.2 $\rightarrow$ custom (https://github.com/matplotlib/matplotlib/blob/main/LICENSE/LICENSE)

Missing modules:
```
44 out of 65 required modules missing:

* libpng/1.6.40-GCCcore-13.2.0 (libpng-1.6.40-GCCcore-13.2.0.eb)
* expat/2.5.0-GCCcore-13.2.0 (expat-2.5.0-GCCcore-13.2.0.eb)
* Ninja/1.11.1-GCCcore-13.2.0 (Ninja-1.11.1-GCCcore-13.2.0.eb)
* hatchling/1.18.0-GCCcore-13.2.0 (hatchling-1.18.0-GCCcore-13.2.0.eb)
* scikit-build/0.17.6-GCCcore-13.2.0 (scikit-build-0.17.6-GCCcore-13.2.0.eb)
* cppy/1.2.1-GCCcore-13.2.0 (cppy-1.2.1-GCCcore-13.2.0.eb)
* Meson/1.2.3-GCCcore-13.2.0 (Meson-1.2.3-GCCcore-13.2.0.eb)
* git/2.42.0-GCCcore-13.2.0 (git-2.42.0-GCCcore-13.2.0.eb)
* flit/3.9.0-GCCcore-13.2.0 (flit-3.9.0-GCCcore-13.2.0.eb)
* Qhull/2020.2-GCCcore-13.2.0 (Qhull-2020.2-GCCcore-13.2.0.eb)
* Eigen/3.4.0-GCCcore-13.2.0 (Eigen-3.4.0-GCCcore-13.2.0.eb)
* Brotli/1.1.0-GCCcore-13.2.0 (Brotli-1.1.0-GCCcore-13.2.0.eb)
* freetype/2.13.2-GCCcore-13.2.0 (freetype-2.13.2-GCCcore-13.2.0.eb)
* virtualenv/20.24.6-GCCcore-13.2.0 (virtualenv-20.24.6-GCCcore-13.2.0.eb)
* Catch2/2.13.9-GCCcore-13.2.0 (Catch2-2.13.9-GCCcore-13.2.0.eb)
* NASM/2.16.01-GCCcore-13.2.0 (NASM-2.16.01-GCCcore-13.2.0.eb)
* Bison/3.8.2-GCCcore-13.2.0 (Bison-3.8.2-GCCcore-13.2.0.eb)
* libjpeg-turbo/3.0.1-GCCcore-13.2.0 (libjpeg-turbo-3.0.1-GCCcore-13.2.0.eb)
* setuptools-rust/1.8.0-GCCcore-13.2.0 (setuptools-rust-1.8.0-GCCcore-13.2.0.eb)
* jbigkit/2.1-GCCcore-13.2.0 (jbigkit-2.1-GCCcore-13.2.0.eb)
* patchelf/0.18.0-GCCcore-13.2.0 (patchelf-0.18.0-GCCcore-13.2.0.eb)
* Rust/1.73.0-GCCcore-13.2.0 (Rust-1.73.0-GCCcore-13.2.0.eb)
* cffi/1.15.1-GCCcore-13.2.0 (cffi-1.15.1-GCCcore-13.2.0.eb)
* fontconfig/2.14.2-GCCcore-13.2.0 (fontconfig-2.14.2-GCCcore-13.2.0.eb)
* libiconv/1.17-GCCcore-13.2.0 (libiconv-1.17-GCCcore-13.2.0.eb)
* cryptography/41.0.5-GCCcore-13.2.0 (cryptography-41.0.5-GCCcore-13.2.0.eb)
* Doxygen/1.9.8-GCCcore-13.2.0 (Doxygen-1.9.8-GCCcore-13.2.0.eb)
* poetry/1.6.1-GCCcore-13.2.0 (poetry-1.6.1-GCCcore-13.2.0.eb)
* Python-bundle-PyPI/2023.10-GCCcore-13.2.0 (Python-bundle-PyPI-2023.10-GCCcore-13.2.0.eb)
* hypothesis/6.90.0-GCCcore-13.2.0 (hypothesis-6.90.0-GCCcore-13.2.0.eb)
* pybind11/2.11.1-GCCcore-13.2.0 (pybind11-2.11.1-GCCcore-13.2.0.eb)
* meson-python/0.15.0-GCCcore-13.2.0 (meson-python-0.15.0-GCCcore-13.2.0.eb)
* libdeflate/1.19-GCCcore-13.2.0 (libdeflate-1.19-GCCcore-13.2.0.eb)
* gzip/1.13-GCCcore-13.2.0 (gzip-1.13-GCCcore-13.2.0.eb)
* gfbf/2023b (gfbf-2023b.eb)
* SciPy-bundle/2023.11-gfbf-2023b (SciPy-bundle-2023.11-gfbf-2023b.eb)
* lz4/1.9.4-GCCcore-13.2.0 (lz4-1.9.4-GCCcore-13.2.0.eb)
* X11/20231019-GCCcore-13.2.0 (X11-20231019-GCCcore-13.2.0.eb)
* zstd/1.5.5-GCCcore-13.2.0 (zstd-1.5.5-GCCcore-13.2.0.eb)
* Tk/8.6.13-GCCcore-13.2.0 (Tk-8.6.13-GCCcore-13.2.0.eb)
* LibTIFF/4.6.0-GCCcore-13.2.0 (LibTIFF-4.6.0-GCCcore-13.2.0.eb)
* Tkinter/3.11.5-GCCcore-13.2.0 (Tkinter-3.11.5-GCCcore-13.2.0.eb)
* Pillow/10.2.0-GCCcore-13.2.0 (Pillow-10.2.0-GCCcore-13.2.0.eb)
* matplotlib/3.8.2-gfbf-2023b (matplotlib-3.8.2-gfbf-2023b.eb)
```

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb10 arch:aarch64/generic

**Comment by trz42** [comment]
Checklist before starting deployment (setting `bot:deploy` label): 

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each staged tarball was a PR for approval/rejection opened
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/SciPy-bundle/2023.11* \
        aarch64/generic/{software,modules/all}/SciPy-bundle/2023.11* \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/netCDF/4.9.2* \
        aarch64/generic/{software,modules/all}/netCDF/4.9.2* \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/matplotlib/3.8.2* \
        aarch64/generic/{software,modules/all}/matplotlib/3.8.2*
  ```
  **log**
```
-rw-r--r-- 1 cvmfs cvmfs 2890 Feb  3 04:18 aarch64/generic/modules/all/matplotlib/3.8.2-gfbf-2023b.lua
-rw-r--r-- 1 cvmfs cvmfs 1931 Feb  3 02:27 aarch64/generic/modules/all/netCDF/4.9.2-gompi-2023b.lua
-rw-r--r-- 1 cvmfs cvmfs 2430 Feb  3 01:27 aarch64/generic/modules/all/SciPy-bundle/2023.11-gfbf-2023b.lua
-rw-rw-r-- 1 cvmfs cvmfs 2890 Feb  2 23:38 x86_64/amd/zen2/modules/all/matplotlib/3.8.2-gfbf-2023b.lua
-rw-rw-r-- 1 cvmfs cvmfs 1931 Feb  2 22:58 x86_64/amd/zen2/modules/all/netCDF/4.9.2-gompi-2023b.lua
-rw-rw-r-- 1 cvmfs cvmfs 2430 Feb  2 22:33 x86_64/amd/zen2/modules/all/SciPy-bundle/2023.11-gfbf-2023b.lua
-rw-rw-r-- 1 cvmfs cvmfs 2889 Feb  3 00:02 x86_64/generic/modules/all/matplotlib/3.8.2-gfbf-2023b.lua
-rw-rw-r-- 1 cvmfs cvmfs 1930 Feb  2 23:18 x86_64/generic/modules/all/netCDF/4.9.2-gompi-2023b.lua
-rw-rw-r-- 1 cvmfs cvmfs 2429 Feb  2 22:53 x86_64/generic/modules/all/SciPy-bundle/2023.11-gfbf-2023b.lua
-rw-rw-r-- 1 cvmfs cvmfs 2897 Feb  3 01:59 x86_64/intel/broadwell/modules/all/matplotlib/3.8.2-gfbf-2023b.lua
-rw-rw-r-- 1 cvmfs cvmfs 1938 Feb  3 00:48 x86_64/intel/broadwell/modules/all/netCDF/4.9.2-gompi-2023b.lua
-rw-rw-r-- 1 cvmfs cvmfs 2437 Feb  3 00:08 x86_64/intel/broadwell/modules/all/SciPy-bundle/2023.11-gfbf-2023b.lua
-rw-rw-r-- 1 cvmfs cvmfs 2902 Feb  3 01:42 x86_64/intel/skylake_avx512/modules/all/matplotlib/3.8.2-gfbf-2023b.lua
-rw-rw-r-- 1 cvmfs cvmfs 1943 Feb  3 00:33 x86_64/intel/skylake_avx512/modules/all/netCDF/4.9.2-gompi-2023b.lua
-rw-rw-r-- 1 cvmfs cvmfs 2442 Feb  2 23:58 x86_64/intel/skylake_avx512/modules/all/SciPy-bundle/2023.11-gfbf-2023b.lua

aarch64/generic/software/matplotlib/3.8.2-gfbf-2023b:
total 19
dr-xr-xr-x 2 cvmfs cvmfs 4096 Feb  3 04:13 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  3 04:18 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  3 04:11 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Feb  3 04:17 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  3 04:13 share

aarch64/generic/software/netCDF/4.9.2-gompi-2023b:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Feb  3 02:27 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  3 02:27 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Feb  3 02:27 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Feb  3 02:27 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Feb  3 02:27 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  3 02:14 share

aarch64/generic/software/SciPy-bundle/2023.11-gfbf-2023b:
total 14
dr-xr-xr-x 2 cvmfs cvmfs 4096 Feb  3 00:00 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  3 01:28 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  2 23:56 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Feb  3 01:26 lib64 -> lib

x86_64/amd/zen2/software/matplotlib/3.8.2-gfbf-2023b:
total 19
dr-xr-xr-x 2 cvmfs cvmfs 4096 Feb  2 23:36 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  2 23:38 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  2 23:35 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Feb  2 23:38 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  2 23:36 share

x86_64/amd/zen2/software/netCDF/4.9.2-gompi-2023b:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Feb  2 22:58 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  2 22:58 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Feb  2 22:58 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Feb  2 22:58 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Feb  2 22:58 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  2 22:52 share

x86_64/amd/zen2/software/SciPy-bundle/2023.11-gfbf-2023b:
total 14
dr-xr-xr-x 2 cvmfs cvmfs 4096 Feb  2 22:04 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  2 22:33 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  2 22:02 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Feb  2 22:32 lib64 -> lib

x86_64/generic/software/matplotlib/3.8.2-gfbf-2023b:
total 19
dr-xr-xr-x 2 cvmfs cvmfs 4096 Feb  3 00:00 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  3 00:02 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  2 23:59 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Feb  3 00:02 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  3 00:00 share

x86_64/generic/software/netCDF/4.9.2-gompi-2023b:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Feb  2 23:18 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  2 23:19 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Feb  2 23:18 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Feb  2 23:18 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Feb  2 23:18 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  2 23:13 share

x86_64/generic/software/SciPy-bundle/2023.11-gfbf-2023b:
total 14
dr-xr-xr-x 2 cvmfs cvmfs 4096 Feb  2 22:21 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  2 22:53 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  2 22:18 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Feb  2 22:52 lib64 -> lib

x86_64/intel/broadwell/software/matplotlib/3.8.2-gfbf-2023b:
total 19
dr-xr-xr-x 2 cvmfs cvmfs 4096 Feb  3 01:55 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  3 01:59 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  3 01:53 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Feb  3 01:58 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  3 01:55 share

x86_64/intel/broadwell/software/netCDF/4.9.2-gompi-2023b:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Feb  3 00:48 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  3 00:49 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Feb  3 00:48 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Feb  3 00:48 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Feb  3 00:48 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  3 00:39 share

x86_64/intel/broadwell/software/SciPy-bundle/2023.11-gfbf-2023b:
total 14
dr-xr-xr-x 2 cvmfs cvmfs 4096 Feb  2 23:08 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  3 00:08 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  2 23:05 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Feb  3 00:07 lib64 -> lib

x86_64/intel/skylake_avx512/software/matplotlib/3.8.2-gfbf-2023b:
total 19
dr-xr-xr-x 2 cvmfs cvmfs 4096 Feb  3 01:38 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  3 01:42 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  3 01:37 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Feb  3 01:41 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  3 01:38 share

x86_64/intel/skylake_avx512/software/netCDF/4.9.2-gompi-2023b:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Feb  3 00:33 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  3 00:33 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Feb  3 00:33 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Feb  3 00:33 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Feb  3 00:33 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  3 00:26 share

x86_64/intel/skylake_avx512/software/SciPy-bundle/2023.11-gfbf-2023b:
total 14
dr-xr-xr-x 2 cvmfs cvmfs 4096 Feb  2 22:53 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  2 23:59 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Feb  2 22:50 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Feb  2 23:57 lib64 -> lib 
```
</details>

**Review by poksumdo — APPROVED** [review]
Looks good.

**Pull request merged**
