### PR TITLE
{2023.06} comment `*-from-pr` & sync with EESSI/2023.06

### PR DESCRIPTION
**Pull request by trz42**
- `*-from-pr` are commented in easystack files to reduce GitHub REST API requests
- `EESSI-pilot-install-software.sh` is synchronised with recent update to branch `2023.06` in https://github.com/EESSI/software-layer

### CODE REVIEW

**Comment by trz42** [comment]
Make a small trial run. Shouldn't take much time.

bot: build inst:AWS arch:x86_64/generic repo:nessi-2023.06-swl-deb11
bot: build inst:eX3 arch:x86_64/amd/zen2 repo:nessi-2023.06-swl-deb11
bot: build inst:eX3 arch:aarch64/generic repo:nessi-2023.06-swl-deb11
bot: build inst:Fram arch:x86_64/intel/broadwell repo:nessi-2023.06-swl-deb10
bot: build inst:Saga arch:x86_64/intel/cascadelake repo:nessi-2023.06-swl-deb11
bot: build inst:Saga arch:x86_64/intel/skylake repo:nessi-2023.06-swl-deb11

**Comment by trz42** [comment]
Went too far with commenting `*-from-pr`. Easyconfig for BAGEL could not be found. Fixed that and also uncomment options for GROMACS. Repeating builds.

bot: build inst:AWS arch:x86_64/generic repo:nessi-2023.06-swl-deb11
bot: build inst:eX3 arch:x86_64/amd/zen2 repo:nessi-2023.06-swl-deb11
bot: build inst:eX3 arch:aarch64/generic repo:nessi-2023.06-swl-deb11
bot: build inst:Fram arch:x86_64/intel/broadwell repo:nessi-2023.06-swl-deb10
bot: build inst:Saga arch:x86_64/intel/cascadelake repo:nessi-2023.06-swl-deb11
bot: build inst:Saga arch:x86_64/intel/skylake repo:nessi-2023.06-swl-deb11

**Comment by trz42** [comment]
All good now.

**Review by poksumdo — APPROVED** [review]
Looks good.

**Pull request merged**
