### PR TITLE
{23.06}[foss/2022a] CMake + OpenMPI + FFTW.MPI + BLIS

### PR DESCRIPTION
**Pull request by trz42**
Add several components of foss/2022a (not OpenBLAS and packages depending on it):

- `CMake/3.23.1` with easyblock PR 2248
- `BLIS/0.9.0`
- `OpenMPI/4.1.4`
- `FFTW.MPI/3.3.10`

### CODE REVIEW

**Comment by trz42** [comment]
bot: build repo:nessi.no-2023.06-software inst:eX3 arch:aarch64/generic
bot: build repo:nessi.no-2023.06-software inst:eX3 arch:zen2
bot: build repo:nessi.no-2023.06-software inst:Fram arch:broadwell
bot: build repo:nessi.no-2023.06-software inst:AWS arch:x86_64/generic
bot: build repo:nessi.no-2023.06-software inst:AWS arch:cascade
bot: build repo:nessi.no-2023.06-software inst:AWS arch:skylake

**Comment by trz42** [comment]
Checklist for building: 

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Target architectures
- `x86_64-intel-broadwell`
- `x86_64-intel-skylake_avx512`
- `x86_64-intel-cascadelake`
- `x86_64-amd-zen2`
- `x86_64-generic`
- `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & output</summary>

  **command**
  ```
  ls -l /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/BLIS/0.9.0-GCC-11.3*
  ls -l /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/{software,modules/all}/BLIS/0.9.0-GCC-11.3*
  ls -l /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/CMake/3.23.1-GCCcore-11.3*
  ls -l /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/{software,modules/all}/CMake/3.23.1-GCCcore-11.3*
  ls -l /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/FFTW.MPI/3.3.10-gompi-2022a*
  ls -l /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/{software,modules/all}/FFTW.MPI/3.3.10-gompi-2022a*
  ls -l /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/OpenMPI/4.1.4-GCC-11.3*
  ls -l /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/{software,modules/all}/OpenMPI/4.1.4-GCC-11.3*
  ```
  **log**
```
-rw-r--r-- 1 cvmfs cvmfs 1296 Jun 28 19:57 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all/BLIS/0.9.0-GCC-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1295 Jun 28 20:29 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/modules/all/BLIS/0.9.0-GCC-11.3.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 1303 Jun 28 20:03 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/modules/all/BLIS/0.9.0-GCC-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1305 Jun 28 23:55 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/modules/all/BLIS/0.9.0-GCC-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1308 Jun 28 20:09 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/modules/all/BLIS/0.9.0-GCC-11.3.0.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/software/BLIS/0.9.0-GCC-11.3.0:
total 19
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 19:57 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 19:57 include
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 19:57 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 28 19:57 lib64 -> lib
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 28 19:57 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/software/BLIS/0.9.0-GCC-11.3.0:
total 19
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 20:29 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 20:29 include
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 20:29 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 28 20:29 lib64 -> lib
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 28 20:29 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/software/BLIS/0.9.0-GCC-11.3.0:
total 19
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 20:03 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 20:03 include
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 20:03 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 28 20:03 lib64 -> lib
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 28 20:03 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/software/BLIS/0.9.0-GCC-11.3.0:
total 19
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 23:56 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 23:55 include
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 23:55 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 28 23:55 lib64 -> lib
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 28 23:55 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/BLIS/0.9.0-GCC-11.3.0:
total 19
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 20:09 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 20:09 include
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 20:09 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 28 20:09 lib64 -> lib
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 28 20:09 share

-rw-r--r-- 1 cvmfs cvmfs 1296 Jun 28 20:43 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/modules/all/BLIS/0.9.0-GCC-11.3.0.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/software/BLIS/0.9.0-GCC-11.3.0:
total 19
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 20:43 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 20:43 include
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 20:43 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 28 20:43 lib64 -> lib
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 28 20:43 share

-rw-r--r-- 1 cvmfs cvmfs 1385 Jun 28 19:10 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all/CMake/3.23.1-GCCcore-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1384 Jun 28 19:21 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/modules/all/CMake/3.23.1-GCCcore-11.3.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 1392 Jun 28 19:07 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/modules/all/CMake/3.23.1-GCCcore-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1394 Jun 28 23:11 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/modules/all/CMake/3.23.1-GCCcore-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1397 Jun 28 19:17 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/modules/all/CMake/3.23.1-GCCcore-11.3.0.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/software/CMake/3.23.1-GCCcore-11.3.0:
total 18
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 19:10 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 19:10 doc
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 19:10 easybuild
dr-xr-xr-x 7 cvmfs cvmfs 4096 Jun 28 19:10 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/software/CMake/3.23.1-GCCcore-11.3.0:
total 18
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 19:21 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 19:21 doc
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 19:21 easybuild
dr-xr-xr-x 7 cvmfs cvmfs 4096 Jun 28 19:21 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/software/CMake/3.23.1-GCCcore-11.3.0:
total 18
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 19:07 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 19:07 doc
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 19:07 easybuild
dr-xr-xr-x 7 cvmfs cvmfs 4096 Jun 28 19:07 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/software/CMake/3.23.1-GCCcore-11.3.0:
total 18
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 23:11 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 23:11 doc
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 23:11 easybuild
dr-xr-xr-x 7 cvmfs cvmfs 4096 Jun 28 23:11 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/CMake/3.23.1-GCCcore-11.3.0:
total 18
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 19:17 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 19:17 doc
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 19:17 easybuild
dr-xr-xr-x 7 cvmfs cvmfs 4096 Jun 28 19:17 share

-rw-r--r-- 1 cvmfs cvmfs 1385 Jun 28 19:12 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/modules/all/CMake/3.23.1-GCCcore-11.3.0.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/software/CMake/3.23.1-GCCcore-11.3.0:
total 18
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 19:12 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 19:12 doc
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 19:12 easybuild
dr-xr-xr-x 7 cvmfs cvmfs 4096 Jun 28 19:12 share

-rw-r--r-- 1 cvmfs cvmfs 1317 Jun 28 21:55 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all/FFTW.MPI/3.3.10-gompi-2022a.lua
-rw-r--r-- 1 cvmfs cvmfs 1316 Jun 28 22:52 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/modules/all/FFTW.MPI/3.3.10-gompi-2022a.lua
-rw-rw-r-- 1 cvmfs cvmfs 1324 Jun 28 22:26 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/modules/all/FFTW.MPI/3.3.10-gompi-2022a.lua
-rw-r--r-- 1 cvmfs cvmfs 1326 Jun 29 01:49 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/modules/all/FFTW.MPI/3.3.10-gompi-2022a.lua
-rw-r--r-- 1 cvmfs cvmfs 1329 Jun 28 22:14 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/modules/all/FFTW.MPI/3.3.10-gompi-2022a.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/software/FFTW.MPI/3.3.10-gompi-2022a:
total 14
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 21:55 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 21:55 include
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 21:55 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 28 21:55 lib64 -> lib

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/software/FFTW.MPI/3.3.10-gompi-2022a:
total 14
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 22:52 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 22:52 include
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 22:52 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 28 22:52 lib64 -> lib

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/software/FFTW.MPI/3.3.10-gompi-2022a:
total 14
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 22:26 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 22:26 include
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 22:26 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 28 22:26 lib64 -> lib

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/software/FFTW.MPI/3.3.10-gompi-2022a:
total 14
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 01:49 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 29 01:49 include
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 29 01:49 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 29 01:49 lib64 -> lib

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/FFTW.MPI/3.3.10-gompi-2022a:
total 14
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 22:14 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 22:14 include
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 22:14 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 28 22:14 lib64 -> lib

-rw-r--r-- 1 cvmfs cvmfs 1317 Jun 28 23:30 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/modules/all/FFTW.MPI/3.3.10-gompi-2022a.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/software/FFTW.MPI/3.3.10-gompi-2022a:
total 14
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 23:31 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 23:30 include
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 23:30 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 28 23:30 lib64 -> lib

-rw-r--r-- 1 cvmfs cvmfs 1836 Jun 28 20:43 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all/OpenMPI/4.1.4-GCC-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1835 Jun 28 21:48 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/modules/all/OpenMPI/4.1.4-GCC-11.3.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 1843 Jun 28 21:00 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/modules/all/OpenMPI/4.1.4-GCC-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1845 Jun 29 00:43 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/modules/all/OpenMPI/4.1.4-GCC-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1848 Jun 28 21:08 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/modules/all/OpenMPI/4.1.4-GCC-11.3.0.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/software/OpenMPI/4.1.4-GCC-11.3.0:
total 28
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 20:43 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 20:44 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 20:42 etc
dr-xr-xr-x 5 cvmfs cvmfs 4096 Jun 28 20:43 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 28 20:43 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 28 20:43 lib64 -> lib
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 28 20:41 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/software/OpenMPI/4.1.4-GCC-11.3.0:
total 28
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 21:48 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 21:48 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 21:46 etc
dr-xr-xr-x 5 cvmfs cvmfs 4096 Jun 28 21:47 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 28 21:47 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 28 21:48 lib64 -> lib
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 28 21:43 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/software/OpenMPI/4.1.4-GCC-11.3.0:
total 28
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 21:00 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 21:00 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 20:58 etc
dr-xr-xr-x 5 cvmfs cvmfs 4096 Jun 28 21:00 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 28 21:00 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 28 21:00 lib64 -> lib
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 28 20:57 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/software/OpenMPI/4.1.4-GCC-11.3.0:
total 28
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 29 00:43 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 00:43 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 29 00:41 etc
dr-xr-xr-x 5 cvmfs cvmfs 4096 Jun 29 00:42 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 29 00:42 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 29 00:43 lib64 -> lib
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 29 00:40 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/OpenMPI/4.1.4-GCC-11.3.0:
total 28
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 21:08 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 21:08 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 21:06 etc
dr-xr-xr-x 5 cvmfs cvmfs 4096 Jun 28 21:08 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 28 21:08 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 28 21:08 lib64 -> lib
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 28 21:05 share

-rw-r--r-- 1 cvmfs cvmfs 1836 Jun 28 22:14 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/modules/all/OpenMPI/4.1.4-GCC-11.3.0.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/software/OpenMPI/4.1.4-GCC-11.3.0:
total 28
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 22:13 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 22:14 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 22:11 etc
dr-xr-xr-x 5 cvmfs cvmfs 4096 Jun 28 22:13 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 28 22:13 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 28 22:13 lib64 -> lib
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 28 22:08 share
```
</details>

**Review by poksumdo — APPROVED** [review]
All fine after fixing some issue with incomplete upload (tarball missing) from eX3.

**Pull request merged**
