### PR TITLE
configure Lmod via `$LMOD_CONFIG_DIR` and `$LMOD_PACKAGE_PATH` + don't set `$LMOD_RC`

### PR DESCRIPTION
**Pull request by trz42**
Sync NESSI with EESSI PR 524. Just used the two commits in 524 and removed some extra whitespaces in the third commit.

Needs build and ingest.

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb11 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
Checklist before starting deployment (setting `bot:deploy` label): 

- [x]  Check if the _SPDX license identifier_ is provided 
  - not needed (no software has been built)
- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
  - no easyconfigs were used
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each staged tarball was a PR for approval/rejection opened
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
  - no rerun needed as CI has already succeeded
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06 ; \
  ls -l \
      init/eessi_env* \
software/linux/x86_64/{generic,amd/zen2,intel/[bsc]*}/.lmod/lmodrc.lua \
      software/linux/aarch64/generic/.lmod/lmodrc.lua
  ```
  **log**
```
-rw-rw-r-- 1 cvmfs cvmfs 4307 Apr  7 16:03 init/eessi_environment_variables
-rw-r--r-- 1 cvmfs cvmfs  265 Apr  7 16:03 software/linux/aarch64/generic/.lmod/lmodrc.lua
-rw-r--r-- 1 cvmfs cvmfs  265 Apr  7 16:09 software/linux/x86_64/amd/zen2/.lmod/lmodrc.lua
-rw-r--r-- 1 cvmfs cvmfs  263 Apr  7 16:09 software/linux/x86_64/generic/.lmod/lmodrc.lua
-rw-rw-r-- 1 cvmfs cvmfs  279 Apr  7 16:03 software/linux/x86_64/intel/broadwell/.lmod/lmodrc.lua
-rw-r--r-- 1 cvmfs cvmfs  283 Jun 18  2023 software/linux/x86_64/intel/cascadelake/.lmod/lmodrc.lua
-rw-r--r-- 1 cvmfs cvmfs  289 Apr  7 16:03 software/linux/x86_64/intel/skylake_avx512/.lmod/lmodrc.lua 
```
</details>

**Review by poksumdo — APPROVED** [review]
All good.

**Pull request merged**
