### PR TITLE
{2023.06}[foss/2022a] ImageMagick v7.1.0-37

### PR DESCRIPTION
**Pull request by trz42**
ImageMagick is a dependency for R-bundle. The PR also serves as a test for #285 

SPDX identifier: `ImageMagick`

Missing installations:
```
6 out of 57 required modules missing:

* LittleCMS/2.13.1-GCCcore-11.3.0 (LittleCMS-2.13.1-GCCcore-11.3.0.eb)
* ATK/2.38.0-GCCcore-11.3.0 (ATK-2.38.0-GCCcore-11.3.0.eb)
* Gdk-Pixbuf/2.42.8-GCCcore-11.3.0 (Gdk-Pixbuf-2.42.8-GCCcore-11.3.0.eb)
* GTK2/2.24.33-GCCcore-11.3.0 (GTK2-2.24.33-GCCcore-11.3.0.eb)
* Ghostscript/9.56.1-GCCcore-11.3.0 (Ghostscript-9.56.1-GCCcore-11.3.0.eb)
* ImageMagick/7.1.0-37-GCCcore-11.3.0 (ImageMagick-7.1.0-37-GCCcore-11.3.0.eb)
```

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/generic
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:zen2
skip bot: build inst:Saga repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb10 arch:aarch64/generic

**Comment by trz42** [comment]
bot: help

**Comment by trz42** [comment]
bot: build inst:Fram repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by trz42** [comment]
Bot instance on Fram crashed because it wasn't upgraded to release v0.4.0.

bot: build inst:Fram repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by trz42** [comment]
Retry after adding dependency for `PCRE/8.45`

bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/generic
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Fram repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb10 arch:aarch64/generic

**Comment by trz42** [comment]
Now retry after adding dependency for PCRE/8.45 via a parse hook

bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/generic
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Fram repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb10 arch:aarch64/generic

**Comment by trz42** [comment]
One more retry after differently adding dependency for PCRE/8.45 via a parse hook

bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/generic
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Fram repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb10 arch:aarch64/generic

**Comment by trz42** [comment]
Last jobs failed because ec PR 20086 wasn't used. Retry using both ec PR and eb hook for dependency for PCRE/8.45

bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/generic
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Fram repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb10 arch:aarch64/generic

**Comment by trz42** [comment]
Rerun after updating PR and hook to add dependency for PCRE/8.45

bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/generic
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Fram repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb10 arch:aarch64/generic

**Review by TopRichard — APPROVED** [review]
Lgtm

**Comment by trz42** [comment]
Checklist before starting deployment (setting `bot:deploy` label): 

- [x]  Check if the _SPDX license identifier_ is provided 
- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
  - added a `parse_hook` to add dependency for `PCRE/8.45`
- [x] Verify that all easyconfig/s being built are included with the EB version used (if not why not)
  - using merged [PR#20086](https://github.com/easybuilders/easybuild-easyconfigs/pull/20086) for easyconfig for `ImageMagick/7.1.0-37` 
- [x] Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)
  - added a `parse_hook` to add dependency for `PCRE/8.45`

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
  - upload from eX3 failed once 
- [x] at least one tarball for each architecture has been staged
- [x] for each staged tarball was a PR for approval/rejection opened
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/ImageMagick/7.1.0-37* \
        aarch64/generic/{software,modules/all}/ImageMagick/7.1.0-37*
  ```
  **log**
```
-rw-r--r-- 1 cvmfs cvmfs 2424 Mar 13 14:37 aarch64/generic/modules/all/ImageMagick/7.1.0-37-GCCcore-11.3.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 2424 Mar 13 14:04 x86_64/amd/zen2/modules/all/ImageMagick/7.1.0-37-GCCcore-11.3.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 2422 Mar 13 14:03 x86_64/generic/modules/all/ImageMagick/7.1.0-37-GCCcore-11.3.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 2438 Mar 13 14:12 x86_64/intel/broadwell/modules/all/ImageMagick/7.1.0-37-GCCcore-11.3.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 2448 Mar 13 14:09 x86_64/intel/skylake_avx512/modules/all/ImageMagick/7.1.0-37-GCCcore-11.3.0.lua

aarch64/generic/software/ImageMagick/7.1.0-37-GCCcore-11.3.0:
total 28
dr-xr-xr-x 2 cvmfs cvmfs 4096 Mar 13 14:37 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 13 14:38 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 13 14:37 etc
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 13 14:37 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Mar 13 14:37 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Mar 13 14:37 lib64 -> lib
dr-xr-xr-x 5 cvmfs cvmfs 4096 Mar 13 14:37 share

x86_64/amd/zen2/software/ImageMagick/7.1.0-37-GCCcore-11.3.0:
total 28
dr-xr-xr-x 2 cvmfs cvmfs 4096 Mar 13 14:04 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 13 14:04 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 13 14:04 etc
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 13 14:04 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Mar 13 14:04 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Mar 13 14:04 lib64 -> lib
dr-xr-xr-x 5 cvmfs cvmfs 4096 Mar 13 14:04 share

x86_64/generic/software/ImageMagick/7.1.0-37-GCCcore-11.3.0:
total 28
dr-xr-xr-x 2 cvmfs cvmfs 4096 Mar 13 14:03 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 13 14:03 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 13 14:03 etc
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 13 14:03 include
lrwxrwxrwx 1 cvmfs cvmfs    3 Mar 13 14:03 lib64 -> lib
dr-xr-xr-x 5 cvmfs cvmfs 4096 Mar 13 14:03 share

x86_64/intel/broadwell/software/ImageMagick/7.1.0-37-GCCcore-11.3.0:
total 28
dr-xr-xr-x 2 cvmfs cvmfs 4096 Mar 13 14:12 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 13 14:12 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 13 14:12 etc
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 13 14:12 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Mar 13 14:12 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Mar 13 14:12 lib64 -> lib
dr-xr-xr-x 5 cvmfs cvmfs 4096 Mar 13 14:12 share

x86_64/intel/skylake_avx512/software/ImageMagick/7.1.0-37-GCCcore-11.3.0:
total 28
dr-xr-xr-x 2 cvmfs cvmfs 4096 Mar 13 14:09 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 13 14:09 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 13 14:09 etc
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 13 14:09 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Mar 13 14:09 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Mar 13 14:09 lib64 -> lib
dr-xr-xr-x 5 cvmfs cvmfs 4096 Mar 13 14:09 share 
```
</details>

**Pull request merged**
