### PR TITLE
 {2023.06}[foss/2022a] CDO v2.0.6

### PR DESCRIPTION
**Pull request by TopRichard**
Trying to add CDO-foss/2022a as a client request, in addition that it is a package which adds essential software to the stack.
license: https://spdx.org/licenses/BSD-3-Clause.html
All modules that will be installed:
```
CDO/2.0.6-gompi-2022a
googletest/1.11.0-GCCcore-11.3.0
nlohmann_json/3.10.5-GCCcore-11.3.0
PROJ/9.0.0-GCCcore-11.3.0
```

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
Checklist for building CDO v2.0.6 : 

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- []  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by TopRichard** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [] encountered issues in the ingestion, likely related to troubles interacting with GitHub via PyGithub … 
- [x] all tests in the CI for the ingested tarballs have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] the PR has a license info for the ingested software
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)

<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; 
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/CDO/2.0.6* \
        aarch64/generic/{software,modules/all}/CDO/2.0.6*
        
        
 -rw-rw-r--. 1 cvmfs cvmfs 1989 Nov  4 20:07 x86_64/amd/zen2/modules/all/CDO/2.0.6-gompi-2022a.lua
-rw-rw-r--. 1 cvmfs cvmfs 1988 Nov  4 20:09 x86_64/generic/modules/all/CDO/2.0.6-gompi-2022a.lua
-rw-rw-r--. 1 cvmfs cvmfs 1996 Nov  4 20:03 x86_64/intel/broadwell/modules/all/CDO/2.0.6-gompi-2022a.lua
-rw-rw-r--. 1 cvmfs cvmfs 2001 Nov  4 20:03 x86_64/intel/skylake_avx512/modules/all/CDO/2.0.6-gompi-2022a.lua

x86_64/amd/zen2/software/CDO/2.0.6-gompi-2022a:
total 19
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Nov  4 20:07 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Nov  4 20:07 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Nov  4 20:07 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Nov  4 20:07 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Nov  4 20:07 lib64 -> lib

x86_64/generic/software/CDO/2.0.6-gompi-2022a:
total 19
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Nov  4 20:09 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Nov  4 20:09 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Nov  4 20:09 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Nov  4 20:09 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Nov  4 20:09 lib64 -> lib

x86_64/intel/broadwell/software/CDO/2.0.6-gompi-2022a:
total 19
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Nov  4 20:03 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Nov  4 20:03 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Nov  4 20:03 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Nov  4 20:03 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Nov  4 20:03 lib64 -> lib

x86_64/intel/skylake_avx512/software/CDO/2.0.6-gompi-2022a:
total 19
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Nov  4 20:03 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Nov  4 20:03 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Nov  4 20:03 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Nov  4 20:03 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Nov  4 20:03 lib64 -> lib

x86_64/intel/skylake_avx512/software/CDO/2.0.6-gompi-2022a:
total 19
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Nov  4 20:03 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Nov  4 20:03 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Nov  4 20:03 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Nov  4 20:03 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Nov  4 20:03 lib64 -> lib

```
</details>

**Review by justadejavu — APPROVED** [review]
Okay!

**Pull request merged**
