### PR TITLE
{2023.06}[foss/2021a] Qt5 V5.15.2

### PR DESCRIPTION
**Pull request by TopRichard**

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi.no-2023.06-software arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:Fram-NESSI repo:nessi.no-2023.06-software arch:x86_64/intel/broadwell

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi.no-2023.06-software arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi.no-2023.06-software arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi.no-2023.06-software arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:Fram-NESSI repo:nessi.no-2023.06-software arch:x86_64/intel/broadwell

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi.no-2023.06-software arch:x86_64/intel/cascadelake 
bot: build inst:AWS repo:nessi.no-2023.06-software arch:x86_64/intel/skylake 
bot: build inst:eX3 repo:nessi.no-2023.06-software arch:zen2
bot: build inst:eX3 repo:nessi.no-2023.06-software arch:aarch64/generic

**Comment by TopRichard** [comment]
on Fram the build fails with : result for command 'python-config --help': FAILED during sanity check of Python-bare

**Comment by TopRichard** [comment]
On AWS Cascadelake it fails : failed (err: 'build failed (first 300 chars): cmd " make install " exited with exit code 2 and output:\ncd qtbase/ && ( test -e Makefile || /tmp/nessibot/easybuild/build/Qt5/5.15.2/GCCcore-10.3.0/qt-everywhere-src-5.15.2/qtbase/bin/qmake -o Makefile /tmp/nessibot/easybuild/build/Qt5/5.15.2/GCCcore-10.3.0/qt-everywhere-src-5.15.2/qtbase/qtbase.pr')

**Comment by TopRichard** [comment]
On AWS-X86/64-generic it fails with :  failed (err: 'build failed (first 300 chars): cmd " make install " exited with exit code 2 and output:\ncd qtbase/ && ( test -e Makefile || /tmp/nessibot/easybuild/build/Qt5/5.15.2/GCCcore-10.3.0/qt-everywhere-src-5.15.2/qtbase/bin/qmake -o Makefile /tmp/nessibot/easybuild/build/Qt5/5.15.2/GCCcore-10.3.0/qt-everywhere-src-5.15.2/qtbase/qtbase.pr')

**Comment by TopRichard** [comment]
bot: build inst:Saga-NESSI repo:nessi.no-2023.06-software arch:x86_64/intel/cascadelake

**Comment by TopRichard** [comment]
Linked to the following PR #154 which is intended to help in building Qt5 dependencies.

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi.no-2023.06-software arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi.no-2023.06-software arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi.no-2023.06-software arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi.no-2023.06-software arch:x86_64/generic

**Comment by TopRichard** [comment]
@trz42 , still failing :-1:

**Comment by TopRichard** [comment]
bot: build inst:Fram-NESSI  repo:nessi.no-2023.06-software arch:x86_64/generic 

- received bot command `build inst:Fram-NESSI  repo:nessi.no-2023.06-software arch:x86_64/generic` from `TopRichard` (expanded command format: `build instance:Fram-NESSI repository:nessi.no-2023.06-software architecture:x86_64/generic`)

**Comment by trz42** [comment]
bot: show_config
- received bot command `show_config` from `trz42` (expanded command format: `show_config `)

**Comment by trz42** [comment]
bot: show_config

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi.no-2023.06-software-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
@trz42  builds using  `nessi.no-2023.06-software-deb11`

**Comment by TopRichard** [comment]
bot: build inst:Fram-NESSI repo:nessi.no-2023.06-software-deb11  arch:x86_64/intel/broadwell

**Comment by TopRichard** [comment]
bot: build inst:Fram-NESSI repo:nessi.no-2023.06-software-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS nessi.no-2023.06-software-deb11 arch:x86_64/intel/cascadelake 
bot: build inst:AWS nessi.no-2023.06-software-deb11 arch:x86_64/intel/skylake

**Comment by TopRichard** [comment]
bot: show_config

**Comment by TopRichard** [comment]
bot: show_config

**Pull request closed without merging**
