### PR TITLE
update Lmod cache for NESSI/2022.11

### PR DESCRIPTION
**Pull request by trz42**
Pseudo PR which should only recreate Lmod cache.

We use it for ingesting an updated Lmod cache, but we must not merge it into the target branch!

We should keep it up to date with other merged PRs.

Before we retrigger an update of the Lmod cache we should leave a comment, e.g., stating why an update was needed.

### CODE REVIEW

**Comment by trz42** [comment]
Ready for updating the Lmod cache with both bot code and software-layer up-to-date with EESSI (incl PRs to be merged still: [bot PR#155](https://github.com/EESSI/eessi-bot-software-layer/pull/155), [swl PR#233](https://github.com/EESSI/software-layer/pull/233) and [swl PR#237](https://github.com/EESSI/software-layer/pull/237)) _PLUS_ it is up-to-date with `nessi.no-2022.11-dev`, hence it should help with using in NESSI for future PRs too.

**Comment by trz42** [comment]
All jobs failed because of bug in `bot/build.sh`: changed `$(pwd)` to `${pwd}` but should have been changed to `${PWD}`.

Should be fixed now. `scancel` still pending jobs and retrigger builds.

**Comment by poksumdo** [comment]
Jobs ran with most recent eessi-bot (incl unmerged PR155) and software-layer (incl unmerged PR233 and PR237). Overall looking good for a first _real_ run with the updates.

- [x] did the builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
  - we will not ingest the builds for `generic` -- they are handled in a separate branch/PR series
  - for all other
- [x] is the PR up-to-date with the target branch `nessi.no-2022.11-dev` in the repository (if not what are the differences)
  - yes plus it is an effort to sync `nessi.no-2022.11-dev` with `EESSI/software-layer` via the helper branch `merge-eessi-PR233-nessi-2022.11` of NorESSI/software-layer
- [x] are all requested changes sound (checking files changed on GitHub.com)
  - lots of changes (in total 100 commits)
- [x] is/are the easyconfig/s being built included with the EB version used (if not why not)
  - not really (except for `generic` which lacks ingested packages)
- [x] were any changes needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by poksumdo** [comment]
Checklist for deployment
- [ ] at least one tarball for each architecture uploaded
- [ ] at least one tarball for each architecture staged
- [ ] for each architecture **one and only one** tarball was approved (for `generic` the tarball built on the oldest architecture shall be ingested ... lower risk that `generic` build is not really `generic`)
  - the tarballs for `x86_64/generic` differ in size $\longrightarrow$ investigate during deployment and approve the correct build only
  - approved build on AWS cluster (Haswell architecture), see https://github.com/NorESSI/staging/pull/70 (rejected builds on Fram/Broadwell https://github.com/NorESSI/staging/pull/69 and Saga/Skylake https://github.com/NorESSI/staging/pull/71)
- [ ] for each architecture **one and only one** tarball was ingested
- [ ] only Lmod cache files have been updated (check time stamps before and after)
  - before
  ```
  ls -l /cvmfs/pilot.nessi.no/versions/latest/software...
  ```
  - after
  ```
  ls -l /cvmfs/pilot.nessi.no/versions/latest/software...
  ```

**Comment by poksumdo** [comment]
All looking good. We won't merge the PR because it was made against the `nessi.no-2022.11-dev` branch and its only purpose was to rebuilt the Lmod cache.

**Review by poksumdo — APPROVED** [review]
All looking good!!!

**Comment by poksumdo** [comment]
We rather close the PR.

**Pull request closed without merging**
