### PR TITLE
{2023.06}[system] ReFrame v4.3.3

### PR DESCRIPTION
**Pull request by trz42**
Adding ReFrame as it is needed for running the EESSI test suite.

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb10 arch:aarch64/generic

**Comment by trz42** [comment]
Checklist before starting deployment (setting `bot:deploy` label): 

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each staged tarball was a PR for approval/rejection opened
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/ReFrame/4.3.3* \
        aarch64/generic/{software,modules/all}/ReFrame/4.3.3*
  ```
  **log**
```
-rw-r--r-- 1 cvmfs cvmfs 1417 Feb 16 23:45 aarch64/generic/modules/all/ReFrame/4.3.3.lua
-rw-rw-r-- 1 cvmfs cvmfs 1417 Feb 16 23:48 x86_64/amd/zen2/modules/all/ReFrame/4.3.3.lua
-rw-rw-r-- 1 cvmfs cvmfs 1416 Feb 16 23:50 x86_64/generic/modules/all/ReFrame/4.3.3.lua
-rw-rw-r-- 1 cvmfs cvmfs 1424 Feb 16 23:49 x86_64/intel/broadwell/modules/all/ReFrame/4.3.3.lua
-rw-rw-r-- 1 cvmfs cvmfs 1429 Feb 16 23:48 x86_64/intel/skylake_avx512/modules/all/ReFrame/4.3.3.lua

aarch64/generic/software/ReFrame/4.3.3:
total 32
dr-xr-xr-x  2 cvmfs cvmfs 4096 Feb 16 23:45 bin
dr-xr-xr-x  3 cvmfs cvmfs 4096 Feb 16 23:46 easybuild
dr-xr-xr-x 93 cvmfs cvmfs 4096 Feb 16 23:45 external
dr-xr-xr-x  3 cvmfs cvmfs 4096 Feb 16 23:43 lib
lrwxrwxrwx  1 cvmfs cvmfs    3 Feb 16 23:45 lib64 -> lib
dr-xr-xr-x  3 cvmfs cvmfs 4096 Feb 16 23:45 share
dr-xr-xr-x  2 cvmfs cvmfs 4096 Sep 12 22:22 tools
dr-xr-xr-x 10 cvmfs cvmfs 4096 Sep 12 22:22 tutorials

x86_64/amd/zen2/software/ReFrame/4.3.3:
total 32
dr-xr-xr-x  2 cvmfs cvmfs 4096 Feb 16 23:48 bin
dr-xr-xr-x  3 cvmfs cvmfs 4096 Feb 16 23:49 easybuild
dr-xr-xr-x 93 cvmfs cvmfs 4096 Feb 16 23:48 external
dr-xr-xr-x  3 cvmfs cvmfs 4096 Feb 16 23:47 lib
lrwxrwxrwx  1 cvmfs cvmfs    3 Feb 16 23:48 lib64 -> lib
dr-xr-xr-x  3 cvmfs cvmfs 4096 Feb 16 23:48 share
dr-xr-xr-x  2 cvmfs cvmfs 4096 Sep 12 22:22 tools
dr-xr-xr-x 10 cvmfs cvmfs 4096 Sep 12 22:22 tutorials

x86_64/generic/software/ReFrame/4.3.3:
total 32
dr-xr-xr-x  2 cvmfs cvmfs 4096 Feb 16 23:50 bin
dr-xr-xr-x  3 cvmfs cvmfs 4096 Feb 16 23:50 easybuild
dr-xr-xr-x 93 cvmfs cvmfs 4096 Feb 16 23:50 external
dr-xr-xr-x  3 cvmfs cvmfs 4096 Feb 16 23:48 lib
lrwxrwxrwx  1 cvmfs cvmfs    3 Feb 16 23:50 lib64 -> lib
dr-xr-xr-x  3 cvmfs cvmfs 4096 Feb 16 23:50 share
dr-xr-xr-x  2 cvmfs cvmfs 4096 Sep 12 22:22 tools
dr-xr-xr-x 10 cvmfs cvmfs 4096 Sep 12 22:22 tutorials

x86_64/intel/broadwell/software/ReFrame/4.3.3:
total 32
dr-xr-xr-x  2 cvmfs cvmfs 4096 Feb 16 23:48 bin
dr-xr-xr-x  3 cvmfs cvmfs 4096 Feb 16 23:49 easybuild
dr-xr-xr-x 93 cvmfs cvmfs 4096 Feb 16 23:48 external
dr-xr-xr-x  3 cvmfs cvmfs 4096 Feb 16 23:46 lib
lrwxrwxrwx  1 cvmfs cvmfs    3 Feb 16 23:48 lib64 -> lib
dr-xr-xr-x  3 cvmfs cvmfs 4096 Feb 16 23:48 share
dr-xr-xr-x  2 cvmfs cvmfs 4096 Sep 12 22:22 tools
dr-xr-xr-x 10 cvmfs cvmfs 4096 Sep 12 22:22 tutorials

x86_64/intel/skylake_avx512/software/ReFrame/4.3.3:
total 32
dr-xr-xr-x  2 cvmfs cvmfs 4096 Feb 16 23:48 bin
dr-xr-xr-x  3 cvmfs cvmfs 4096 Feb 16 23:48 easybuild
dr-xr-xr-x 93 cvmfs cvmfs 4096 Feb 16 23:48 external
dr-xr-xr-x  3 cvmfs cvmfs 4096 Feb 16 23:45 lib
lrwxrwxrwx  1 cvmfs cvmfs    3 Feb 16 23:48 lib64 -> lib
dr-xr-xr-x  3 cvmfs cvmfs 4096 Feb 16 23:48 share
dr-xr-xr-x  2 cvmfs cvmfs 4096 Sep 12 22:22 tools
dr-xr-xr-x 10 cvmfs cvmfs 4096 Sep 12 22:22 tutorials 
```
</details>

**Review by poksumdo — APPROVED** [review]
Looks good. Some trouble uploading from `eX3`.

**Pull request merged**
