### PR TITLE
Add ImageMagick/7.0.11-14 with GCC/10.3.0 to NESSI/2022.11

### PR DESCRIPTION
**Pull request by TopRichard**
Trying to add ImageMagick/7.0.11.14 with GCC/10.3.0 to NESSI/2022.11

### CODE REVIEW

**Comment by trz42** [comment]
- [ ] did the builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
  - builds succeeded for `x86_64/generic`, `x86_64/intel/{broadwell,skylake_avx512,cascadelake}`
  - builds did NOT succeed for `x86_64/amd/zen2`
- [x] is the PR up-to-date with the target branch `nessi.no-2022.11-dev` in the repository (if not what are the differences)
- [x] are all requested changes sound (checking files changed on GitHub.com)
  - no rationale for building the package was given (not found as a separate build in original `EESSI-pilot-install-software.sh`)
- [x] is/are the easyconfig/s being built included with the EB version used (if not why not)
  - included with EB v4.7.0
- [ ] were any changes needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)
  
@TopRichard Failed only for `zen2`. It might just work out (on AWS) when you retrigger the building. A bit curious why ImageMagick was chosen ... just another "small" / "random" pick? Maybe information such as _Why should the package added?_ might help us understand the reasoning.

**Comment by TopRichard** [comment]
Maybe we can agree to set (the reason of adding a specific package) within the description field while opening the PR, i chose ImageMagick because i thought it has many dependencies so it can be considered at least mid ranged(not small) package and it will help in building all dependencies.

**Comment by trz42** [comment]
- [x] did the builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x] is the PR up-to-date with the target branch `nessi.no-2022.11-dev` in the repository (if not what are the differences)
- [x] are all requested changes sound (checking files changed on GitHub.com)
- [x] is/are the easyconfig/s being built included with the EB version used (if not why not)
- [x] were any changes needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)
  
@TopRichard Looks good. :tada: We can deploy it next.

**Comment by trz42** [comment]
Checklist for deployment
- [x] was at least one tarball for each architecture uploaded
- [ ] was at least one tarball for each architecture staged
- [ ] was at least one tarball for each architecture approved
- [ ] was at least one tarball for each architecture ingested
- [ ] has the package become available via CernVM-FS for all architectures ingested
  ```
  [EESSI pilot 2022.11] $ ls /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/x86_64/{generic,amd/zen2,intel/[bsc]*}/modules/all/ImageMagick/7.0.11-14*
  ```

**Review by trz42 — APPROVED** [review]
All built, ingested and available via CernVM-FS.

**Pull request merged**
