### PR TITLE
add GCC/12.2.0 to NESSI/2023.04

### PR DESCRIPTION
**Pull request by trz42**
Using [PR#2921](https://github.com/easybuilders/easybuild-easyblocks/pull/2921) via easystack file options.

### CODE REVIEW

**Comment by trz42** [comment]
bot: build repo:nessi.no-2023.04
- received bot command `build repo:nessi.no-2023.04` from `trz42` (expanded command format: `build repository:nessi.no-2023.04`)

**Comment by trz42** [comment]
With fixes to easyblock and ld wrappers used by EasyBuild we can make a new attempt to build this.

**Comment by trz42** [comment]
bot: build inst:eX3 repo:nessi.no-2023.04
bot: build inst:AWS repo:nessi.no-2023.04 arch:generic
bot: build inst:AWS repo:nessi.no-2023.04 arch:cascadelake
bot: build inst:Fram repo:nessi.no-2023.04 arch:broadwell
- received bot command `build inst:eX3 repo:nessi.no-2023.04` from `trz42` (expanded command format: `build instance:eX3 repository:nessi.no-2023.04`)
- received bot command `build inst:AWS repo:nessi.no-2023.04 arch:generic` from `trz42` (expanded command format: `build instance:AWS repository:nessi.no-2023.04 architecture:generic`)
- received bot command `build inst:AWS repo:nessi.no-2023.04 arch:cascadelake` from `trz42` (expanded command format: `build instance:AWS repository:nessi.no-2023.04 architecture:cascadelake`)
- received bot command `build inst:Fram repo:nessi.no-2023.04 arch:broadwell` from `trz42` (expanded command format: `build instance:Fram repository:nessi.no-2023.04 architecture:broadwell`)

**Comment by trz42** [comment]
bot: build inst:AWS repo:nessi.no-2023.04 arch:skylake
bot: build inst:AWS repo:nessi.no-2023.04 arch:zen2
bot: build inst:Fram repo:nessi.no-2023.04 arch:generic
- received bot command `build inst:AWS repo:nessi.no-2023.04 arch:skylake` from `trz42` (expanded command format: `build instance:AWS repository:nessi.no-2023.04 architecture:skylake`)
- received bot command `build inst:AWS repo:nessi.no-2023.04 arch:zen2` from `trz42` (expanded command format: `build instance:AWS repository:nessi.no-2023.04 architecture:zen2`)
- received bot command `build inst:Fram repo:nessi.no-2023.04 arch:generic` from `trz42` (expanded command format: `build instance:Fram repository:nessi.no-2023.04 architecture:generic`)

**Comment by trz42** [comment]
Checklist for building: 

- [x]  did the builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  is the PR up-to-date with the target branch nessi.no-2023.04-dev in the repository (if not what are the differences)
  - only missing commits are from #111, but this should be no problem to fix before merging; the build itself should not be influenced
- [x]  are all requested changes sound (checking files changed on GitHub.com)
- [x]  is/are the easyconfig/s being built included with the EB version used (if not why not)
- [x]  were any changes needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)
  - another hook was needed to provide missing ld RPATH wrappers

**Comment by trz42** [comment]
Checklist for deployment/ingestion

- [x] at least one tarball for each architecture has been uploaded
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512`
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] at least one tarball for each architecture has been staged
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512`
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] for each architecture **one and only one** tarball has been approved
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512`
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] for each architecture **one and only one** tarball was ingested
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512` 
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
  **command**
  ```
  ls -l /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/{GCC,GCCcore}/12.2.0*
  ls -l /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/aarch64/generic/{software,modules/all}/{GCC,GCCcore}/12.2.0*
  ```
  **log**
```
-rw-r--r--.  1 cvmfs cvmfs 1023 May 27 20:18 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/amd/zen2/modules/all/GCC/12.2.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1133 May 27 20:18 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/amd/zen2/modules/all/GCCcore/12.2.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1021 May 27 20:32 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/generic/modules/all/GCC/12.2.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1132 May 27 20:32 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/generic/modules/all/GCCcore/12.2.0.lua
-rw-rw-r--.  1 cvmfs cvmfs 1037 May 27 20:12 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/broadwell/modules/all/GCC/12.2.0.lua
-rw-rw-r--.  1 cvmfs cvmfs 1140 May 27 20:11 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/broadwell/modules/all/GCCcore/12.2.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1041 May 27 21:44 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/cascadelake/modules/all/GCC/12.2.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1142 May 27 21:44 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/cascadelake/modules/all/GCCcore/12.2.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1047 May 27 20:14 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/skylake_avx512/modules/all/GCC/12.2.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1145 May 27 20:13 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/skylake_avx512/modules/all/GCCcore/12.2.0.lua

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/amd/zen2/software/GCC/12.2.0:
total 5
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 27 20:18 easybuild

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/amd/zen2/software/GCCcore/12.2.0:
total 36
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 27 20:18 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 27 20:18 easybuild
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 27 20:01 include
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 27 20:01 lib
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 27 20:17 lib64
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 27 20:01 libexec
drwxr-xr-x. 5 cvmfs cvmfs 4096 May 27 20:17 nvptx-none
drwxr-xr-x. 6 cvmfs cvmfs 4096 May 27 20:01 share

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/generic/software/GCC/12.2.0:
total 5
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 27 20:32 easybuild

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/generic/software/GCCcore/12.2.0:
total 36
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 27 20:32 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 27 20:32 easybuild
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 27 20:18 include
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 27 20:17 lib
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 27 20:31 lib64
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 27 20:17 libexec
drwxr-xr-x. 5 cvmfs cvmfs 4096 May 27 20:32 nvptx-none
drwxr-xr-x. 6 cvmfs cvmfs 4096 May 27 20:18 share

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/broadwell/software/GCC/12.2.0:
total 5
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 27 20:12 easybuild

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/broadwell/software/GCCcore/12.2.0:
total 36
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 27 20:11 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 27 20:12 easybuild
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 27 19:54 include
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 27 19:53 lib
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 27 20:11 lib64
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 27 19:53 libexec
drwxr-xr-x. 5 cvmfs cvmfs 4096 May 27 20:11 nvptx-none
drwxr-xr-x. 6 cvmfs cvmfs 4096 May 27 19:54 share

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/cascadelake/software/GCC/12.2.0:
total 5
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 27 21:44 easybuild

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/cascadelake/software/GCCcore/12.2.0:
total 36
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 27 21:44 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 27 21:44 easybuild
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 27 21:35 include
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 27 21:34 lib
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 27 21:44 lib64
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 27 21:34 libexec
drwxr-xr-x. 5 cvmfs cvmfs 4096 May 27 21:44 nvptx-none
drwxr-xr-x. 6 cvmfs cvmfs 4096 May 27 21:35 share

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/skylake_avx512/software/GCC/12.2.0:
total 5
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 27 20:14 easybuild

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/skylake_avx512/software/GCCcore/12.2.0:
total 36
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 27 20:13 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 27 20:14 easybuild
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 27 20:02 include
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 27 20:02 lib
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 27 20:13 lib64
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 27 20:02 libexec
drwxr-xr-x. 5 cvmfs cvmfs 4096 May 27 20:13 nvptx-none
drwxr-xr-x. 6 cvmfs cvmfs 4096 May 27 20:02 share

-rw-r--r--.  1 cvmfs cvmfs 1023 May 27 21:05 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/aarch64/generic/modules/all/GCC/12.2.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1133 May 27 21:04 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/aarch64/generic/modules/all/GCCcore/12.2.0.lua

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/aarch64/generic/software/GCC/12.2.0:
total 5
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 27 21:05 easybuild

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/aarch64/generic/software/GCCcore/12.2.0:
total 36
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 27 21:04 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 27 21:05 easybuild
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 27 20:35 include
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 27 20:35 lib
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 27 21:03 lib64
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 27 20:35 libexec
drwxr-xr-x. 5 cvmfs cvmfs 4096 May 27 21:04 nvptx-none
drwxr-xr-x. 6 cvmfs cvmfs 4096 May 27 20:35 share 
```

**Review by TopRichard — APPROVED** [review]

**Pull request merged**
