### PR TITLE
{2023.06}[foss/2021a] WRF-dmpar V4.3

### PR DESCRIPTION
**Pull request by TopRichard**

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11arch:x86_64/intel/cascadelake
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11arch:x86_64/intel/cascadelake
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake

**Comment by TopRichard** [comment]
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb10 arch:x86_64/intel/broadwell

**Comment by TopRichard** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11arch:x86_64/intel/cascadelake

**Comment by TopRichard** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/cascadelake

**Comment by TopRichard** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/cascadelake
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake

**Comment by TopRichard** [comment]
Checklist for building: {2023.06}[foss/2021a] WRF-dmpar V4.3] https://github.com/NorESSI/software-layer/pull/166

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by TopRichard** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-intel-cascadelake`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [] encountered issues in the ingestion, likely related to troubles interacting with GitHub via PyGithub … 
- [ ] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; 
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/WRF/4.3-foss-2021a-dmpar* \
        aarch64/generic/{software,modules/all}/WRF/4.3-foss-2021a-dmpar*
  
-rw-r--r--. 1 cvmfs cvmfs 1747 Sep 20 10:51 aarch64/generic/modules/all/WRF/4.3-foss-2021a-dmpar.lua
-rw-r--r--. 1 cvmfs cvmfs 1747 Sep 20 08:13 x86_64/amd/zen2/modules/all/WRF/4.3-foss-2021a-dmpar.lua
-rw-r--r--. 1 cvmfs cvmfs 1744 Sep 20 09:18 x86_64/generic/modules/all/WRF/4.3-foss-2021a-dmpar.lua
-rw-rw-r--. 1 cvmfs cvmfs 1768 Sep 20 10:42 x86_64/intel/broadwell/modules/all/WRF/4.3-foss-2021a-dmpar.lua
-rw-rw-r--. 1 cvmfs cvmfs 1774 Sep 20 14:24 x86_64/intel/cascadelake/modules/all/WRF/4.3-foss-2021a-dmpar.lua
-rw-rw-r--. 1 cvmfs cvmfs 1783 Sep 20 09:34 x86_64/intel/skylake_avx512/modules/all/WRF/4.3-foss-2021a-dmpar.lua

aarch64/generic/software/WRF/4.3-foss-2021a-dmpar:
total 9
dr-xr-xr-x.  3 cvmfs cvmfs 4096 Sep 20 10:52 easybuild
dr-xr-xr-x. 21 cvmfs cvmfs 4096 Sep 20 06:46 WRF-4.3

x86_64/amd/zen2/software/WRF/4.3-foss-2021a-dmpar:
total 9
dr-xr-xr-x.  3 cvmfs cvmfs 4096 Sep 20 08:13 easybuild
dr-xr-xr-x. 21 cvmfs cvmfs 4096 Sep 20 06:42 WRF-4.3

x86_64/generic/software/WRF/4.3-foss-2021a-dmpar:
total 9
dr-xr-xr-x.  3 cvmfs cvmfs 4096 Sep 20 09:19 easybuild
dr-xr-xr-x. 21 cvmfs cvmfs 4096 Sep 20 06:53 WRF-4.3

x86_64/intel/broadwell/software/WRF/4.3-foss-2021a-dmpar:
total 9
dr-xr-xr-x.  3 cvmfs cvmfs 4096 Sep 20 10:42 easybuild
dr-xr-xr-x. 21 cvmfs cvmfs 4096 Sep 20 08:15 WRF-4.3

x86_64/intel/cascadelake/software/WRF/4.3-foss-2021a-dmpar:
total 9
dr-xr-xr-x.  3 cvmfs cvmfs 4096 Sep 20 14:24 easybuild
dr-xr-xr-x. 21 cvmfs cvmfs 4096 Sep 20 11:17 WRF-4.3

x86_64/intel/skylake_avx512/software/WRF/4.3-foss-2021a-dmpar:
total 9
dr-xr-xr-x.  3 cvmfs cvmfs 4096 Sep 20 14:24 easybuild
dr-xr-xr-x. 21 cvmfs cvmfs 4096 Sep 20 11:17 WRF-4.3

x86_64/intel/skylake_avx512/software/WRF/4.3-foss-2021a-dmpar:
total 9
dr-xr-xr-x.  3 cvmfs cvmfs 4096 Sep 20 09:34 easybuild
dr-xr-xr-x. 21 cvmfs cvmfs 4096 Sep 20 06:46 WRF-4.3

```
</details>

**Review by justadejavu — APPROVED** [review]

**Pull request merged**
