### PR TITLE
workaround for LMOD to register two hooks

### PR DESCRIPTION
**Pull request by trz42**
PR to sync changes made in https://github.com/EESSI/software-layer/pull/490

We need to build and ingest the tarballs.

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb11 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
Checklist before starting deployment (setting `bot:deploy` label): 

- [x]  Check if the _SPDX license identifier_ is provided
  - not needed because no software was built (just updating an Lmod config script)
- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
  - no easyconfigs were used
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each staged tarball was a PR for approval/rejection opened
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
  - no rerun needed as CI is independent of changes to `lmodrc.lua`
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
  - file `lmodrc.lua` for `cascadelake` wasn't updated (which is fine); should remove software branch for this microarchitecture
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/.lmod/lmodrc.lua \
        aarch64/generic/.lmod/lmodrc.lua
  ```
  **log**
```
-rw-r--r--. 1 cvmfs cvmfs 5908 Apr  7 00:42 aarch64/generic/.lmod/lmodrc.lua
-rw-r--r--. 1 cvmfs cvmfs 5908 Apr  7 00:46 x86_64/amd/zen2/.lmod/lmodrc.lua
-rw-r--r--. 1 cvmfs cvmfs 5906 Apr  7 00:46 x86_64/generic/.lmod/lmodrc.lua
-rw-rw-r--. 1 cvmfs cvmfs 5922 Apr  7 00:41 x86_64/intel/broadwell/.lmod/lmodrc.lua
-rw-r--r--. 1 cvmfs cvmfs  283 Jun 18  2023 x86_64/intel/cascadelake/.lmod/lmodrc.lua
-rw-r--r--. 1 cvmfs cvmfs 5932 Apr  7 00:42 x86_64/intel/skylake_avx512/.lmod/lmodrc.lua
```
</details>

**Review by poksumdo — APPROVED** [review]
All ingested.

**Pull request merged**
