### PR TITLE
add CMake, Python, OpenMPI and ImageMagick with GCC/10.3.0 to NESSI/2022.11 (generic only)

### PR DESCRIPTION
**Pull request by trz42**
Installing
- `CMake-3.20.1-GCCcore-10.3.0.eb`
- `Python-3.9.5-GCCcore-10.3.0.eb`
- `OpenMPI-4.1.1-GCC-10.3.0.eb`
- `ImageMagick-7.0.11-14-GCCcore-10.3.0.eb`

### CODE REVIEW

**Comment by trz42** [comment]
Closes #75

**Comment by trz42** [comment]
Fails because of OpenSSL test issue on Saga and Fram ... since we would not ingest the builds from there we let it go on and see if it builds on AWS (x86_64/generic/Haswell) and eX3 (aarch64/generic/ThunderX2) we ingest those without the need to patch the OpenSSL easyconfig.

**Comment by trz42** [comment]
- [ ] did the builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
  -  [ ] `x86_64-generic` on `AWS-NESSI` (Haswell) succeeded with reasonably sized tarball
  -  [ ] `aarch64-generic` on `eX3-NESSI` (ThunderX2) succeeded with reasonably sized tarball
- [ ] is the PR up-to-date with the target branch `nessi.no-2022.11-generic-rebuild` in the repository (if not what are the differences)
- [ ] are all requested changes sound (checking files changed on GitHub.com)
  - yes, but the EB command for ImageMagick is commented out in `EESSI-pilot-install-software.sh` while it is present in `eessi-2022.11.yml`
  - could be a result of pulling in updated `nessi.no-2022.11-generic-rebuild` $\longrightarrow$ check files in actual job directories
- [ ] is/are the easyconfig/s being built included with the EB version used (if not why not)
- [ ] were any changes needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)
  - no changes needed

**Comment by trz42** [comment]
Need to rebuild all.

**Comment by trz42** [comment]
Updated to latest state of rebuild branch. Need to rebuild.

**Comment by trz42** [comment]
- [x] did the builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
  -  [x] `x86_64-generic` on `AWS-NESSI` (Haswell) succeeded with reasonably sized tarball
    - couldn't really compare to builds on Saga & Fram because they failed due to failing OpenSSL test
  -  [x] `aarch64-generic` on `eX3-NESSI` (ThunderX2) succeeded with reasonably sized tarball
- [x] is the PR up-to-date with the target branch `nessi.no-2022.11-generic-rebuild` in the repository (if not what are the differences)
- [x] are all requested changes sound (checking files changed on GitHub.com)
  - yes, but a section for OpenBLAS was prepared, then commented ... maybe we should not do that in the future _or_ we might confuse a reviewer
- [x] is/are the easyconfig/s being built included with the EB version used (if not why not)
- [x] were any changes needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)
  - no changes needed

**Comment by trz42** [comment]
Checklist for deployment
- [x] at least one tarball for each architecture has been uploaded
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] at least one tarball for each architecture has been staged
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] for each architecture **one and only one** tarball was approved (for `generic` the tarball built on the oldest architecture shall be ingested ... lower risk that `generic` build is not really `generic`)
  - we only ingest one tarball for each of `aarch64/generic` and `x86_64/generic`
  - tarballs for other architectures have been rejected
  - [x] for `x86_64/generic` we chose a build from AWS (built on Haswell)
  - [x] for `aarch64/generic` we chose a build from eX3 (built on ThunderX2)
- [x] for each architecture **one and only one** tarball was ingested
  - [x] `x86_64-generic` see https://github.com/NorESSI/software-layer/pull/72#issuecomment-1478521852
  - [x] `aarch64-generic` see https://github.com/NorESSI/software-layer/pull/72#issuecomment-1478521621
- [x] has the package become available via CernVM-FS for all architectures ingested
  ```
  ls -l /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/{x86_64,aarch64}/generic/modules/all/{CMake,OpenMPI,Python,ImageMagick}/*
  ls -l /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/{x86_64,aarch64}/generic/software/{CMake,OpenMPI,Python,ImageMagick}/*
  ```
  - [x] `x86_64-generic`

    **command**
    ```
    ls -l /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/x86_64/generic/{modules/all,software}/{OpenBLAS,OpenMPI,Python,Perl}/*
    ```
    **output**
    ```
    too much to copy
    ```
  - [x] `aarch64`

    **command**
    ```
    ls -l /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/x86_64/generic/{modules/all,software}/{OpenBLAS,OpenMPI,Python,Perl}/*
    ```
    **output**
    ```
    too much to copy
    ```

**Review by poksumdo — APPROVED** [review]
All looking good. Quite some work. Getting closer to the "main" dev branch.

**Pull request merged**
