### PR TITLE
Fix archdetect: ensure we use instructions introduced with ARM v8.2 for Neoverse N1

### PR DESCRIPTION
**Pull request by TopRichard**
Sync NESSI with EESSI (PR 540)

On the Raspberry Pi 4, we've seen incorrect matching to Neoverse N1 due to checking an instruction that is actually available with ARM v8.0 (rather than something introduced in ARM v8.2)

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
@trz42 , requires manual change as the tarball step doesn't seem to pick this up .

**Comment by TopRichard** [comment]
Will handle this PR after #360  to avoid manual steps.

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
Checklist before starting deployment (setting `bot:deploy` label): 

- [x]  Check if the _SPDX license identifier_ is provided 
  - internal script from repo
- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
  - only a single build is needed because the CVMFS repo contains a single file for all architectures 
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
  - no easyconfigs being used 
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Target architectures
  - only a single file under `init` top-level directory will be ingested

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each staged tarball was a PR for approval/rejection opened
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
  - all CI already green; no need to rerun 
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  ls -l /cvmfs/pilot.nessi.no/versions/2023.06/init/arch_specs/eessi_arch_arm.spec
  ```
  **log**
```
 
```
</details>

**Review by trz42 — APPROVED** [review]
looks good

**Pull request merged**
