### PR TITLE
{2023.06}[foss/2022b] GDAL v3.6.2

### PR DESCRIPTION
**Pull request by trz42**
Syncing NESSI with EESSI (PR 419).

SPDX license identifier: MIT style license

Missing installations:
```
32 out of 90 required modules missing:

* Szip/2.1.1-GCCcore-12.2.0 (Szip-2.1.1-GCCcore-12.2.0.eb)
* GEOS/3.11.1-GCC-12.2.0 (GEOS-3.11.1-GCC-12.2.0.eb)
* PCRE/8.45-GCCcore-12.2.0 (PCRE-8.45-GCCcore-12.2.0.eb)
* googletest/1.12.1-GCCcore-12.2.0 (googletest-1.12.1-GCCcore-12.2.0.eb)
* nlohmann_json/3.11.2-GCCcore-12.2.0 (nlohmann_json-3.11.2-GCCcore-12.2.0.eb)
* PROJ/9.1.1-GCCcore-12.2.0 (PROJ-9.1.1-GCCcore-12.2.0.eb)
* libgeotiff/1.7.1-GCCcore-12.2.0 (libgeotiff-1.7.1-GCCcore-12.2.0.eb)
* HDF5/1.14.0-gompi-2022b (HDF5-1.14.0-gompi-2022b.eb)
* netCDF/4.9.0-gompi-2022b (netCDF-4.9.0-gompi-2022b.eb)
* hypothesis/6.68.2-GCCcore-12.2.0 (hypothesis-6.68.2-GCCcore-12.2.0.eb)
* libtirpc/1.3.3-GCCcore-12.2.0 (libtirpc-1.3.3-GCCcore-12.2.0.eb)
* HDF/4.2.15-GCCcore-12.2.0 (HDF-4.2.15-GCCcore-12.2.0.eb)
* CFITSIO/4.2.0-GCCcore-12.2.0 (CFITSIO-4.2.0-GCCcore-12.2.0.eb)
* giflib/5.2.1-GCCcore-12.2.0 (giflib-5.2.1-GCCcore-12.2.0.eb)
* Boost/1.81.0-GCC-12.2.0 (Boost-1.81.0-GCC-12.2.0.eb)
* json-c/0.16-GCCcore-12.2.0 (json-c-0.16-GCCcore-12.2.0.eb)
* Eigen/3.4.0-GCCcore-12.2.0 (Eigen-3.4.0-GCCcore-12.2.0.eb)
* Xerces-C++/3.2.4-GCCcore-12.2.0 (Xerces-C++-3.2.4-GCCcore-12.2.0.eb)
* Catch2/2.13.9-GCCcore-12.2.0 (Catch2-2.13.9-GCCcore-12.2.0.eb)
* pybind11/2.10.3-GCCcore-12.2.0 (pybind11-2.10.3-GCCcore-12.2.0.eb)
* Imath/3.1.6-GCCcore-12.2.0 (Imath-3.1.6-GCCcore-12.2.0.eb)
* OpenEXR/3.1.5-GCCcore-12.2.0 (OpenEXR-3.1.5-GCCcore-12.2.0.eb)
* gfbf/2022b (gfbf-2022b.eb)
* SciPy-bundle/2023.02-gfbf-2022b (SciPy-bundle-2023.02-gfbf-2022b.eb)
* arpack-ng/3.8.0-foss-2022b (arpack-ng-3.8.0-foss-2022b.eb)
* Armadillo/11.4.3-foss-2022b (Armadillo-11.4.3-foss-2022b.eb)
* Qhull/2020.2-GCCcore-12.2.0 (Qhull-2020.2-GCCcore-12.2.0.eb)
* LERC/4.0.0-GCCcore-12.2.0 (LERC-4.0.0-GCCcore-12.2.0.eb)
* Highway/1.0.3-GCCcore-12.2.0 (Highway-1.0.3-GCCcore-12.2.0.eb)
* Brunsli/0.1-GCCcore-12.2.0 (Brunsli-0.1-GCCcore-12.2.0.eb)
* OpenJPEG/2.5.0-GCCcore-12.2.0 (OpenJPEG-2.5.0-GCCcore-12.2.0.eb)
* GDAL/3.6.2-foss-2022b (GDAL-3.6.2-foss-2022b.eb)
```

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb10 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by trz42** [comment]
bot: build inst:AWS repo:nessi-2023.06-swl-deb10 arch:x86_64/generic

**Comment by trz42** [comment]
bot: build inst:AWS repo:nessi-2023.06-swl-deb10 arch:x86_64/generic
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
Checklist before starting deployment (setting `bot:deploy` label): 

- [x]  Check if the _SPDX license identifier_ is provided 
- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
  - arch `x86_64/generic` required some extra attempts 
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each staged tarball was a PR for approval/rejection opened
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/GDAL/3.6.2* \
        aarch64/generic/{software,modules/all}/GDAL/3.6.2*
  ```
  **log**
```
-rw-r--r-- 1 cvmfs cvmfs 4632 Apr 14 15:12 aarch64/generic/modules/all/GDAL/3.6.2-foss-2022b.lua
-rw-rw-r-- 1 cvmfs cvmfs 4632 Apr 14 13:23 x86_64/amd/zen2/modules/all/GDAL/3.6.2-foss-2022b.lua
-rw-rw-r-- 1 cvmfs cvmfs 4631 Apr 14 20:50 x86_64/generic/modules/all/GDAL/3.6.2-foss-2022b.lua
-rw-rw-r-- 1 cvmfs cvmfs 4639 Apr 14 15:24 x86_64/intel/broadwell/modules/all/GDAL/3.6.2-foss-2022b.lua
-rw-rw-r-- 1 cvmfs cvmfs 4644 Apr 14 13:50 x86_64/intel/skylake_avx512/modules/all/GDAL/3.6.2-foss-2022b.lua

aarch64/generic/software/GDAL/3.6.2-foss-2022b:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Apr 14 15:12 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Apr 14 15:12 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Apr 14 15:12 include
dr-xr-xr-x 6 cvmfs cvmfs 4096 Apr 14 15:12 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Apr 14 15:12 lib64 -> lib
dr-xr-xr-x 5 cvmfs cvmfs 4096 Apr 14 14:52 share

x86_64/amd/zen2/software/GDAL/3.6.2-foss-2022b:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Apr 14 13:23 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Apr 14 13:23 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Apr 14 13:23 include
dr-xr-xr-x 6 cvmfs cvmfs 4096 Apr 14 13:23 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Apr 14 13:23 lib64 -> lib
dr-xr-xr-x 5 cvmfs cvmfs 4096 Apr 14 13:13 share

x86_64/generic/software/GDAL/3.6.2-foss-2022b:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Apr 14 20:50 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Apr 14 20:50 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Apr 14 20:50 include
dr-xr-xr-x 6 cvmfs cvmfs 4096 Apr 14 20:50 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Apr 14 20:50 lib64 -> lib
dr-xr-xr-x 5 cvmfs cvmfs 4096 Apr 14 20:42 share

x86_64/intel/broadwell/software/GDAL/3.6.2-foss-2022b:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Apr 14 15:24 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Apr 14 15:25 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Apr 14 15:24 include
dr-xr-xr-x 6 cvmfs cvmfs 4096 Apr 14 15:24 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Apr 14 15:24 lib64 -> lib
dr-xr-xr-x 5 cvmfs cvmfs 4096 Apr 14 15:19 share

x86_64/intel/skylake_avx512/software/GDAL/3.6.2-foss-2022b:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Apr 14 13:50 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Apr 14 13:50 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Apr 14 13:50 include
dr-xr-xr-x 6 cvmfs cvmfs 4096 Apr 14 13:50 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Apr 14 13:50 lib64 -> lib
dr-xr-xr-x 5 cvmfs cvmfs 4096 Apr 14 13:41 share 
```
</details>

**Review by poksumdo — APPROVED** [review]
All ok.

**Pull request merged**
