### PR TITLE
{23.06} GCC/11.3.0

### PR DESCRIPTION
**Pull request by trz42**
Add GCC/11.3.0 to NESSI/2023.06

### CODE REVIEW

**Comment by trz42** [comment]
bot: build repo:nessi.no-2023.06-software inst:eX3 arch:aarch64/generic
bot: build repo:nessi.no-2023.06-software inst:eX3 arch:zen2
bot: build repo:nessi.no-2023.06-software inst:Fram arch:broadwell
bot: build repo:nessi.no-2023.06-software inst:AWS arch:x86_64/generic
bot: build repo:nessi.no-2023.06-software inst:AWS arch:cascade
bot: build repo:nessi.no-2023.06-software inst:AWS arch:skylake

**Comment by trz42** [comment]
bot: build repo:nessi.no-2023.06-software inst:AWS arch:x86_64/generic
bot: build repo:nessi.no-2023.06-software inst:AWS arch:zen2
bot: build repo:nessi.no-2023.06-software inst:AWS arch:skylake

**Comment by trz42** [comment]
Checklist for building: 

- [x]  did the builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  is the PR up-to-date with the target branch nessi.no-2022.11-dev in the repository (if not what are the differences)
- [x]  are all requested changes sound (checking files changed on GitHub.com)
- [x]  is/are the easyconfig/s being built included with the EB version used (if not why not)
- [x]  were any changes needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Checklist for deployment/ingestion

- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
  **command**
  ```
  ls -l /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/{GCC,GCCcore}/11.3.0*
  ls -l /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/{software,modules/all}/{GCC,GCCcore}/11.3.0*
  ```
  **log**
```
$ ls -l /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/{GCC,GCCcore}/11.3.0*
-rw-r--r--.  1 cvmfs cvmfs 1121 Jun 27 23:05 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all/GCC/11.3.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1231 Jun 27 23:05 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all/GCCcore/11.3.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1119 Jun 27 22:14 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/modules/all/GCC/11.3.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1230 Jun 27 22:14 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/modules/all/GCCcore/11.3.0.lua
-rw-rw-r--.  1 cvmfs cvmfs 1135 Jun 27 18:37 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/modules/all/GCC/11.3.0.lua
-rw-rw-r--.  1 cvmfs cvmfs 1238 Jun 27 18:36 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/modules/all/GCCcore/11.3.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1139 Jun 27 20:27 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/modules/all/GCC/11.3.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1240 Jun 27 20:27 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/modules/all/GCCcore/11.3.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1145 Jun 27 21:51 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/modules/all/GCC/11.3.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1243 Jun 27 21:51 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/modules/all/GCCcore/11.3.0.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/software/GCC/11.3.0:
total 5
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 23:05 easybuild

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/software/GCCcore/11.3.0:
total 36
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 27 23:04 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 23:05 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 22:51 include
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 22:51 lib
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 27 23:04 lib64
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 22:51 libexec
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jun 27 23:04 nvptx-none
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jun 27 22:52 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/software/GCC/11.3.0:
total 5
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 22:14 easybuild

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/software/GCCcore/11.3.0:
total 36
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 27 22:14 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 22:14 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 21:53 include
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 21:53 lib
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 27 22:14 lib64
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 21:53 libexec
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jun 27 22:14 nvptx-none
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jun 27 21:53 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/software/GCC/11.3.0:
total 5
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 18:37 easybuild

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/software/GCCcore/11.3.0:
total 36
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 27 18:36 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 18:36 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 18:24 include
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 18:23 lib
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 27 18:36 lib64
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 18:23 libexec
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jun 27 18:36 nvptx-none
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jun 27 18:24 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/software/GCC/11.3.0:
total 5
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 20:27 easybuild

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/software/GCCcore/11.3.0:
total 36
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 27 20:27 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 20:27 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 20:14 include
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 20:13 lib
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 27 20:26 lib64
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 20:13 libexec
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jun 27 20:26 nvptx-none
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jun 27 20:14 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/GCC/11.3.0:
total 5
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 21:51 easybuild

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/GCCcore/11.3.0:
total 36
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 27 21:50 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 21:51 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 21:34 include
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 21:33 lib
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 27 21:50 lib64
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 21:33 libexec
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jun 27 21:50 nvptx-none
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jun 27 21:34 share

-rw-r--r--.  1 cvmfs cvmfs 1121 Jun 27 19:28 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/modules/all/GCC/11.3.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1231 Jun 27 19:27 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/modules/all/GCCcore/11.3.0.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/software/GCC/11.3.0:
total 5
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 19:28 easybuild

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/software/GCCcore/11.3.0:
total 36
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 27 19:27 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 19:28 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 19:03 include
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 19:02 lib
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 27 19:27 lib64
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 19:02 libexec
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jun 27 19:27 nvptx-none
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jun 27 19:03 share 
```

**Review by poksumdo — APPROVED** [review]
lgtm

**Pull request merged**
