### PR TITLE
{2023.06}[foss/2023a] ESPResSo V4.2.2

### PR DESCRIPTION
**Pull request by TopRichard**
Sync with EESSI PR 584
Lic --> GPL

```
1 out of 87 required modules missing:

* ESPResSo/4.2.2-foss-2023a (ESPResSo-4.2.2-foss-2023a.eb)
```

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
Checklist before starting deployment (setting bot:deploy label):

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by TopRichard** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x]  Check if the _SPDX license identifier_ is provided 
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI for the ingested tarballs have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)

<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; 
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/ESPResSo/4.2.2-foss-2023a* \
        aarch64/generic/{software,modules/all}/ESPResSo/4.2.2-foss-2023a*
  ```
  **log**
```
-rw-r--r--. 1 cvmfs cvmfs 1864 May 29 07:57 aarch64/generic/modules/all/ESPResSo/4.2.2-foss-2023a.lua
-rw-rw-r--. 1 cvmfs cvmfs 1864 May 29 07:54 x86_64/amd/zen2/modules/all/ESPResSo/4.2.2-foss-2023a.lua
-rw-rw-r--. 1 cvmfs cvmfs 1863 May 29 07:52 x86_64/generic/modules/all/ESPResSo/4.2.2-foss-2023a.lua
-rw-rw-r--. 1 cvmfs cvmfs 1871 May 29 08:17 x86_64/intel/broadwell/modules/all/ESPResSo/4.2.2-foss-2023a.lua
-rw-rw-r--. 1 cvmfs cvmfs 1876 May 29 07:53 x86_64/intel/skylake_avx512/modules/all/ESPResSo/4.2.2-foss-2023a.lua

aarch64/generic/software/ESPResSo/4.2.2-foss-2023a:
total 14
dr-xr-xr-x. 2 cvmfs cvmfs 4096 May 29 07:56 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May 29 07:57 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May 29 07:56 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 May 29 07:56 lib64 -> lib

x86_64/amd/zen2/software/ESPResSo/4.2.2-foss-2023a:
total 14
dr-xr-xr-x. 2 cvmfs cvmfs 4096 May 29 07:54 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May 29 07:55 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May 29 07:54 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 May 29 07:54 lib64 -> lib

x86_64/generic/software/ESPResSo/4.2.2-foss-2023a:
total 14
dr-xr-xr-x. 2 cvmfs cvmfs 4096 May 29 07:51 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May 29 07:52 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May 29 07:51 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 May 29 07:51 lib64 -> lib

x86_64/intel/broadwell/software/ESPResSo/4.2.2-foss-2023a:
total 14
dr-xr-xr-x. 2 cvmfs cvmfs 4096 May 29 08:17 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May 29 08:17 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May 29 08:17 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 May 29 08:17 lib64 -> lib

x86_64/intel/skylake_avx512/software/ESPResSo/4.2.2-foss-2023a:
total 14
dr-xr-xr-x. 2 cvmfs cvmfs 4096 May 29 07:52 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May 29 07:53 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May 29 07:52 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 May 29 07:52 lib64 -> lib

```
</details>

**Review by justadejavu — APPROVED** [review]
lgtm

**Pull request merged**
