### PR TITLE
{2023.06}[gompi/2022a] OpenBabel V3.1.1

### PR DESCRIPTION
**Pull request by TopRichard**
Trying to build OpenBabel/3.1.1-gompi/2022a as a step forward for getting closer to the current available HPC software stack.
License:https://spdx.org/licenses/GPL-2.0-only.html
Will install the following packages:
```
* SWIG/4.0.2-GCCcore-11.3.0 (SWIG-4.0.2-GCCcore-11.3.0.eb)
* RapidJSON/1.1.0-GCCcore-11.3.0 (RapidJSON-1.1.0-GCCcore-11.3.0.eb)
* maeparser/1.3.0-gompi-2022a (maeparser-1.3.0-gompi-2022a.eb)
* CoordgenLibs/3.0.1-gompi-2022a (CoordgenLibs-3.0.1-gompi-2022a.eb)
* OpenBabel/3.1.1-gompi-2022a (OpenBabel-3.1.1-gompi-2022a.eb)
```

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/cascadelake 
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake 
bot: build inst:AWS repo:nessi-2023.06-swl-deb10 arch:zen2
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb10 arch:x86_64/intel/broadwell
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:eX3 repo:nessi-2023.06-swl-deb10 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by trz42** [comment]
Can start deployment. Do tasks described in https://gitlab.sigma2.no/nessi/pilot/-/issues/7

**Comment by trz42** [comment]
Checklist for building: 

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
  - Didn't succeed for `aarch64/generic`.
  - Listed this PR in https://gitlab.sigma2.no/nessi/pilot/-/issues/7
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - ~`x86_64-intel-cascadelake`~ (dropped in general)
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - ~`aarch64-generic`~ (not successfully built in this PR)

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
  - Needs an update CI first, see https://github.com/NorESSI/software-layer/actions/runs/6757086696/workflow#L29
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/OpenBabel/* \
        aarch64/generic/{software,modules/all}/OpenBabel/*
  ```
  **log**
```
ls: cannot access 'aarch64/generic/software/OpenBabel/*': No such file or directory
ls: cannot access 'aarch64/generic/modules/all/OpenBabel/*': No such file or directory
-rw-rw-r-- 1 cvmfs cvmfs 2770 Nov  4 22:04  x86_64/amd/zen2/modules/all/OpenBabel/3.1.1-gompi-2022a.lua
-rw-rw-r-- 1 cvmfs cvmfs 2767 Nov  4 22:05  x86_64/generic/modules/all/OpenBabel/3.1.1-gompi-2022a.lua
-rw-rw-r-- 1 cvmfs cvmfs 2791 Nov  4 22:04  x86_64/intel/broadwell/modules/all/OpenBabel/3.1.1-gompi-2022a.lua
-rw-rw-r-- 1 cvmfs cvmfs 2806 Nov  4 22:13  x86_64/intel/skylake_avx512/modules/all/OpenBabel/3.1.1-gompi-2022a.lua

x86_64/amd/zen2/software/OpenBabel/3.1.1-gompi-2022a:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Nov  4 22:02 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Nov  4 22:04 easybuild
dr-xr-xr-x 4 cvmfs cvmfs 4096 Nov  4 22:02 include
dr-xr-xr-x 6 cvmfs cvmfs 4096 Nov  4 22:02 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Nov  4 22:02 lib64 -> lib
dr-xr-xr-x 4 cvmfs cvmfs 4096 Nov  4 22:02 share

x86_64/generic/software/OpenBabel/3.1.1-gompi-2022a:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Nov  4 22:04 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Nov  4 22:05 easybuild
dr-xr-xr-x 4 cvmfs cvmfs 4096 Nov  4 22:04 include
dr-xr-xr-x 6 cvmfs cvmfs 4096 Nov  4 22:04 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Nov  4 22:04 lib64 -> lib
dr-xr-xr-x 4 cvmfs cvmfs 4096 Nov  4 22:04 share

x86_64/intel/broadwell/software/OpenBabel/3.1.1-gompi-2022a:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Nov  4 22:04 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Nov  4 22:04 easybuild
dr-xr-xr-x 4 cvmfs cvmfs 4096 Nov  4 22:04 include
dr-xr-xr-x 6 cvmfs cvmfs 4096 Nov  4 22:04 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Nov  4 22:04 lib64 -> lib
dr-xr-xr-x 4 cvmfs cvmfs 4096 Nov  4 22:04 share

x86_64/intel/skylake_avx512/software/OpenBabel/3.1.1-gompi-2022a:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Nov  4 22:12 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Nov  4 22:13 easybuild
dr-xr-xr-x 4 cvmfs cvmfs 4096 Nov  4 22:12 include
dr-xr-xr-x 6 cvmfs cvmfs 4096 Nov  4 22:12 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Nov  4 22:12 lib64 -> lib
dr-xr-xr-x 4 cvmfs cvmfs 4096 Nov  4 22:12 share 
```
</details>

**Review by trz42 — APPROVED** [review]
All good now! :100:

**Pull request merged**
