### PR TITLE
{2023.06}[foss/2022a] CDO V2.0.6

### PR DESCRIPTION
**Pull request by TopRichard**
Trying to add CDO-foss/2022a as a client request, in addition that it is a package which adds essential software to the stack.
license: https://spdx.org/licenses/BSD-3-Clause.html
All modules that will be installed:
```
CDO/2.0.6-gompi-2022a
googletest/1.11.0-GCCcore-11.3.0
nlohmann_json/3.10.5-GCCcore-11.3.0
PROJ/9.0.0-GCCcore-11.3.0
```

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/cascadelake
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/cascadelake 
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake

**Comment by TopRichard** [comment]
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb10 arch:x86_64/intel/broadwell

**Comment by TopRichard** [comment]
bot: build inst:eX3 repo:nessi-2023.06-swl-deb10 arch:aarch64/generic

**Comment by TopRichard** [comment]
Missing only build for aarch64

**Comment by trz42** [comment]
Likely has to be rebuilt because dependencies were ingested in the meantime.

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake 
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by TopRichard** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb10 arch:x86_64/intel/broadwell

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
@trz42  , The same package builds for EESSI : https://github.com/EESSI/software-layer/pull/373 just as it used to do 3 weeks ago.

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb10 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
The branch has been synced with the target, yet not additional differences existed but the addition of EasyBuild in another system-yml file and modifications to the CI script. So no rebuild is necessary.

**Comment by TopRichard** [comment]
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:zen2

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2

**Comment by TopRichard** [comment]
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSIrepo:nessi-2023.06-swl-deb11 arch:x86_64/intel/cascadelake

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/cascadelake

**Pull request closed without merging**
