### PR TITLE
{2023.06}[foss/2023b] DP3-6.0, WSClean 3.4 and deps

### PR DESCRIPTION
**Pull request by trz42**
Sync NESSI with EESSI (PR 479).

SPDX license identifiers:
- `AOFlagger-3.4.0-foss-2023b.eb`:
- `arpack-ng-3.9.0-foss-2023b.eb`:
- `Armadillo-12.8.0-foss-2023b.eb`:
- `casacore-3.5.0-foss-2023b.eb`:
- `IDG-1.2.0-foss-2023b.eb`:
- `EveryBeam-0.5.2-foss-2023b.eb`:
- `DP3-6.0-foss-2023b.eb`:
- `WSClean-3.4-foss-2023b.eb`:

Missing packages:

- `AOFlagger-3.4.0-foss-2023b.eb`
```
13 out of 82 required modules missing:

* CFITSIO/4.3.1-GCCcore-13.2.0 (CFITSIO-4.3.1-GCCcore-13.2.0.eb)
* GSL/2.7-GCC-13.2.0 (GSL-2.7-GCC-13.2.0.eb)
* Lua/5.4.6-GCCcore-13.2.0 (Lua-5.4.6-GCCcore-13.2.0.eb)
* PCRE/8.45-GCCcore-13.2.0 (PCRE-8.45-GCCcore-13.2.0.eb)
* libidn2/2.3.2-GCCcore-13.2.0 (libidn2-2.3.2-GCCcore-13.2.0.eb)
* wget/1.21.4-GCCcore-13.2.0 (wget-1.21.4-GCCcore-13.2.0.eb)
* ICU/74.1-GCCcore-13.2.0 (ICU-74.1-GCCcore-13.2.0.eb)
* Boost/1.83.0-GCC-13.2.0 (Boost-1.83.0-GCC-13.2.0.eb)
* Boost.Python/1.83.0-GCC-13.2.0 (Boost.Python-1.83.0-GCC-13.2.0.eb)
* PGPLOT/5.2.2-GCCcore-13.2.0 (PGPLOT-5.2.2-GCCcore-13.2.0.eb)
* WCSLIB/7.11-GCC-13.2.0 (WCSLIB-7.11-GCC-13.2.0.eb)
* casacore/3.5.0-foss-2023b (casacore-3.5.0-foss-2023b.eb)
* AOFlagger/3.4.0-foss-2023b (AOFlagger-3.4.0-foss-2023b.eb)
```

- `arpack-ng-3.9.0-foss-2023b.eb`
```
1 out of 36 required modules missing:

* arpack-ng/3.9.0-foss-2023b (arpack-ng-3.9.0-foss-2023b.eb)
```

- `Armadillo-12.8.0-foss-2023b.eb`
```
4 out of 42 required modules missing:

* ICU/74.1-GCCcore-13.2.0 (ICU-74.1-GCCcore-13.2.0.eb)
* Boost/1.83.0-GCC-13.2.0 (Boost-1.83.0-GCC-13.2.0.eb)
* arpack-ng/3.9.0-foss-2023b (arpack-ng-3.9.0-foss-2023b.eb)
* Armadillo/12.8.0-foss-2023b (Armadillo-12.8.0-foss-2023b.eb)
```

- `casacore-3.5.0-foss-2023b.eb`
```
11 out of 80 required modules missing:

* CFITSIO/4.3.1-GCCcore-13.2.0 (CFITSIO-4.3.1-GCCcore-13.2.0.eb)
* PCRE/8.45-GCCcore-13.2.0 (PCRE-8.45-GCCcore-13.2.0.eb)
* libidn2/2.3.2-GCCcore-13.2.0 (libidn2-2.3.2-GCCcore-13.2.0.eb)
* wget/1.21.4-GCCcore-13.2.0 (wget-1.21.4-GCCcore-13.2.0.eb)
* GSL/2.7-GCC-13.2.0 (GSL-2.7-GCC-13.2.0.eb)
* ICU/74.1-GCCcore-13.2.0 (ICU-74.1-GCCcore-13.2.0.eb)
* Boost/1.83.0-GCC-13.2.0 (Boost-1.83.0-GCC-13.2.0.eb)
* Boost.Python/1.83.0-GCC-13.2.0 (Boost.Python-1.83.0-GCC-13.2.0.eb)
* PGPLOT/5.2.2-GCCcore-13.2.0 (PGPLOT-5.2.2-GCCcore-13.2.0.eb)
* WCSLIB/7.11-GCC-13.2.0 (WCSLIB-7.11-GCC-13.2.0.eb)
* casacore/3.5.0-foss-2023b (casacore-3.5.0-foss-2023b.eb)
```

- `IDG-1.2.0-foss-2023b.eb`
```
3 out of 40 required modules missing:

* ICU/74.1-GCCcore-13.2.0 (ICU-74.1-GCCcore-13.2.0.eb)
* Boost/1.83.0-GCC-13.2.0 (Boost-1.83.0-GCC-13.2.0.eb)
* IDG/1.2.0-foss-2023b (IDG-1.2.0-foss-2023b.eb)
```

- `EveryBeam-0.5.2-foss-2023b.eb`
```
12 out of 81 required modules missing:

* CFITSIO/4.3.1-GCCcore-13.2.0 (CFITSIO-4.3.1-GCCcore-13.2.0.eb)
* PCRE/8.45-GCCcore-13.2.0 (PCRE-8.45-GCCcore-13.2.0.eb)
* libidn2/2.3.2-GCCcore-13.2.0 (libidn2-2.3.2-GCCcore-13.2.0.eb)
* wget/1.21.4-GCCcore-13.2.0 (wget-1.21.4-GCCcore-13.2.0.eb)
* GSL/2.7-GCC-13.2.0 (GSL-2.7-GCC-13.2.0.eb)
* ICU/74.1-GCCcore-13.2.0 (ICU-74.1-GCCcore-13.2.0.eb)
* Boost/1.83.0-GCC-13.2.0 (Boost-1.83.0-GCC-13.2.0.eb)
* Boost.Python/1.83.0-GCC-13.2.0 (Boost.Python-1.83.0-GCC-13.2.0.eb)
* PGPLOT/5.2.2-GCCcore-13.2.0 (PGPLOT-5.2.2-GCCcore-13.2.0.eb)
* WCSLIB/7.11-GCC-13.2.0 (WCSLIB-7.11-GCC-13.2.0.eb)
* casacore/3.5.0-foss-2023b (casacore-3.5.0-foss-2023b.eb)
* EveryBeam/0.5.2-foss-2023b (EveryBeam-0.5.2-foss-2023b.eb)
```

- `DP3-6.0-foss-2023b.eb`
```
18 out of 87 required modules missing:

* CFITSIO/4.3.1-GCCcore-13.2.0 (CFITSIO-4.3.1-GCCcore-13.2.0.eb)
* GSL/2.7-GCC-13.2.0 (GSL-2.7-GCC-13.2.0.eb)
* PCRE/8.45-GCCcore-13.2.0 (PCRE-8.45-GCCcore-13.2.0.eb)
* libidn2/2.3.2-GCCcore-13.2.0 (libidn2-2.3.2-GCCcore-13.2.0.eb)
* wget/1.21.4-GCCcore-13.2.0 (wget-1.21.4-GCCcore-13.2.0.eb)
* ICU/74.1-GCCcore-13.2.0 (ICU-74.1-GCCcore-13.2.0.eb)
* Boost/1.83.0-GCC-13.2.0 (Boost-1.83.0-GCC-13.2.0.eb)
* Boost.Python/1.83.0-GCC-13.2.0 (Boost.Python-1.83.0-GCC-13.2.0.eb)
* Lua/5.4.6-GCCcore-13.2.0 (Lua-5.4.6-GCCcore-13.2.0.eb)
* PGPLOT/5.2.2-GCCcore-13.2.0 (PGPLOT-5.2.2-GCCcore-13.2.0.eb)
* WCSLIB/7.11-GCC-13.2.0 (WCSLIB-7.11-GCC-13.2.0.eb)
* arpack-ng/3.9.0-foss-2023b (arpack-ng-3.9.0-foss-2023b.eb)
* IDG/1.2.0-foss-2023b (IDG-1.2.0-foss-2023b.eb)
* Armadillo/12.8.0-foss-2023b (Armadillo-12.8.0-foss-2023b.eb)
* casacore/3.5.0-foss-2023b (casacore-3.5.0-foss-2023b.eb)
* EveryBeam/0.5.2-foss-2023b (EveryBeam-0.5.2-foss-2023b.eb)
* AOFlagger/3.4.0-foss-2023b (AOFlagger-3.4.0-foss-2023b.eb)
* DP3/6.0-foss-2023b (DP3-6.0-foss-2023b.eb)
```

- `WSClean-3.4-foss-2023b.eb`:
```
14 out of 83 required modules missing:

* CFITSIO/4.3.1-GCCcore-13.2.0 (CFITSIO-4.3.1-GCCcore-13.2.0.eb)
* PCRE/8.45-GCCcore-13.2.0 (PCRE-8.45-GCCcore-13.2.0.eb)
* GSL/2.7-GCC-13.2.0 (GSL-2.7-GCC-13.2.0.eb)
* libidn2/2.3.2-GCCcore-13.2.0 (libidn2-2.3.2-GCCcore-13.2.0.eb)
* wget/1.21.4-GCCcore-13.2.0 (wget-1.21.4-GCCcore-13.2.0.eb)
* ICU/74.1-GCCcore-13.2.0 (ICU-74.1-GCCcore-13.2.0.eb)
* Boost/1.83.0-GCC-13.2.0 (Boost-1.83.0-GCC-13.2.0.eb)
* Boost.Python/1.83.0-GCC-13.2.0 (Boost.Python-1.83.0-GCC-13.2.0.eb)
* PGPLOT/5.2.2-GCCcore-13.2.0 (PGPLOT-5.2.2-GCCcore-13.2.0.eb)
* WCSLIB/7.11-GCC-13.2.0 (WCSLIB-7.11-GCC-13.2.0.eb)
* IDG/1.2.0-foss-2023b (IDG-1.2.0-foss-2023b.eb)
* casacore/3.5.0-foss-2023b (casacore-3.5.0-foss-2023b.eb)
* EveryBeam/0.5.2-foss-2023b (EveryBeam-0.5.2-foss-2023b.eb)
* WSClean/3.4-foss-2023b (WSClean-3.4-foss-2023b.eb)
```

- all missing packages
```
* AOFlagger/3.4.0-foss-2023b (AOFlagger-3.4.0-foss-2023b.eb)
* Armadillo/12.8.0-foss-2023b (Armadillo-12.8.0-foss-2023b.eb)
* arpack-ng/3.9.0-foss-2023b (arpack-ng-3.9.0-foss-2023b.eb)
* Boost/1.83.0-GCC-13.2.0 (Boost-1.83.0-GCC-13.2.0.eb)
* Boost.Python/1.83.0-GCC-13.2.0 (Boost.Python-1.83.0-GCC-13.2.0.eb)
* casacore/3.5.0-foss-2023b (casacore-3.5.0-foss-2023b.eb)
* CFITSIO/4.3.1-GCCcore-13.2.0 (CFITSIO-4.3.1-GCCcore-13.2.0.eb)
* DP3/6.0-foss-2023b (DP3-6.0-foss-2023b.eb)
* EveryBeam/0.5.2-foss-2023b (EveryBeam-0.5.2-foss-2023b.eb)
* GSL/2.7-GCC-13.2.0 (GSL-2.7-GCC-13.2.0.eb)
* ICU/74.1-GCCcore-13.2.0 (ICU-74.1-GCCcore-13.2.0.eb)
* IDG/1.2.0-foss-2023b (IDG-1.2.0-foss-2023b.eb)
* libidn2/2.3.2-GCCcore-13.2.0 (libidn2-2.3.2-GCCcore-13.2.0.eb)
* Lua/5.4.6-GCCcore-13.2.0 (Lua-5.4.6-GCCcore-13.2.0.eb)
* PCRE/8.45-GCCcore-13.2.0 (PCRE-8.45-GCCcore-13.2.0.eb)
* PGPLOT/5.2.2-GCCcore-13.2.0 (PGPLOT-5.2.2-GCCcore-13.2.0.eb)
* WCSLIB/7.11-GCC-13.2.0 (WCSLIB-7.11-GCC-13.2.0.eb)
* wget/1.21.4-GCCcore-13.2.0 (wget-1.21.4-GCCcore-13.2.0.eb)
* WSClean/3.4-foss-2023b (WSClean-3.4-foss-2023b.eb)
```

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb10 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
Repeat failed builds

bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2

**Comment by trz42** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake

**Comment by trz42** [comment]
Try different container

bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb10 arch:x86_64/intel/skylake

**Comment by trz42** [comment]
Copied `pgplot522.tar.gz` manually to `/cluster/projects/nn9992k/pilot.nessi.no/shared_fs_path/easybuild/sources/p/PGPLOT`

bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake

**Comment by trz42** [comment]
Copied `wcslib-7.11.tar.bz2` to `saga:/cluster/projects/nn9992k/pilot.nessi.no/shared_fs_path/easybuild/sources/w/WCSLIB/`

bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake

**Comment by trz42** [comment]
Build currently doesn't work on Saga.

bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake

**Comment by trz42** [comment]
Retry build on AWS

bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb10 arch:x86_64/intel/skylake
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake

**Comment by trz42** [comment]
Build after FTP issue might have been resolved on Saga

bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake

**Comment by trz42** [comment]
Next attempt after setting `ftp_proxy` environment variable

bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake

**Comment by trz42** [comment]
Rebuild others ... just to be sure

bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb10 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
Now Fram is infected with the same problem Saga had before 😢 

bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by trz42** [comment]
Checklist before starting deployment (setting `bot:deploy` label): 

- [x]  Check if the _SPDX license identifier_ is provided 
  - no ...
- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each staged tarball was a PR for approval/rejection opened
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/WSClean/3.4* \
        aarch64/generic/{software,modules/all}/WSClean/3.4*
  ```
  **log**
```
-rw-r--r-- 1 cvmfs cvmfs 1959 Apr 26 16:39 aarch64/generic/modules/all/WSClean/3.4-foss-2023b.lua
-rw-rw-r-- 1 cvmfs cvmfs 1959 Apr 26 17:18 x86_64/amd/zen2/modules/all/WSClean/3.4-foss-2023b.lua
-rw-rw-r-- 1 cvmfs cvmfs 1958 Apr 26 17:16 x86_64/generic/modules/all/WSClean/3.4-foss-2023b.lua
-rw-rw-r-- 1 cvmfs cvmfs 1966 Apr 26 21:34 x86_64/intel/broadwell/modules/all/WSClean/3.4-foss-2023b.lua
-rw-rw-r-- 1 cvmfs cvmfs 1971 Apr 26 14:43 x86_64/intel/skylake_avx512/modules/all/WSClean/3.4-foss-2023b.lua

aarch64/generic/software/WSClean/3.4-foss-2023b:
total 19
dr-xr-xr-x 2 cvmfs cvmfs 4096 Apr 26 16:39 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Apr 26 16:39 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Apr 26 16:39 include
dr-xr-xr-x 2 cvmfs cvmfs 4096 Apr 26 16:39 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Apr 26 16:39 lib64 -> lib

x86_64/amd/zen2/software/WSClean/3.4-foss-2023b:
total 19
dr-xr-xr-x 2 cvmfs cvmfs 4096 Apr 26 17:18 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Apr 26 17:18 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Apr 26 17:18 include
dr-xr-xr-x 2 cvmfs cvmfs 4096 Apr 26 17:18 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Apr 26 17:18 lib64 -> lib

x86_64/generic/software/WSClean/3.4-foss-2023b:
total 19
dr-xr-xr-x 2 cvmfs cvmfs 4096 Apr 26 17:16 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Apr 26 17:17 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Apr 26 17:16 include
dr-xr-xr-x 2 cvmfs cvmfs 4096 Apr 26 17:16 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Apr 26 17:16 lib64 -> lib

x86_64/intel/broadwell/software/WSClean/3.4-foss-2023b:
total 19
dr-xr-xr-x 2 cvmfs cvmfs 4096 Apr 26 21:34 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Apr 26 21:34 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Apr 26 21:34 include
dr-xr-xr-x 2 cvmfs cvmfs 4096 Apr 26 21:34 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Apr 26 21:34 lib64 -> lib

x86_64/intel/skylake_avx512/software/WSClean/3.4-foss-2023b:
total 19
dr-xr-xr-x 2 cvmfs cvmfs 4096 Apr 26 14:42 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Apr 26 14:43 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Apr 26 14:42 include
dr-xr-xr-x 2 cvmfs cvmfs 4096 Apr 26 14:42 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Apr 26 14:42 lib64 -> lib 
```
</details>

**Review by poksumdo — APPROVED** [review]
Tough one.

**Pull request merged**
