### PR TITLE
{2023.06}[foss/2021a] Yambo V5.1.1

### PR DESCRIPTION
**Pull request by TopRichard**
Trying to build Yambo which was initially built on intel-toolchain on foss/2021a.
Yambo is not yet supported on the ARM architecture.

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb10 arch:x86_64/intel/broadwell

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb10 arch:x86_64/intel/broadwell
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/cascadelake
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake

**Comment by TopRichard** [comment]
Updated the branch with the latest changes done on NESSI.

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/generic
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb10 arch:x86_64/intel/broadwell
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/cascadelake
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake

**Comment by trz42** [comment]
> Updated the branch with the latest changes done on NESSI.

Good. Just curious what the changes were? If there were no significant changes maybe rebuilding wasn't necessary. Doesn't hurt though.

**Comment by TopRichard** [comment]
> > Updated the branch with the latest changes done on NESSI.
[{2023.06} comment *-from-pr & sync with EESSI/2023.06](https://github.com/NorESSI/software-layer/pull/174)
> 
> Good. Just curious what the changes were? If there were no significant changes maybe rebuilding wasn't necessary. Doesn't hurt though.

Initiated a build process to comply with the  `Check if the PR is up-to-date with the target branch nessi.no-2023.06` in the building checklist.

**Comment by TopRichard** [comment]
Jobs failed on Saga since the docker container image could not be fetched, so we will proceed the ingestion process as we can use the already built packages.

**Comment by TopRichard** [comment]
Checklist for building Yambo V5.1.1: 

- []  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
        - **Yambo is not yet supported on the ARM architecture.**
- []  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
        - Easybuild 4.8.1 is ingested.
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by TopRichard** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-intel-cascadelake`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [] encountered issues in the ingestion, likely related to troubles interacting with GitHub via PyGithub … 
- [ ] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
    The targeted architecture CI tests are successful.
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; 
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/Yambo/5.1.1-foss-2021a* \
        aarch64/generic/{software,modules/all}/Yambo/5.1.1-foss-2021a*
  ```
-rw-r--r--. 1 cvmfs cvmfs 1685 Oct  5 05:36 x86_64/amd/zen2/modules/all/Yambo/5.1.1-foss-2021a.lua
-rw-r--r--. 1 cvmfs cvmfs 1684 Oct  5 05:48 x86_64/generic/modules/all/Yambo/5.1.1-foss-2021a.lua
-rw-rw-r--. 1 cvmfs cvmfs 1692 Oct  5 05:44 x86_64/intel/broadwell/modules/all/Yambo/5.1.1-foss-2021a.lua
-rw-rw-r--. 1 cvmfs cvmfs 1694 Oct  5 04:49 x86_64/intel/cascadelake/modules/all/Yambo/5.1.1-foss-2021a.lua
-rw-rw-r--. 1 cvmfs cvmfs 1697 Oct  5 04:52 x86_64/intel/skylake_avx512/modules/all/Yambo/5.1.1-foss-2021a.lua

x86_64/amd/zen2/software/Yambo/5.1.1-foss-2021a:
total 9
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct  5 05:36 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct  5 05:36 easybuild

x86_64/generic/software/Yambo/5.1.1-foss-2021a:
total 9
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct  5 05:48 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct  5 05:48 easybuild

x86_64/intel/broadwell/software/Yambo/5.1.1-foss-2021a:
total 9
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct  5 05:44 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct  5 05:44 easybuild

x86_64/intel/cascadelake/software/Yambo/5.1.1-foss-2021a:
total 9
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct  5 04:49 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct  5 04:49 easybuild

x86_64/intel/skylake_avx512/software/Yambo/5.1.1-foss-2021a:
total 9
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct  5 04:52 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct  5 04:52 easybuild
```

```
</details>

**Review by justadejavu — APPROVED** [review]

**Pull request merged**
