### PR TITLE
{23.06}[foss/2022b] CMake + OpenMPI + FFTW.MPI + BLIS

### PR DESCRIPTION
**Pull request by trz42**
Add several components of foss/2022a (not OpenBLAS and packages depending on it):

- `CMake/3.24.3` with easyblock PR 2248
- `BLIS/0.9.0`
- `OpenMPI/4.1.4`
- `FFTW.MPI/3.3.10`

### CODE REVIEW

**Comment by trz42** [comment]
bot: build repo:nessi.no-2023.06-software inst:eX3 arch:aarch64/generic
bot: build repo:nessi.no-2023.06-software inst:eX3 arch:zen2
bot: build repo:nessi.no-2023.06-software inst:Fram arch:broadwell
bot: build repo:nessi.no-2023.06-software inst:AWS arch:x86_64/generic
bot: build repo:nessi.no-2023.06-software inst:AWS arch:cascade
bot: build repo:nessi.no-2023.06-software inst:AWS arch:skylake

**Comment by trz42** [comment]
bot: build repo:nessi.no-2023.06-software inst:AWS arch:cascade

**Comment by trz42** [comment]
Checklist for building: 

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-intel-cascadelake`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & output</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/BLIS/0.9.0-GCC-12.2* \
        aarch64/generic/{software,modules/all}/BLIS/0.9.0-GCC-12.2* \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/CMake/3.24.3-GCCcore-12.2* \
        aarch64/generic/{software,modules/all}/CMake/3.24.3-GCCcore-12.2* \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/FFTW.MPI/3.3.10-gompi-2022b* \
        aarch64/generic/{software,modules/all}/FFTW.MPI/3.3.10-gompi-2022b* \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/OpenMPI/4.1.4-GCC-12.2* \
        aarch64/generic/{software,modules/all}/OpenMPI/4.1.4-GCC-12.2*
  ```
  _or_
  ```
  pwd ; \
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  pwd ; \
  for pkg in "BLIS/0.9.0-GCC-12.2" "CMake/3.24.3-GCCcore-12.2" "FFTW.MPI/3.3.10-gompi-2022b" "OpenMPI/4.1.4-GCC-12.2" ; do
    ls -l x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/${pkg}*
    ls -l aarch64/generic/{software,modules/all}/${pkg}*
  done ; \
  cd -
  ```
  **log**
```
/cvmfs/pilot.nessi.no/versions/2023.06/software/linux
-rw-r--r-- 1 cvmfs cvmfs 1296 Jun 28 20:48 aarch64/generic/modules/all/BLIS/0.9.0-GCC-12.2.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1385 Jun 28 19:18 aarch64/generic/modules/all/CMake/3.24.3-GCCcore-12.2.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1317 Jun 28 23:36 aarch64/generic/modules/all/FFTW.MPI/3.3.10-gompi-2022b.lua
-rw-r--r-- 1 cvmfs cvmfs 1836 Jun 28 22:18 aarch64/generic/modules/all/OpenMPI/4.1.4-GCC-12.2.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1296 Jun 28 20:04 x86_64/amd/zen2/modules/all/BLIS/0.9.0-GCC-12.2.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1385 Jun 28 19:16 x86_64/amd/zen2/modules/all/CMake/3.24.3-GCCcore-12.2.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1317 Jun 28 22:05 x86_64/amd/zen2/modules/all/FFTW.MPI/3.3.10-gompi-2022b.lua
-rw-r--r-- 1 cvmfs cvmfs 1836 Jun 28 20:50 x86_64/amd/zen2/modules/all/OpenMPI/4.1.4-GCC-12.2.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1295 Jun 29 00:24 x86_64/generic/modules/all/BLIS/0.9.0-GCC-12.2.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1384 Jun 28 23:14 x86_64/generic/modules/all/CMake/3.24.3-GCCcore-12.2.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1316 Jun 29 03:25 x86_64/generic/modules/all/FFTW.MPI/3.3.10-gompi-2022b.lua
-rw-r--r-- 1 cvmfs cvmfs 1835 Jun 29 01:43 x86_64/generic/modules/all/OpenMPI/4.1.4-GCC-12.2.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 1303 Jun 28 20:15 x86_64/intel/broadwell/modules/all/BLIS/0.9.0-GCC-12.2.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 1392 Jun 28 19:18 x86_64/intel/broadwell/modules/all/CMake/3.24.3-GCCcore-12.2.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 1324 Jun 28 22:15 x86_64/intel/broadwell/modules/all/FFTW.MPI/3.3.10-gompi-2022b.lua
-rw-rw-r-- 1 cvmfs cvmfs 1843 Jun 28 21:10 x86_64/intel/broadwell/modules/all/OpenMPI/4.1.4-GCC-12.2.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1305 Jun 29 05:15 x86_64/intel/cascadelake/modules/all/BLIS/0.9.0-GCC-12.2.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1394 Jun 29 04:29 x86_64/intel/cascadelake/modules/all/CMake/3.24.3-GCCcore-12.2.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1326 Jun 29 07:05 x86_64/intel/cascadelake/modules/all/FFTW.MPI/3.3.10-gompi-2022b.lua
-rw-r--r-- 1 cvmfs cvmfs 1845 Jun 29 06:03 x86_64/intel/cascadelake/modules/all/OpenMPI/4.1.4-GCC-12.2.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1308 Jun 28 23:27 x86_64/intel/skylake_avx512/modules/all/BLIS/0.9.0-GCC-12.2.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1397 Jun 28 22:32 x86_64/intel/skylake_avx512/modules/all/CMake/3.24.3-GCCcore-12.2.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1329 Jun 29 01:26 x86_64/intel/skylake_avx512/modules/all/FFTW.MPI/3.3.10-gompi-2022b.lua
-rw-r--r-- 1 cvmfs cvmfs 1848 Jun 29 00:25 x86_64/intel/skylake_avx512/modules/all/OpenMPI/4.1.4-GCC-12.2.0.lua

aarch64/generic/software/BLIS/0.9.0-GCC-12.2.0:
total 19
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 20:49 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 20:48 include
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 20:48 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 28 20:48 lib64 -> lib
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 28 20:48 share

aarch64/generic/software/CMake/3.24.3-GCCcore-12.2.0:
total 18
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 19:18 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 19:18 doc
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 19:18 easybuild
dr-xr-xr-x 7 cvmfs cvmfs 4096 Jun 28 19:18 share

aarch64/generic/software/FFTW.MPI/3.3.10-gompi-2022b:
total 14
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 23:36 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 23:36 include
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 23:36 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 28 23:36 lib64 -> lib

aarch64/generic/software/OpenMPI/4.1.4-GCC-12.2.0:
total 28
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 22:17 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 22:18 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 22:15 etc
dr-xr-xr-x 5 cvmfs cvmfs 4096 Jun 28 22:17 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 28 22:17 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 28 22:17 lib64 -> lib
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 28 22:12 share

x86_64/amd/zen2/software/BLIS/0.9.0-GCC-12.2.0:
total 19
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 20:04 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 20:04 include
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 20:04 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 28 20:04 lib64 -> lib
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 28 20:04 share

x86_64/amd/zen2/software/CMake/3.24.3-GCCcore-12.2.0:
total 18
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 19:16 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 19:16 doc
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 19:16 easybuild
dr-xr-xr-x 7 cvmfs cvmfs 4096 Jun 28 19:16 share

x86_64/amd/zen2/software/FFTW.MPI/3.3.10-gompi-2022b:
total 14
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 22:05 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 22:05 include
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 22:05 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 28 22:05 lib64 -> lib

x86_64/amd/zen2/software/OpenMPI/4.1.4-GCC-12.2.0:
total 28
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 20:50 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 20:50 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 20:49 etc
dr-xr-xr-x 5 cvmfs cvmfs 4096 Jun 28 20:50 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 28 20:50 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 28 20:50 lib64 -> lib
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 28 20:47 share

x86_64/generic/software/BLIS/0.9.0-GCC-12.2.0:
total 19
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 00:24 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 00:24 include
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 29 00:24 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 29 00:24 lib64 -> lib
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 29 00:24 share

x86_64/generic/software/CMake/3.24.3-GCCcore-12.2.0:
total 18
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 23:14 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 23:14 doc
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 23:14 easybuild
dr-xr-xr-x 7 cvmfs cvmfs 4096 Jun 28 23:14 share

x86_64/generic/software/FFTW.MPI/3.3.10-gompi-2022b:
total 14
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 03:25 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 29 03:25 include
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 29 03:25 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 29 03:25 lib64 -> lib

x86_64/generic/software/OpenMPI/4.1.4-GCC-12.2.0:
total 28
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 29 01:43 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 01:43 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 29 01:41 etc
dr-xr-xr-x 5 cvmfs cvmfs 4096 Jun 29 01:42 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 29 01:42 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 29 01:43 lib64 -> lib
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 29 01:38 share

x86_64/intel/broadwell/software/BLIS/0.9.0-GCC-12.2.0:
total 19
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 20:15 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 20:15 include
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 20:15 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 28 20:15 lib64 -> lib
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 28 20:15 share

x86_64/intel/broadwell/software/CMake/3.24.3-GCCcore-12.2.0:
total 18
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 19:18 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 19:18 doc
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 19:18 easybuild
dr-xr-xr-x 7 cvmfs cvmfs 4096 Jun 28 19:18 share

x86_64/intel/broadwell/software/FFTW.MPI/3.3.10-gompi-2022b:
total 14
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 22:15 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 22:15 include
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 22:15 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 28 22:15 lib64 -> lib

x86_64/intel/broadwell/software/OpenMPI/4.1.4-GCC-12.2.0:
total 28
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 21:10 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 21:10 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 21:08 etc
dr-xr-xr-x 5 cvmfs cvmfs 4096 Jun 28 21:09 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 28 21:09 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 28 21:10 lib64 -> lib
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 28 21:06 share

x86_64/intel/cascadelake/software/BLIS/0.9.0-GCC-12.2.0:
total 19
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 05:15 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 05:15 include
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 29 05:15 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 29 05:15 lib64 -> lib
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 29 05:15 share

x86_64/intel/cascadelake/software/CMake/3.24.3-GCCcore-12.2.0:
total 18
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 29 04:29 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 04:29 doc
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 04:30 easybuild
dr-xr-xr-x 7 cvmfs cvmfs 4096 Jun 29 04:29 share

x86_64/intel/cascadelake/software/FFTW.MPI/3.3.10-gompi-2022b:
total 14
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 07:05 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 29 07:04 include
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 29 07:05 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 29 07:05 lib64 -> lib

x86_64/intel/cascadelake/software/OpenMPI/4.1.4-GCC-12.2.0:
total 28
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 29 06:03 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 06:03 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 29 06:02 etc
dr-xr-xr-x 5 cvmfs cvmfs 4096 Jun 29 06:02 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 29 06:02 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 29 06:03 lib64 -> lib
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 29 06:00 share

x86_64/intel/skylake_avx512/software/BLIS/0.9.0-GCC-12.2.0:
total 19
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 23:27 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 23:27 include
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 23:27 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 28 23:27 lib64 -> lib
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 28 23:27 share

x86_64/intel/skylake_avx512/software/CMake/3.24.3-GCCcore-12.2.0:
total 18
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 22:32 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 22:32 doc
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 22:32 easybuild
dr-xr-xr-x 7 cvmfs cvmfs 4096 Jun 28 22:32 share

x86_64/intel/skylake_avx512/software/FFTW.MPI/3.3.10-gompi-2022b:
total 14
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 01:26 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 29 01:26 include
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 29 01:26 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 29 01:26 lib64 -> lib

x86_64/intel/skylake_avx512/software/OpenMPI/4.1.4-GCC-12.2.0:
total 28
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 29 00:25 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 00:26 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 29 00:24 etc
dr-xr-xr-x 5 cvmfs cvmfs 4096 Jun 29 00:25 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 29 00:25 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 29 00:25 lib64 -> lib
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 29 00:22 share
```
</details>

**Review by poksumdo — APPROVED** [review]
All good.

**Pull request merged**
