### PR TITLE
{23.06}[foss/2022b] Python/3.10.8

### PR DESCRIPTION
**Pull request by trz42**
Secondary objective is to update lmod cache for foss/2021b and foss/2022a.

### CODE REVIEW

**Comment by trz42** [comment]
bot: build repo:nessi.no-2023.06-software inst:eX3 arch:aarch64/generic
bot: build repo:nessi.no-2023.06-software inst:eX3 arch:zen2
bot: build repo:nessi.no-2023.06-software inst:Fram arch:broadwell
bot: build repo:nessi.no-2023.06-software inst:AWS arch:x86_64/generic
bot: build repo:nessi.no-2023.06-software inst:AWS arch:cascade
bot: build repo:nessi.no-2023.06-software inst:AWS arch:skylake

**Comment by trz42** [comment]
Checklist for building: 

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-intel-cascadelake`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)

<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/Python/3.10.8* \
        aarch64/generic/{software,modules/all}/Python/3.10.8*
  ```
  **log**
```
-rw-r--r-- 1 cvmfs cvmfs  1673 Jun 28 20:44 aarch64/generic/modules/all/Python/3.10.8-GCCcore-12.2.0-bare.lua
-rw-r--r-- 1 cvmfs cvmfs 12094 Jun 29 17:12 aarch64/generic/modules/all/Python/3.10.8-GCCcore-12.2.0.lua
-rw-r--r-- 1 cvmfs cvmfs  1673 Jun 28 20:01 x86_64/amd/zen2/modules/all/Python/3.10.8-GCCcore-12.2.0-bare.lua
-rw-r--r-- 1 cvmfs cvmfs 12094 Jun 29 16:18 x86_64/amd/zen2/modules/all/Python/3.10.8-GCCcore-12.2.0.lua
-rw-r--r-- 1 cvmfs cvmfs  1672 Jun 29 00:20 x86_64/generic/modules/all/Python/3.10.8-GCCcore-12.2.0-bare.lua
-rw-r--r-- 1 cvmfs cvmfs 12093 Jun 29 17:19 x86_64/generic/modules/all/Python/3.10.8-GCCcore-12.2.0.lua
-rw-rw-r-- 1 cvmfs cvmfs  1680 Jun 28 20:12 x86_64/intel/broadwell/modules/all/Python/3.10.8-GCCcore-12.2.0-bare.lua
-rw-rw-r-- 1 cvmfs cvmfs 12101 Jun 29 16:47 x86_64/intel/broadwell/modules/all/Python/3.10.8-GCCcore-12.2.0.lua
-rw-r--r-- 1 cvmfs cvmfs  1682 Jun 29 05:13 x86_64/intel/cascadelake/modules/all/Python/3.10.8-GCCcore-12.2.0-bare.lua
-rw-r--r-- 1 cvmfs cvmfs 12103 Jun 29 16:28 x86_64/intel/cascadelake/modules/all/Python/3.10.8-GCCcore-12.2.0.lua
-rw-r--r-- 1 cvmfs cvmfs  1685 Jun 28 23:24 x86_64/intel/skylake_avx512/modules/all/Python/3.10.8-GCCcore-12.2.0-bare.lua
-rw-r--r-- 1 cvmfs cvmfs 12106 Jun 29 16:36 x86_64/intel/skylake_avx512/modules/all/Python/3.10.8-GCCcore-12.2.0.lua

aarch64/generic/software/Python/3.10.8-GCCcore-12.2.0:
total 23
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 17:02 bin
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 29 17:13 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 16:31 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 29 16:31 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 29 17:02 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 16:31 share

aarch64/generic/software/Python/3.10.8-GCCcore-12.2.0-bare:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 20:43 bin
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 28 20:44 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 20:43 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 28 20:43 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 28 20:43 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 20:43 share

x86_64/amd/zen2/software/Python/3.10.8-GCCcore-12.2.0:
total 23
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 16:14 bin
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 29 16:19 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 15:58 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 29 15:58 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 29 16:14 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 15:58 share

x86_64/amd/zen2/software/Python/3.10.8-GCCcore-12.2.0-bare:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 20:01 bin
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 28 20:01 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 20:01 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 28 20:01 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 28 20:01 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 20:01 share

x86_64/generic/software/Python/3.10.8-GCCcore-12.2.0:
total 23
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 17:12 bin
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 29 17:20 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 16:47 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 29 16:47 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 29 17:12 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 16:47 share

x86_64/generic/software/Python/3.10.8-GCCcore-12.2.0-bare:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 29 00:20 bin
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 29 00:20 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 00:20 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 29 00:20 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 29 00:20 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 00:20 share

x86_64/intel/broadwell/software/Python/3.10.8-GCCcore-12.2.0:
total 23
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 16:40 bin
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 29 16:48 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 16:18 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 29 16:18 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 29 16:40 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 16:18 share

x86_64/intel/broadwell/software/Python/3.10.8-GCCcore-12.2.0-bare:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 20:12 bin
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 28 20:12 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 20:12 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 28 20:12 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 28 20:12 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 20:12 share

x86_64/intel/cascadelake/software/Python/3.10.8-GCCcore-12.2.0:
total 23
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 16:24 bin
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 29 16:29 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 16:06 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 29 16:06 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 29 16:24 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 16:06 share

x86_64/intel/cascadelake/software/Python/3.10.8-GCCcore-12.2.0-bare:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 29 05:13 bin
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 29 05:13 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 05:13 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 29 05:13 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 29 05:13 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 05:13 share

x86_64/intel/skylake_avx512/software/Python/3.10.8-GCCcore-12.2.0:
total 23
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 16:30 bin
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 29 16:36 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 16:11 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 29 16:11 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 29 16:31 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 29 16:11 share

x86_64/intel/skylake_avx512/software/Python/3.10.8-GCCcore-12.2.0-bare:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jun 28 23:24 bin
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 28 23:24 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 23:24 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 28 23:24 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 28 23:24 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 28 23:24 share 
```
</details>

**Review by poksumdo — APPROVED** [review]
Voila 🥳

**Pull request merged**
