### PR TITLE
Add OSU-Micro-Benchmarks/5.6.3 with GCC/9.3.0 to NESSI/2022.11

### PR DESCRIPTION
**Pull request by TopRichard**
Trying to add OSU-Micro-Benchmarks/5.6.3 with GCC/9.3.0 to NESSI/2022.11

### CODE REVIEW

**Comment by dajon** [comment]
- [x] did the builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
  - No eX3 build in last rebuild, but there are other successful zen2 builds. 
- [x] is the PR up-to-date with the target branch `nessi.no-2022.11-dev` in the repository (if not what are the differences)
- [x] are all requested changes sound (checking files changed on GitHub.com)
- [x] is/are the easyconfig/s being built included with the EB version used (if not why not)
- [x] were any changes needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by TopRichard** [comment]
Trying to rebuild to check the package size consistency among different architectures.

**Comment by trz42** [comment]
- [x] did the builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x] is the PR up-to-date with the target branch `nessi.no-2022.11-dev` in the repository (if not what are the differences)
- [x] are all requested changes sound (checking files changed on GitHub.com)
- [x] is/are the easyconfig/s being built included with the EB version used (if not why not)
- [x] were any changes needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Checklist for deployment

- [x] at least one tarball for each architecture has been uploaded
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512`
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] at least one tarball for each architecture has been staged
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512`
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] for each architecture **one and only one** tarball has been approved
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512`
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] for each architecture **one and only one** tarball was ingested
  - [x] `x86_64-intel-broadwell` see https://github.com/NorESSI/software-layer/pull/45#issuecomment-1484764861
  - [x] `x86_64-intel-skylake_avx512` see https://github.com/NorESSI/software-layer/pull/45#issuecomment-1484764976
  - [x] `x86_64-intel-cascadelake` see https://github.com/NorESSI/software-layer/pull/45#issuecomment-1484764928
  - [x] `x86_64-amd-zen2` see https://github.com/NorESSI/software-layer/pull/45#issuecomment-1484764803
  - [x] `x86_64-generic` see https://github.com/NorESSI/software-layer/pull/45#issuecomment-1484765117
  - [x] `aarch64-generic` see https://github.com/NorESSI/software-layer/pull/45#issuecomment-1484764852
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
  **command**
  ```
  ls -l /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/OSU*
  ls -l /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/aarch64/generic/{software,modules/all}/OSU*
  ```
  **log**
  ```
  too long to show here
  ```

**Review by trz42 — APPROVED** [review]
Everything good. Nice.

:clap:

**Pull request merged**
