### PR TITLE
{2023.06}[system] add EasyBuild/4.8.0

### PR DESCRIPTION
**Pull request by trz42**
adds EasyBuild via a new easystack file for the system toolchain

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:AWS arch:x86_64/generic repo:nessi-2023.06-swl-deb11
bot: build inst:eX3 arch:x86_64/amd/zen2 repo:nessi-2023.06-swl-deb11
bot: build inst:eX3 arch:aarch64/generic repo:nessi-2023.06-swl-deb11
bot: build inst:Fram arch:x86_64/intel/broadwell repo:nessi-2023.06-swl-deb10
bot: build inst:Saga arch:x86_64/intel/cascadelake repo:nessi-2023.06-swl-deb11
bot: build inst:Saga arch:x86_64/intel/skylake repo:nessi-2023.06-swl-deb11

**Comment by trz42** [comment]
`git diff --name-only` didn't catch the added easystack file. changed to original approach introduced in https://github.com/EESSI/software-layer/pull/351 by @boegel

bot: build inst:AWS arch:x86_64/generic repo:nessi-2023.06-swl-deb11
bot: build inst:eX3 arch:x86_64/amd/zen2 repo:nessi-2023.06-swl-deb11
bot: build inst:eX3 arch:aarch64/generic repo:nessi-2023.06-swl-deb11
bot: build inst:Fram arch:x86_64/intel/broadwell repo:nessi-2023.06-swl-deb10
bot: build inst:Saga arch:x86_64/intel/cascadelake repo:nessi-2023.06-swl-deb11
bot: build inst:Saga arch:x86_64/intel/skylake repo:nessi-2023.06-swl-deb11

**Comment by trz42** [comment]
Checklist for building: 

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
  - needed to use a PR because easyconfig for 4.8.0 is not part of release 4.7.2
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)
  - needed to revert back to the original method for determining changed/added easystack files

- CI did not verify new easystack file, fixed with https://github.com/NorESSI/software-layer/pull/175/commits/a7c66f63092af30f7133391081f040f1dee73095

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-intel-cascadelake`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/EasyBuild/4.8.* \
        aarch64/generic/{software,modules/all}/EasyBuild/4.8.*
  ```
  **log**
```
-rw-r--r-- 1 cvmfs cvmfs 1321 Oct  4 21:14 aarch64/generic/modules/all/EasyBuild/4.8.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1320 Oct  4 21:14 x86_64/amd/zen2/modules/all/EasyBuild/4.8.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1319 Oct  4 21:22 x86_64/generic/modules/all/EasyBuild/4.8.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 1327 Oct  4 21:16 x86_64/intel/broadwell/modules/all/EasyBuild/4.8.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 1329 Oct  4 23:14 x86_64/intel/cascadelake/modules/all/EasyBuild/4.8.0.lua

aarch64/generic/software/EasyBuild/4.8.0:
total 23
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  4 21:13 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  4 21:13 contrib
dr-xr-xr-x 5 cvmfs cvmfs 4096 Oct  4 21:15 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  4 21:13 etc
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  4 21:12 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  4 21:13 lib64 -> lib

x86_64/amd/zen2/software/EasyBuild/4.8.0:
total 23
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  4 21:14 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  4 21:14 contrib
dr-xr-xr-x 5 cvmfs cvmfs 4096 Oct  4 21:15 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  4 21:14 etc
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  4 21:13 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  4 21:14 lib64 -> lib

x86_64/generic/software/EasyBuild/4.8.0:
total 23
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  4 21:21 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  4 21:21 contrib
dr-xr-xr-x 5 cvmfs cvmfs 4096 Oct  4 21:23 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  4 21:21 etc
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  4 21:21 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  4 21:22 lib64 -> lib

x86_64/intel/broadwell/software/EasyBuild/4.8.0:
total 23
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  4 21:15 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  4 21:15 contrib
dr-xr-xr-x 5 cvmfs cvmfs 4096 Oct  4 21:17 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  4 21:15 etc
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  4 21:15 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  4 21:16 lib64 -> lib

x86_64/intel/cascadelake/software/EasyBuild/4.8.0:
total 23
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  4 23:14 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  4 23:14 contrib
dr-xr-xr-x 5 cvmfs cvmfs 4096 Oct  4 23:15 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  4 23:14 etc
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  4 23:13 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  4 23:14 lib64 -> lib 
```
</details>

**Review by poksumdo — APPROVED** [review]
Looks good.

**Pull request merged**
