### PR TITLE
{2023.06}[foss/2023a] bx-python V0.10.0

### PR DESCRIPTION
**Pull request by TopRichard**
bx-python-0.10.0 is found on Saga:
Lic --> MIT
```
2 out of 57 required modules missing:

* LZO/2.10-GCCcore-12.3.0 (LZO-2.10-GCCcore-12.3.0.eb)
* bx-python/0.10.0-foss-2023a (bx-python-0.10.0-foss-2023a.eb)

```

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
Checklist before starting deployment (setting bot:deploy label):

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by TopRichard** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x]  Check if the _SPDX license identifier_ is provided 
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI for the ingested tarballs have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)

<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; 
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/bx-python/0.10.0-foss-2023a* \
        aarch64/generic/{software,modules/all}/bx-python/0.10.0-foss-2023a*
  ```
  **log**
```
-rw-r--r--. 1 cvmfs cvmfs 1820 Jun 10 09:55 aarch64/generic/modules/all/bx-python/0.10.0-foss-2023a.lua
-rw-rw-r--. 1 cvmfs cvmfs 1820 Jun 10 10:03 x86_64/amd/zen2/modules/all/bx-python/0.10.0-foss-2023a.lua
-rw-rw-r--. 1 cvmfs cvmfs 1819 Jun 10 10:03 x86_64/generic/modules/all/bx-python/0.10.0-foss-2023a.lua
-rw-rw-r--. 1 cvmfs cvmfs 1827 Jun 10 10:14 x86_64/intel/broadwell/modules/all/bx-python/0.10.0-foss-2023a.lua
-rw-rw-r--. 1 cvmfs cvmfs 1832 Jun 10 10:11 x86_64/intel/skylake_avx512/modules/all/bx-python/0.10.0-foss-2023a.lua

aarch64/generic/software/bx-python/0.10.0-foss-2023a:
total 14
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 10 09:55 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 10 09:55 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 10 09:52 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 10 09:55 lib64 -> lib

x86_64/amd/zen2/software/bx-python/0.10.0-foss-2023a:
total 14
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 10 10:03 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 10 10:03 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 10 10:00 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 10 10:03 lib64 -> lib

x86_64/generic/software/bx-python/0.10.0-foss-2023a:
total 14
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 10 10:03 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 10 10:03 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 10 10:00 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 10 10:03 lib64 -> lib

x86_64/intel/broadwell/software/bx-python/0.10.0-foss-2023a:
total 14
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 10 10:14 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 10 10:14 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 10 10:10 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 10 10:14 lib64 -> lib

x86_64/intel/skylake_avx512/software/bx-python/0.10.0-foss-2023a:
total 14
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 10 10:11 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 10 10:11 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 10 10:08 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 10 10:11 lib64 -> lib
```
</details>

**Review by justadejavu — APPROVED** [review]
lgtm

**Pull request merged**
