### PR TITLE
{2023.06}[foss/2022b] ImageMagick v7.1.0-53

### PR DESCRIPTION
**Pull request by trz42**
ImageMagick is a dependency for R-bundle.

SPDX identifier: `ImageMagick`

Missing installations:
```
14 out of 66 required modules missing:

* jbigkit/2.1-GCCcore-12.2.0 (jbigkit-2.1-GCCcore-12.2.0.eb)
* LittleCMS/2.14-GCCcore-12.2.0 (LittleCMS-2.14-GCCcore-12.2.0.eb)
* libdeflate/1.15-GCCcore-12.2.0 (libdeflate-1.15-GCCcore-12.2.0.eb)
* FriBidi/1.0.12-GCCcore-12.2.0 (FriBidi-1.0.12-GCCcore-12.2.0.eb)
* LibTIFF/4.4.0-GCCcore-12.2.0 (LibTIFF-4.4.0-GCCcore-12.2.0.eb)
* ATK/2.38.0-GCCcore-12.2.0 (ATK-2.38.0-GCCcore-12.2.0.eb)
* Pango/1.50.12-GCCcore-12.2.0 (Pango-1.50.12-GCCcore-12.2.0.eb)
* Gdk-Pixbuf/2.42.10-GCCcore-12.2.0 (Gdk-Pixbuf-2.42.10-GCCcore-12.2.0.eb)
* at-spi2-core/2.46.0-GCCcore-12.2.0 (at-spi2-core-2.46.0-GCCcore-12.2.0.eb)
* at-spi2-atk/2.38.0-GCCcore-12.2.0 (at-spi2-atk-2.38.0-GCCcore-12.2.0.eb)
* libepoxy/1.5.10-GCCcore-12.2.0 (libepoxy-1.5.10-GCCcore-12.2.0.eb)
* GTK3/3.24.35-GCCcore-12.2.0 (GTK3-3.24.35-GCCcore-12.2.0.eb)
* Ghostscript/10.0.0-GCCcore-12.2.0 (Ghostscript-10.0.0-GCCcore-12.2.0.eb)
* ImageMagick/7.1.0-53-GCCcore-12.2.0 (ImageMagick-7.1.0-53-GCCcore-12.2.0.eb)
```

### CODE REVIEW

**Comment by trz42** [comment]
Test if it works for `foss/2022b` without adding `PCRE/8.45` as dependency.

skip bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/generic
skip bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Fram repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
skip bot: build inst:eX3 repo:nessi-2023.06-swl-deb10 arch:aarch64/generic

**Comment by trz42** [comment]
Test if the `parse_hook` for v7.1.0-37 "works" for v7.1.0-53 too, that is the dependency for `PCRE/8.45` is not added.

skip bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/generic
skip bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Fram repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
skip bot: build inst:eX3 repo:nessi-2023.06-swl-deb10 arch:aarch64/generic

**Comment by trz42** [comment]
Rebuild after updating PR

bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/generic
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Fram repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb10 arch:aarch64/generic

**Comment by trz42** [comment]
Seems the job on Fram is waiting very long ... trying a build on Saga too.

bot: build inst:Saga repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by trz42** [comment]
Checklist before starting deployment (setting `bot:deploy` label): 

- [x]  Check if the _SPDX license identifier_ is provided 
- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
  - upload from eX3 failed once
  - upload from eX3 failed twice
  - upload from eX3 failed three times
  - did upload it manually with (~700 KiB/s transfer speed)
  ```
  (venv_bot_p310) thomarob@srl-login1:~/bot-devel/test_sync_feb24/eessi-bot-software-layer$ aws --endpoint-url=https://minio.nessi.no:60900 s3 cp /home/thomarob/pilot.nessi.no/jobs/2024.03/pr_287/152495/eessi-2023.06-software-linux-aarch64-generic-1710535021.tar.gz s3://nessi-2023.06/tarballs/2023.06/software/linux/aarch64/generic/1710535021/eessi-2023.06-software-linux-aarch64-generic-1710535021.tar.gz
  ```
- [x] at least one tarball for each architecture has been staged
- [x] for each staged tarball was a PR for approval/rejection opened
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/ImageMagick/7.1.0-53-GCCcore-12.2.0* \
        aarch64/generic/{software,modules/all}/ImageMagick/7.1.0-53-GCCcore-12.2.0*
  ```
  **log**
```
-rw-r--r--. 1 cvmfs cvmfs 2325 Mar 15 20:36 aarch64/generic/modules/all/ImageMagick/7.1.0-53-GCCcore-12.2.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 2325 Mar 15 20:15 x86_64/amd/zen2/modules/all/ImageMagick/7.1.0-53-GCCcore-12.2.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 2323 Mar 15 20:08 x86_64/generic/modules/all/ImageMagick/7.1.0-53-GCCcore-12.2.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 2339 Mar 17 18:25 x86_64/intel/broadwell/modules/all/ImageMagick/7.1.0-53-GCCcore-12.2.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 2349 Mar 15 20:06 x86_64/intel/skylake_avx512/modules/all/ImageMagick/7.1.0-53-GCCcore-12.2.0.lua

aarch64/generic/software/ImageMagick/7.1.0-53-GCCcore-12.2.0:
total 28
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Mar 15 20:35 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Mar 15 20:36 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Mar 15 20:35 etc
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Mar 15 20:35 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Mar 15 20:36 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Mar 15 20:36 lib64 -> lib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Mar 15 20:36 share

x86_64/amd/zen2/software/ImageMagick/7.1.0-53-GCCcore-12.2.0:
total 28
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Mar 15 20:15 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Mar 15 20:15 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Mar 15 20:15 etc
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Mar 15 20:15 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Mar 15 20:15 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Mar 15 20:15 lib64 -> lib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Mar 15 20:15 share

x86_64/generic/software/ImageMagick/7.1.0-53-GCCcore-12.2.0:
total 28
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Mar 15 20:08 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Mar 15 20:08 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Mar 15 20:08 etc
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Mar 15 20:08 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Mar 15 20:08 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Mar 15 20:08 lib64 -> lib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Mar 15 20:08 share

x86_64/intel/broadwell/software/ImageMagick/7.1.0-53-GCCcore-12.2.0:
total 28
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Mar 17 18:25 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Mar 17 18:25 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Mar 17 18:25 etc
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Mar 17 18:25 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Mar 17 18:25 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Mar 17 18:25 lib64 -> lib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Mar 17 18:25 share

x86_64/intel/skylake_avx512/software/ImageMagick/7.1.0-53-GCCcore-12.2.0:
total 28
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Mar 15 20:06 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Mar 15 20:06 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Mar 15 20:06 etc
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Mar 15 20:06 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Mar 15 20:06 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Mar 15 20:06 lib64 -> lib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Mar 15 20:06 share
```
</details>

**Review by poksumdo — APPROVED** [review]
lgtm

upload from eX3 is very slow.

**Pull request merged**
