### PR TITLE
{2023.06}[foss/2023b] pyMBE V0.8.0

### PR DESCRIPTION
**Pull request by TopRichard**
Sync with EESSI ( PR  651)
Lic --> GPL-3.0
```
missing packages:

Boost.MPI/1.83.0-gompi-2023b
ESPResSo/4.2.2-foss-2023b
Pint/0.24-GCCcore-13.2.0
pyMBE/0.8.0-foss-2023b
```

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
Checklist before starting deployment (setting bot:deploy label):

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by TopRichard** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x]  Check if the _SPDX license identifier_ is provided 
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI for the ingested tarballs have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)

<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; 
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/pyMBE/0.8.0-foss-2023b* \
        aarch64/generic/{software,modules/all}/pyMBE/0.8.0-foss-2023b*
  ```
  **log**
```
-rw-rw-r--.  1 cvmfs cvmfs 2302 Jul 24 11:34 aarch64/generic/modules/all/pyMBE/0.8.0-foss-2023b.lua
-rw-rw-r--.  1 cvmfs cvmfs 2302 Jul 24 11:38 x86_64/amd/zen2/modules/all/pyMBE/0.8.0-foss-2023b.lua
-rw-rw-r--.  1 cvmfs cvmfs 2301 Jul 24 11:35 x86_64/generic/modules/all/pyMBE/0.8.0-foss-2023b.lua
-rw-rw-r--.  1 cvmfs cvmfs 2309 Jul 24 12:20 x86_64/intel/broadwell/modules/all/pyMBE/0.8.0-foss-2023b.lua
-rw-rw-r--.  1 cvmfs cvmfs 2314 Jul 24 11:45 x86_64/intel/skylake_avx512/modules/all/pyMBE/0.8.0-foss-2023b.lua

aarch64/generic/software/pyMBE/0.8.0-foss-2023b:
total 294
-r--r--r--. 1 cvmfs cvmfs   1141 Jun 18 16:05 AUTHORS.md
-r--r--r--. 1 cvmfs cvmfs    317 Jun 18 16:05 CHANGELOG.md
-r--r--r--. 1 cvmfs cvmfs   3373 Jun 18 16:05 CITATION.cff
-r--r--r--. 1 cvmfs cvmfs   1590 Jun 18 16:05 CONTRIBUTING.md
-r--r--r--. 1 cvmfs cvmfs   1174 Jul 24 11:33 df1.csv
-r--r--r--. 1 cvmfs cvmfs  16175 Jul 24 11:33 df2.csv
dr-xr-xr-x. 3 cvmfs cvmfs   4096 Jul 24 11:34 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs   4096 Jun 18 16:05 figs
dr-xr-xr-x. 4 cvmfs cvmfs   4096 Jul 24 11:33 lib
lrwxrwxrwx. 1 cvmfs cvmfs      3 Jul 24 11:32 lib64 -> lib
-r--r--r--. 1 cvmfs cvmfs  35147 Jun 18 16:05 LICENSE.txt
dr-xr-xr-x. 2 cvmfs cvmfs   4096 Jun 18 16:05 maintainer
-r--r--r--. 1 cvmfs cvmfs   2800 Jun 18 16:05 Makefile
dr-xr-xr-x. 5 cvmfs cvmfs   4096 Jun 18 16:05 parameters
dr-xr-xr-x. 2 cvmfs cvmfs   4096 Jul 24 11:32 __pycache__
-r--r--r--. 1 cvmfs cvmfs 176557 Jun 18 16:05 pyMBE.py
-r--r--r--. 1 cvmfs cvmfs   7742 Jun 18 16:05 README.md
dr-xr-xr-x. 2 cvmfs cvmfs   4096 Jun 18 16:05 refs
-r--r--r--. 1 cvmfs cvmfs    101 Jun 18 16:05 requirements.txt
dr-xr-xr-x. 3 cvmfs cvmfs   4096 Jun 18 16:05 samples
dr-xr-xr-x. 9 cvmfs cvmfs   4096 Jun 18 16:05 testsuite
dr-xr-xr-x. 2 cvmfs cvmfs   4096 Jun 18 16:05 tutorials
dr-xr-xr-x. 2 cvmfs cvmfs   4096 Jun 18 16:05 visualization

x86_64/amd/zen2/software/pyMBE/0.8.0-foss-2023b:
total 294
-r--r--r--. 1 cvmfs cvmfs   1141 Jun 18 16:05 AUTHORS.md
-r--r--r--. 1 cvmfs cvmfs    317 Jun 18 16:05 CHANGELOG.md
-r--r--r--. 1 cvmfs cvmfs   3373 Jun 18 16:05 CITATION.cff
-r--r--r--. 1 cvmfs cvmfs   1590 Jun 18 16:05 CONTRIBUTING.md
-r--r--r--. 1 cvmfs cvmfs   1174 Jul 24 11:36 df1.csv
-r--r--r--. 1 cvmfs cvmfs  16175 Jul 24 11:37 df2.csv
dr-xr-xr-x. 3 cvmfs cvmfs   4096 Jul 24 11:38 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs   4096 Jun 18 16:05 figs
dr-xr-xr-x. 4 cvmfs cvmfs   4096 Jul 24 11:36 lib
lrwxrwxrwx. 1 cvmfs cvmfs      3 Jul 24 11:35 lib64 -> lib
-r--r--r--. 1 cvmfs cvmfs  35147 Jun 18 16:05 LICENSE.txt
dr-xr-xr-x. 2 cvmfs cvmfs   4096 Jun 18 16:05 maintainer
-r--r--r--. 1 cvmfs cvmfs   2800 Jun 18 16:05 Makefile
dr-xr-xr-x. 5 cvmfs cvmfs   4096 Jun 18 16:05 parameters
dr-xr-xr-x. 2 cvmfs cvmfs   4096 Jul 24 11:35 __pycache__
-r--r--r--. 1 cvmfs cvmfs 176557 Jun 18 16:05 pyMBE.py
-r--r--r--. 1 cvmfs cvmfs   7742 Jun 18 16:05 README.md
dr-xr-xr-x. 2 cvmfs cvmfs   4096 Jun 18 16:05 refs
-r--r--r--. 1 cvmfs cvmfs    101 Jun 18 16:05 requirements.txt
dr-xr-xr-x. 3 cvmfs cvmfs   4096 Jun 18 16:05 samples
dr-xr-xr-x. 9 cvmfs cvmfs   4096 Jun 18 16:05 testsuite
dr-xr-xr-x. 2 cvmfs cvmfs   4096 Jun 18 16:05 tutorials
dr-xr-xr-x. 2 cvmfs cvmfs   4096 Jun 18 16:05 visualization

x86_64/generic/software/pyMBE/0.8.0-foss-2023b:
total 294
-r--r--r--. 1 cvmfs cvmfs   1141 Jun 18 16:05 AUTHORS.md
-r--r--r--. 1 cvmfs cvmfs    317 Jun 18 16:05 CHANGELOG.md
-r--r--r--. 1 cvmfs cvmfs   3373 Jun 18 16:05 CITATION.cff
-r--r--r--. 1 cvmfs cvmfs   1590 Jun 18 16:05 CONTRIBUTING.md
-r--r--r--. 1 cvmfs cvmfs   1174 Jul 24 11:34 df1.csv
-r--r--r--. 1 cvmfs cvmfs  16175 Jul 24 11:34 df2.csv
dr-xr-xr-x. 3 cvmfs cvmfs   4096 Jul 24 11:35 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs   4096 Jun 18 16:05 figs
dr-xr-xr-x. 4 cvmfs cvmfs   4096 Jul 24 11:34 lib
lrwxrwxrwx. 1 cvmfs cvmfs      3 Jul 24 11:33 lib64 -> lib
-r--r--r--. 1 cvmfs cvmfs  35147 Jun 18 16:05 LICENSE.txt
dr-xr-xr-x. 2 cvmfs cvmfs   4096 Jun 18 16:05 maintainer
-r--r--r--. 1 cvmfs cvmfs   2800 Jun 18 16:05 Makefile
dr-xr-xr-x. 5 cvmfs cvmfs   4096 Jun 18 16:05 parameters
dr-xr-xr-x. 2 cvmfs cvmfs   4096 Jul 24 11:33 __pycache__
-r--r--r--. 1 cvmfs cvmfs 176557 Jun 18 16:05 pyMBE.py
-r--r--r--. 1 cvmfs cvmfs   7742 Jun 18 16:05 README.md
dr-xr-xr-x. 2 cvmfs cvmfs   4096 Jun 18 16:05 refs
-r--r--r--. 1 cvmfs cvmfs    101 Jun 18 16:05 requirements.txt
dr-xr-xr-x. 3 cvmfs cvmfs   4096 Jun 18 16:05 samples
dr-xr-xr-x. 9 cvmfs cvmfs   4096 Jun 18 16:05 testsuite
dr-xr-xr-x. 2 cvmfs cvmfs   4096 Jun 18 16:05 tutorials
dr-xr-xr-x. 2 cvmfs cvmfs   4096 Jun 18 16:05 visualization

x86_64/intel/broadwell/software/pyMBE/0.8.0-foss-2023b:
total 294
-r--r--r--. 1 cvmfs cvmfs   1141 Jun 18 16:05 AUTHORS.md
-r--r--r--. 1 cvmfs cvmfs    317 Jun 18 16:05 CHANGELOG.md
-r--r--r--. 1 cvmfs cvmfs   3373 Jun 18 16:05 CITATION.cff
-r--r--r--. 1 cvmfs cvmfs   1590 Jun 18 16:05 CONTRIBUTING.md
-r--r--r--. 1 cvmfs cvmfs   1174 Jul 24 12:17 df1.csv
-r--r--r--. 1 cvmfs cvmfs  16175 Jul 24 12:17 df2.csv
dr-xr-xr-x. 3 cvmfs cvmfs   4096 Jul 24 12:20 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs   4096 Jun 18 16:05 figs
dr-xr-xr-x. 4 cvmfs cvmfs   4096 Jul 24 12:16 lib
lrwxrwxrwx. 1 cvmfs cvmfs      3 Jul 24 12:15 lib64 -> lib
-r--r--r--. 1 cvmfs cvmfs  35147 Jun 18 16:05 LICENSE.txt
dr-xr-xr-x. 2 cvmfs cvmfs   4096 Jun 18 16:05 maintainer
-r--r--r--. 1 cvmfs cvmfs   2800 Jun 18 16:05 Makefile
dr-xr-xr-x. 5 cvmfs cvmfs   4096 Jun 18 16:05 parameters
dr-xr-xr-x. 2 cvmfs cvmfs   4096 Jul 24 12:15 __pycache__
-r--r--r--. 1 cvmfs cvmfs 176557 Jun 18 16:05 pyMBE.py
-r--r--r--. 1 cvmfs cvmfs   7742 Jun 18 16:05 README.md
dr-xr-xr-x. 2 cvmfs cvmfs   4096 Jun 18 16:05 refs
-r--r--r--. 1 cvmfs cvmfs    101 Jun 18 16:05 requirements.txt
dr-xr-xr-x. 3 cvmfs cvmfs   4096 Jun 18 16:05 samples
dr-xr-xr-x. 9 cvmfs cvmfs   4096 Jun 18 16:05 testsuite
dr-xr-xr-x. 2 cvmfs cvmfs   4096 Jun 18 16:05 tutorials
dr-xr-xr-x. 2 cvmfs cvmfs   4096 Jun 18 16:05 visualization

x86_64/intel/skylake_avx512/software/pyMBE/0.8.0-foss-2023b:
total 294
-r--r--r--. 1 cvmfs cvmfs   1141 Jun 18 16:05 AUTHORS.md
-r--r--r--. 1 cvmfs cvmfs    317 Jun 18 16:05 CHANGELOG.md
-r--r--r--. 1 cvmfs cvmfs   3373 Jun 18 16:05 CITATION.cff
-r--r--r--. 1 cvmfs cvmfs   1590 Jun 18 16:05 CONTRIBUTING.md
-r--r--r--. 1 cvmfs cvmfs   1174 Jul 24 11:43 df1.csv
-r--r--r--. 1 cvmfs cvmfs  16175 Jul 24 11:43 df2.csv
dr-xr-xr-x. 3 cvmfs cvmfs   4096 Jul 24 11:45 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs   4096 Jun 18 16:05 figs
dr-xr-xr-x. 4 cvmfs cvmfs   4096 Jul 24 11:42 lib
lrwxrwxrwx. 1 cvmfs cvmfs      3 Jul 24 11:41 lib64 -> lib
-r--r--r--. 1 cvmfs cvmfs  35147 Jun 18 16:05 LICENSE.txt
dr-xr-xr-x. 2 cvmfs cvmfs   4096 Jun 18 16:05 maintainer
-r--r--r--. 1 cvmfs cvmfs   2800 Jun 18 16:05 Makefile
dr-xr-xr-x. 5 cvmfs cvmfs   4096 Jun 18 16:05 parameters
dr-xr-xr-x. 2 cvmfs cvmfs   4096 Jul 24 11:42 __pycache__
-r--r--r--. 1 cvmfs cvmfs 176557 Jun 18 16:05 pyMBE.py
-r--r--r--. 1 cvmfs cvmfs   7742 Jun 18 16:05 README.md
dr-xr-xr-x. 2 cvmfs cvmfs   4096 Jun 18 16:05 refs
-r--r--r--. 1 cvmfs cvmfs    101 Jun 18 16:05 requirements.txt
dr-xr-xr-x. 3 cvmfs cvmfs   4096 Jun 18 16:05 samples
dr-xr-xr-x. 9 cvmfs cvmfs   4096 Jun 18 16:05 testsuite
dr-xr-xr-x. 2 cvmfs cvmfs   4096 Jun 18 16:05 tutorials
dr-xr-xr-x. 2 cvmfs cvmfs   4096 Jun 18 16:05 visualization

```
</details>

**Review by justadejavu — APPROVED** [review]
Okay

**Pull request merged**
