### PR TITLE
{2023.06}[gompi/2022a] HISAT2 V2.2.1

### PR DESCRIPTION
**Pull request by TopRichard**
Trying to build HISAT2/2.2.1-gompi/2022a as a step forward for getting closer to the current available HPC software stack.
License: https://spdx.org/licenses/GPL-3.0-only.html
Will install the following packages:

```
* Perl/5.34.1-GCCcore-11.3.0-minimal (Perl-5.34.1-GCCcore-11.3.0-minimal.eb)
* file/5.43-GCCcore-11.3.0 (file-5.43-GCCcore-11.3.0.eb)
* ncbi-vdb/3.0.2-gompi-2022a (ncbi-vdb-3.0.2-gompi-2022a.eb)
* SRA-Toolkit/3.0.3-gompi-2022a (SRA-Toolkit-3.0.3-gompi-2022a.eb)
* HISAT2/2.2.1-gompi-2022a (HISAT2-2.2.1-gompi-2022a.eb)
```

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS repo:nessi-2023.06-swl-deb10 arch:zen2
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb10 arch:x86_64/intel/broadwell
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/cascadelake
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/cascadelake 
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake

**Comment by TopRichard** [comment]
```
Building this to avoid errors of none accessible old AWS infra during the bot:deploy before rejecting cascadelake
```
bot: build inst:AWS-MC-NESSIrepo:nessi-2023.06-swl-deb11 arch:x86_64/intel/cascadelake

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb10 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake

**Comment by trz42** [comment]
Builds on Saga (https://github.com/NorESSI/software-layer/pull/197#issuecomment-1884510990 and https://github.com/NorESSI/software-layer/pull/197#issuecomment-1884511277) failed because a tarball that is stored on an FTP server cannot be downloaded on compute nodes. It seems the Squid proxy on Saga is preventing the download from FTP servers.

As a quick workaround we amend `EASYBUILD_SOURCEPATH` in `configure_easybuild` and deposit the tarball in the added directory.

**Comment by TopRichard** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by TopRichard** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by TopRichard** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by TopRichard** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by TopRichard** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by TopRichard** [comment]
Now that it has built successfully for Saga, we will revert back the additional changes.

**Comment by trz42** [comment]
> Builds on Saga ([#197 (comment)](https://github.com/NorESSI/software-layer/pull/197#issuecomment-1884510990) and [#197 (comment)](https://github.com/NorESSI/software-layer/pull/197#issuecomment-1884511277)) failed because a tarball that is stored on an FTP server cannot be downloaded on compute nodes. It seems the Squid proxy on Saga is preventing the download from FTP servers.
> 
> As a quick workaround we amend `EASYBUILD_SOURCEPATH` in `configure_easybuild` and deposit the tarball in the added directory.

This didn't work, because the directory where we deposited the tarball likely wasn't visible inside the container.

**Comment by TopRichard** [comment]
Summary for the issue and the workaround applied within this PR:
On Saga the Proxy server on the compute nodes didn't allow downloads using **FTP** and so the download of the source file for file-5.43-GCCcore-11.3.0.eb failed. The workaround was to download the file-5.43-GCCcore-11.3.0.eb, modify it so that the download protocol for the source file is **HTTP** instead of  **FTP**, and then set the file within the main repository.
After the successful built on Saga, all changes were reverted back, and the ingestion procedure will be followed as usual.

**Comment by TopRichard** [comment]
Checklist for building: 

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
  - Didn't succeed for `aarch64/generic`.
  - Listed this PR in https://gitlab.sigma2.no/nessi/pilot/-/issues/7
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)
         ```A workaround was applied for the builds on Saga.```

**Comment by TopRichard** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [] encountered issues in the ingestion, likely related to troubles interacting with GitHub via PyGithub … 
- [x] all tests in the CI for the ingested tarballs have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] the PR has a license info for the ingested software
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)

<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; 
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/HISAT2/2.2.1-gompi-2022a* \
        aarch64/generic/{software,modules/all}/HISAT2/2.2.1-gompi-2022a*
  ```
  **log** (note, output includes `-bare` modules)
```
ls: cannot access 'aarch64/generic/software/HISAT2/2.2.1-gompi-2022a*': No such file or directory
ls: cannot access 'aarch64/generic/modules/all/HISAT2/2.2.1-gompi-2022a*': No such file or directory
-rw-rw-r-- 1 cvmfs cvmfs 1377 Jan 10 11:13  x86_64/amd/zen2/modules/all/HISAT2/2.2.1-gompi-2022a.lua
-rw-rw-r-- 1 cvmfs cvmfs 1376 Jan 10 11:10  x86_64/generic/modules/all/HISAT2/2.2.1-gompi-2022a.lua
-rw-rw-r-- 1 cvmfs cvmfs 1384 Jan 10 19:12  x86_64/intel/broadwell/modules/all/HISAT2/2.2.1-gompi-2022a.lua
-rw-rw-r-- 1 cvmfs cvmfs 1389 Jan 10 13:22  x86_64/intel/skylake_avx512/modules/all/HISAT2/2.2.1-gompi-2022a.lua

x86_64/amd/zen2/software/HISAT2/2.2.1-gompi-2022a:
total 18
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 10 11:13 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 10 11:14 easybuild
dr-xr-xr-x 5 cvmfs cvmfs 4096 Jul 24  2020 example
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jul 24  2020 scripts

x86_64/generic/software/HISAT2/2.2.1-gompi-2022a:
total 18
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 10 11:10 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 10 11:10 easybuild
dr-xr-xr-x 5 cvmfs cvmfs 4096 Jul 24  2020 example
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jul 24  2020 scripts

x86_64/intel/broadwell/software/HISAT2/2.2.1-gompi-2022a:
total 18
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 10 19:12 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 10 19:12 easybuild
dr-xr-xr-x 5 cvmfs cvmfs 4096 Jul 24  2020 example
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jul 24  2020 scripts

x86_64/intel/skylake_avx512/software/HISAT2/2.2.1-gompi-2022a:
total 18
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 10 13:22 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 10 13:22 easybuild
dr-xr-xr-x 5 cvmfs cvmfs 4096 Jul 24  2020 example
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jul 24  2020 scripts

```
</details>

**Review by justadejavu — APPROVED** [review]
👍🏻

**Pull request merged**
