### PR TITLE
Allow defining lmod hooks in host injections

### PR DESCRIPTION
**Pull request by trz42**
PR to sync NESSI with EESSI (PR 525).

Need to build and ingest tarballs. Also serves as a test if upload from eX3 is improved.

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb11 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
Checklist before starting deployment (setting `bot:deploy` label): 

- [x]  Check if the _SPDX license identifier_ is provided 
  - just updates an internal script
- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
  - no easyconfig has been used
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
  - first upload attempt from eX3 failed because the metadata file was created on the frontend node under `/tmp`; after changing the location to a shared location it now works (better than before) 
- [x] at least one tarball for each architecture has been staged
- [x] for each staged tarball was a PR for approval/rejection opened
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
  - only one known to fail test failed; ok to ignore for now
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/.lmod/SitePackage.lua \
        aarch64/generic/.lmod/SitePackage.lua
  ```
  **log**
```
-rw-r--r-- 1 cvmfs cvmfs 8141 Apr 11 21:49 aarch64/generic/.lmod/SitePackage.lua
-rw-rw-r-- 1 cvmfs cvmfs 8141 Apr 11 21:54 x86_64/amd/zen2/.lmod/SitePackage.lua
-rw-rw-r-- 1 cvmfs cvmfs 8141 Apr 11 21:54 x86_64/generic/.lmod/SitePackage.lua
-rw-rw-r-- 1 cvmfs cvmfs 8141 Apr 11 21:48 x86_64/intel/broadwell/.lmod/SitePackage.lua
-rw-rw-r-- 1 cvmfs cvmfs 8141 Apr 11 21:49 x86_64/intel/skylake_avx512/.lmod/SitePackage.lua 
```
</details>

**Review by poksumdo — APPROVED** [review]
Looks good.

**Pull request merged**
