### PR TITLE
split Lmod hooks

### PR DESCRIPTION
**Pull request by trz42**
PR to sync changes made in https://github.com/EESSI/software-layer/pull/496

We need to build and probably ingest the tarballs.

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb11 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
Rebuilding after #307 got ingested and merged.

bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb11 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
Checklist before starting deployment (setting `bot:deploy` label): 

- [x]  Check if the _SPDX license identifier_ is provided
  - not needed because no software was built (just updating some scripts: Lmod config scripts and init scripts)
- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
  - no easyconfigs were used
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each staged tarball was a PR for approval/rejection opened
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
  - one CI workflow for `load_easybuild_module.sh` (which typically works in every PR; hence we ignore it here), see https://github.com/NorESSI/software-layer/actions/runs/8588455621/job/23533321698?pr=306
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
  - according to the log below, ingest seems incomplete for `broadwell`, `zen2` and `skylake` 
  - all fine after second run
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06 ; \
  ls -l \
      init/eessi_env* \
      software/linux/*/generic/.lmod/cache/* \
      software/linux/*/generic/.lmod/*.lua \
      software/linux/x86_64/*/*/.lmod/cache/* \  
      software/linux/x86_64/*/*/.lmod/*.lua
  ```
  **log**
```
ls: cannot access  : No such file or directory
-rw-rw-r--. 1 cvmfs cvmfs    4590 Apr  7 13:44 init/eessi_environment_variables
-rw-r--r--. 1 cvmfs cvmfs 1382346 Apr  7 13:44 software/linux/aarch64/generic/.lmod/cache/spiderT.lua
-rw-r--r--. 1 cvmfs cvmfs  916127 Apr  7 13:44 software/linux/aarch64/generic/.lmod/cache/spiderT.luac_5.1
-rw-r--r--. 1 cvmfs cvmfs       0 Apr  7 13:44 software/linux/aarch64/generic/.lmod/cache/timestamp
-rw-r--r--. 1 cvmfs cvmfs     265 Apr  7 13:44 software/linux/aarch64/generic/.lmod/lmodrc.lua
-rw-r--r--. 1 cvmfs cvmfs    5648 Apr  7 13:44 software/linux/aarch64/generic/.lmod/SitePackage.lua
-rw-r--r--. 1 cvmfs cvmfs 1443712 Apr  7 13:49 software/linux/x86_64/amd/zen2/.lmod/cache/spiderT.lua
-rw-r--r--. 1 cvmfs cvmfs  953119 Apr  7 13:49 software/linux/x86_64/amd/zen2/.lmod/cache/spiderT.luac_5.1
-rw-rw-r--. 1 cvmfs cvmfs       0 Apr  7 13:48 software/linux/x86_64/amd/zen2/.lmod/cache/timestamp
-rw-r--r--. 1 cvmfs cvmfs 1441339 Apr  7 13:49 software/linux/x86_64/generic/.lmod/cache/spiderT.lua
-rw-r--r--. 1 cvmfs cvmfs  951478 Apr  7 13:49 software/linux/x86_64/generic/.lmod/cache/spiderT.luac_5.1
-rw-rw-r--. 1 cvmfs cvmfs       0 Apr  7 13:48 software/linux/x86_64/generic/.lmod/cache/timestamp
-rw-r--r--. 1 cvmfs cvmfs     263 Apr  7 13:48 software/linux/x86_64/generic/.lmod/lmodrc.lua
-rw-rw-r--. 1 cvmfs cvmfs    5648 Apr  7 13:48 software/linux/x86_64/generic/.lmod/SitePackage.lua
-rw-r--r--. 1 cvmfs cvmfs 1460323 Apr  7 13:44 software/linux/x86_64/intel/broadwell/.lmod/cache/spiderT.lua
-rw-r--r--. 1 cvmfs cvmfs  964606 Apr  7 13:44 software/linux/x86_64/intel/broadwell/.lmod/cache/spiderT.luac_5.1
-rw-rw-r--. 1 cvmfs cvmfs       0 Apr  7 13:44 software/linux/x86_64/intel/broadwell/.lmod/cache/timestamp
-rw-r--r--. 1 cvmfs cvmfs  694693 Oct 10 14:55 software/linux/x86_64/intel/cascadelake/.lmod/cache/spiderT.lua
-rw-r--r--. 1 cvmfs cvmfs  490787 Oct 10 14:55 software/linux/x86_64/intel/cascadelake/.lmod/cache/spiderT.luac_5.1
-rw-r--r--. 1 cvmfs cvmfs       0 Oct 10 14:55 software/linux/x86_64/intel/cascadelake/.lmod/cache/timestamp
-rw-r--r--. 1 cvmfs cvmfs 1472188 Apr  7 13:44 software/linux/x86_64/intel/skylake_avx512/.lmod/cache/spiderT.lua
-rw-r--r--. 1 cvmfs cvmfs  972811 Apr  7 13:44 software/linux/x86_64/intel/skylake_avx512/.lmod/cache/spiderT.luac_5.1
-rw-rw-r--. 1 cvmfs cvmfs       0 Apr  7 13:44 software/linux/x86_64/intel/skylake_avx512/.lmod/cache/timestamp
-bash: software/linux/x86_64/amd/zen2/.lmod/lmodrc.lua: Permission denied 
```
** log for 2nd run **
```
-rw-rw-r--. 1 cvmfs cvmfs    4590 Apr  7 13:44 init/eessi_environment_variables
-rw-r--r--. 1 cvmfs cvmfs 1382346 Apr  7 13:44 software/linux/aarch64/generic/.lmod/cache/spiderT.lua
-rw-r--r--. 1 cvmfs cvmfs  916127 Apr  7 13:44 software/linux/aarch64/generic/.lmod/cache/spiderT.luac_5.1
-rw-r--r--. 1 cvmfs cvmfs       0 Apr  7 13:44 software/linux/aarch64/generic/.lmod/cache/timestamp
-rw-r--r--. 1 cvmfs cvmfs     265 Apr  7 13:44 software/linux/aarch64/generic/.lmod/lmodrc.lua
-rw-r--r--. 1 cvmfs cvmfs    5648 Apr  7 13:44 software/linux/aarch64/generic/.lmod/SitePackage.lua
-rw-r--r--. 1 cvmfs cvmfs 1443712 Apr  7 13:49 software/linux/x86_64/amd/zen2/.lmod/cache/spiderT.lua
-rw-r--r--. 1 cvmfs cvmfs  953119 Apr  7 13:49 software/linux/x86_64/amd/zen2/.lmod/cache/spiderT.luac_5.1
-rw-rw-r--. 1 cvmfs cvmfs       0 Apr  7 13:48 software/linux/x86_64/amd/zen2/.lmod/cache/timestamp
-rw-r--r--. 1 cvmfs cvmfs     265 Apr  7 13:48 software/linux/x86_64/amd/zen2/.lmod/lmodrc.lua
-rw-rw-r--. 1 cvmfs cvmfs    5648 Apr  7 13:48 software/linux/x86_64/amd/zen2/.lmod/SitePackage.lua
-rw-r--r--. 1 cvmfs cvmfs 1441339 Apr  7 13:49 software/linux/x86_64/generic/.lmod/cache/spiderT.lua
-rw-r--r--. 1 cvmfs cvmfs  951478 Apr  7 13:49 software/linux/x86_64/generic/.lmod/cache/spiderT.luac_5.1
-rw-rw-r--. 1 cvmfs cvmfs       0 Apr  7 13:48 software/linux/x86_64/generic/.lmod/cache/timestamp
-rw-r--r--. 1 cvmfs cvmfs     263 Apr  7 13:48 software/linux/x86_64/generic/.lmod/lmodrc.lua
-rw-rw-r--. 1 cvmfs cvmfs    5648 Apr  7 13:48 software/linux/x86_64/generic/.lmod/SitePackage.lua
-rw-r--r--. 1 cvmfs cvmfs 1460323 Apr  7 13:44 software/linux/x86_64/intel/broadwell/.lmod/cache/spiderT.lua
-rw-r--r--. 1 cvmfs cvmfs  964606 Apr  7 13:44 software/linux/x86_64/intel/broadwell/.lmod/cache/spiderT.luac_5.1
-rw-rw-r--. 1 cvmfs cvmfs       0 Apr  7 13:44 software/linux/x86_64/intel/broadwell/.lmod/cache/timestamp
-rw-rw-r--. 1 cvmfs cvmfs     279 Apr  7 13:44 software/linux/x86_64/intel/broadwell/.lmod/lmodrc.lua
-rw-rw-r--. 1 cvmfs cvmfs    5648 Apr  7 13:44 software/linux/x86_64/intel/broadwell/.lmod/SitePackage.lua
-rw-r--r--. 1 cvmfs cvmfs  694693 Oct 10 14:55 software/linux/x86_64/intel/cascadelake/.lmod/cache/spiderT.lua
-rw-r--r--. 1 cvmfs cvmfs  490787 Oct 10 14:55 software/linux/x86_64/intel/cascadelake/.lmod/cache/spiderT.luac_5.1
-rw-r--r--. 1 cvmfs cvmfs       0 Oct 10 14:55 software/linux/x86_64/intel/cascadelake/.lmod/cache/timestamp
-rw-r--r--. 1 cvmfs cvmfs     283 Jun 18  2023 software/linux/x86_64/intel/cascadelake/.lmod/lmodrc.lua
-rw-r--r--. 1 cvmfs cvmfs 1472188 Apr  7 13:44 software/linux/x86_64/intel/skylake_avx512/.lmod/cache/spiderT.lua
-rw-r--r--. 1 cvmfs cvmfs  972811 Apr  7 13:44 software/linux/x86_64/intel/skylake_avx512/.lmod/cache/spiderT.luac_5.1
-rw-rw-r--. 1 cvmfs cvmfs       0 Apr  7 13:44 software/linux/x86_64/intel/skylake_avx512/.lmod/cache/timestamp
-rw-r--r--. 1 cvmfs cvmfs     289 Apr  7 13:44 software/linux/x86_64/intel/skylake_avx512/.lmod/lmodrc.lua
-rw-rw-r--. 1 cvmfs cvmfs    5648 Apr  7 13:44 software/linux/x86_64/intel/skylake_avx512/.lmod/SitePackage.lua
```
</details>

**Review by poksumdo — APPROVED** [review]
All good. Upload from eX3 is pathetically slow and repeatedly failing.

**Pull request merged**
