### PR TITLE
Rebuild `hatchling 1.18.0`, `Python 3.11.*`, `Python-bundle-PyPI-2023.*` to solve `setuptools_scm`

### PR DESCRIPTION
**Pull request by trz42**
Sync NESSI with EESSI (PR 546).

We first need to remove the packages on the Stratum-0. Then after a while trigger the building, then ingest ...

### CODE REVIEW

**Comment by trz42** [comment]
We need to remove packages on Stratum-0 first:
```
cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux
rm -rf aarch64/generic/software/hatchling/1.18.0-GCCcore-12.3.0
rm -rf aarch64/generic/software/hatchling/1.18.0-GCCcore-13.2.0
rm -rf x86_64/generic/software/hatchling/1.18.0-GCCcore-12.3.0
rm -rf x86_64/generic/software/hatchling/1.18.0-GCCcore-13.2.0
rm -rf x86_64/amd/zen2/software/hatchling/1.18.0-GCCcore-12.3.0
rm -rf x86_64/amd/zen2/software/hatchling/1.18.0-GCCcore-13.2.0
rm -rf x86_64/intel/broadwell/software/hatchling/1.18.0-GCCcore-12.3.0
rm -rf x86_64/intel/broadwell/software/hatchling/1.18.0-GCCcore-13.2.0
rm -rf x86_64/intel/skylake_avx512/software/hatchling/1.18.0-GCCcore-12.3.0
rm -rf x86_64/intel/skylake_avx512/software/hatchling/1.18.0-GCCcore-13.2.0

rm -f aarch64/generic/modules/all/hatchling/1.18.0-GCCcore-{12.3.0,13.2.0}.lua
rm -f x86_64/generic/modules/all/hatchling/1.18.0-GCCcore-{12.3.0,13.2.0}.lua
rm -f x86_64/amd/zen2/modules/all/hatchling/1.18.0-GCCcore-{12.3.0,13.2.0}.lua
rm -f x86_64/intel/broadwell/modules/all/hatchling/1.18.0-GCCcore-{12.3.0,13.2.0}.lua
rm -f x86_64/intel/skylake_avx512/modules/all/hatchling/1.18.0-GCCcore-{12.3.0,13.2.0}.lua

rm -rf aarch64/generic/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0
rm -rf aarch64/generic/software/Python-bundle-PyPI/2023.10-GCCcore-13.2.0
rm -rf x86_64/generic/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0
rm -rf x86_64/generic/software/Python-bundle-PyPI/2023.10-GCCcore-13.2.0
rm -rf x86_64/amd/zen2/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0
rm -rf x86_64/amd/zen2/software/Python-bundle-PyPI/2023.10-GCCcore-13.2.0
rm -rf x86_64/intel/broadwell/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0
rm -rf x86_64/intel/broadwell/software/Python-bundle-PyPI/2023.10-GCCcore-13.2.0
rm -rf x86_64/intel/skylake_avx512/software/Python-bundle-PyPI/2023.06-GCCcore-12.3.0
rm -rf x86_64/intel/skylake_avx512/software/Python-bundle-PyPI/2023.10-GCCcore-13.2.0

rm -f aarch64/generic/modules/all/Python-bundle-PyPI/{2023.06-GCCcore-12.3.0,2023.10-GCCcore-13.2.0}.lua
rm -f x86_64/generic/modules/all/Python-bundle-PyPI/{2023.06-GCCcore-12.3.0,2023.10-GCCcore-13.2.0}.lua
rm -f x86_64/amd/zen2/modules/all/Python-bundle-PyPI/{2023.06-GCCcore-12.3.0,2023.10-GCCcore-13.2.0}.lua
rm -f x86_64/intel/broadwell/modules/all/Python-bundle-PyPI/{2023.06-GCCcore-12.3.0,2023.10-GCCcore-13.2.0}.lua
rm -f x86_64/intel/skylake_avx512/modules/all/Python-bundle-PyPI/{2023.06-GCCcore-12.3.0,2023.10-GCCcore-13.2.0}.lua

rm -rf aarch64/generic/software/Python/3.11.3-GCCcore-12.3.0
rm -rf aarch64/generic/software/Python/3.11.5-GCCcore-13.2.0
rm -rf x86_64/generic/software/Python/3.11.3-GCCcore-12.3.0
rm -rf x86_64/generic/software/Python/3.11.5-GCCcore-13.2.0
rm -rf x86_64/amd/zen2/software/Python/3.11.3-GCCcore-12.3.0
rm -rf x86_64/amd/zen2/software/Python/3.11.5-GCCcore-13.2.0
rm -rf x86_64/intel/broadwell/software/Python/3.11.3-GCCcore-12.3.0
rm -rf x86_64/intel/broadwell/software/Python/3.11.5-GCCcore-13.2.0
rm -rf x86_64/intel/skylake_avx512/software/Python/3.11.3-GCCcore-12.3.0
rm -rf x86_64/intel/skylake_avx512/software/Python/3.11.5-GCCcore-13.2.0

rm -f aarch64/generic/modules/all/Python/{3.11.3-GCCcore-12.3.0,3.11.5-GCCcore-13.2.0}.lua
rm -f x86_64/generic/modules/all/Python/{3.11.3-GCCcore-12.3.0,3.11.5-GCCcore-13.2.0}.lua
rm -f x86_64/amd/zen2/modules/all/Python/{3.11.3-GCCcore-12.3.0,3.11.5-GCCcore-13.2.0}.lua
rm -f x86_64/intel/broadwell/modules/all/Python/{3.11.3-GCCcore-12.3.0,3.11.5-GCCcore-13.2.0}.lua
rm -f x86_64/intel/skylake_avx512/modules/all/Python/{3.11.3-GCCcore-12.3.0,3.11.5-GCCcore-13.2.0}.lua
```

**Comment by trz42** [comment]
CI for missing installations was succeeding initially. After removing software it failed.

**Comment by trz42** [comment]
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb10 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by trz42** [comment]
bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by trz42** [comment]
First two builds on `aarch64/generic` failed because one package wasn't removed on S0.

bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb10 arch:aarch64/generic

**Comment by trz42** [comment]
Checklist before starting deployment (setting `bot:deploy` label): 

- [ ]  Check if the _SPDX license identifier_ is provided 
  - just rebuilds
- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each staged tarball was a PR for approval/rejection opened
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/Python/3.11.{3,5}* \
        aarch64/generic/{software,modules/all}/Python/3.11.{3,5}*
  ```
  **log**
```
-rw-r--r-- 1 cvmfs cvmfs 2296 May  1 21:52 aarch64/generic/modules/all/Python/3.11.3-GCCcore-12.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 2297 May  1 22:23 aarch64/generic/modules/all/Python/3.11.5-GCCcore-13.2.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 2296 May  1 19:47 x86_64/amd/zen2/modules/all/Python/3.11.3-GCCcore-12.3.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 2297 May  1 20:01 x86_64/amd/zen2/modules/all/Python/3.11.5-GCCcore-13.2.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 2295 May  1 19:48 x86_64/generic/modules/all/Python/3.11.3-GCCcore-12.3.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 2296 May  1 20:04 x86_64/generic/modules/all/Python/3.11.5-GCCcore-13.2.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 2303 May  1 20:28 x86_64/intel/broadwell/modules/all/Python/3.11.3-GCCcore-12.3.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 2304 May  1 20:43 x86_64/intel/broadwell/modules/all/Python/3.11.5-GCCcore-13.2.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 2308 May  1 19:55 x86_64/intel/skylake_avx512/modules/all/Python/3.11.3-GCCcore-12.3.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 2309 May  1 20:23 x86_64/intel/skylake_avx512/modules/all/Python/3.11.5-GCCcore-13.2.0.lua

aarch64/generic/software/Python/3.11.3-GCCcore-12.3.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 May  1 21:52 bin
dr-xr-xr-x 4 cvmfs cvmfs 4096 May  1 21:52 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 May  1 21:51 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 May  1 21:51 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 May  1 21:52 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 May  1 21:51 share

aarch64/generic/software/Python/3.11.5-GCCcore-13.2.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 May  1 22:23 bin
dr-xr-xr-x 4 cvmfs cvmfs 4096 May  1 22:24 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 May  1 22:22 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 May  1 22:22 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 May  1 22:23 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 May  1 22:22 share

x86_64/amd/zen2/software/Python/3.11.3-GCCcore-12.3.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 May  1 19:47 bin
dr-xr-xr-x 4 cvmfs cvmfs 4096 May  1 19:47 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 May  1 19:46 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 May  1 19:46 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 May  1 19:47 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 May  1 19:46 share

x86_64/amd/zen2/software/Python/3.11.5-GCCcore-13.2.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 May  1 20:01 bin
dr-xr-xr-x 4 cvmfs cvmfs 4096 May  1 20:01 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 May  1 20:00 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 May  1 20:00 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 May  1 20:01 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 May  1 20:00 share

x86_64/generic/software/Python/3.11.3-GCCcore-12.3.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 May  1 19:48 bin
dr-xr-xr-x 4 cvmfs cvmfs 4096 May  1 19:49 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 May  1 19:48 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 May  1 19:48 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 May  1 19:48 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 May  1 19:48 share

x86_64/generic/software/Python/3.11.5-GCCcore-13.2.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 May  1 20:04 bin
dr-xr-xr-x 4 cvmfs cvmfs 4096 May  1 20:04 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 May  1 20:03 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 May  1 20:03 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 May  1 20:04 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 May  1 20:03 share

x86_64/intel/broadwell/software/Python/3.11.3-GCCcore-12.3.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 May  1 20:28 bin
dr-xr-xr-x 4 cvmfs cvmfs 4096 May  1 20:28 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 May  1 20:27 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 May  1 20:27 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 May  1 20:28 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 May  1 20:27 share

x86_64/intel/broadwell/software/Python/3.11.5-GCCcore-13.2.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 May  1 20:43 bin
dr-xr-xr-x 4 cvmfs cvmfs 4096 May  1 20:44 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 May  1 20:43 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 May  1 20:43 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 May  1 20:43 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 May  1 20:43 share

x86_64/intel/skylake_avx512/software/Python/3.11.3-GCCcore-12.3.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 May  1 19:54 bin
dr-xr-xr-x 4 cvmfs cvmfs 4096 May  1 19:55 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 May  1 19:54 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 May  1 19:54 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 May  1 19:54 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 May  1 19:54 share

x86_64/intel/skylake_avx512/software/Python/3.11.5-GCCcore-13.2.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 May  1 20:22 bin
dr-xr-xr-x 4 cvmfs cvmfs 4096 May  1 20:23 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 May  1 20:22 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 May  1 20:22 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 May  1 20:22 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 May  1 20:22 share 
```
</details>

**Review by poksumdo — APPROVED** [review]
done

**Pull request merged**
