### PR TITLE
{2023.06}[gompi/2023a] OSU Microbenchmarks V7.2 w/ CUDA 12.1.1

### PR DESCRIPTION
**Pull request by TopRichard**
Sync with EESSI (PR 487)

Lic:
```
GDRCopy/2.3.1 --> MIT 
UCX-CUDA/1.14.1 --> Similar to BSD
NCCL/2.18.3 --> BSD 
UCC-CUDA/1.2.0 --> BSD-3-Clause 
OSU-Micro-Benchmarks/7.2 --> BSD
```
```

5 out of 24 required modules missing:

* GDRCopy/2.3.1-GCCcore-12.3.0 (GDRCopy-2.3.1-GCCcore-12.3.0.eb)
* UCX-CUDA/1.14.1-GCCcore-12.3.0-CUDA-12.1.1 (UCX-CUDA-1.14.1-GCCcore-12.3.0-CUDA-12.1.1.eb)
* NCCL/2.18.3-GCCcore-12.3.0-CUDA-12.1.1 (NCCL-2.18.3-GCCcore-12.3.0-CUDA-12.1.1.eb)
* UCC-CUDA/1.2.0-GCCcore-12.3.0-CUDA-12.1.1 (UCC-CUDA-1.2.0-GCCcore-12.3.0-CUDA-12.1.1.eb)
* OSU-Micro-Benchmarks/7.2-gompi-2023a-CUDA-12.1.1 (OSU-Micro-Benchmarks-7.2-gompi-2023a-CUDA-12.1.1.eb)
```

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
FAILURE:
`== FAILED: Installation ended unsuccessfully (build directory: /tmp/nessibot/easybuild/build/NCCL/2.18.3/GCCcore-12.3.0-CUDA-12.1.1): build failed (first 300 chars): Module command '/cvmfs/pilot.nessi.no/versions/2023.06/compat/linux/x86_64/usr/share/Lmod/libexec/lmod python load UCX-CUDA/1.14.1-GCCcore-12.3.0-CUDA-12.1.1' failed with exit code 1; stderr: Lmod has detected the following error:
You requested to load UCX-CUDA  which relies on the CUDA runtime envi`

**Comment by TopRichard** [comment]
Must get done with #362 first

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
Checklist before starting deployment (setting bot:deploy label):

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by TopRichard** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x]  Check if the _SPDX license identifier_ is provided 
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI for the ingested tarballs have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)

<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; 
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/OSU-Micro-Benchmarks/7.2-gompi-2023a-CUDA-12.1.1* \
        aarch64/generic/{software,modules/all}/OSU-Micro-Benchmarks/7.2-gompi-2023a-CUDA-12.1.1*
  ```
  **log**
```
-rw-r--r--. 1 cvmfs cvmfs 1719 May 17 12:52 aarch64/generic/modules/all/OSU-Micro-Benchmarks/7.2-gompi-2023a-CUDA-12.1.1.lua
-rw-rw-r--. 1 cvmfs cvmfs 1719 May 17 06:16 x86_64/amd/zen2/modules/all/OSU-Micro-Benchmarks/7.2-gompi-2023a-CUDA-12.1.1.lua
-rw-rw-r--. 1 cvmfs cvmfs 1718 May 17 06:19 x86_64/generic/modules/all/OSU-Micro-Benchmarks/7.2-gompi-2023a-CUDA-12.1.1.lua
-rw-rw-r--. 1 cvmfs cvmfs 1726 May 17 06:46 x86_64/intel/broadwell/modules/all/OSU-Micro-Benchmarks/7.2-gompi-2023a-CUDA-12.1.1.lua
-rw-rw-r--. 1 cvmfs cvmfs 1731 May 17 06:25 x86_64/intel/skylake_avx512/modules/all/OSU-Micro-Benchmarks/7.2-gompi-2023a-CUDA-12.1.1.lua

aarch64/generic/software/OSU-Micro-Benchmarks/7.2-gompi-2023a-CUDA-12.1.1:
total 9
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May 17 12:52 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May 17 12:52 libexec

x86_64/amd/zen2/software/OSU-Micro-Benchmarks/7.2-gompi-2023a-CUDA-12.1.1:
total 9
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May 17 06:16 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May 17 06:16 libexec

x86_64/generic/software/OSU-Micro-Benchmarks/7.2-gompi-2023a-CUDA-12.1.1:
total 9
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May 17 06:19 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May 17 06:19 libexec

x86_64/intel/broadwell/software/OSU-Micro-Benchmarks/7.2-gompi-2023a-CUDA-12.1.1:
total 9
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May 17 06:46 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May 17 06:46 libexec

x86_64/intel/skylake_avx512/software/OSU-Micro-Benchmarks/7.2-gompi-2023a-CUDA-12.1.1:
total 9
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May 17 06:25 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May 17 06:25 libexec

```
</details>

**Review by justadejavu — APPROVED** [review]
lgtm, requires testing with GPUs

**Pull request merged**
