### PR TITLE
{2023.06}[foss/2021a] GROMACS V2021.3

### PR DESCRIPTION
**Pull request by TopRichard**

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi.no-2023.06-software arch:x86_64/generic 
bot: build inst:AWS repo:nessi.no-2023.06-software arch:x86_64/intel/cascadelake 
bot: build inst:AWS repo:nessi.no-2023.06-software arch:x86_64/intel/skylake 
bot: build inst:Fram-NESSI repo:nessi.no-2023.06-software arch:x86_64/intel/broadwell
bot: build inst:eX3 repo:nessi.no-2023.06-software arch:zen2
bot: build inst:eX3 repo:nessi.no-2023.06-software arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:eX3 repo:nessi.no-2023.06-software arch:zen2

**Comment by TopRichard** [comment]
Checklist for building: 

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by TopRichard** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-intel-cascadelake`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; 
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/GROMACS/2021.3-foss-2021a* \
        aarch64/generic/{software,modules/all}/GROMACS/2021.3-foss-2021a*
  ```
```
-rw-r--r--. 1 cvmfs cvmfs 2328 Jul 26 15:59 aarch64/generic/modules/all/GROMACS/2021.3-foss-2021a.lua
-rw-r--r--. 1 cvmfs cvmfs 2328 Jul 27 07:53 x86_64/amd/zen2/modules/all/GROMACS/2021.3-foss-2021a.lua
-rw-r--r--. 1 cvmfs cvmfs 2327 Jul 26 15:43 x86_64/generic/modules/all/GROMACS/2021.3-foss-2021a.lua
-rw-rw-r--. 1 cvmfs cvmfs 2335 Jul 26 14:57 x86_64/intel/broadwell/modules/all/GROMACS/2021.3-foss-2021a.lua
-rw-r--r--. 1 cvmfs cvmfs 2337 Jul 26 15:03 x86_64/intel/cascadelake/modules/all/GROMACS/2021.3-foss-2021a.lua
-rw-r--r--. 1 cvmfs cvmfs 2340 Jul 26 15:18 x86_64/intel/skylake_avx512/modules/all/GROMACS/2021.3-foss-2021a.lua

aarch64/generic/software/GROMACS/2021.3-foss-2021a:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 26 15:58 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 26 15:59 easybuild
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 26 15:02 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jul 26 15:58 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 26 15:59 lib64 -> lib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 26 15:02 share

x86_64/amd/zen2/software/GROMACS/2021.3-foss-2021a:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 27 07:52 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 27 07:53 easybuild
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 27 07:13 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jul 27 07:52 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 27 07:53 lib64 -> lib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 27 07:13 share

x86_64/generic/software/GROMACS/2021.3-foss-2021a:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 26 15:42 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 26 15:44 easybuild
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 26 14:42 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jul 26 15:42 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 26 15:43 lib64 -> lib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 26 14:42 share

x86_64/intel/broadwell/software/GROMACS/2021.3-foss-2021a:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 26 14:57 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 26 14:58 easybuild
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 26 14:25 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jul 26 14:57 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 26 14:57 lib64 -> lib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 26 14:25 share

x86_64/intel/cascadelake/software/GROMACS/2021.3-foss-2021a:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 26 15:02 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 26 15:03 easybuild
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 26 14:22 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jul 26 15:02 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 26 15:03 lib64 -> lib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 26 14:22 share

x86_64/intel/skylake_avx512/software/GROMACS/2021.3-foss-2021a:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 26 15:17 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 26 15:18 easybuild
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 26 14:30 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jul 26 15:17 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 26 15:18 lib64 -> lib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 26 14:30 share

```
</details>

**Review by justadejavu — APPROVED** [review]

**Comment by TopRichard** [comment]
During the tests, always following `/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/` on all archs!

**Pull request merged**
