### PR TITLE
Add OpenBLAS/0.3.15-GCC/10.3.0 to NESSI/2023.04

### PR DESCRIPTION
**Pull request by TopRichard**
Trying to add OpenBLAS/0.3.15-GCC/10.3.0 to NESSI/2023.04 using the [PR#17924](https://github.com/easybuilders/easybuild-easyconfigs/pull/17924) which includes make 4.3 as build-dependency,this is a fix for the issue introduced by GNU make v4.4, the option using --parallel 1 didn't come out with satisfactory results.

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:AWS arch:x86_64/generic repo:nessi.no-2023.04
bot: build inst:AWS arch:x86_64/intel/cascadelake repo:nessi.no-2023.04
bot: build inst:AWS arch:x86_64/intel/skylake repo:nessi.no-2023.04
bot: build inst:Fram-NESSI arch:x86_64/intel/broadwell repo:nessi.no-2023.04
bot: build inst:eX3 arch:zen2 repo:nessi.no-2023.04
bot: build inst:eX3 arch:aarch64/generic repo:nessi.no-2023.04
- received bot command `build inst:AWS arch:x86_64/generic repo:nessi.no-2023.04` from `TopRichard` (expanded command format: `build instance:AWS architecture:x86_64/generic repository:nessi.no-2023.04`)
- received bot command `build inst:AWS arch:x86_64/intel/cascadelake repo:nessi.no-2023.04` from `TopRichard` (expanded command format: `build instance:AWS architecture:x86_64/intel/cascadelake repository:nessi.no-2023.04`)
- received bot command `build inst:AWS arch:x86_64/intel/skylake repo:nessi.no-2023.04` from `TopRichard` (expanded command format: `build instance:AWS architecture:x86_64/intel/skylake repository:nessi.no-2023.04`)
- received bot command `build inst:Fram-NESSI arch:x86_64/intel/broadwell repo:nessi.no-2023.04` from `TopRichard` (expanded command format: `build instance:Fram-NESSI architecture:x86_64/intel/broadwell repository:nessi.no-2023.04`)
- received bot command `build inst:eX3 arch:zen2 repo:nessi.no-2023.04` from `TopRichard` (expanded command format: `build instance:eX3 architecture:zen2 repository:nessi.no-2023.04`)
- received bot command `build inst:eX3 arch:aarch64/generic repo:nessi.no-2023.04` from `TopRichard` (expanded command format: `build instance:eX3 architecture:aarch64/generic repository:nessi.no-2023.04`)
- handling `build` resulted in: no jobs were prepared
- handling `build` resulted in: no jobs were prepared
- handling `build` resulted in: no jobs were prepared
- handling `build` resulted in: no jobs were prepared
- handling `build` resulted in: no jobs were prepared
- handling `build` resulted in: no jobs were prepared

**Comment by trz42** [comment]
Checklist for building: 

- [x] did the builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x] is the PR up-to-date with the target branch nessi.no-2023.04-dev in the repository (if not what are the differences)
- [x] are all requested changes sound (checking files changed on GitHub.com)
  - the PR lacks special handling of `GENERIC` CPU targets (see #108)
  - addressed with https://github.com/NorESSI/software-layer/pull/110/commits/67163b27249e4327d168594b2a1a0b242ec7b82c
- [x] is/are the easyconfig/s being built included with the EB version used (if not why not)
  - yes, but it is modified via PR#17924 (easyconfigs repo) is used
- [x] were any changes needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)
  - yes, PR#17924 is needed

**Comment by TopRichard** [comment]
bot: build inst:eX3 arch:aarch64/generic repo:nessi.no-2023.04
- received bot command `build inst:eX3 arch:aarch64/generic repo:nessi.no-2023.04` from `TopRichard` (expanded command format: `build instance:eX3 architecture:aarch64/generic repository:nessi.no-2023.04`)
- handling `build` resulted in: no jobs were prepared

**Comment by TopRichard** [comment]
bot: build inst:AWS arch:x86_64/generic repo:nessi.no-2023.04
- received bot command `build inst:AWS arch:x86_64/generic repo:nessi.no-2023.04` from `TopRichard` (expanded command format: `build instance:AWS architecture:x86_64/generic repository:nessi.no-2023.04`)
- handling `build` resulted in: no jobs were prepared

**Comment by TopRichard** [comment]
bot: build inst:Saga-NESSI arch:x86_64/generic repo:nessi.no-2023.04
- received bot command `build inst:Saga-NESSI arch:x86_64/generic repo:nessi.no-2023.04` from `TopRichard` (expanded command format: `build instance:Saga-NESSI architecture:x86_64/generic repository:nessi.no-2023.04`)
- handling `build` resulted in: created jobs: 8685452

**Comment by TopRichard** [comment]
bot: build inst:AWS arch:x86_64/intel/cascadelake repo:nessi.no-2023.04
bot: build inst:AWS arch:x86_64/intel/skylake repo:nessi.no-2023.04
bot: build inst:Fram-NESSI arch:x86_64/intel/broadwell repo:nessi.no-2023.04
bot: build inst:eX3 arch:zen2 repo:nessi.no-2023.04
bot: build inst:eX3 arch:aarch64/generic repo:nessi.no-2023.04
bot: build inst:AWS arch:x86_64/generic repo:nessi.no-2023.04
bot: build inst:Saga-NESSI arch:x86_64/generic repo:nessi.no-2023.04

- received bot command `build inst:AWS arch:x86_64/intel/cascadelake repo:nessi.no-2023.04` from `TopRichard` (expanded command format: `build instance:AWS architecture:x86_64/intel/cascadelake repository:nessi.no-2023.04`)
- received bot command `build inst:AWS arch:x86_64/intel/skylake repo:nessi.no-2023.04` from `TopRichard` (expanded command format: `build instance:AWS architecture:x86_64/intel/skylake repository:nessi.no-2023.04`)
- received bot command `build inst:Fram-NESSI arch:x86_64/intel/broadwell repo:nessi.no-2023.04` from `TopRichard` (expanded command format: `build instance:Fram-NESSI architecture:x86_64/intel/broadwell repository:nessi.no-2023.04`)
- received bot command `build inst:eX3 arch:zen2 repo:nessi.no-2023.04` from `TopRichard` (expanded command format: `build instance:eX3 architecture:zen2 repository:nessi.no-2023.04`)
- received bot command `build inst:eX3 arch:aarch64/generic repo:nessi.no-2023.04` from `TopRichard` (expanded command format: `build instance:eX3 architecture:aarch64/generic repository:nessi.no-2023.04`)
- received bot command `build inst:AWS arch:x86_64/generic repo:nessi.no-2023.04` from `TopRichard` (expanded command format: `build instance:AWS architecture:x86_64/generic repository:nessi.no-2023.04`)
- received bot command `build inst:Saga-NESSI arch:x86_64/generic repo:nessi.no-2023.04` from `TopRichard` (expanded command format: `build instance:Saga-NESSI architecture:x86_64/generic repository:nessi.no-2023.04`)
- handling `build` resulted in: no jobs were prepared
- handling `build` resulted in: no jobs were prepared
- handling `build` resulted in: no jobs were prepared
- handling `build` resulted in: no jobs were prepared
- handling `build` resulted in: no jobs were prepared
- handling `build` resulted in: no jobs were prepared
- handling `build` resulted in: created jobs: 8685633

**Comment by TopRichard** [comment]
bot: build inst:AWS arch:x86_64/generic repo:nessi.no-2023.04
- received bot command `build inst:AWS arch:x86_64/generic repo:nessi.no-2023.04` from `TopRichard` (expanded command format: `build instance:AWS architecture:x86_64/generic repository:nessi.no-2023.04`)
- handling `build` resulted in: no jobs were prepared

**Comment by TopRichard** [comment]
bot: build inst:AWS arch:x86_64/intel/cascadelake repo:nessi.no-2023.04
bot: build inst:AWS arch:x86_64/intel/skylake repo:nessi.no-2023.04
- received bot command `build inst:AWS arch:x86_64/intel/cascadelake repo:nessi.no-2023.04` from `TopRichard` (expanded command format: `build instance:AWS architecture:x86_64/intel/cascadelake repository:nessi.no-2023.04`)
- received bot command `build inst:AWS arch:x86_64/intel/skylake repo:nessi.no-2023.04` from `TopRichard` (expanded command format: `build instance:AWS architecture:x86_64/intel/skylake repository:nessi.no-2023.04`)
- handling `build` resulted in: no jobs were prepared
- handling `build` resulted in: no jobs were prepared

**Comment by trz42** [comment]
check if bot on Saga is still noisy

**Comment by trz42** [comment]
Checklist for deployment/ingestion

- [x] at least one tarball for each architecture has been uploaded
  - [x] `x86_64-intel-broadwell` (see [Fram-NESSI job 5187273](https://github.com/NorESSI/software-layer/pull/110#issuecomment-1558816262))
  - [x] `x86_64-intel-skylake_avx512` (see [AWS-NESSI job 4786](https://github.com/NorESSI/software-layer/pull/110#issuecomment-1560562945))
  - [x] `x86_64-intel-cascadelake` (see [AWS-NESSI job 4785](https://github.com/NorESSI/software-layer/pull/110#issuecomment-1560562809))
  - [x] `x86_64-amd-zen2` (see [eX3-NESSI job 479106](https://github.com/NorESSI/software-layer/pull/110#issuecomment-1558816235))
  - [x] `x86_64-generic` (see [AWS-NESSI job 4784](https://github.com/NorESSI/software-layer/pull/110#issuecomment-1560521790))
  - [x] `aarch64-generic` (see [eX3-NESSI job 479107](https://github.com/NorESSI/software-layer/pull/110#issuecomment-1558816403))
- [x] at least one tarball for each architecture has been staged
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512`
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] for each architecture **one and only one** tarball has been approved
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512`
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] for each architecture **one and only one** tarball was ingested
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512` 
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
  **command**
  ```
  ls -l /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/OpenBLAS/*
  ls -l /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/aarch64/generic/{software,modules/all}/OpenBLAS/*
  ```
  **log**
```
-rw-r--r--. 1 cvmfs cvmfs 1049 May 23 08:52 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/amd/zen2/modules/all/OpenBLAS/0.3.15-GCC-10.3.0.lua
-rw-r--r--. 1 cvmfs cvmfs 1048 May 24 06:50 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/generic/modules/all/OpenBLAS/0.3.15-GCC-10.3.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 1056 May 23 08:55 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/broadwell/modules/all/OpenBLAS/0.3.15-GCC-10.3.0.lua
-rw-r--r--. 1 cvmfs cvmfs 1058 May 24 07:20 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/cascadelake/modules/all/OpenBLAS/0.3.15-GCC-10.3.0.lua
-rw-r--r--. 1 cvmfs cvmfs 1061 May 24 07:21 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/skylake_avx512/modules/all/OpenBLAS/0.3.15-GCC-10.3.0.lua

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/amd/zen2/software/OpenBLAS/0.3.15-GCC-10.3.0:
total 19
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 23 08:52 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 23 08:52 easybuild
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 23 08:52 include
drwxr-xr-x. 4 cvmfs cvmfs 4096 May 23 08:52 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 May 23 08:52 lib64 -> lib

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/generic/software/OpenBLAS/0.3.15-GCC-10.3.0:
total 19
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 24 06:50 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 24 06:50 easybuild
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 24 06:50 include
drwxr-xr-x. 4 cvmfs cvmfs 4096 May 24 06:50 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 May 24 06:50 lib64 -> lib

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/broadwell/software/OpenBLAS/0.3.15-GCC-10.3.0:
total 19
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 23 08:55 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 23 08:55 easybuild
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 23 08:55 include
drwxr-xr-x. 4 cvmfs cvmfs 4096 May 23 08:55 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 May 23 08:55 lib64 -> lib

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/cascadelake/software/OpenBLAS/0.3.15-GCC-10.3.0:
total 19
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 24 07:20 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 24 07:20 easybuild
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 24 07:20 include
drwxr-xr-x. 4 cvmfs cvmfs 4096 May 24 07:20 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 May 24 07:20 lib64 -> lib

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/skylake_avx512/software/OpenBLAS/0.3.15-GCC-10.3.0:
total 19
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 24 07:21 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 24 07:21 easybuild
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 24 07:21 include
drwxr-xr-x. 4 cvmfs cvmfs 4096 May 24 07:21 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 May 24 07:21 lib64 -> lib

-rw-r--r--. 1 cvmfs cvmfs 1049 May 23 09:25 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/aarch64/generic/modules/all/OpenBLAS/0.3.15-GCC-10.3.0.lua

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/aarch64/generic/software/OpenBLAS/0.3.15-GCC-10.3.0:
total 19
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 23 09:25 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 23 09:25 easybuild
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 23 09:25 include
drwxr-xr-x. 4 cvmfs cvmfs 4096 May 23 09:25 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 May 23 09:25 lib64 -> lib 
```

**Review by trz42 — APPROVED** [review]
Finally all looking good. OpenBLAS is ingested and available on client.

**Pull request merged**
