### PR TITLE
{2023.06}[foss/2022a] bio packages - set 1

### PR DESCRIPTION
**Pull request by trz42**
Will install a first set of bio packages (incl dependencies). For each package the licenses are listed too.

- `BAMM-2.5.0-foss-2022a.eb` "GNU General Public License v2.0"
- `BamTools-2.5.2-GCC-11.3.0.eb` "The MIT License”
- `BCFtools-1.15.1-GCC-11.3.0.eb` "The MIT/Expat License”
  - `GSL-2.7-GCC-11.3.0.eb` "GNU General Public License v3.0"
  - `HTSlib-1.15.1-GCC-11.3.0.eb` "The MIT/Expat License”
- `Bowtie2-2.4.5-GCC-11.3.0.eb` "GNU General Public License v3.0”
- `FastTree-2.1.11-GCCcore-11.3.0.eb` “GNU General Public License v2.0“
- `SAMtools-1.16.1-GCC-11.3.0.eb` "The MIT/Expat License”

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:AWS arch:x86_64/generic repo:nessi-2023.06-swl-deb11
bot: build inst:eX3 arch:x86_64/amd/zen2 repo:nessi-2023.06-swl-deb11
bot: build inst:eX3 arch:aarch64/generic repo:nessi-2023.06-swl-deb11
bot: build inst:Fram arch:x86_64/intel/broadwell repo:nessi-2023.06-swl-deb10
bot: build inst:AWS arch:x86_64/intel/cascadelake repo:nessi-2023.06-swl-deb11
bot: build inst:AWS arch:x86_64/intel/skylake repo:nessi-2023.06-swl-deb11

**Comment by trz42** [comment]
Checklist for building: 

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
  - lacks addition of easystack file to CI $\longrightarrow$ added now
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-intel-cascadelake`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
  - all succeeded except for `aarch64/generic`+`eessi-2023.06-eb-4.7.2-2021a.yml` due to `Yambo` not being supported on `aarch64`
  - for details see https://github.com/NorESSI/software-layer/actions/runs/6431790645
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/{BAMM,BamTools,BCFtools,Bowtie2,FastTree,SAMtools}/* \
        aarch64/generic/{software,modules/all}/{BAMM,BamTools,BCFtools,Bowtie2,FastTree,SAMtools}/*
  ```
  **log**
```
-rw-r--r-- 1 cvmfs cvmfs 1233 Oct  5 20:59 aarch64/generic/modules/all/BAMM/2.5.0-foss-2022a.lua
-rw-r--r-- 1 cvmfs cvmfs 1136 Oct  5 21:00 aarch64/generic/modules/all/BamTools/2.5.2-GCC-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1441 Oct  5 21:04 aarch64/generic/modules/all/BCFtools/1.15.1-GCC-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 2028 Oct  5 21:06 aarch64/generic/modules/all/Bowtie2/2.4.5-GCC-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1266 Oct  5 21:06 aarch64/generic/modules/all/FastTree/2.1.11-GCCcore-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1397 Oct  5 21:07 aarch64/generic/modules/all/SAMtools/1.16.1-GCC-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1233 Oct  5 21:01 x86_64/amd/zen2/modules/all/BAMM/2.5.0-foss-2022a.lua
-rw-r--r-- 1 cvmfs cvmfs 1136 Oct  5 21:01 x86_64/amd/zen2/modules/all/BamTools/2.5.2-GCC-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1441 Oct  5 21:04 x86_64/amd/zen2/modules/all/BCFtools/1.15.1-GCC-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 2028 Oct  5 21:05 x86_64/amd/zen2/modules/all/Bowtie2/2.4.5-GCC-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1266 Oct  5 21:05 x86_64/amd/zen2/modules/all/FastTree/2.1.11-GCCcore-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1397 Oct  5 21:06 x86_64/amd/zen2/modules/all/SAMtools/1.16.1-GCC-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1232 Oct  5 20:53 x86_64/generic/modules/all/BAMM/2.5.0-foss-2022a.lua
-rw-r--r-- 1 cvmfs cvmfs 1135 Oct  5 20:54 x86_64/generic/modules/all/BamTools/2.5.2-GCC-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1440 Oct  5 20:57 x86_64/generic/modules/all/BCFtools/1.15.1-GCC-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 2027 Oct  5 20:59 x86_64/generic/modules/all/Bowtie2/2.4.5-GCC-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1265 Oct  5 20:59 x86_64/generic/modules/all/FastTree/2.1.11-GCCcore-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1396 Oct  5 21:00 x86_64/generic/modules/all/SAMtools/1.16.1-GCC-11.3.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 1240 Oct  5 20:47 x86_64/intel/broadwell/modules/all/BAMM/2.5.0-foss-2022a.lua
-rw-rw-r-- 1 cvmfs cvmfs 1143 Oct  5 20:48 x86_64/intel/broadwell/modules/all/BamTools/2.5.2-GCC-11.3.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 1448 Oct  5 20:53 x86_64/intel/broadwell/modules/all/BCFtools/1.15.1-GCC-11.3.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 2035 Oct  5 20:55 x86_64/intel/broadwell/modules/all/Bowtie2/2.4.5-GCC-11.3.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 1273 Oct  5 20:55 x86_64/intel/broadwell/modules/all/FastTree/2.1.11-GCCcore-11.3.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 1404 Oct  5 20:56 x86_64/intel/broadwell/modules/all/SAMtools/1.16.1-GCC-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1242 Oct  5 20:53 x86_64/intel/cascadelake/modules/all/BAMM/2.5.0-foss-2022a.lua
-rw-r--r-- 1 cvmfs cvmfs 1145 Oct  5 20:53 x86_64/intel/cascadelake/modules/all/BamTools/2.5.2-GCC-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1450 Oct  5 20:56 x86_64/intel/cascadelake/modules/all/BCFtools/1.15.1-GCC-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 2037 Oct  5 20:58 x86_64/intel/cascadelake/modules/all/Bowtie2/2.4.5-GCC-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1275 Oct  5 20:58 x86_64/intel/cascadelake/modules/all/FastTree/2.1.11-GCCcore-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1406 Oct  5 20:59 x86_64/intel/cascadelake/modules/all/SAMtools/1.16.1-GCC-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1245 Oct  5 20:56 x86_64/intel/skylake_avx512/modules/all/BAMM/2.5.0-foss-2022a.lua
-rw-r--r-- 1 cvmfs cvmfs 1148 Oct  5 20:57 x86_64/intel/skylake_avx512/modules/all/BamTools/2.5.2-GCC-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1453 Oct  5 20:59 x86_64/intel/skylake_avx512/modules/all/BCFtools/1.15.1-GCC-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 2040 Oct  5 21:01 x86_64/intel/skylake_avx512/modules/all/Bowtie2/2.4.5-GCC-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1278 Oct  5 21:01 x86_64/intel/skylake_avx512/modules/all/FastTree/2.1.11-GCCcore-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1409 Oct  5 21:02 x86_64/intel/skylake_avx512/modules/all/SAMtools/1.16.1-GCC-11.3.0.lua

aarch64/generic/software/BAMM/2.5.0-foss-2022a:
total 9
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 20:59 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 21:00 easybuild

aarch64/generic/software/BamTools/2.5.2-GCC-11.3.0:
total 19
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 21:00 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 21:00 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 21:00 include
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 21:00 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  5 21:00 lib64 -> lib

aarch64/generic/software/BCFtools/1.15.1-GCC-11.3.0:
total 18
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 21:04 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 21:04 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 21:04 libexec
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 21:04 share

aarch64/generic/software/Bowtie2/2.4.5-GCC-11.3.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 21:06 bin
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 17  2022 doc
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 21:06 easybuild
dr-xr-xr-x 5 cvmfs cvmfs 4096 Jan 17  2022 example
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 17  2022 scripts

aarch64/generic/software/FastTree/2.1.11-GCCcore-11.3.0:
total 9
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 21:06 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 21:06 easybuild

aarch64/generic/software/SAMtools/1.16.1-GCC-11.3.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 21:07 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 21:07 easybuild
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  5 21:07 include
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 21:07 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  5 21:07 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 21:07 share

x86_64/amd/zen2/software/BAMM/2.5.0-foss-2022a:
total 9
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 21:00 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 21:01 easybuild

x86_64/amd/zen2/software/BamTools/2.5.2-GCC-11.3.0:
total 19
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 21:01 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 21:01 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 21:01 include
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 21:01 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  5 21:01 lib64 -> lib

x86_64/amd/zen2/software/BCFtools/1.15.1-GCC-11.3.0:
total 18
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 21:04 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 21:04 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 21:04 libexec
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 21:04 share

x86_64/amd/zen2/software/Bowtie2/2.4.5-GCC-11.3.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 21:05 bin
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 17  2022 doc
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 21:05 easybuild
dr-xr-xr-x 5 cvmfs cvmfs 4096 Jan 17  2022 example
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 17  2022 scripts

x86_64/amd/zen2/software/FastTree/2.1.11-GCCcore-11.3.0:
total 9
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 21:05 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 21:05 easybuild

x86_64/amd/zen2/software/SAMtools/1.16.1-GCC-11.3.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 21:06 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 21:06 easybuild
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  5 21:06 include
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 21:06 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  5 21:06 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 21:06 share

x86_64/generic/software/BAMM/2.5.0-foss-2022a:
total 9
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 20:53 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:53 easybuild

x86_64/generic/software/BamTools/2.5.2-GCC-11.3.0:
total 19
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 20:54 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:54 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:54 include
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:54 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  5 20:54 lib64 -> lib

x86_64/generic/software/BCFtools/1.15.1-GCC-11.3.0:
total 18
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 20:57 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:57 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:57 libexec
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:57 share

x86_64/generic/software/Bowtie2/2.4.5-GCC-11.3.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 20:58 bin
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 17  2022 doc
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:59 easybuild
dr-xr-xr-x 5 cvmfs cvmfs 4096 Jan 17  2022 example
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 17  2022 scripts

x86_64/generic/software/FastTree/2.1.11-GCCcore-11.3.0:
total 9
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 20:59 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:59 easybuild

x86_64/generic/software/SAMtools/1.16.1-GCC-11.3.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 21:00 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 21:00 easybuild
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  5 21:00 include
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 21:00 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  5 21:00 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 21:00 share

x86_64/intel/broadwell/software/BAMM/2.5.0-foss-2022a:
total 9
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 20:47 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:47 easybuild

x86_64/intel/broadwell/software/BamTools/2.5.2-GCC-11.3.0:
total 19
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 20:48 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:48 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:48 include
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:48 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  5 20:48 lib64 -> lib

x86_64/intel/broadwell/software/BCFtools/1.15.1-GCC-11.3.0:
total 18
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 20:53 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:53 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:53 libexec
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:53 share

x86_64/intel/broadwell/software/Bowtie2/2.4.5-GCC-11.3.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 20:54 bin
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 17  2022 doc
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:55 easybuild
dr-xr-xr-x 5 cvmfs cvmfs 4096 Jan 17  2022 example
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 17  2022 scripts

x86_64/intel/broadwell/software/FastTree/2.1.11-GCCcore-11.3.0:
total 9
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 20:55 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:55 easybuild

x86_64/intel/broadwell/software/SAMtools/1.16.1-GCC-11.3.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 20:56 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:56 easybuild
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  5 20:56 include
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 20:56 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  5 20:56 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:56 share

x86_64/intel/cascadelake/software/BAMM/2.5.0-foss-2022a:
total 9
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 20:52 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:53 easybuild

x86_64/intel/cascadelake/software/BamTools/2.5.2-GCC-11.3.0:
total 19
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 20:53 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:53 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:53 include
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:53 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  5 20:53 lib64 -> lib

x86_64/intel/cascadelake/software/BCFtools/1.15.1-GCC-11.3.0:
total 18
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 20:56 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:56 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:56 libexec
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:56 share

x86_64/intel/cascadelake/software/Bowtie2/2.4.5-GCC-11.3.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 20:57 bin
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 17  2022 doc
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:58 easybuild
dr-xr-xr-x 5 cvmfs cvmfs 4096 Jan 17  2022 example
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 17  2022 scripts

x86_64/intel/cascadelake/software/FastTree/2.1.11-GCCcore-11.3.0:
total 9
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 20:58 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:58 easybuild

x86_64/intel/cascadelake/software/SAMtools/1.16.1-GCC-11.3.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 20:59 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:59 easybuild
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  5 20:59 include
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 20:59 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  5 20:59 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:59 share

x86_64/intel/skylake_avx512/software/BAMM/2.5.0-foss-2022a:
total 9
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 20:56 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:56 easybuild

x86_64/intel/skylake_avx512/software/BamTools/2.5.2-GCC-11.3.0:
total 19
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 20:57 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:57 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:57 include
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:57 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  5 20:57 lib64 -> lib

x86_64/intel/skylake_avx512/software/BCFtools/1.15.1-GCC-11.3.0:
total 18
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 20:59 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:59 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:59 libexec
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 20:59 share

x86_64/intel/skylake_avx512/software/Bowtie2/2.4.5-GCC-11.3.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 21:00 bin
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 17  2022 doc
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 21:01 easybuild
dr-xr-xr-x 5 cvmfs cvmfs 4096 Jan 17  2022 example
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 17  2022 scripts

x86_64/intel/skylake_avx512/software/FastTree/2.1.11-GCCcore-11.3.0:
total 9
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 21:01 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 21:01 easybuild

x86_64/intel/skylake_avx512/software/SAMtools/1.16.1-GCC-11.3.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 21:02 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 21:02 easybuild
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  5 21:02 include
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  5 21:02 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  5 21:02 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  5 21:02 share 
```
</details>

**Review by poksumdo — APPROVED** [review]
Looks good.

**Pull request merged**
