### PR TITLE
add GCC/10.3.0 to NESSI/2023.04

### PR DESCRIPTION
**Pull request by trz42**

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:AWS repo:nessi.no-2023.04 arch:x86_64/generic
- received bot command `build inst:AWS repo:nessi.no-2023.04 arch:x86_64/generic` from `trz42` (expanded command format: `build instance:AWS repository:nessi.no-2023.04 architecture:x86_64/generic`)

**Comment by trz42** [comment]
bot: build inst:AWS repo:nessi.no-2023.04 arch:x86_64/generic
- received bot command `build inst:AWS repo:nessi.no-2023.04 arch:x86_64/generic` from `trz42` (expanded command format: `build instance:AWS repository:nessi.no-2023.04 architecture:x86_64/generic`)

**Comment by trz42** [comment]
bot: build inst:AWS repo:nessi.no-2023.04 arch:x86_64/generic
- received bot command `build inst:AWS repo:nessi.no-2023.04 arch:x86_64/generic` from `trz42` (expanded command format: `build instance:AWS repository:nessi.no-2023.04 architecture:x86_64/generic`)

**Comment by trz42** [comment]
bot: build inst:AWS repo:nessi.no-2023.04 arch:x86_64/generic
- received bot command `build inst:AWS repo:nessi.no-2023.04 arch:x86_64/generic` from `trz42` (expanded command format: `build instance:AWS repository:nessi.no-2023.04 architecture:x86_64/generic`)

**Comment by trz42** [comment]
bot: build inst:AWS repo:nessi.no-2023.04 arch:x86_64/generic
- received bot command `build inst:AWS repo:nessi.no-2023.04 arch:x86_64/generic` from `trz42` (expanded command format: `build instance:AWS repository:nessi.no-2023.04 architecture:x86_64/generic`)

**Comment by trz42** [comment]
bot: build inst:AWS repo:nessi.no-2023.04 arch:x86_64/generic
- received bot command `build inst:AWS repo:nessi.no-2023.04 arch:x86_64/generic` from `trz42` (expanded command format: `build instance:AWS repository:nessi.no-2023.04 architecture:x86_64/generic`)

**Comment by trz42** [comment]
bot: showconfig
- received bot command `showconfig` from `trz42` (expanded command format: `showconfig `)

**Comment by trz42** [comment]
bot: build repo:nessi.no-2023.04
- received bot command `build repo:nessi.no-2023.04` from `trz42` (expanded command format: `build repository:nessi.no-2023.04`)

**Comment by trz42** [comment]
Checklist for building: 

- [x]  did the builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  is the PR up-to-date with the target branch nessi.no-2023.04-dev in the repository (if not what are the differences)
- [x]  are all requested changes sound (checking files changed on GitHub.com)
  - [PR#2921](https://github.com/easybuilders/easybuild-easyblocks/pull/2921) may not be final, but the change needed for building GCC/10.3.0 here will be kept in place one way or the other
  - the temporarily used custom GCC easyblock has been moved to to that PR (it's not part of this PR here any longer) 
- [x]  is/are the easyconfig/s being built included with the EB version used (if not why not)
  - only the easyblock is not yet part (because a PR needed to be used)
- [x]  were any changes needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)
  - yes, see [PR#2921](https://github.com/easybuilders/easybuild-easyblocks/pull/2921)

**Comment by trz42** [comment]
Checklist for deployment/ingestion

- [x] at least one tarball for each architecture has been uploaded
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512`
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] at least one tarball for each architecture has been staged
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512`
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] for each architecture **one and only one** tarball has been approved
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512`
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] for each architecture **one and only one** tarball was ingested
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512` 
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
  **command**
  ```
  ls -l /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/{EasyBuild,GCC*}/*
  ls -l /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/aarch64/generic/{software,modules/all}/{EasyBuild,GCC*}/*
  ```
  **log**
```
-rw-r--r--.  1 cvmfs cvmfs 1222 Apr 21 20:35 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/amd/zen2/modules/all/EasyBuild/4.7.1.lua
-rw-r--r--.  1 cvmfs cvmfs 1023 Apr 21 21:45 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/amd/zen2/modules/all/GCC/10.3.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1133 Apr 21 21:45 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/amd/zen2/modules/all/GCCcore/10.3.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1221 Apr 21 20:42 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/generic/modules/all/EasyBuild/4.7.1.lua
-rw-r--r--.  1 cvmfs cvmfs 1021 Apr 21 21:57 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/generic/modules/all/GCC/10.3.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1132 Apr 21 21:57 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/generic/modules/all/GCCcore/10.3.0.lua
-rw-rw-r--.  1 cvmfs cvmfs 1229 Apr 22 06:05 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/broadwell/modules/all/EasyBuild/4.7.1.lua
-rw-rw-r--.  1 cvmfs cvmfs 1037 Apr 22 07:08 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/broadwell/modules/all/GCC/10.3.0.lua
-rw-rw-r--.  1 cvmfs cvmfs 1140 Apr 22 07:08 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/broadwell/modules/all/GCCcore/10.3.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1231 Apr 21 20:41 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/cascadelake/modules/all/EasyBuild/4.7.1.lua
-rw-r--r--.  1 cvmfs cvmfs 1041 Apr 21 21:34 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/cascadelake/modules/all/GCC/10.3.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1142 Apr 21 21:34 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/cascadelake/modules/all/GCCcore/10.3.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1234 Apr 21 20:41 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/skylake_avx512/modules/all/EasyBuild/4.7.1.lua
-rw-r--r--.  1 cvmfs cvmfs 1047 Apr 21 21:42 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/skylake_avx512/modules/all/GCC/10.3.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1145 Apr 21 21:42 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/skylake_avx512/modules/all/GCCcore/10.3.0.lua

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/amd/zen2/software/EasyBuild/4.7.1:
total 23
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 20:34 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 20:34 contrib
drwxr-xr-x. 5 cvmfs cvmfs 4096 Apr 21 20:35 easybuild
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 21 20:34 etc
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 20:34 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 21 20:35 lib64 -> lib

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/amd/zen2/software/GCC/10.3.0:
total 5
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 21:45 easybuild

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/amd/zen2/software/GCCcore/10.3.0:
total 36
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 21 21:45 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 21:45 easybuild
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 21:33 include
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 21:32 lib
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 21 21:44 lib64
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 21:32 libexec
drwxr-xr-x. 5 cvmfs cvmfs 4096 Apr 21 21:45 nvptx-none
drwxr-xr-x. 6 cvmfs cvmfs 4096 Apr 21 21:33 share

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/generic/software/EasyBuild/4.7.1:
total 23
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 20:41 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 20:41 contrib
drwxr-xr-x. 5 cvmfs cvmfs 4096 Apr 21 20:42 easybuild
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 21 20:41 etc
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 20:41 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 21 20:42 lib64 -> lib

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/generic/software/GCC/10.3.0:
total 5
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 21:57 easybuild

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/generic/software/GCCcore/10.3.0:
total 36
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 21 21:57 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 21:57 easybuild
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 21:46 include
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 21:46 lib
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 21 21:57 lib64
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 21:46 libexec
drwxr-xr-x. 5 cvmfs cvmfs 4096 Apr 21 21:57 nvptx-none
drwxr-xr-x. 6 cvmfs cvmfs 4096 Apr 21 21:46 share

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/broadwell/software/EasyBuild/4.7.1:
total 23
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 22 06:04 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 22 06:04 contrib
drwxr-xr-x. 5 cvmfs cvmfs 4096 Apr 22 06:05 easybuild
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 22 06:04 etc
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 22 06:04 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 22 06:05 lib64 -> lib

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/broadwell/software/GCC/10.3.0:
total 5
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 22 07:08 easybuild

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/broadwell/software/GCCcore/10.3.0:
total 36
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 22 07:08 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 22 07:08 easybuild
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 22 06:56 include
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 22 06:55 lib
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 22 07:07 lib64
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 22 06:55 libexec
drwxr-xr-x. 5 cvmfs cvmfs 4096 Apr 22 07:07 nvptx-none
drwxr-xr-x. 6 cvmfs cvmfs 4096 Apr 22 06:56 share

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/cascadelake/software/EasyBuild/4.7.1:
total 23
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 20:41 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 20:41 contrib
drwxr-xr-x. 5 cvmfs cvmfs 4096 Apr 21 20:42 easybuild
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 21 20:41 etc
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 20:41 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 21 20:41 lib64 -> lib

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/cascadelake/software/GCC/10.3.0:
total 5
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 21:34 easybuild

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/cascadelake/software/GCCcore/10.3.0:
total 36
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 21 21:34 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 21:34 easybuild
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 21:26 include
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 21:26 lib
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 21 21:34 lib64
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 21:26 libexec
drwxr-xr-x. 5 cvmfs cvmfs 4096 Apr 21 21:34 nvptx-none
drwxr-xr-x. 6 cvmfs cvmfs 4096 Apr 21 21:27 share

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/skylake_avx512/software/EasyBuild/4.7.1:
total 23
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 20:41 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 20:41 contrib
drwxr-xr-x. 5 cvmfs cvmfs 4096 Apr 21 20:42 easybuild
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 21 20:41 etc
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 20:41 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 21 20:41 lib64 -> lib

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/skylake_avx512/software/GCC/10.3.0:
total 5
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 21:43 easybuild

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/skylake_avx512/software/GCCcore/10.3.0:
total 36
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 21 21:42 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 21:42 easybuild
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 21:33 include
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 21:33 lib
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 21 21:42 lib64
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 21:33 libexec
drwxr-xr-x. 5 cvmfs cvmfs 4096 Apr 21 21:42 nvptx-none
drwxr-xr-x. 6 cvmfs cvmfs 4096 Apr 21 21:33 share

-rw-r--r--.  1 cvmfs cvmfs 1223 Apr 21 20:36 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/aarch64/generic/modules/all/EasyBuild/4.7.1.lua
-rw-r--r--.  1 cvmfs cvmfs 1023 Apr 21 22:20 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/aarch64/generic/modules/all/GCC/10.3.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1133 Apr 21 22:20 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/aarch64/generic/modules/all/GCCcore/10.3.0.lua

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/aarch64/generic/software/EasyBuild/4.7.1:
total 23
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 20:35 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 20:35 contrib
drwxr-xr-x. 5 cvmfs cvmfs 4096 Apr 21 20:37 easybuild
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 21 20:35 etc
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 20:35 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 21 20:36 lib64 -> lib

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/aarch64/generic/software/GCC/10.3.0:
total 5
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 22:20 easybuild

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/aarch64/generic/software/GCCcore/10.3.0:
total 36
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 21 22:19 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 22:20 easybuild
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 22:00 include
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 21:59 lib
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 21 22:19 lib64
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 21 21:59 libexec
drwxr-xr-x. 5 cvmfs cvmfs 4096 Apr 21 22:19 nvptx-none
drwxr-xr-x. 6 cvmfs cvmfs 4096 Apr 21 22:00 share
```

**Review by poksumdo — APPROVED** [review]
Everything looks good. Let's build some more software!

**Pull request merged**
