### PR TITLE
{2023.06}[foss/2023a] PyTorch v2.1.2 with CUDA/12.1.1

### PR DESCRIPTION
**Pull request by trz42**
Add `PyTorch/2.1.2-foss-2023a-CUDA-12.1.1` to NESSI.

SPDX license identifier: `BSD-style`

Missing packages:
```
2 out of 107 required modules missing:

* magma/2.7.2-foss-2023a-CUDA-12.1.1 (magma-2.7.2-foss-2023a-CUDA-12.1.1.eb)
* PyTorch/2.1.2-foss-2023a-CUDA-12.1.1 (PyTorch-2.1.2-foss-2023a-CUDA-12.1.1.eb)
```

### CODE REVIEW

**Comment by trz42** [comment]
Just a first test on a single architecture...

bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2

**Comment by trz42** [comment]
Next try after #370 (fix for GPU check)...

bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2

**Comment by trz42** [comment]
Next try after putting source file under shared source path...

bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2

**Comment by trz42** [comment]
Setting of compute capability was missing. For now, just build for `7.0`...

bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2

**Comment by trz42** [comment]
Good page discussing compute capabilities: https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/

**Comment by trz42** [comment]
Attempting to add directory `$CUDA/extras/CUPTI/lib64` to `LIBRARY_PATH`...

bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2

**Comment by trz42** [comment]
Attempting to add directory `$EESSI_SOFTWARE_PATH/software/CUDA/12.1.1/extras/CUPTI/lib64` to `LIBRARY_PATH`...

bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2

**Comment by trz42** [comment]
Check availability of `nvcc` after installing it under `host_injections`...

bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2

**Comment by trz42** [comment]
Let's try a build for all architectures...

bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb10 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
We may still want to add changes done in https://github.com/EESSI/software-layer/pull/579, https://github.com/EESSI/software-layer/pull/581 and https://github.com/EESSI/software-layer/pull/586, and do a rebuild before ingesting.

**Comment by trz42** [comment]
Node didn't spin up...

bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
Repeat the builds with all relevant compute capabilities (`6.0,6.1,7.0,7.5,8.0,8.6,8.9,9.0`)...

bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb10 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by trz42** [comment]
Strange error on AWS (some command not found). Just retry...

bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
Similar strange error on AWS (some command not found). Just keep retrying...

bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2

**Comment by trz42** [comment]
Job on `eX3` might run out of time. Launching another one giving it more resources and time (updated `app.cfg`)...

bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb10 arch:aarch64/generic

**Comment by trz42** [comment]
Job on `Saga` (`Broadwell` nodes) might run out of time. Launching another one giving it more resources and time (updated app.cfg)...

bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by trz42** [comment]
Job on Saga (`Broadwell` nodes) might run out of time. Launching another one giving it more resources and time (tweaked `app.cfg`)...

bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by trz42** [comment]
After some strange error on AWS (some command not found). Built on `zen2`, now retry `x86_64/generic` too...

bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
Job on `eX3` shows lots of Python errors. Launching another one giving it more resources and time (updated `app.cfg`)...

bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb10 arch:aarch64/generic

**Comment by trz42** [comment]
Try job on AWS and with different container (on eX3)...

bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:aarch64/generic
bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by trz42** [comment]
Try again `deb10` container

bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb10 arch:aarch64/generic

**Comment by trz42** [comment]
Try running tests sequentially...

bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb10 arch:aarch64/generic

**Comment by trz42** [comment]
Checklist before starting deployment (setting `bot:deploy` label): 

- [x]  Check if the _SPDX license identifier_ is provided 
- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
  - lots of problems building for `aarch64/generic` on `eX3`, hence using a build from `AWS`
  - anyhow these builds should be considered experimental and will be replaced in the future 
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
  - it includes a change to `eb_hooks.py` to run tests sequentially
  - we should comment that out before merging, because it wasn't needed when building the package on `AWS` 
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
We need to be very careful which staging PRs shall be approved and which shall be rejected. Also any tarball we ingest may not include the updated `eb_hooks.py` (running PyTorch tests sequentially on `aarch64`), hence subsequent PRs may/will include `eb_hooks.py` which could come as a surprise.

Target architectures
  - `x86_64-intel-broadwell`: `eessi-2023.06-software-linux-x86_64-intel-broadwell-1716873120.tar.gz`
  - `x86_64-intel-skylake_avx512`: `eessi-2023.06-software-linux-x86_64-intel-skylake_avx512-1716771995.tar.gz`
  - `x86_64-amd-zen2`: `eessi-2023.06-software-linux-x86_64-amd-zen2-1716794817.tar.gz`
  - `x86_64-generic`: `eessi-2023.06-software-linux-x86_64-generic-1716836288.tar.gz`
  - `aarch64-generic`: `eessi-2023.06-software-linux-aarch64-generic-1717036716.tar.gz`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each staged tarball was a PR for approval/rejection opened
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```bash
BASE_DIR=/cvmfs/pilot.nessi.no/versions/2023.06/software/linux \
ARCHS=() \
ARCHS+=("aarch64/generic") ; \
ARCHS+=("x86_64/generic") ; \
ARCHS+=("x86_64/amd/zen2") ; \
ARCHS+=("x86_64/intel/broadwell") ; \
ARCHS+=("x86_64/intel/skylake_avx512") ; \
for arch in "${ARCHS[@]}"; do \
ls -l \
  ${BASE_DIR}/${arch}/{software,modules/all}/magma/2.7.2-foss-2023a-CUDA-12.1.1* \
  ${BASE_DIR}/${arch}/{software,modules/all}/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1* ; \
done ; \
ls -l \
  ${BASE_DIR}/../../init/easybuild/eb_hooks.py
  ```
  **log - BEFORE ingestion**
```bash
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/software/magma/2.7.2-foss-2023a-CUDA-12.1.1*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/modules/all/magma/2.7.2-foss-2023a-CUDA-12.1.1*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/software/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/modules/all/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/software/magma/2.7.2-foss-2023a-CUDA-12.1.1*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/modules/all/magma/2.7.2-foss-2023a-CUDA-12.1.1*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/software/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/modules/all/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/software/magma/2.7.2-foss-2023a-CUDA-12.1.1*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all/magma/2.7.2-foss-2023a-CUDA-12.1.1*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/software/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/software/magma/2.7.2-foss-2023a-CUDA-12.1.1*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/modules/all/magma/2.7.2-foss-2023a-CUDA-12.1.1*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/software/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/modules/all/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/magma/2.7.2-foss-2023a-CUDA-12.1.1*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/modules/all/magma/2.7.2-foss-2023a-CUDA-12.1.1*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/modules/all/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1*': No such file or directory
-rw-rw-r-- 1 cvmfs cvmfs 43825 May 22 23:12 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/../../init/easybuild/eb_hooks.py 
```
  **log - AFTER ingestion**
```bash
-rw-rw-r-- 1 cvmfs cvmfs 1425 May 29 19:05 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/modules/all/magma/2.7.2-foss-2023a-CUDA-12.1.1.lua
-rw-rw-r-- 1 cvmfs cvmfs 3238 May 30 04:34 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/modules/all/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/software/magma/2.7.2-foss-2023a-CUDA-12.1.1:
total 14
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 29 19:05 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 May 29 19:05 include
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 29 19:05 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 May 29 19:05 lib64 -> lib

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/software/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1:
total 14
dr-xr-xr-x 2 cvmfs cvmfs 4096 May 30 04:34 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 30 04:35 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 30 04:32 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 May 30 04:34 lib64 -> lib
-rw-rw-r-- 1 cvmfs cvmfs 1424 May 27 11:29 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/modules/all/magma/2.7.2-foss-2023a-CUDA-12.1.1.lua
-rw-rw-r-- 1 cvmfs cvmfs 3237 May 27 20:54 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/modules/all/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/software/magma/2.7.2-foss-2023a-CUDA-12.1.1:
total 14
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 27 11:29 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 May 27 11:29 include
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 27 11:29 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 May 27 11:29 lib64 -> lib

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/software/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1:
total 14
dr-xr-xr-x 2 cvmfs cvmfs 4096 May 27 20:54 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 27 20:55 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 27 20:52 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 May 27 20:54 lib64 -> lib
-rw-rw-r-- 1 cvmfs cvmfs 1425 May 26 23:06 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all/magma/2.7.2-foss-2023a-CUDA-12.1.1.lua
-rw-rw-r-- 1 cvmfs cvmfs 3238 May 27 09:23 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/software/magma/2.7.2-foss-2023a-CUDA-12.1.1:
total 14
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 26 23:07 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 May 26 23:06 include
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 26 23:06 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 May 26 23:06 lib64 -> lib

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/software/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1:
total 14
dr-xr-xr-x 2 cvmfs cvmfs 4096 May 27 09:22 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 27 09:24 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 27 09:20 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 May 27 09:22 lib64 -> lib
-rw-rw-r-- 1 cvmfs cvmfs 1432 May 27 11:14 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/modules/all/magma/2.7.2-foss-2023a-CUDA-12.1.1.lua
-rw-rw-r-- 1 cvmfs cvmfs 3245 May 28 07:06 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/modules/all/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/software/magma/2.7.2-foss-2023a-CUDA-12.1.1:
total 14
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 27 11:14 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 May 27 11:14 include
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 27 11:14 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 May 27 11:14 lib64 -> lib

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/software/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1:
total 14
dr-xr-xr-x 2 cvmfs cvmfs 4096 May 28 07:06 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 28 07:08 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 28 07:02 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 May 28 07:06 lib64 -> lib
-rw-rw-r-- 1 cvmfs cvmfs 1437 May 26 09:03 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/modules/all/magma/2.7.2-foss-2023a-CUDA-12.1.1.lua
-rw-rw-r-- 1 cvmfs cvmfs 3250 May 27 03:02 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/modules/all/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/magma/2.7.2-foss-2023a-CUDA-12.1.1:
total 14
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 26 09:03 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 May 26 09:02 include
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 26 09:02 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 May 26 09:02 lib64 -> lib

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/PyTorch/2.1.2-foss-2023a-CUDA-12.1.1:
total 14
dr-xr-xr-x 2 cvmfs cvmfs 4096 May 27 03:01 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 27 03:03 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 27 01:03 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 May 27 03:01 lib64 -> lib
-rw-rw-r-- 1 cvmfs cvmfs 45378 May 26 08:15 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/../../init/easybuild/eb_hooks.py 
```
</details>

**Review by poksumdo — APPROVED** [review]
Not an easy one.

We'll have to redo it once it is clear how to build such modules in EESSI and when the bot is ready for it.

In the meantime we can test it on Saga, Betzy and eX3.

**Pull request merged**
