### PR TITLE
prevent GObject-Introspection from setting EB-filtered environment variables

### PR DESCRIPTION
**Pull request by TopRichard**
Sync with EESSI ( PR 646)

### CODE REVIEW

**Comment by TopRichard** [comment]
We will remove the necessary files from Stratum-0 :
```
rm -rf  aarch64/generic/software/GObject-Introspection/1.74.0-GCCcore-12.2.0
rm -rf  aarch64/generic/software/GObject-Introspection/1.76.1-GCCcore-12.3.0 
rm -rf  aarch64/generic/software/GObject-Introspection/1.78.1-GCCcore-13.2.0 
rm -rf  aarch64/generic/software/at-spi2-core/2.46.0-GCCcore-12.2.0         
rm -rf  aarch64/generic/software/at-spi2-core/2.49.91-GCCcore-12.3.0

rm -rf  x86_64/amd/zen2/software/GObject-Introspection/1.74.0-GCCcore-12.2.0    
rm -rf  x86_64/amd/zen2/software/GObject-Introspection/1.76.1-GCCcore-12.3.0
rm -rf  x86_64/amd/zen2/software/GObject-Introspection/1.78.1-GCCcore-13.2.0 
rm -rf  x86_64/amd/zen2/software/at-spi2-core/2.46.0-GCCcore-12.2.0         
rm -rf  x86_64/amd/zen2/software/at-spi2-core/2.49.91-GCCcore-12.3.0

rm -rf  x86_64/generic/software/GObject-Introspection/1.74.0-GCCcore-12.2.0 
rm -rf  x86_64/generic/software/GObject-Introspection/1.76.1-GCCcore-12.3.0 
rm -rf  x86_64/generic/software/GObject-Introspection/1.78.1-GCCcore-13.2.0
rm -rf  x86_64/generic/software/at-spi2-core/2.46.0-GCCcore-12.2.0 
rm -rf  x86_64/generic/software/at-spi2-core/2.49.91-GCCcore-12.3.0

rm -rf  x86_64/intel/broadwell/software/GObject-Introspection/1.74.0-GCCcore-12.2.0 
rm -rf  x86_64/intel/broadwell/software/GObject-Introspection/1.76.1-GCCcore-12.3.0 
rm -rf  x86_64/intel/broadwell/software/GObject-Introspection/1.78.1-GCCcore-13.2.0 
rm -rf  x86_64/intel/broadwell/software/at-spi2-core/2.46.0-GCCcore-12.2.0         
rm -rf  x86_64/intel/broadwell/software/at-spi2-core/2.49.91-GCCcore-12.3.0 

rm -rf  x86_64/intel/skylake_avx512/software/GObject-Introspection/1.74.0-GCCcore-12.2.0
rm -rf  x86_64/intel/skylake_avx512/software/GObject-Introspection/1.76.1-GCCcore-12.3.0
rm -rf  x86_64/intel/skylake_avx512/software/GObject-Introspection/1.78.1-GCCcore-13.2.0
rm -rf  x86_64/intel/skylake_avx512/software/at-spi2-core/2.46.0-GCCcore-12.2.0
rm -rf  x86_64/intel/skylake_avx512/software/at-spi2-core/2.49.91-GCCcore-12.3.0

rm aarch64/generic/modules/all/GObject-Introspection/{1.74.0-GCCcore-12.2.0,1.76.1-GCCcore-12.3.0,1.78.1-GCCcore-13.2.0}.lua
rm aarch64/generic/modules/all/at-spi2-core/{2.46.0-GCCcore-12.2.0,2.49.91-GCCcore-12.3.0}.lua

rm x86_64/amd/zen2/modules/all/GObject-Introspection/{1.74.0-GCCcore-12.2.0,1.76.1-GCCcore-12.3.0,1.78.1-GCCcore-13.2.0}.lua
rm x86_64/amd/zen2/modules/all/at-spi2-core/{2.46.0-GCCcore-12.2.0,2.49.91-GCCcore-12.3.0}.lua

rm x86_64/generic/modules/all/GObject-Introspection/{1.74.0-GCCcore-12.2.0,1.76.1-GCCcore-12.3.0,1.78.1-GCCcore-13.2.0}.lua
rm x86_64/generic/modules/all/at-spi2-core/{2.46.0-GCCcore-12.2.0,2.49.91-GCCcore-12.3.0}.lua

rm x86_64/intel/broadwell/modules/all/GObject-Introspection/{1.74.0-GCCcore-12.2.0,1.76.1-GCCcore-12.3.0,1.78.1-GCCcore-13.2.0}.lua
rm x86_64/intel/broadwell/modules/all/at-spi2-core/{2.46.0-GCCcore-12.2.0,2.49.91-GCCcore-12.3.0}.lua

rm x86_64/intel/skylake_avx512/modules/all/GObject-Introspection/{1.74.0-GCCcore-12.2.0,1.76.1-GCCcore-12.3.0,1.78.1-GCCcore-13.2.0}.lua
rm x86_64/intel/skylake_avx512/modules/all/at-spi2-core/{2.46.0-GCCcore-12.2.0,2.49.91-GCCcore-12.3.0}.lua


```

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
The failure is due to :
```
CernVM-FS: loading Fuse module... done
ESC[31mERROR: NESSI repository at /cvmfs/pilot.nessi.no/versions/2023.06 not found!ESC[0m
ESC[32m/cvmfs/pilot.nessi.no available, OK!ESC[0m
ESC[31mERROR: Failed to determine software subdirectory?!ESC[0m

```

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
Checklist before starting deployment (setting bot:deploy label):

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by TopRichard** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x]  Check if the _SPDX license identifier_ is provided 
    - Only rebuild
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI for the ingested tarballs have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)

<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; 
  for soft in "at-spi2-core/2.46.0-GCCcore-12.2.0" "at-spi2-core/2.49.91-GCCcore-12.3.0" "GObject-Introspection/1.74.0-GCCcore-12.2.0" "GObject-Introspection/1.76.1-GCCcore-12.3.0" "GObject-Introspection/1.78.1-GCCcore-13.2.0"
  do
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/$soft* \
        aarch64/generic/{software,modules/all}/$soft* 
  ```
  **log** 
```
-rw-rw-r--. 1 cvmfs cvmfs 1382 Jul 22 13:59 aarch64/generic/modules/all/at-spi2-core/2.46.0-GCCcore-12.2.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 1382 Jul 22 13:53 x86_64/amd/zen2/modules/all/at-spi2-core/2.46.0-GCCcore-12.2.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 1381 Jul 22 13:58 x86_64/generic/modules/all/at-spi2-core/2.46.0-GCCcore-12.2.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 1389 Jul 22 13:57 x86_64/intel/broadwell/modules/all/at-spi2-core/2.46.0-GCCcore-12.2.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 1394 Jul 22 13:51 x86_64/intel/skylake_avx512/modules/all/at-spi2-core/2.46.0-GCCcore-12.2.0.lua

aarch64/generic/software/at-spi2-core/2.46.0-GCCcore-12.2.0:
total 28
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:59 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:59 etc
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 22 13:59 include
dr-xr-xr-x. 7 cvmfs cvmfs 4096 Jul 22 13:59 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 22 13:59 lib64 -> lib
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 22 13:59 libexec
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jul 22 13:59 share

x86_64/amd/zen2/software/at-spi2-core/2.46.0-GCCcore-12.2.0:
total 28
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:54 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:53 etc
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 22 13:53 include
dr-xr-xr-x. 7 cvmfs cvmfs 4096 Jul 22 13:53 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 22 13:53 lib64 -> lib
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 22 13:53 libexec
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jul 22 13:53 share

x86_64/generic/software/at-spi2-core/2.46.0-GCCcore-12.2.0:
total 28
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:58 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:58 etc
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 22 13:58 include
dr-xr-xr-x. 7 cvmfs cvmfs 4096 Jul 22 13:58 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 22 13:58 lib64 -> lib
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 22 13:58 libexec
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jul 22 13:58 share

x86_64/intel/broadwell/software/at-spi2-core/2.46.0-GCCcore-12.2.0:
total 28
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:57 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:57 etc
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 22 13:57 include
dr-xr-xr-x. 7 cvmfs cvmfs 4096 Jul 22 13:57 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 22 13:57 lib64 -> lib
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 22 13:57 libexec
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jul 22 13:57 share

x86_64/intel/skylake_avx512/software/at-spi2-core/2.46.0-GCCcore-12.2.0:
total 28
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:51 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:51 etc
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 22 13:51 include
dr-xr-xr-x. 7 cvmfs cvmfs 4096 Jul 22 13:51 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 22 13:51 lib64 -> lib
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 22 13:51 libexec
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jul 22 13:51 share




-rw-rw-r--. 1 cvmfs cvmfs 1385 Jul 22 14:00 aarch64/generic/modules/all/at-spi2-core/2.49.91-GCCcore-12.3.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 1385 Jul 22 13:54 x86_64/amd/zen2/modules/all/at-spi2-core/2.49.91-GCCcore-12.3.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 1384 Jul 22 13:58 x86_64/generic/modules/all/at-spi2-core/2.49.91-GCCcore-12.3.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 1392 Jul 22 13:58 x86_64/intel/broadwell/modules/all/at-spi2-core/2.49.91-GCCcore-12.3.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 1397 Jul 22 13:51 x86_64/intel/skylake_avx512/modules/all/at-spi2-core/2.49.91-GCCcore-12.3.0.lua

aarch64/generic/software/at-spi2-core/2.49.91-GCCcore-12.3.0:
total 28
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 14:00 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 14:00 etc
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 22 14:00 include
dr-xr-xr-x. 7 cvmfs cvmfs 4096 Jul 22 14:00 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 22 14:00 lib64 -> lib
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 22 14:00 libexec
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jul 22 14:00 share

x86_64/amd/zen2/software/at-spi2-core/2.49.91-GCCcore-12.3.0:
total 28
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:54 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:54 etc
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 22 13:54 include
dr-xr-xr-x. 7 cvmfs cvmfs 4096 Jul 22 13:54 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 22 13:54 lib64 -> lib
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 22 13:54 libexec
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jul 22 13:54 share

x86_64/generic/software/at-spi2-core/2.49.91-GCCcore-12.3.0:
total 28
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:58 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:58 etc
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 22 13:58 include
dr-xr-xr-x. 7 cvmfs cvmfs 4096 Jul 22 13:58 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 22 13:58 lib64 -> lib
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 22 13:58 libexec
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jul 22 13:58 share

x86_64/intel/broadwell/software/at-spi2-core/2.49.91-GCCcore-12.3.0:
total 28
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:58 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:58 etc
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 22 13:58 include
dr-xr-xr-x. 7 cvmfs cvmfs 4096 Jul 22 13:58 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 22 13:58 lib64 -> lib
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 22 13:58 libexec
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jul 22 13:58 share

x86_64/intel/skylake_avx512/software/at-spi2-core/2.49.91-GCCcore-12.3.0:
total 28
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:51 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:51 etc
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 22 13:51 include
dr-xr-xr-x. 7 cvmfs cvmfs 4096 Jul 22 13:51 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 22 13:51 lib64 -> lib
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 22 13:51 libexec
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jul 22 13:51 share




-rw-rw-r--. 1 cvmfs cvmfs 2285 Jul 22 13:52 aarch64/generic/modules/all/GObject-Introspection/1.74.0-GCCcore-12.2.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 2285 Jul 22 13:48 x86_64/amd/zen2/modules/all/GObject-Introspection/1.74.0-GCCcore-12.2.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 2284 Jul 22 13:50 x86_64/generic/modules/all/GObject-Introspection/1.74.0-GCCcore-12.2.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 2292 Jul 22 13:49 x86_64/intel/broadwell/modules/all/GObject-Introspection/1.74.0-GCCcore-12.2.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 2297 Jul 22 13:46 x86_64/intel/skylake_avx512/modules/all/GObject-Introspection/1.74.0-GCCcore-12.2.0.lua

aarch64/generic/software/GObject-Introspection/1.74.0-GCCcore-12.2.0:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 22 13:52 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:53 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:52 include
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 22 13:52 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 22 13:52 lib64 -> lib
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jul 22 13:52 share

x86_64/amd/zen2/software/GObject-Introspection/1.74.0-GCCcore-12.2.0:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 22 13:48 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:48 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:48 include
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 22 13:48 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 22 13:48 lib64 -> lib
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jul 22 13:48 share

x86_64/generic/software/GObject-Introspection/1.74.0-GCCcore-12.2.0:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 22 13:50 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:50 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:50 include
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 22 13:50 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 22 13:50 lib64 -> lib
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jul 22 13:50 share

x86_64/intel/broadwell/software/GObject-Introspection/1.74.0-GCCcore-12.2.0:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 22 13:49 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:49 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:49 include
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 22 13:49 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 22 13:49 lib64 -> lib
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jul 22 13:49 share

x86_64/intel/skylake_avx512/software/GObject-Introspection/1.74.0-GCCcore-12.2.0:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 22 13:46 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:46 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:46 include
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 22 13:46 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 22 13:46 lib64 -> lib
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jul 22 13:46 share




-rw-rw-r--. 1 cvmfs cvmfs 2285 Jul 22 13:55 aarch64/generic/modules/all/GObject-Introspection/1.76.1-GCCcore-12.3.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 2285 Jul 22 13:51 x86_64/amd/zen2/modules/all/GObject-Introspection/1.76.1-GCCcore-12.3.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 2284 Jul 22 13:53 x86_64/generic/modules/all/GObject-Introspection/1.76.1-GCCcore-12.3.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 2292 Jul 22 13:52 x86_64/intel/broadwell/modules/all/GObject-Introspection/1.76.1-GCCcore-12.3.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 2297 Jul 22 13:48 x86_64/intel/skylake_avx512/modules/all/GObject-Introspection/1.76.1-GCCcore-12.3.0.lua

aarch64/generic/software/GObject-Introspection/1.76.1-GCCcore-12.3.0:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 22 13:55 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:55 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:55 include
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 22 13:55 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 22 13:55 lib64 -> lib
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jul 22 13:55 share

x86_64/amd/zen2/software/GObject-Introspection/1.76.1-GCCcore-12.3.0:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 22 13:50 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:51 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:50 include
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 22 13:50 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 22 13:50 lib64 -> lib
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jul 22 13:50 share

x86_64/generic/software/GObject-Introspection/1.76.1-GCCcore-12.3.0:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 22 13:53 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:53 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:53 include
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 22 13:53 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 22 13:53 lib64 -> lib
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jul 22 13:53 share

x86_64/intel/broadwell/software/GObject-Introspection/1.76.1-GCCcore-12.3.0:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 22 13:52 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:52 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:52 include
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 22 13:52 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 22 13:52 lib64 -> lib
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jul 22 13:52 share

x86_64/intel/skylake_avx512/software/GObject-Introspection/1.76.1-GCCcore-12.3.0:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 22 13:48 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:48 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:48 include
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 22 13:48 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 22 13:48 lib64 -> lib
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jul 22 13:48 share




-rw-rw-r--. 1 cvmfs cvmfs 2285 Jul 22 13:59 aarch64/generic/modules/all/GObject-Introspection/1.78.1-GCCcore-13.2.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 2285 Jul 22 13:53 x86_64/amd/zen2/modules/all/GObject-Introspection/1.78.1-GCCcore-13.2.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 2284 Jul 22 13:57 x86_64/generic/modules/all/GObject-Introspection/1.78.1-GCCcore-13.2.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 2292 Jul 22 13:56 x86_64/intel/broadwell/modules/all/GObject-Introspection/1.78.1-GCCcore-13.2.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 2297 Jul 22 13:50 x86_64/intel/skylake_avx512/modules/all/GObject-Introspection/1.78.1-GCCcore-13.2.0.lua

aarch64/generic/software/GObject-Introspection/1.78.1-GCCcore-13.2.0:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 22 13:59 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:59 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:59 include
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 22 13:59 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 22 13:59 lib64 -> lib
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jul 22 13:59 share

x86_64/amd/zen2/software/GObject-Introspection/1.78.1-GCCcore-13.2.0:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 22 13:53 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:53 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:53 include
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 22 13:53 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 22 13:53 lib64 -> lib
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jul 22 13:53 share

x86_64/generic/software/GObject-Introspection/1.78.1-GCCcore-13.2.0:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 22 13:57 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:57 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:57 include
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 22 13:57 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 22 13:57 lib64 -> lib
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jul 22 13:57 share

x86_64/intel/broadwell/software/GObject-Introspection/1.78.1-GCCcore-13.2.0:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 22 13:56 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:56 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:56 include
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 22 13:56 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 22 13:56 lib64 -> lib
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jul 22 13:56 share

x86_64/intel/skylake_avx512/software/GObject-Introspection/1.78.1-GCCcore-13.2.0:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jul 22 13:50 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:50 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 22 13:50 include
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jul 22 13:50 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 22 13:50 lib64 -> lib
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jul 22 13:50 share

```
</details>

**Review by justadejavu — APPROVED** [review]
Okay

**Pull request merged**
