### PR TITLE
{2023.06}[foss/2023a] R-bundle-CRAN 2023.12

### PR DESCRIPTION
**Pull request by trz42**
Attempt to add `R-bundle-CRAN/2023.12` to `software.eessi.io/2023.06`. See also https://github.com/EESSI/software-layer/pull/428

License:
- ca. 1100 R packages $\rightarrow$ need automation to determine individual licenses

Missing installations:
```
18 out of 148 required modules missing:

* NLopt/2.7.1-GCCcore-12.3.0 (NLopt-2.7.1-GCCcore-12.3.0.eb)
* nettle/3.9.1-GCCcore-12.3.0 (nettle-3.9.1-GCCcore-12.3.0.eb)
* libogg/1.3.5-GCCcore-12.3.0 (libogg-1.3.5-GCCcore-12.3.0.eb)
* FLAC/1.4.2-GCCcore-12.3.0 (FLAC-1.4.2-GCCcore-12.3.0.eb)
* libvorbis/1.3.7-GCCcore-12.3.0 (libvorbis-1.3.7-GCCcore-12.3.0.eb)
* Xvfb/21.1.8-GCCcore-12.3.0 (Xvfb-21.1.8-GCCcore-12.3.0.eb)
* libopus/1.4-GCCcore-12.3.0 (libopus-1.4-GCCcore-12.3.0.eb)
* libsndfile/1.2.2-GCCcore-12.3.0 (libsndfile-1.2.2-GCCcore-12.3.0.eb)
* ATK/2.38.0-GCCcore-12.3.0 (ATK-2.38.0-GCCcore-12.3.0.eb)
* PostgreSQL/16.1-GCCcore-12.3.0 (PostgreSQL-16.1-GCCcore-12.3.0.eb)
* Gdk-Pixbuf/2.42.10-GCCcore-12.3.0 (Gdk-Pixbuf-2.42.10-GCCcore-12.3.0.eb)
* at-spi2-atk/2.38.0-GCCcore-12.3.0 (at-spi2-atk-2.38.0-GCCcore-12.3.0.eb)
* libepoxy/1.5.10-GCCcore-12.3.0 (libepoxy-1.5.10-GCCcore-12.3.0.eb)
* Wayland/1.22.0-GCCcore-12.3.0 (Wayland-1.22.0-GCCcore-12.3.0.eb)
* GTK3/3.24.37-GCCcore-12.3.0 (GTK3-3.24.37-GCCcore-12.3.0.eb)
* Ghostscript/10.01.2-GCCcore-12.3.0 (Ghostscript-10.01.2-GCCcore-12.3.0.eb)
* ImageMagick/7.1.1-15-GCCcore-12.3.0 (ImageMagick-7.1.1-15-GCCcore-12.3.0.eb)
* R-bundle-CRAN/2023.12-foss-2023a (R-bundle-CRAN-2023.12-foss-2023a.eb)
```

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/generic
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Fram repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb10 arch:aarch64/generic

**Comment by trz42** [comment]
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb11 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
Failed with `deb11` container

bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb10 arch:aarch64/generic

**Comment by trz42** [comment]
Repeat failed build (error was: could not write to some directory)

bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake

**Comment by trz42** [comment]
Repeat failed builds

bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake

**Comment by trz42** [comment]
Checklist before starting deployment (setting `bot:deploy` label): 

- [x]  Check if the _SPDX license identifier_ is provided
  - too many extensions/packages to determine licenses manually
- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
  - eventually all succeeded, but we had to try several times and also download some tarballs manually because some had failed to download entirely or were not downloaded completely 
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
  - update after building only concerns pulling in non-overlapping changes by #328
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each staged tarball was a PR for approval/rejection opened
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/R-bundle-CRAN/2023.12* \
        aarch64/generic/{software,modules/all}/R-bundle-CRAN/2023.12* | head -n 20
  ```
  **log**
```
-rw-r--r--    1 cvmfs cvmfs 69491 Apr 16 06:00 aarch64/generic/modules/all/R-bundle-CRAN/2023.12-foss-2023a.lua
-rw-rw-r--    1 cvmfs cvmfs 69491 Apr 16 07:25 x86_64/amd/zen2/modules/all/R-bundle-CRAN/2023.12-foss-2023a.lua
-rw-rw-r--    1 cvmfs cvmfs 69489 Apr 16 07:06 x86_64/generic/modules/all/R-bundle-CRAN/2023.12-foss-2023a.lua
-rw-rw-r--    1 cvmfs cvmfs 69505 Apr 15 21:40 x86_64/intel/broadwell/modules/all/R-bundle-CRAN/2023.12-foss-2023a.lua
-rw-rw-r--    1 cvmfs cvmfs 69515 Apr 16 10:25 x86_64/intel/skylake_avx512/modules/all/R-bundle-CRAN/2023.12-foss-2023a.lua

aarch64/generic/software/R-bundle-CRAN/2023.12-foss-2023a:
total 4973
dr-xr-xr-x  7 cvmfs cvmfs 4096 Apr 15 20:51 abc
dr-xr-xr-x  6 cvmfs cvmfs 4096 Apr 15 20:51 abc.data
dr-xr-xr-x  6 cvmfs cvmfs 4096 Apr 16 00:27 abe
dr-xr-xr-x  6 cvmfs cvmfs 4096 Apr 15 15:58 abind
dr-xr-xr-x  7 cvmfs cvmfs 4096 Apr 15 18:18 acepack
dr-xr-xr-x  7 cvmfs cvmfs 4096 Apr 15 20:46 adabag
dr-xr-xr-x 10 cvmfs cvmfs 4096 Apr 15 16:23 ade4
dr-xr-xr-x  6 cvmfs cvmfs 4096 Apr 15 16:18 ADGofTest
dr-xr-xr-x  7 cvmfs cvmfs 4096 Apr 16 02:36 admisc
dr-xr-xr-x  6 cvmfs cvmfs 4096 Apr 15 23:56 aggregation
dr-xr-xr-x  8 cvmfs cvmfs 4096 Apr 16 01:20 AICcmodavg
dr-xr-xr-x  8 cvmfs cvmfs 4096 Apr 15 17:56 akima
... in total 5545 lines 
```
</details>

**Review by poksumdo — APPROVED** [review]
Great progress!

**Pull request merged**
