### PR TITLE
{2023.06}[foss/2022a] add oneTBB

### PR DESCRIPTION
**Pull request by trz42**
Will add the following packages:

* tbb/2021.5.0-GCCcore-11.3.0 (tbb-2021.5.0-GCCcore-11.3.0.eb)

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:AWS arch:x86_64/generic repo:nessi-2023.06-swl-deb11
bot: build inst:AWS arch:x86_64/amd/zen2 repo:nessi-2023.06-swl-deb11
bot: build inst:eX3 arch:aarch64/generic repo:nessi-2023.06-swl-deb11
bot: build inst:Fram arch:x86_64/intel/broadwell repo:nessi-2023.06-swl-deb10
bot: build inst:AWS arch:x86_64/intel/cascadelake repo:nessi-2023.06-swl-deb11
bot: build inst:AWS arch:x86_64/intel/skylake repo:nessi-2023.06-swl-deb11

**Comment by trz42** [comment]
Checklist for building: 

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-intel-cascadelake`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/tbb/* \
        aarch64/generic/{software,modules/all}/tbb/*
  ```
  **log**
```
-rw-r--r-- 1 cvmfs cvmfs 1470 Oct  7 19:40 aarch64/generic/modules/all/tbb/2021.5.0-GCCcore-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1470 Oct  7 19:49 x86_64/amd/zen2/modules/all/tbb/2021.5.0-GCCcore-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1469 Oct  7 19:47 x86_64/generic/modules/all/tbb/2021.5.0-GCCcore-11.3.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 1477 Oct  7 19:39 x86_64/intel/broadwell/modules/all/tbb/2021.5.0-GCCcore-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1479 Oct  7 19:47 x86_64/intel/cascadelake/modules/all/tbb/2021.5.0-GCCcore-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1482 Oct  7 19:46 x86_64/intel/skylake_avx512/modules/all/tbb/2021.5.0-GCCcore-11.3.0.lua

aarch64/generic/software/tbb/2021.5.0-GCCcore-11.3.0:
total 19
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  7 19:40 easybuild
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  7 19:40 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  7 19:40 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  7 19:40 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  7 19:40 share

x86_64/amd/zen2/software/tbb/2021.5.0-GCCcore-11.3.0:
total 19
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  7 19:49 easybuild
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  7 19:49 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  7 19:49 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  7 19:49 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  7 19:49 share

x86_64/generic/software/tbb/2021.5.0-GCCcore-11.3.0:
total 19
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  7 19:47 easybuild
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  7 19:47 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  7 19:47 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  7 19:47 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  7 19:47 share

x86_64/intel/broadwell/software/tbb/2021.5.0-GCCcore-11.3.0:
total 19
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  7 19:39 easybuild
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  7 19:39 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  7 19:39 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  7 19:39 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  7 19:39 share

x86_64/intel/cascadelake/software/tbb/2021.5.0-GCCcore-11.3.0:
total 19
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  7 19:47 easybuild
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  7 19:47 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  7 19:47 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  7 19:47 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  7 19:47 share

x86_64/intel/skylake_avx512/software/tbb/2021.5.0-GCCcore-11.3.0:
total 19
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  7 19:46 easybuild
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  7 19:46 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  7 19:46 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  7 19:46 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  7 19:46 share 
```
</details>

**Review by poksumdo — APPROVED** [review]
Small but ok.

**Pull request merged**
