### PR TITLE
{2023.06}[gompi/2023a] BLAST+ V2.14.1

### PR DESCRIPTION
**Pull request by TopRichard**
BLAST+ is found on SAGA 
Lic --> check NCBI licenses
```
2 out of 38 required modules missing:

* LMDB/0.9.31-GCCcore-12.3.0 (LMDB-0.9.31-GCCcore-12.3.0.eb)
* BLAST+/2.14.1-gompi-2023a (BLAST+-2.14.1-gompi-2023a.eb)
```

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
Failure:
```
/bin/bash: line 3: cpio: command not found
/bin/bash: line 3: cpio: command not found
make[1]: *** [Makefile:47: install-toolkit] Error 127
make[1]: Leaving directory '/tmp/nessibot/easybuild/build/BLAST/2.14.1/gompi-2023a/ncbi-blast-2.14.1+-src/c++'
make: *** [Makefile:63: install] Error 2

```

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
Checklist before starting deployment (setting bot:deploy label):

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by TopRichard** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x]  Check if the _SPDX license identifier_ is provided 
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI for the ingested tarballs have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)

<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; 
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/BLAST+/2.14.1-gompi-2023a* \
        aarch64/generic/{software,modules/all}/BLAST+/2.14.1-gompi-2023a*
  ```
  **log**
```
-rw-rw-r--. 1 cvmfs cvmfs 1891 Jun 11 13:31 aarch64/generic/modules/all/BLAST+/2.14.1-gompi-2023a.lua
-rw-rw-r--. 1 cvmfs cvmfs 1891 Jun 11 13:31 x86_64/amd/zen2/modules/all/BLAST+/2.14.1-gompi-2023a.lua
-rw-rw-r--. 1 cvmfs cvmfs 1890 Jun 11 13:27 x86_64/generic/modules/all/BLAST+/2.14.1-gompi-2023a.lua
-rw-rw-r--. 1 cvmfs cvmfs 1898 Jun 11 14:47 x86_64/intel/broadwell/modules/all/BLAST+/2.14.1-gompi-2023a.lua
-rw-rw-r--. 1 cvmfs cvmfs 1903 Jun 11 14:20 x86_64/intel/skylake_avx512/modules/all/BLAST+/2.14.1-gompi-2023a.lua

aarch64/generic/software/BLAST+/2.14.1-gompi-2023a:
total 19
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 11 13:31 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 11 13:31 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 11 13:31 include
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 11 13:31 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 11 13:31 lib64 -> lib

x86_64/amd/zen2/software/BLAST+/2.14.1-gompi-2023a:
total 19
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 11 13:30 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 11 13:31 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 11 13:30 include
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 11 13:30 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 11 13:30 lib64 -> lib

x86_64/generic/software/BLAST+/2.14.1-gompi-2023a:
total 19
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 11 13:27 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 11 13:27 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 11 13:27 include
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 11 13:27 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 11 13:27 lib64 -> lib

x86_64/intel/broadwell/software/BLAST+/2.14.1-gompi-2023a:
total 19
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 11 14:47 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 11 14:47 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 11 14:46 include
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 11 14:47 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 11 14:47 lib64 -> lib

x86_64/intel/skylake_avx512/software/BLAST+/2.14.1-gompi-2023a:
total 19
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 11 14:20 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 11 14:20 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 11 14:20 include
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 11 14:20 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 11 14:20 lib64 -> lib
```
</details>

**Review by justadejavu — APPROVED** [review]
lgtm

**Pull request merged**
