### PR TITLE
{2023.06}[foss/2022a] GROMACS V2023.1

### PR DESCRIPTION
**Pull request by TopRichard**
Trying to add GROMACS/2023.1-foss/2022a to NESSI stack.

All modules that will be installed:
```
* scikit-build/0.15.0-GCCcore-11.3.0 (scikit-build-0.15.0-GCCcore-11.3.0.eb)
* networkx/2.8.4-foss-2022a (networkx-2.8.4-foss-2022a.eb)
* GROMACS/2023.1-foss-2022a (GROMACS-2023.1-foss-2022a.eb)
```

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb10 arch:x86_64/intel/broadwell

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/cascadelake 
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake 
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi-2023.06-swl-deb10 arch:x86_64/intel/skylake

**Comment by TopRichard** [comment]
bot: build inst:eX3 repo:nessi-2023.06-swl-deb10 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:eX3 repo:nessi-2023.06-swl-deb10 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:eX3 repo:nessi-2023.06-swl-deb10 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:zen2

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi-2023.06-swl-deb10 arch:zen2

**Comment by TopRichard** [comment]
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/cascadelake 
bot: build inst:AWS repo:nessi-2023.06-swl-deb10 arch:x86_64/intel/skylake 
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb10 arch:x86_64/intel/broadwell
bot: build inst:eX3 repo:nessi-2023.06-swl-deb10 arch:aarch64/generic

**Comment by TopRichard** [comment]
Checklist for building `GROMACS V2023.1 `: 

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by TopRichard** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-intel-cascadelake`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [] encountered issues in the ingestion, likely related to troubles interacting with GitHub via PyGithub … 
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; 
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/GROMACS/2023.1-foss-2022a* \
        aarch64/generic/{software,modules/all}/GROMACS/2023.1-foss-2022a*

-rw-r--r--. 1 cvmfs cvmfs 2335 Oct  8 20:20 aarch64/generic/modules/all/GROMACS/2023.1-foss-2022a.lua
-rw-r--r--. 1 cvmfs cvmfs 2335 Oct  8 12:43 x86_64/amd/zen2/modules/all/GROMACS/2023.1-foss-2022a.lua
-rw-r--r--. 1 cvmfs cvmfs 2334 Oct  8 18:54 x86_64/generic/modules/all/GROMACS/2023.1-foss-2022a.lua
-rw-rw-r--. 1 cvmfs cvmfs 2342 Oct  8 18:56 x86_64/intel/broadwell/modules/all/GROMACS/2023.1-foss-2022a.lua
-rw-r--r--. 1 cvmfs cvmfs 2344 Oct  8 18:55 x86_64/intel/cascadelake/modules/all/GROMACS/2023.1-foss-2022a.lua
-rw-r--r--. 1 cvmfs cvmfs 2347 Oct  8 19:02 x86_64/intel/skylake_avx512/modules/all/GROMACS/2023.1-foss-2022a.lua

aarch64/generic/software/GROMACS/2023.1-foss-2022a:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct  8 20:17 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct  8 20:20 easybuild
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Oct  8 18:28 include
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Oct  8 20:17 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct  8 20:19 lib64 -> lib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Oct  8 18:28 share

x86_64/amd/zen2/software/GROMACS/2023.1-foss-2022a:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct  8 12:42 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct  8 12:44 easybuild
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Oct  8 11:39 include
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Oct  8 12:42 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct  8 12:43 lib64 -> lib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Oct  8 11:39 share

x86_64/generic/software/GROMACS/2023.1-foss-2022a:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct  8 18:53 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct  8 18:55 easybuild
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Oct  8 18:20 include
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Oct  8 18:53 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct  8 18:54 lib64 -> lib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Oct  8 18:20 share

x86_64/intel/broadwell/software/GROMACS/2023.1-foss-2022a:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct  8 18:54 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct  8 18:56 easybuild
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Oct  8 18:11 include
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Oct  8 18:54 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct  8 18:55 lib64 -> lib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Oct  8 18:11 share

x86_64/intel/cascadelake/software/GROMACS/2023.1-foss-2022a:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct  8 18:54 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct  8 18:55 easybuild
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Oct  8 18:19 include
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Oct  8 18:55 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct  8 18:55 lib64 -> lib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Oct  8 18:19 share

x86_64/intel/skylake_avx512/software/GROMACS/2023.1-foss-2022a:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct  8 19:01 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct  8 19:02 easybuild
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Oct  8 18:16 include
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Oct  8 19:01 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct  8 19:02 lib64 -> lib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Oct  8 18:16 share
```
</details>

**Review by justadejavu — APPROVED** [review]

**Pull request merged**
