### PR TITLE
{2023.06}[foss/2021a] libGLU V9.0.1

### PR DESCRIPTION
**Pull request by TopRichard**
Trying to build Qt5 dependencies.

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi.no-2023.06-software arch:x86_64/generic 
bot: build inst:AWS repo:nessi.no-2023.06-software arch:x86_64/intel/cascadelake 
bot: build inst:AWS repo:nessi.no-2023.06-software arch:x86_64/intel/skylake 
bot: build inst:Fram-NESSI repo:nessi.no-2023.06-software arch:x86_64/intel/broadwell
bot: build inst:eX3 repo:nessi.no-2023.06-software arch:zen2
bot: build inst:eX3 repo:nessi.no-2023.06-software arch:aarch64/generic

**Comment by TopRichard** [comment]
Failed on AWS builds with :`Unexpected error occurred when trying to download https://download.sourceforge.net/libpng/libpng-1.6.37.tar.gz `

**Comment by TopRichard** [comment]
bot: build inst:eX3 repo:nessi.no-2023.06-software arch:zen2

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi.no-2023.06-software arch:x86_64/intel/cascadelake

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi.no-2023.06-software arch:x86_64/intel/skylake 
bot: build inst:eX3 repo:nessi.no-2023.06-software arch:zen2
bot: build inst:eX3 repo:nessi.no-2023.06-software arch:aarch64/generic

**Comment by TopRichard** [comment]
Checklist for building: 

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by TopRichard** [comment]
@trz42 bug during ingestion: 
```
processing tarball (state=new): tarballs/2023.06/software/linux/aarch64/generic/1690465978/eessi-2023.06-software-linux-aarch64-generic-1690465978.tar.gz                                                         
    Found new tarball tarballs/2023.06/software/linux/aarch64/generic/1690465978/eessi-2023.06-software-linux-aarch64-generic-1690465978.tar.gz, downloading it...                                                
Traceback (most recent call last):
  File "/home/rocky/filesystem-layer/scripts/automated_ingestion/./automated_ingestion.py", line 228, in <module>                                                                                                 
    main()
  File "/home/rocky/tests/vtboto3/lib64/python3.9/site-packages/pid/decorator.py", line 14, in decorator
    return func(*func_args, **func_kwargs)
  File "/home/rocky/filesystem-layer/scripts/automated_ingestion/./automated_ingestion.py", line 222, in main                                                                                                     
    tar.run_handler()
  File "/home/rocky/filesystem-layer/scripts/automated_ingestion/eessitarball.py", line 305, in run_handler                                                                                                       
    handler()
  File "/home/rocky/filesystem-layer/scripts/automated_ingestion/eessitarball.py", line 507, in handle_new_tarball                                                                                                
    self.download()
  File "/home/rocky/filesystem-layer/scripts/automated_ingestion/eessitarball.py", line 208, in download
    if force or tarball_force or not os.path.exists(self.local_tarball_path):
  File "/usr/lib64/python3.9/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Review by justadejavu — APPROVED** [review]

**Comment by TopRichard** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-intel-cascadelake`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] encountered issues in the ingestion, likely related to troubles interacting with GitHub via PyGithub … 
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; 
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/libGLU/9.0.1-GCCcore-10.3.0* \
        aarch64/generic/{software,modules/all}/libGLU/9.0.1-GCCcore-10.3.0*
  ```

```
-rw-r--r--. 1 cvmfs cvmfs 1268 Jul 27 13:51 aarch64/generic/modules/all/libGLU/9.0.1-GCCcore-10.3.0.lua
-rw-r--r--. 1 cvmfs cvmfs 1268 Jul 27 13:14 x86_64/amd/zen2/modules/all/libGLU/9.0.1-GCCcore-10.3.0.lua
-rw-r--r--. 1 cvmfs cvmfs 1267 Jul  7 12:07 x86_64/generic/modules/all/libGLU/9.0.1-GCCcore-10.3.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 1275 Jul  7 20:19 x86_64/intel/broadwell/modules/all/libGLU/9.0.1-GCCcore-10.3.0.lua
-rw-r--r--. 1 cvmfs cvmfs 1277 Jul  7 14:26 x86_64/intel/cascadelake/modules/all/libGLU/9.0.1-GCCcore-10.3.0.lua
-rw-r--r--. 1 cvmfs cvmfs 1280 Jul 27 13:41 x86_64/intel/skylake_avx512/modules/all/libGLU/9.0.1-GCCcore-10.3.0.lua

aarch64/generic/software/libGLU/9.0.1-GCCcore-10.3.0:
total 14
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 27 13:51 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 27 13:50 include
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 27 13:50 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 27 13:50 lib64 -> lib

x86_64/amd/zen2/software/libGLU/9.0.1-GCCcore-10.3.0:
total 14
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 27 13:14 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 27 13:14 include
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 27 13:14 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 27 13:14 lib64 -> lib

x86_64/generic/software/libGLU/9.0.1-GCCcore-10.3.0:
total 14
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul  7 12:07 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul  7 12:07 include
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul  7 12:07 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul  7 12:07 lib64 -> lib

x86_64/intel/broadwell/software/libGLU/9.0.1-GCCcore-10.3.0:
total 14
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul  7 20:19 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul  7 20:19 include
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul  7 20:19 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul  7 20:19 lib64 -> lib

x86_64/intel/cascadelake/software/libGLU/9.0.1-GCCcore-10.3.0:
total 14
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul  7 14:26 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul  7 14:25 include
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul  7 14:25 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul  7 14:25 lib64 -> lib

x86_64/intel/skylake_avx512/software/libGLU/9.0.1-GCCcore-10.3.0:
total 14
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 27 13:41 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 27 13:41 include
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 27 13:41 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 27 13:41 lib64 -> lib

```
</details>

**Pull request merged**
