### PR TITLE
{2023.06}[system] foss/2023a

### PR DESCRIPTION
**Pull request by trz42**
Adds `foss/2023a` toolchain. This is one of the major toolchains being populated in `software.eessi.io`.

Modules to be installed:

```
32 out of 34 required modules missing:

* GCCcore/12.3.0 (GCCcore-12.3.0.eb)
* GCC/12.3.0 (GCC-12.3.0.eb)
* pkgconf/1.9.5-GCCcore-12.3.0 (pkgconf-1.9.5-GCCcore-12.3.0.eb)
* FFTW/3.3.10-GCC-12.3.0 (FFTW-3.3.10-GCC-12.3.0.eb)
* Perl/5.36.1-GCCcore-12.3.0 (Perl-5.36.1-GCCcore-12.3.0.eb)
* numactl/2.0.16-GCCcore-12.3.0 (numactl-2.0.16-GCCcore-12.3.0.eb)
* UnZip/6.0-GCCcore-12.3.0 (UnZip-6.0-GCCcore-12.3.0.eb)
* UCX/1.14.1-GCCcore-12.3.0 (UCX-1.14.1-GCCcore-12.3.0.eb)
* libxml2/2.11.4-GCCcore-12.3.0 (libxml2-2.11.4-GCCcore-12.3.0.eb)
* cURL/8.0.1-GCCcore-12.3.0 (cURL-8.0.1-GCCcore-12.3.0.eb)
* libevent/2.1.12-GCCcore-12.3.0 (libevent-2.1.12-GCCcore-12.3.0.eb)
* libarchive/3.6.2-GCCcore-12.3.0 (libarchive-3.6.2-GCCcore-12.3.0.eb)
* CMake/3.26.3-GCCcore-12.3.0 (CMake-3.26.3-GCCcore-12.3.0.eb)
* libfabric/1.18.0-GCCcore-12.3.0 (libfabric-1.18.0-GCCcore-12.3.0.eb)
* libffi/3.4.4-GCCcore-12.3.0 (libffi-3.4.4-GCCcore-12.3.0.eb)
* make/4.4.1-GCCcore-12.3.0 (make-4.4.1-GCCcore-12.3.0.eb)
* Tcl/8.6.13-GCCcore-12.3.0 (Tcl-8.6.13-GCCcore-12.3.0.eb)
* SQLite/3.42.0-GCCcore-12.3.0 (SQLite-3.42.0-GCCcore-12.3.0.eb)
* Python/3.11.3-GCCcore-12.3.0 (Python-3.11.3-GCCcore-12.3.0.eb)
* BLIS/0.9.0-GCC-12.3.0 (BLIS-0.9.0-GCC-12.3.0.eb)
* OpenBLAS/0.3.23-GCC-12.3.0 (OpenBLAS-0.3.23-GCC-12.3.0.eb)
* FlexiBLAS/3.3.1-GCC-12.3.0 (FlexiBLAS-3.3.1-GCC-12.3.0.eb)
* xorg-macros/1.20.0-GCCcore-12.3.0 (xorg-macros-1.20.0-GCCcore-12.3.0.eb)
* libpciaccess/0.17-GCCcore-12.3.0 (libpciaccess-0.17-GCCcore-12.3.0.eb)
* hwloc/2.9.1-GCCcore-12.3.0 (hwloc-2.9.1-GCCcore-12.3.0.eb)
* PMIx/4.2.4-GCCcore-12.3.0 (PMIx-4.2.4-GCCcore-12.3.0.eb)
* UCC/1.2.0-GCCcore-12.3.0 (UCC-1.2.0-GCCcore-12.3.0.eb)
* OpenMPI/4.1.5-GCC-12.3.0 (OpenMPI-4.1.5-GCC-12.3.0.eb)
* gompi/2023a (gompi-2023a.eb)
* FFTW.MPI/3.3.10-gompi-2023a (FFTW.MPI-3.3.10-gompi-2023a.eb)
* ScaLAPACK/2.2.0-gompi-2023a-fb (ScaLAPACK-2.2.0-gompi-2023a-fb.eb)
* foss/2023a (foss-2023a.eb)
```

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/generic
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by trz42** [comment]
Try with `deb10` container

bot: build inst:eX3 repo:nessi-2023.06-swl-deb10 arch:aarch64/generic

**Comment by trz42** [comment]
Checklist before starting deployment: 

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
  - wasn't; lacked updates to CI which only clear warnings; so should have no affect on building; will re-run all CI before merging
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)
  - needed to use `deb10` container for arch `aarch64/generic` on `eX3`

**Comment by trz42** [comment]
Upload for `aarch64/generic` actually failed. Reconfigured `upload_policy` to once on `eX3`. Setting label again.

**Comment by trz42** [comment]
Needed to remove `aarch64/generic` from `jobs/2024.01/pr_257/uploaded.txt`.

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - ~`x86_64-intel-cascadelake`~
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/foss/2023a* \
        aarch64/generic/{software,modules/all}/foss/2023a*
  ```
  **log**
```
-rw-r--r-- 1 cvmfs cvmfs 1568 Jan 28 09:34 aarch64/generic/modules/all/foss/2023a.lua
-rw-r--r-- 1 cvmfs cvmfs 1568 Jan 28 01:57 x86_64/amd/zen2/modules/all/foss/2023a.lua
-rw-rw-r-- 1 cvmfs cvmfs 1567 Jan 28 02:17 x86_64/generic/modules/all/foss/2023a.lua
-rw-rw-r-- 1 cvmfs cvmfs 1575 Jan 28 03:53 x86_64/intel/broadwell/modules/all/foss/2023a.lua
-rw-rw-r-- 1 cvmfs cvmfs 1580 Jan 28 03:31 x86_64/intel/skylake_avx512/modules/all/foss/2023a.lua

aarch64/generic/software/foss/2023a:
total 5
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 28 09:34 easybuild

x86_64/amd/zen2/software/foss/2023a:
total 5
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 28 01:57 easybuild

x86_64/generic/software/foss/2023a:
total 5
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 28 02:17 easybuild

x86_64/intel/broadwell/software/foss/2023a:
total 5
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 28 03:53 easybuild

x86_64/intel/skylake_avx512/software/foss/2023a:
total 5
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 28 03:31 easybuild 
```
</details>

**Review by poksumdo — APPROVED** [review]
All ingested and CI green.

**Pull request merged**
