### PR TITLE
Adding ScaLAPACK/2.1.0 with gompi/2021a to NESSI/2023.04

### PR DESCRIPTION
**Pull request by TopRichard**
Adding ScaLAPACK/2.1.0 with gompi/2021a which has  FlexiBLAS as dependency + FFTW-3.3.9 with gompi/2021a  to NESSI/2023.04

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:AWS arch:x86_64/generic repo:nessi.no-2023.04
bot: build inst:AWS arch:x86_64/intel/cascadelake repo:nessi.no-2023.04
bot: build inst:AWS arch:x86_64/intel/skylake repo:nessi.no-2023.04
bot: build inst:Fram-NESSI arch:x86_64/intel/broadwell repo:nessi.no-2023.04
bot: build inst:eX3 arch:zen2 repo:nessi.no-2023.04
bot: build inst:eX3 arch:aarch64/generic repo:nessi.no-2023.04
- received bot command `build inst:AWS arch:x86_64/generic repo:nessi.no-2023.04` from `TopRichard` (expanded command format: `build instance:AWS architecture:x86_64/generic repository:nessi.no-2023.04`)
- received bot command `build inst:AWS arch:x86_64/intel/cascadelake repo:nessi.no-2023.04` from `TopRichard` (expanded command format: `build instance:AWS architecture:x86_64/intel/cascadelake repository:nessi.no-2023.04`)
- received bot command `build inst:AWS arch:x86_64/intel/skylake repo:nessi.no-2023.04` from `TopRichard` (expanded command format: `build instance:AWS architecture:x86_64/intel/skylake repository:nessi.no-2023.04`)
- received bot command `build inst:Fram-NESSI arch:x86_64/intel/broadwell repo:nessi.no-2023.04` from `TopRichard` (expanded command format: `build instance:Fram-NESSI architecture:x86_64/intel/broadwell repository:nessi.no-2023.04`)
- received bot command `build inst:eX3 arch:zen2 repo:nessi.no-2023.04` from `TopRichard` (expanded command format: `build instance:eX3 architecture:zen2 repository:nessi.no-2023.04`)
- received bot command `build inst:eX3 arch:aarch64/generic repo:nessi.no-2023.04` from `TopRichard` (expanded command format: `build instance:eX3 architecture:aarch64/generic repository:nessi.no-2023.04`)

**Comment by trz42** [comment]
Checklist for building: 
- [x] did the builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x] is the PR up-to-date with the target branch nessi.no-2023.04-dev in the repository (if not what are the differences)
- [x] are all requested changes sound (checking files changed on GitHub.com)
- [x] is/are the easyconfig/s being built included with the EB version used (if not why not)
- [x] were any changes needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

Note, `bot:deploy` should use the new upload script that stores tarballs under `{bucket}/tarballs` and metadata files under `{bucket}/new`.
- Seems we've got the paths wrong. For example, one tarball was uploaded to
  ```
  s3://nessi-2023.04-pre/2023.04/software/linux/x86_64/intel/cascadelake/1684937427/tarballs/eessi-2023.04-software-linux-x86_64-intel-cascadelake-1684937427.tar.gz
  ```
  while it should have been
  ```
  s3://nessi-2023.04-pre/2023.04/tarballs/software/linux/x86_64/intel/cascadelake/1684937427/eessi-2023.04-software-linux-x86_64-intel-cascadelake-1684937427.tar.gz
  ```
  Similarly, path for metadata file is wrong.

**Comment by trz42** [comment]
Checklist for deployment/ingestion
- notes
  - apparently, the build for `aarch64/generic` contains 20 files fewer all related to `fftw3q`

- [x] at least one tarball for each architecture has been uploaded
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512`
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] at least one tarball for each architecture has been staged
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512`
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] for each architecture **one and only one** tarball has been approved
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512`
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] for each architecture **one and only one** tarball was ingested
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512` 
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
  **command**
  ```
  ls -l /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/{ScaLAPACK,FFTW}/*
  ls -l /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/aarch64/generic/{software,modules/all}/{ScaLAPACK,FFTW}/*
  ```
  **log**
```
-rw-r--r--. 1 cvmfs cvmfs 1320 May 24 14:26 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/amd/zen2/modules/all/FFTW/3.3.9-gompi-2021a.lua
-rw-r--r--. 1 cvmfs cvmfs 1236 May 24 13:34 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/amd/zen2/modules/all/ScaLAPACK/2.1.0-gompi-2021a-fb.lua
-rw-r--r--. 1 cvmfs cvmfs 1319 May 24 14:27 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/generic/modules/all/FFTW/3.3.9-gompi-2021a.lua
-rw-r--r--. 1 cvmfs cvmfs 1235 May 24 13:39 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/generic/modules/all/ScaLAPACK/2.1.0-gompi-2021a-fb.lua
-rw-rw-r--. 1 cvmfs cvmfs 1327 May 24 14:50 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/broadwell/modules/all/FFTW/3.3.9-gompi-2021a.lua
-rw-rw-r--. 1 cvmfs cvmfs 1243 May 24 13:38 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/broadwell/modules/all/ScaLAPACK/2.1.0-gompi-2021a-fb.lua
-rw-r--r--. 1 cvmfs cvmfs 1329 May 24 14:09 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/cascadelake/modules/all/FFTW/3.3.9-gompi-2021a.lua
-rw-r--r--. 1 cvmfs cvmfs 1245 May 24 13:35 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/cascadelake/modules/all/ScaLAPACK/2.1.0-gompi-2021a-fb.lua
-rw-r--r--. 1 cvmfs cvmfs 1332 May 24 14:25 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/skylake_avx512/modules/all/FFTW/3.3.9-gompi-2021a.lua
-rw-r--r--. 1 cvmfs cvmfs 1248 May 24 13:36 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/skylake_avx512/modules/all/ScaLAPACK/2.1.0-gompi-2021a-fb.lua

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/amd/zen2/software/FFTW/3.3.9-gompi-2021a:
total 23
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 24 14:26 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 24 14:26 easybuild
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 24 14:26 include
drwxr-xr-x. 4 cvmfs cvmfs 4096 May 24 14:26 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 May 24 14:26 lib64 -> lib
drwxr-xr-x. 4 cvmfs cvmfs 4096 May 24 13:44 share

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/amd/zen2/software/ScaLAPACK/2.1.0-gompi-2021a-fb:
total 10
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 24 13:34 easybuild
drwxr-xr-x. 4 cvmfs cvmfs 4096 May 24 13:34 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 May 24 13:34 lib64 -> lib

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/generic/software/FFTW/3.3.9-gompi-2021a:
total 23
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 24 14:27 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 24 14:27 easybuild
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 24 14:27 include
drwxr-xr-x. 4 cvmfs cvmfs 4096 May 24 14:27 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 May 24 14:27 lib64 -> lib
drwxr-xr-x. 4 cvmfs cvmfs 4096 May 24 13:43 share

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/generic/software/ScaLAPACK/2.1.0-gompi-2021a-fb:
total 10
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 24 13:39 easybuild
drwxr-xr-x. 4 cvmfs cvmfs 4096 May 24 13:39 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 May 24 13:39 lib64 -> lib

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/broadwell/software/FFTW/3.3.9-gompi-2021a:
total 23
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 24 14:50 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 24 14:50 easybuild
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 24 14:50 include
drwxr-xr-x. 4 cvmfs cvmfs 4096 May 24 14:50 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 May 24 14:50 lib64 -> lib
drwxr-xr-x. 4 cvmfs cvmfs 4096 May 24 13:47 share

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/broadwell/software/ScaLAPACK/2.1.0-gompi-2021a-fb:
total 10
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 24 13:38 easybuild
drwxr-xr-x. 4 cvmfs cvmfs 4096 May 24 13:38 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 May 24 13:38 lib64 -> lib

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/cascadelake/software/FFTW/3.3.9-gompi-2021a:
total 23
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 24 14:09 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 24 14:09 easybuild
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 24 14:09 include
drwxr-xr-x. 4 cvmfs cvmfs 4096 May 24 14:09 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 May 24 14:09 lib64 -> lib
drwxr-xr-x. 4 cvmfs cvmfs 4096 May 24 13:40 share

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/cascadelake/software/ScaLAPACK/2.1.0-gompi-2021a-fb:
total 10
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 24 13:35 easybuild
drwxr-xr-x. 4 cvmfs cvmfs 4096 May 24 13:35 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 May 24 13:35 lib64 -> lib

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/skylake_avx512/software/FFTW/3.3.9-gompi-2021a:
total 23
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 24 14:25 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 24 14:25 easybuild
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 24 14:25 include
drwxr-xr-x. 4 cvmfs cvmfs 4096 May 24 14:25 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 May 24 14:25 lib64 -> lib
drwxr-xr-x. 4 cvmfs cvmfs 4096 May 24 13:41 share

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/skylake_avx512/software/ScaLAPACK/2.1.0-gompi-2021a-fb:
total 10
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 24 13:36 easybuild
drwxr-xr-x. 4 cvmfs cvmfs 4096 May 24 13:36 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 May 24 13:36 lib64 -> lib

-rw-r--r--. 1 cvmfs cvmfs 1320 May 24 14:26 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/aarch64/generic/modules/all/FFTW/3.3.9-gompi-2021a.lua
-rw-r--r--. 1 cvmfs cvmfs 1236 May 24 13:46 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/aarch64/generic/modules/all/ScaLAPACK/2.1.0-gompi-2021a-fb.lua

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/aarch64/generic/software/FFTW/3.3.9-gompi-2021a:
total 23
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 24 14:26 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 24 14:26 easybuild
drwxr-xr-x. 2 cvmfs cvmfs 4096 May 24 14:26 include
drwxr-xr-x. 4 cvmfs cvmfs 4096 May 24 14:26 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 May 24 14:26 lib64 -> lib
drwxr-xr-x. 4 cvmfs cvmfs 4096 May 24 13:54 share

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/aarch64/generic/software/ScaLAPACK/2.1.0-gompi-2021a-fb:
total 10
drwxr-xr-x. 3 cvmfs cvmfs 4096 May 24 13:46 easybuild
drwxr-xr-x. 4 cvmfs cvmfs 4096 May 24 13:46 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 May 24 13:46 lib64 -> lib 
```

**Comment by trz42** [comment]
Ingest was partially done with improved `automated_ingestion.py`

**Review by trz42 — APPROVED** [review]
All looking good. :100:

**Pull request merged**
