### PR TITLE
{2023.06}[foss/2023a] CP2K V2023.1

### PR DESCRIPTION
**Pull request by TopRichard**
Sync with EESSI ( PR 630)
Lic --> GPL

```
missing packages:

CP2K/2023.1-foss-2023a
Libint/2.7.2-GCC-12.3.0-lmax-6-cp2k
libvori/220621-GCCcore-12.3.0
libxsmm/1.17-GCC-12.3.0
```

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
Checklist before starting deployment (setting bot:deploy label):

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by TopRichard** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x]  Check if the _SPDX license identifier_ is provided 
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI for the ingested tarballs have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)

<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; 
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/CP2K/2023.1-foss-2023a* \
        aarch64/generic/{software,modules/all}/CP2K/2023.1-foss-2023a* 
  ```
  **log**
```
-rw-rw-r--. 1 cvmfs cvmfs 2087 Jul 23 18:09 aarch64/generic/modules/all/CP2K/2023.1-foss-2023a.lua
-rw-rw-r--. 1 cvmfs cvmfs 2180 Jul 23 19:17 x86_64/amd/zen2/modules/all/CP2K/2023.1-foss-2023a.lua
-rw-rw-r--. 1 cvmfs cvmfs 2178 Jul 23 19:02 x86_64/generic/modules/all/CP2K/2023.1-foss-2023a.lua
-rw-rw-r--. 1 cvmfs cvmfs 2194 Jul 23 19:45 x86_64/intel/broadwell/modules/all/CP2K/2023.1-foss-2023a.lua
-rw-rw-r--. 1 cvmfs cvmfs 2204 Jul 23 21:55 x86_64/intel/skylake_avx512/modules/all/CP2K/2023.1-foss-2023a.lua

aarch64/generic/software/CP2K/2023.1-foss-2023a:
total 23
dr-xr-xr-x.  2 cvmfs cvmfs 4096 Jul 23 15:13 bin
dr-xr-xr-x.  7 cvmfs cvmfs 4096 Jul 23 15:04 data
dr-xr-xr-x.  3 cvmfs cvmfs 4096 Jul 23 18:09 easybuild
dr-xr-xr-x. 23 cvmfs cvmfs 4096 Jul 23 18:07 TEST-Linux-x86-64-foss-psmp-2024-07-23_15-13-18
dr-xr-xr-x. 21 cvmfs cvmfs 4096 Jul 23 15:04 tests

x86_64/amd/zen2/software/CP2K/2023.1-foss-2023a:
total 23
dr-xr-xr-x.  2 cvmfs cvmfs 4096 Jul 23 15:29 bin
dr-xr-xr-x.  7 cvmfs cvmfs 4096 Jul 23 15:22 data
dr-xr-xr-x.  3 cvmfs cvmfs 4096 Jul 23 19:18 easybuild
dr-xr-xr-x. 23 cvmfs cvmfs 4096 Jul 23 19:14 TEST-Linux-x86-64-foss-psmp-2024-07-23_15-29-02
dr-xr-xr-x. 21 cvmfs cvmfs 4096 Jul 23 15:22 tests

x86_64/generic/software/CP2K/2023.1-foss-2023a:
total 23
dr-xr-xr-x.  2 cvmfs cvmfs 4096 Jul 23 15:36 bin
dr-xr-xr-x.  7 cvmfs cvmfs 4096 Jul 23 15:29 data
dr-xr-xr-x.  3 cvmfs cvmfs 4096 Jul 23 19:02 easybuild
dr-xr-xr-x. 23 cvmfs cvmfs 4096 Jul 23 18:59 TEST-Linux-x86-64-foss-psmp-2024-07-23_15-36-02
dr-xr-xr-x. 21 cvmfs cvmfs 4096 Jul 23 15:29 tests

x86_64/intel/broadwell/software/CP2K/2023.1-foss-2023a:
total 23
dr-xr-xr-x.  2 cvmfs cvmfs 4096 Jul 23 19:32 bin
dr-xr-xr-x.  7 cvmfs cvmfs 4096 Jul 23 19:12 data
dr-xr-xr-x.  3 cvmfs cvmfs 4096 Jul 23 19:46 easybuild
dr-xr-xr-x. 22 cvmfs cvmfs 4096 Jul 23 19:44 TEST-Linux-x86-64-foss-psmp-2024-07-23_21-32-47
dr-xr-xr-x. 21 cvmfs cvmfs 4096 Jul 23 19:12 tests

x86_64/intel/skylake_avx512/software/CP2K/2023.1-foss-2023a:
total 23
dr-xr-xr-x.  2 cvmfs cvmfs 4096 Jul 23 16:21 bin
dr-xr-xr-x.  7 cvmfs cvmfs 4096 Jul 23 16:11 data
dr-xr-xr-x.  3 cvmfs cvmfs 4096 Jul 23 21:56 easybuild
dr-xr-xr-x. 23 cvmfs cvmfs 4096 Jul 23 21:51 TEST-Linux-x86-64-foss-psmp-2024-07-23_18-21-27
dr-xr-xr-x. 21 cvmfs cvmfs 4096 Jul 23 16:11 tests

```
</details>

**Review by justadejavu — APPROVED** [review]
Lgtm

**Pull request merged**
