### PR TITLE
{2023.06}[gfbf/2023a] ipympl v0.9.3

### PR DESCRIPTION
**Pull request by trz42**
Replacement for version built with foss/2023a

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb10 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb10 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb10 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
Repeat Broadwell build that is stuck in test step...

bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by trz42** [comment]
Checklist before starting deployment (setting `bot:deploy` label): 

- [x]  Check if the _SPDX license identifier_ is provided 
- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each staged tarball was a PR for approval/rejection opened
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```bash
BASE_DIR=/cvmfs/pilot.nessi.no/versions/2023.06/software/linux \
ARCHS=() \
ARCHS+=("aarch64/generic") ; \
ARCHS+=("x86_64/generic") ; \
ARCHS+=("x86_64/amd/zen2") ; \
ARCHS+=("x86_64/intel/broadwell") ; \
ARCHS+=("x86_64/intel/skylake_avx512") ; \
for arch in "${ARCHS[@]}"; do \
ls -l \
  ${BASE_DIR}/${arch}/{software,modules/all}/ipympl/0.9.3-gfbf-* ; \
done
  ```
  **log - BEFORE ingestion**
```bash
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/software/ipympl/0.9.3-gfbf-*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/modules/all/ipympl/0.9.3-gfbf-*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/software/ipympl/0.9.3-gfbf-*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/modules/all/ipympl/0.9.3-gfbf-*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/software/ipympl/0.9.3-gfbf-*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all/ipympl/0.9.3-gfbf-*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/software/ipympl/0.9.3-gfbf-*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/modules/all/ipympl/0.9.3-gfbf-*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/ipympl/0.9.3-gfbf-*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/modules/all/ipympl/0.9.3-gfbf-*': No such file or directory 
```
  **log - AFTER ingestion**
```bash
-rw-r--r-- 1 cvmfs cvmfs 2150 May 28 20:58 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/modules/all/ipympl/0.9.3-gfbf-2023a.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/software/ipympl/0.9.3-gfbf-2023a:
total 19
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 28 20:58 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 28 20:58 etc
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 28 20:58 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 May 28 20:58 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 28 20:58 share
-rw-rw-r-- 1 cvmfs cvmfs 2149 May 28 21:03 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/modules/all/ipympl/0.9.3-gfbf-2023a.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/software/ipympl/0.9.3-gfbf-2023a:
total 19
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 28 21:04 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 28 21:03 etc
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 28 21:02 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 May 28 21:03 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 28 21:03 share
-rw-rw-r-- 1 cvmfs cvmfs 2150 May 28 21:02 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all/ipympl/0.9.3-gfbf-2023a.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/software/ipympl/0.9.3-gfbf-2023a:
total 19
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 28 21:02 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 28 21:02 etc
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 28 21:01 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 May 28 21:02 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 28 21:02 share
-rw-rw-r-- 1 cvmfs cvmfs 2157 May 28 22:16 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/modules/all/ipympl/0.9.3-gfbf-2023a.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/software/ipympl/0.9.3-gfbf-2023a:
total 19
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 28 22:17 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 28 22:16 etc
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 28 22:16 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 May 28 22:16 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 28 22:16 share
-rw-rw-r-- 1 cvmfs cvmfs 2162 May 28 21:01 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/modules/all/ipympl/0.9.3-gfbf-2023a.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/ipympl/0.9.3-gfbf-2023a:
total 19
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 28 21:01 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 28 21:00 etc
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 28 21:00 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 May 28 21:00 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 28 21:00 share 
```
</details>

**Review by poksumdo — APPROVED** [review]
looks good.

**Pull request merged**
