### PR TITLE
{2023.06}[foss/2022a] nodejs/16.15.1

### PR DESCRIPTION
**Pull request by trz42**
Will only install `nodejs`.

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:AWS arch:x86_64/generic repo:nessi-2023.06-swl-deb11
bot: build inst:AWS arch:x86_64/amd/zen2 repo:nessi-2023.06-swl-deb11
bot: build inst:eX3 arch:aarch64/generic repo:nessi-2023.06-swl-deb10
bot: build inst:Fram arch:x86_64/intel/broadwell repo:nessi-2023.06-swl-deb10
bot: build inst:AWS arch:x86_64/intel/cascadelake repo:nessi-2023.06-swl-deb11
bot: build inst:AWS arch:x86_64/intel/skylake repo:nessi-2023.06-swl-deb11

**Comment by trz42** [comment]
Checklist for building: 

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)
  - increased download timeout to 1000 seconds

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-intel-cascadelake`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/nodejs/* \
        aarch64/generic/{software,modules/all}/nodejs/*
  ```
  **log**
```
-rw-r--r-- 1 cvmfs cvmfs 1704 Oct  8 19:53 aarch64/generic/modules/all/nodejs/16.15.1-GCCcore-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1704 Oct  8 20:03 x86_64/amd/zen2/modules/all/nodejs/16.15.1-GCCcore-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1703 Oct  8 19:51 x86_64/generic/modules/all/nodejs/16.15.1-GCCcore-11.3.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 1711 Oct  8 19:30 x86_64/intel/broadwell/modules/all/nodejs/16.15.1-GCCcore-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1713 Oct  8 20:06 x86_64/intel/cascadelake/modules/all/nodejs/16.15.1-GCCcore-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1716 Oct  8 19:45 x86_64/intel/skylake_avx512/modules/all/nodejs/16.15.1-GCCcore-11.3.0.lua

aarch64/generic/software/nodejs/16.15.1-GCCcore-11.3.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  8 19:53 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  8 19:53 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  8 19:32 include
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  8 19:53 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  8 19:53 lib64 -> lib
dr-xr-xr-x 5 cvmfs cvmfs 4096 Oct  8 19:32 share

x86_64/amd/zen2/software/nodejs/16.15.1-GCCcore-11.3.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  8 20:03 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  8 20:03 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  8 19:41 include
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  8 20:03 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  8 20:03 lib64 -> lib
dr-xr-xr-x 5 cvmfs cvmfs 4096 Oct  8 19:41 share

x86_64/generic/software/nodejs/16.15.1-GCCcore-11.3.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  8 19:51 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  8 19:51 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  8 19:35 include
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  8 19:51 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  8 19:51 lib64 -> lib
dr-xr-xr-x 5 cvmfs cvmfs 4096 Oct  8 19:35 share

x86_64/intel/broadwell/software/nodejs/16.15.1-GCCcore-11.3.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  8 19:30 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  8 19:30 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  8 19:22 include
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  8 19:30 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  8 19:30 lib64 -> lib
dr-xr-xr-x 5 cvmfs cvmfs 4096 Oct  8 19:22 share

x86_64/intel/cascadelake/software/nodejs/16.15.1-GCCcore-11.3.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  8 20:06 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  8 20:06 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  8 19:46 include
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  8 20:06 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  8 20:06 lib64 -> lib
dr-xr-xr-x 5 cvmfs cvmfs 4096 Oct  8 19:46 share

x86_64/intel/skylake_avx512/software/nodejs/16.15.1-GCCcore-11.3.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  8 19:45 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  8 19:45 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  8 19:33 include
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  8 19:45 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  8 19:45 lib64 -> lib
dr-xr-xr-x 5 cvmfs cvmfs 4096 Oct  8 19:33 share 
```
</details>

**Review by poksumdo — APPROVED** [review]
Great.

**Pull request merged**
