### PR TITLE
{2023.06}[GCCcore/12.3.0] LittleCMS V2.15

### PR DESCRIPTION
**Pull request by TopRichard**
SPDX license identifier: MIT
Required for CI tests in #292

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by TopRichard** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:zen2

**Comment by TopRichard** [comment]
Builds fail while running `check_missing_installations.sh`  :
```
1 out of 93 required modules missing:

* GPAW-setups/24.1.0 (GPAW-setups-24.1.0.eb)
```

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by TopRichard** [comment]
Checklist before starting deployment (setting bot:deploy label):

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by TopRichard** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  -  `aarch64-generic`

Checklist for deployment/ingestion
- [x]  Check if the _SPDX license identifier_ is provided 
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [] encountered issues in the ingestion, likely related to troubles interacting with GitHub via PyGithub … 
- [x] all tests in the CI for the ingested tarballs have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)

<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; 
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/LittleCMS/2.15-GCCcore-13.2.0* \
        aarch64/generic/{software,modules/all}/LittleCMS/2.15-GCCcore-13.2.0*
  ```
  **log** (note, output includes `-bare` modules)
```
-rw-r--r-- 1 cvmfs cvmfs 1417 Mar 26 14:57 aarch64/generic/modules/all/LittleCMS/2.15-GCCcore-13.2.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 1417 Mar 26 13:54 x86_64/amd/zen2/modules/all/LittleCMS/2.15-GCCcore-13.2.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 1416 Mar 26 13:50 x86_64/generic/modules/all/LittleCMS/2.15-GCCcore-13.2.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 1424 Mar 26 13:49 x86_64/intel/broadwell/modules/all/LittleCMS/2.15-GCCcore-13.2.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 1429 Mar 26 13:50 x86_64/intel/skylake_avx512/modules/all/LittleCMS/2.15-GCCcore-13.2.0.lua

aarch64/generic/software/LittleCMS/2.15-GCCcore-13.2.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Mar 26 14:57 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 26 14:57 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Mar 26 14:57 include
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 26 14:57 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Mar 26 14:57 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 26 14:57 share

x86_64/amd/zen2/software/LittleCMS/2.15-GCCcore-13.2.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Mar 26 13:54 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 26 13:54 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Mar 26 13:54 include
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 26 13:54 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Mar 26 13:54 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 26 13:54 share

x86_64/generic/software/LittleCMS/2.15-GCCcore-13.2.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Mar 26 13:50 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 26 13:50 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Mar 26 13:50 include
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 26 13:50 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Mar 26 13:50 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 26 13:50 share

x86_64/intel/broadwell/software/LittleCMS/2.15-GCCcore-13.2.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Mar 26 13:49 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 26 13:49 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Mar 26 13:49 include
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 26 13:49 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Mar 26 13:49 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 26 13:49 share

x86_64/intel/skylake_avx512/software/LittleCMS/2.15-GCCcore-13.2.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Mar 26 13:50 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 26 13:50 easybuild
dr-xr-xr-x 2 cvmfs cvmfs 4096 Mar 26 13:50 include
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 26 13:50 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Mar 26 13:50 lib64 -> lib
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 26 13:50 share

```
</details>

**Review by justadejavu — APPROVED** [review]
lgtm

**Pull request merged**
