### PR TITLE
{2023.06}[foss/2023a] GATK v4.5.0.0

### PR DESCRIPTION
**Pull request by trz42**
Add GATK v4.5.0.0

SPDX license identifier: `Apache-2.0`

Missing packages:
```
3 out of 12 required modules missing:

* Java/17.0.6 (Java-17.0.6.eb)
* Java/17 (Java-17.eb)
* GATK/4.5.0.0-GCCcore-12.3.0-Java-17 (GATK-4.5.0.0-GCCcore-12.3.0-Java-17.eb)
```

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb10 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
Repeat job on Broadwell

bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by trz42** [comment]
Repeat job on Broadwell (after fixing `ipympl` issue and pruning number of ReFrame tests run after build step)...

bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by trz42** [comment]
Checklist before starting deployment (setting `bot:deploy` label): 

- [x]  Check if the _SPDX license identifier_ is provided 
- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Repeat job on Broadwell (after fixing ipympl issue and pruning number of ReFrame tests run after build step)...

bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each staged tarball was a PR for approval/rejection opened
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```bash
BASE_DIR=/cvmfs/pilot.nessi.no/versions/2023.06/software/linux \
ARCHS=() \
ARCHS+=("aarch64/generic") ; \
ARCHS+=("x86_64/generic") ; \
ARCHS+=("x86_64/amd/zen2") ; \
ARCHS+=("x86_64/intel/broadwell") ; \
ARCHS+=("x86_64/intel/skylake_avx512") ; \
for arch in "${ARCHS[@]}"; do \
ls -l \
  ${BASE_DIR}/${arch}/{software,modules/all}/GATK/4.5.0.0-GCCcore-12.3.0-Java-17* \
  ${BASE_DIR}/${arch}/{software,modules/all}/Java/17.0.6* ; \
done
  ```
  **log - BEFORE ingestion**
```bash
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/software/GATK/4.5.0.0-GCCcore-12.3.0-Java-17.lua': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/modules/all/GATK/4.5.0.0-GCCcore-12.3.0-Java-17.lua': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/software/Java/17.0.6.lua*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/modules/all/Java/17.0.6.lua*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/software/GATK/4.5.0.0-GCCcore-12.3.0-Java-17.lua': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/modules/all/GATK/4.5.0.0-GCCcore-12.3.0-Java-17.lua': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/software/Java/17.0.6.lua*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/modules/all/Java/17.0.6.lua*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/software/GATK/4.5.0.0-GCCcore-12.3.0-Java-17.lua': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all/GATK/4.5.0.0-GCCcore-12.3.0-Java-17.lua': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/software/Java/17.0.6.lua*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all/Java/17.0.6.lua*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/software/GATK/4.5.0.0-GCCcore-12.3.0-Java-17.lua': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/modules/all/GATK/4.5.0.0-GCCcore-12.3.0-Java-17.lua': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/software/Java/17.0.6.lua*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/modules/all/Java/17.0.6.lua*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/GATK/4.5.0.0-GCCcore-12.3.0-Java-17.lua': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/modules/all/GATK/4.5.0.0-GCCcore-12.3.0-Java-17.lua': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/Java/17.0.6.lua*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/modules/all/Java/17.0.6.lua*': No such file or directory 
```
  **log - AFTER ingestion**
```bash
-rw-r--r--  1 cvmfs cvmfs 1968 May 27 22:44 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/modules/all/GATK/4.5.0.0-GCCcore-12.3.0-Java-17.lua
-rw-r--r--  1 cvmfs cvmfs 1143 May 27 22:43 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/modules/all/Java/17.0.6.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/software/GATK/4.5.0.0-GCCcore-12.3.0-Java-17:
total 759574
dr-xr-xr-x 3 cvmfs cvmfs      4096 May 27 22:44 easybuild
-r-xr-xr-x 1 cvmfs cvmfs     21097 Dec 13 17:44 gatk
-r--r--r-- 1 cvmfs cvmfs   1040338 Dec 13 17:44 gatk-completion.sh
-r--r--r-- 1 cvmfs cvmfs      4249 Dec 13 17:44 gatkcondaenv.yml
-r--r--r-- 1 cvmfs cvmfs      3630 Dec 13 17:44 GATKConfig.EXAMPLE.properties
dr-xr-xr-x 2 cvmfs cvmfs      4096 Dec 13 17:44 gatkdoc
-r--r--r-- 1 cvmfs cvmfs 442046045 Dec 13 17:44 gatk-package-4.5.0.0-local.jar
-r--r--r-- 1 cvmfs cvmfs 334511810 Dec 13 17:44 gatk-package-4.5.0.0-spark.jar
-r--r--r-- 1 cvmfs cvmfs    119765 Dec 13 17:44 gatkPythonPackageArchive.zip
-r--r--r-- 1 cvmfs cvmfs     40565 Dec 13 17:44 README.md
dr-xr-xr-x 5 cvmfs cvmfs      4096 Dec 13 17:44 scripts

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/software/Java/17.0.6:
total 41
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jan 18  2023 bin
dr-xr-xr-x  5 cvmfs cvmfs 4096 Jan 18  2023 conf
dr-xr-xr-x  3 cvmfs cvmfs 4096 May 27 22:43 easybuild
dr-xr-xr-x  3 cvmfs cvmfs 4096 Jan 18  2023 include
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jan 18  2023 jmods
dr-xr-xr-x 72 cvmfs cvmfs 4096 Jan 18  2023 legal
dr-xr-xr-x  5 cvmfs cvmfs 4096 Jan 18  2023 lib
lrwxrwxrwx  1 cvmfs cvmfs    3 May 27 22:43 lib64 -> lib
dr-xr-xr-x  3 cvmfs cvmfs 4096 Jan 18  2023 man
-r--r--r--  1 cvmfs cvmfs 2439 Jan 18  2023 NOTICE
-r--r--r--  1 cvmfs cvmfs 1594 Jan 18  2023 release
-rw-rw-r--  1 cvmfs cvmfs 1967 May 27 23:08 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/modules/all/GATK/4.5.0.0-GCCcore-12.3.0-Java-17.lua
-rw-rw-r--  1 cvmfs cvmfs 1141 May 27 23:07 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/modules/all/Java/17.0.6.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/software/GATK/4.5.0.0-GCCcore-12.3.0-Java-17:
total 759574
dr-xr-xr-x 3 cvmfs cvmfs      4096 May 27 23:08 easybuild
-r-xr-xr-x 1 cvmfs cvmfs     21097 Dec 13 18:44 gatk
-r--r--r-- 1 cvmfs cvmfs   1040338 Dec 13 18:44 gatk-completion.sh
-r--r--r-- 1 cvmfs cvmfs      4249 Dec 13 18:44 gatkcondaenv.yml
-r--r--r-- 1 cvmfs cvmfs      3630 Dec 13 18:44 GATKConfig.EXAMPLE.properties
dr-xr-xr-x 2 cvmfs cvmfs      4096 Dec 13 18:44 gatkdoc
-r--r--r-- 1 cvmfs cvmfs 442046045 Dec 13 18:44 gatk-package-4.5.0.0-local.jar
-r--r--r-- 1 cvmfs cvmfs 334511810 Dec 13 18:44 gatk-package-4.5.0.0-spark.jar
-r--r--r-- 1 cvmfs cvmfs    119765 Dec 13 18:44 gatkPythonPackageArchive.zip
-r--r--r-- 1 cvmfs cvmfs     40565 Dec 13 18:44 README.md
dr-xr-xr-x 5 cvmfs cvmfs      4096 Dec 13 18:44 scripts

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/software/Java/17.0.6:
total 41
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jan 18  2023 bin
dr-xr-xr-x  5 cvmfs cvmfs 4096 Jan 18  2023 conf
dr-xr-xr-x  3 cvmfs cvmfs 4096 May 27 23:07 easybuild
dr-xr-xr-x  3 cvmfs cvmfs 4096 Jan 18  2023 include
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jan 18  2023 jmods
dr-xr-xr-x 72 cvmfs cvmfs 4096 Jan 18  2023 legal
dr-xr-xr-x  5 cvmfs cvmfs 4096 Jan 18  2023 lib
lrwxrwxrwx  1 cvmfs cvmfs    3 May 27 23:07 lib64 -> lib
dr-xr-xr-x  3 cvmfs cvmfs 4096 Jan 18  2023 man
-r--r--r--  1 cvmfs cvmfs 2439 Jan 18  2023 NOTICE
-r--r--r--  1 cvmfs cvmfs 1593 Jan 18  2023 release
-rw-rw-r--  1 cvmfs cvmfs 1968 May 27 22:50 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all/GATK/4.5.0.0-GCCcore-12.3.0-Java-17.lua
-rw-rw-r--  1 cvmfs cvmfs 1143 May 27 22:49 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all/Java/17.0.6.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/software/GATK/4.5.0.0-GCCcore-12.3.0-Java-17:
total 759574
dr-xr-xr-x 3 cvmfs cvmfs      4096 May 27 22:50 easybuild
-r-xr-xr-x 1 cvmfs cvmfs     21097 Dec 13 18:44 gatk
-r--r--r-- 1 cvmfs cvmfs   1040338 Dec 13 18:44 gatk-completion.sh
-r--r--r-- 1 cvmfs cvmfs      4249 Dec 13 18:44 gatkcondaenv.yml
-r--r--r-- 1 cvmfs cvmfs      3630 Dec 13 18:44 GATKConfig.EXAMPLE.properties
dr-xr-xr-x 2 cvmfs cvmfs      4096 Dec 13 18:44 gatkdoc
-r--r--r-- 1 cvmfs cvmfs 442046045 Dec 13 18:44 gatk-package-4.5.0.0-local.jar
-r--r--r-- 1 cvmfs cvmfs 334511810 Dec 13 18:44 gatk-package-4.5.0.0-spark.jar
-r--r--r-- 1 cvmfs cvmfs    119765 Dec 13 18:44 gatkPythonPackageArchive.zip
-r--r--r-- 1 cvmfs cvmfs     40565 Dec 13 18:44 README.md
dr-xr-xr-x 5 cvmfs cvmfs      4096 Dec 13 18:44 scripts

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/software/Java/17.0.6:
total 41
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jan 18  2023 bin
dr-xr-xr-x  5 cvmfs cvmfs 4096 Jan 18  2023 conf
dr-xr-xr-x  3 cvmfs cvmfs 4096 May 27 22:49 easybuild
dr-xr-xr-x  3 cvmfs cvmfs 4096 Jan 18  2023 include
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jan 18  2023 jmods
dr-xr-xr-x 72 cvmfs cvmfs 4096 Jan 18  2023 legal
dr-xr-xr-x  5 cvmfs cvmfs 4096 Jan 18  2023 lib
lrwxrwxrwx  1 cvmfs cvmfs    3 May 27 22:49 lib64 -> lib
dr-xr-xr-x  3 cvmfs cvmfs 4096 Jan 18  2023 man
-r--r--r--  1 cvmfs cvmfs 2439 Jan 18  2023 NOTICE
-r--r--r--  1 cvmfs cvmfs 1593 Jan 18  2023 release
-rw-rw-r--  1 cvmfs cvmfs 1975 May 28 23:39 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/modules/all/GATK/4.5.0.0-GCCcore-12.3.0-Java-17.lua
-rw-rw-r--  1 cvmfs cvmfs 1157 May 28 23:37 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/modules/all/Java/17.0.6.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/software/GATK/4.5.0.0-GCCcore-12.3.0-Java-17:
total 759574
dr-xr-xr-x 3 cvmfs cvmfs      4096 May 28 23:39 easybuild
-r-xr-xr-x 1 cvmfs cvmfs     21097 Dec 13 17:44 gatk
-r--r--r-- 1 cvmfs cvmfs   1040338 Dec 13 17:44 gatk-completion.sh
-r--r--r-- 1 cvmfs cvmfs      4249 Dec 13 17:44 gatkcondaenv.yml
-r--r--r-- 1 cvmfs cvmfs      3630 Dec 13 17:44 GATKConfig.EXAMPLE.properties
dr-xr-xr-x 2 cvmfs cvmfs      4096 Dec 13 17:44 gatkdoc
-r--r--r-- 1 cvmfs cvmfs 442046045 Dec 13 17:44 gatk-package-4.5.0.0-local.jar
-r--r--r-- 1 cvmfs cvmfs 334511810 Dec 13 17:44 gatk-package-4.5.0.0-spark.jar
-r--r--r-- 1 cvmfs cvmfs    119765 Dec 13 17:44 gatkPythonPackageArchive.zip
-r--r--r-- 1 cvmfs cvmfs     40565 Dec 13 17:44 README.md
dr-xr-xr-x 5 cvmfs cvmfs      4096 Dec 13 17:44 scripts

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/software/Java/17.0.6:
total 41
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jan 18  2023 bin
dr-xr-xr-x  5 cvmfs cvmfs 4096 Jan 18  2023 conf
dr-xr-xr-x  3 cvmfs cvmfs 4096 May 28 23:38 easybuild
dr-xr-xr-x  3 cvmfs cvmfs 4096 Jan 18  2023 include
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jan 18  2023 jmods
dr-xr-xr-x 72 cvmfs cvmfs 4096 Jan 18  2023 legal
dr-xr-xr-x  5 cvmfs cvmfs 4096 Jan 18  2023 lib
lrwxrwxrwx  1 cvmfs cvmfs    3 May 28 23:37 lib64 -> lib
dr-xr-xr-x  3 cvmfs cvmfs 4096 Jan 18  2023 man
-r--r--r--  1 cvmfs cvmfs 2439 Jan 18  2023 NOTICE
-r--r--r--  1 cvmfs cvmfs 1593 Jan 18  2023 release
-rw-rw-r--  1 cvmfs cvmfs 1980 May 27 22:49 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/modules/all/GATK/4.5.0.0-GCCcore-12.3.0-Java-17.lua
-rw-rw-r--  1 cvmfs cvmfs 1167 May 27 22:47 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/modules/all/Java/17.0.6.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/GATK/4.5.0.0-GCCcore-12.3.0-Java-17:
total 759574
dr-xr-xr-x 3 cvmfs cvmfs      4096 May 27 22:50 easybuild
-r-xr-xr-x 1 cvmfs cvmfs     21097 Dec 13 17:44 gatk
-r--r--r-- 1 cvmfs cvmfs   1040338 Dec 13 17:44 gatk-completion.sh
-r--r--r-- 1 cvmfs cvmfs      4249 Dec 13 17:44 gatkcondaenv.yml
-r--r--r-- 1 cvmfs cvmfs      3630 Dec 13 17:44 GATKConfig.EXAMPLE.properties
dr-xr-xr-x 2 cvmfs cvmfs      4096 Dec 13 17:44 gatkdoc
-r--r--r-- 1 cvmfs cvmfs 442046045 Dec 13 17:44 gatk-package-4.5.0.0-local.jar
-r--r--r-- 1 cvmfs cvmfs 334511810 Dec 13 17:44 gatk-package-4.5.0.0-spark.jar
-r--r--r-- 1 cvmfs cvmfs    119765 Dec 13 17:44 gatkPythonPackageArchive.zip
-r--r--r-- 1 cvmfs cvmfs     40565 Dec 13 17:44 README.md
dr-xr-xr-x 5 cvmfs cvmfs      4096 Dec 13 17:44 scripts

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/Java/17.0.6:
total 41
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jan 18  2023 bin
dr-xr-xr-x  5 cvmfs cvmfs 4096 Jan 18  2023 conf
dr-xr-xr-x  3 cvmfs cvmfs 4096 May 27 22:47 easybuild
dr-xr-xr-x  3 cvmfs cvmfs 4096 Jan 18  2023 include
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jan 18  2023 jmods
dr-xr-xr-x 72 cvmfs cvmfs 4096 Jan 18  2023 legal
dr-xr-xr-x  5 cvmfs cvmfs 4096 Jan 18  2023 lib
lrwxrwxrwx  1 cvmfs cvmfs    3 May 27 22:47 lib64 -> lib
dr-xr-xr-x  3 cvmfs cvmfs 4096 Jan 18  2023 man
-r--r--r--  1 cvmfs cvmfs 2439 Jan 18  2023 NOTICE
-r--r--r--  1 cvmfs cvmfs 1593 Jan 18  2023 release 
```
</details>

**Review by poksumdo — APPROVED** [review]
nice

**Pull request merged**
