### PR TITLE
Adding CMake/3.20-Rust/1.52.1-foss/2021a to NESSI/2023.06

### PR DESCRIPTION
**Pull request by TopRichard**
Trying to add CMake/3.20-Rust/1.52.1-foss/2021a to NESSI/2023.06

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi.no-2023.06-software arch:generic
bot: build inst:AWS repo:nessi.no-2023.06-software arch:x86_64/intel/cascadelake 
bot: build inst:AWS repo:nessi.no-2023.06-software arch:x86_64/intel/skylake 
bot: build inst:Fram-NESSI repo:nessi.no-2023.06-software arch:x86_64/intel/broadwell
bot: build inst:eX3 repo:nessi.no-2023.06-software arch:zen2
bot: build inst:eX3 repo:nessi.no-2023.06-software arch:aarch64/generic

**Comment by trz42** [comment]
Checklist for building: 

- [x]  did the builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  is the PR up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  are all requested changes sound (checking files changed on GitHub.com)
- [x]  is/are the easyconfig/s being built included with the EB version used (if not why not)
- [x]  were any changes needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by TopRichard** [comment]
Checklist for deployment/ingestion

- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] at least one PR for each architecture has been opened
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512`
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
  **command**
  ```
  ls -l /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/foss/*
  ls -l /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/{software,modules/all}/foss/*
  ```
  **log**
```
ls -l /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/foss/*
-rw-r--r--. 1 eessi eessi 1565 Jun 21 01:58 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/module/all/foss/2021a.lua
-rw-r--r--. 1 eessi eessi 1564 Jun 21 04:34 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/modules/all/foss/2021a.lua
-rw-rw-r--. 1 eessi eessi 1572 Jun 21 02:09 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/modules/all/foss/2021a.lua
-rw-r--r--. 1 eessi eessi 1574 Jun 21 05:06 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelak/modules/all/foss/2021a.lua
-rw-r--r--. 1 eessi eessi 1577 Jun 21 04:17 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/modules/all/foss/2021a.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/software/foss/2021a:
total 5
drwxr-xr-x. 3 eessi eessi 4096 Jun 21 01:58 easybuild

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/software/foss/2021a:
total 5
drwxr-xr-x. 3 eessi eessi 4096 Jun 21 04:34 easybuild

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/software/foss/2021a:
total 5
drwxr-xr-x. 3 eessi eessi 4096 Jun 21 02:09 easybuild

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/software/foss/2021a:
total 5
drwxr-xr-x. 3 eessi eessi 4096 Jun 21 05:06 easybuild

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/foss/2021a:
total 5
drwxr-xr-x. 3 eessi eessi 4096 Jun 21 04:17 easybuild
-rw-r--r--. 1 eessi eessi 1565 Jun 21 04:47 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/modules/all/foss/2021a.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/software/foss/2021a:
total 5
drwxr-xr-x. 3 eessi eessi 4096 Jun 21 04:47 easybuild

```

**Review by trz42 — APPROVED** [review]
Nice!

**Pull request merged**
