### PR TITLE
{2023.06}[system] add EasyBuild/4.8.1

### PR DESCRIPTION
**Pull request by trz42**
adds EasyBuild via a new easystack file for the system toolchain

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:AWS arch:x86_64/generic repo:nessi-2023.06-swl-deb11
bot: build inst:eX3 arch:x86_64/amd/zen2 repo:nessi-2023.06-swl-deb11
bot: build inst:eX3 arch:aarch64/generic repo:nessi-2023.06-swl-deb11
bot: build inst:Fram arch:x86_64/intel/broadwell repo:nessi-2023.06-swl-deb10
bot: build inst:Saga arch:x86_64/intel/cascadelake repo:nessi-2023.06-swl-deb11
bot: build inst:Saga arch:x86_64/intel/skylake repo:nessi-2023.06-swl-deb11

**Comment by trz42** [comment]
Checklist for building: 

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
  - needed to use a PR because easyconfig for next version of EasyBuild (`4.8.1`) is not available via current/used version (`4.8.0`)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-intel-cascadelake`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/EasyBuild/4.8.1* \
        aarch64/generic/{software,modules/all}/EasyBuild/4.8.1*
  ```
  **log**
```
-rw-r--r--. 1 cvmfs cvmfs 1321 Oct  5 00:28 aarch64/generic/modules/all/EasyBuild/4.8.1.lua
-rw-r--r--. 1 cvmfs cvmfs 1320 Oct  5 00:29 x86_64/amd/zen2/modules/all/EasyBuild/4.8.1.lua
-rw-r--r--. 1 cvmfs cvmfs 1319 Oct  5 00:38 x86_64/generic/modules/all/EasyBuild/4.8.1.lua
-rw-rw-r--. 1 cvmfs cvmfs 1327 Oct  5 00:31 x86_64/intel/broadwell/modules/all/EasyBuild/4.8.1.lua
-rw-rw-r--. 1 cvmfs cvmfs 1329 Oct  5 00:46 x86_64/intel/cascadelake/modules/all/EasyBuild/4.8.1.lua
-rw-rw-r--. 1 cvmfs cvmfs 1332 Oct  5 00:43 x86_64/intel/skylake_avx512/modules/all/EasyBuild/4.8.1.lua

aarch64/generic/software/EasyBuild/4.8.1:
total 23
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct  5 00:27 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct  5 00:27 contrib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Oct  5 00:30 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct  5 00:27 etc
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct  5 00:27 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct  5 00:28 lib64 -> lib

x86_64/amd/zen2/software/EasyBuild/4.8.1:
total 23
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct  5 00:28 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct  5 00:28 contrib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Oct  5 00:29 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct  5 00:28 etc
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct  5 00:28 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct  5 00:29 lib64 -> lib

x86_64/generic/software/EasyBuild/4.8.1:
total 23
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct  5 00:38 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct  5 00:38 contrib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Oct  5 00:39 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct  5 00:38 etc
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct  5 00:37 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct  5 00:38 lib64 -> lib

x86_64/intel/broadwell/software/EasyBuild/4.8.1:
total 23
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct  5 00:30 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct  5 00:30 contrib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Oct  5 00:32 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct  5 00:30 etc
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct  5 00:30 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct  5 00:31 lib64 -> lib

x86_64/intel/cascadelake/software/EasyBuild/4.8.1:
total 23
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct  5 00:45 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct  5 00:45 contrib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Oct  5 00:46 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct  5 00:45 etc
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct  5 00:45 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct  5 00:46 lib64 -> lib

x86_64/intel/skylake_avx512/software/EasyBuild/4.8.1:
total 23
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct  5 00:42 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct  5 00:42 contrib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Oct  5 00:44 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct  5 00:42 etc
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct  5 00:42 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct  5 00:43 lib64 -> lib 
```
</details>

**Review by poksumdo — APPROVED** [review]
Looks good. Ready to build more packages.

**Pull request merged**
