### PR TITLE
Adding QuantumESPRESSO to NESSI/2022.11

### PR DESCRIPTION
**Pull request by rungitta**

### CODE REVIEW

**Review by terjekv — APPROVED** [review]
lgtm

**Comment by terjekv** [comment]
Much belated checklist. Post this _before_ you approve and merge, even if you have done it manually. Don't be like me.

- [x] did the builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  is the PR up-to-date with the target branch nessi.no-2022.11-dev in the repository (if not what are the differences)
- [x]  are all requested changes sound (checking files changed on GitHub.com)
- [x]  is/are the easyconfig/s being built included with the EB version used (if not why not)
- [x]  were any changes needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)
(QuantuESPRESSO is specifically excluded on Power, this is a known upstream issue.)

**Comment by terjekv** [comment]
Checklist for deployment:

- [x] at least one tarball for each architecture has been uploaded
  - [x]  `x86_64-intel-broadwell`
  - [x]  `x86_64-intel-skylake_avx512`
  - [x]  `x86_64-intel-cascadelake`
  - [x]  `x86_64-amd-zen2`
  - [x]  `x86_64-generic`
  - [x]  `aarch64-generic`
 
- [x]  at least one tarball for each architecture has been staged
  - [x]  `x86_64-intel-broadwell`
  - [x]  `x86_64-intel-skylake_avx512`
  - [x]  `x86_64-intel-cascadelake`
  - [x]  `x86_64-amd-zen2`
  - [x]  `x86_64-generic`
  - [x]  `aarch64-generic`

- [x]  for each architecture one and only one tarball has been approved
  - [x]  `x86_64-intel-broadwell`
  - [x]  `x86_64-intel-skylake_avx512`
  - [x]  `x86_64-intel-cascadelake`
  - [x]  `x86_64-amd-zen2`
  - [x]  `x86_64-generic`
  - [x]  `aarch64-generic`
 
- [x]  for each architecture one and only one tarball was ingested
  - [x]  `x86_64-intel-broadwell`
  - [x]  `x86_64-intel-skylake_avx512`
  - [x]  `x86_64-intel-cascadelake`
  - [x]  `x86_64-amd-zen2`
  - [x]  `x86_64-generic`
  - [x]  `aarch64-generic`

- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files). Command to check:
  - [x] does the output for the following command lists results for all `x86_64` architectures?
    ```
    ls -l /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/QuantumESPRESSO/*
    ```
  - [x] does the output for the following command lists results for all `aarch64` architectures?
    ```
    ls -l /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/aarch64/generic/{software,modules/all}/QuantumESPRESSO/*
    ```

**Comment by trz42** [comment]
All done now.

**Pull request merged**
