### PR TITLE
{2023.06}[foss/2023b] Wayland v1.22.0

### PR DESCRIPTION
**Pull request by trz42**
Sync NESSI with EESSI (PR 520).

SPDX license identifier: `MIT`

Missing packages:
```
1 out of 17 required modules missing:

* Wayland/1.22.0-GCCcore-13.2.0 (Wayland-1.22.0-GCCcore-13.2.0.eb)
```

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb10 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
Checklist before starting deployment (setting `bot:deploy` label): 

- [x]  Check if the _SPDX license identifier_ is provided 
- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [ ]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
  - essentially up-to-date, final update will be done after all tarballs have been ingested to trigger CI workflows
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each staged tarball was a PR for approval/rejection opened
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/Wayland/1.22.0-GCCcore-13* \
        aarch64/generic/{software,modules/all}/Wayland/1.22.0-GCCcore-13*
  ```
  **log**
```
-rw-r--r--. 1 cvmfs cvmfs 2245 Apr 17 19:27 aarch64/generic/modules/all/Wayland/1.22.0-GCCcore-13.2.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 2245 Apr 17 19:36 x86_64/amd/zen2/modules/all/Wayland/1.22.0-GCCcore-13.2.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 2244 Apr 17 19:35 x86_64/generic/modules/all/Wayland/1.22.0-GCCcore-13.2.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 2252 Apr 17 19:31 x86_64/intel/broadwell/modules/all/Wayland/1.22.0-GCCcore-13.2.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 2257 Apr 17 19:28 x86_64/intel/skylake_avx512/modules/all/Wayland/1.22.0-GCCcore-13.2.0.lua

aarch64/generic/software/Wayland/1.22.0-GCCcore-13.2.0:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Apr 17 19:26 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 17 19:27 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Apr 17 19:26 include
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 17 19:26 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 17 19:27 lib64 -> lib
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Apr 17 19:27 share

x86_64/amd/zen2/software/Wayland/1.22.0-GCCcore-13.2.0:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Apr 17 19:36 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 17 19:36 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Apr 17 19:36 include
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 17 19:36 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 17 19:36 lib64 -> lib
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Apr 17 19:36 share

x86_64/generic/software/Wayland/1.22.0-GCCcore-13.2.0:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Apr 17 19:35 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 17 19:35 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Apr 17 19:35 include
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 17 19:35 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 17 19:35 lib64 -> lib
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Apr 17 19:35 share

x86_64/intel/broadwell/software/Wayland/1.22.0-GCCcore-13.2.0:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Apr 17 19:31 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 17 19:31 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Apr 17 19:31 include
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 17 19:31 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 17 19:31 lib64 -> lib
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Apr 17 19:31 share

x86_64/intel/skylake_avx512/software/Wayland/1.22.0-GCCcore-13.2.0:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Apr 17 19:28 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 17 19:28 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Apr 17 19:28 include
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 17 19:28 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 17 19:28 lib64 -> lib
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Apr 17 19:28 share 
```
</details>

**Review by poksumdo — APPROVED** [review]
One more done.

**Pull request merged**
