### PR TITLE
{2023.06}[foss/2023a] GPAW V23.9.1

### PR DESCRIPTION
**Pull request by TopRichard**
GPAW is found on Saga, will try to build it on NESSI:
 license --> https://spdx.org/licenses/GPL-3.0-or-later.html
 ```
8 out of 89 required modules missing:


* GPAW-setups/0.9.20000 (GPAW-setups-0.9.20000.eb)
* Flask/2.3.3-GCCcore-12.3.0 (Flask-2.3.3-GCCcore-12.3.0.eb)
* scikit-build-core/0.5.0-GCCcore-12.3.0 (scikit-build-core-0.5.0-GCCcore-12.3.0.eb)
* spglib-python/2.1.0-gfbf-2023a (spglib-python-2.1.0-gfbf-2023a.eb)
* libvdwxc/0.4.0-foss-2023a (libvdwxc-0.4.0-foss-2023a.eb)
* ELPA/2023.05.001-foss-2023a (ELPA-2023.05.001-foss-2023a.eb)
* ASE/3.22.1-gfbf-2023a (ASE-3.22.1-gfbf-2023a.eb)
* GPAW/23.9.1-foss-2023a (GPAW-23.9.1-foss-2023a.eb)
 ```

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb10 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot :config

**Comment by TopRichard** [comment]
bot: config

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:Fram repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by trz42** [comment]
Checklist before starting deployment (setting `bot:deploy` label): 

- [x]  Check if the _SPDX license identifier_ is provided 
- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)
  - a `parse_hook` is needed to define some options (via `siteconfig.py`) and to let `setup.py` use the interpreter from the compat layer (via `%(sysroot)s`)

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
  - upload from eX3 failed once - annoying 🤦 (see https://github.com/NorESSI/software-layer/pull/276#issuecomment-1998288929, reporting is wrong though)
  - upload from eX3 failed a second time 
- [x] at least one tarball for each architecture has been staged
- [x] for each staged tarball was a PR for approval/rejection opened
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/GPAW/23.9.1-foss-2023a* \
        aarch64/generic/{software,modules/all}/GPAW/23.9.1-foss-2023a*
  ```
  **log**
```
-rw-r--r-- 1 cvmfs cvmfs 2203 Mar 14 21:44 aarch64/generic/modules/all/GPAW/23.9.1-foss-2023a.lua
-rw-rw-r-- 1 cvmfs cvmfs 2203 Mar 14 21:35 x86_64/amd/zen2/modules/all/GPAW/23.9.1-foss-2023a.lua
-rw-rw-r-- 1 cvmfs cvmfs 2202 Mar 14 21:32 x86_64/generic/modules/all/GPAW/23.9.1-foss-2023a.lua
-rw-rw-r-- 1 cvmfs cvmfs 2210 Mar 14 13:40 x86_64/intel/broadwell/modules/all/GPAW/23.9.1-foss-2023a.lua
-rw-rw-r-- 1 cvmfs cvmfs 2215 Mar 14 21:45 x86_64/intel/skylake_avx512/modules/all/GPAW/23.9.1-foss-2023a.lua

aarch64/generic/software/GPAW/23.9.1-foss-2023a:
total 14
dr-xr-xr-x 2 cvmfs cvmfs 4096 Mar 14 21:43 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 14 21:44 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 14 21:43 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Mar 14 21:43 lib64 -> lib

x86_64/amd/zen2/software/GPAW/23.9.1-foss-2023a:
total 14
dr-xr-xr-x 2 cvmfs cvmfs 4096 Mar 14 21:35 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 14 21:35 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 14 21:34 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Mar 14 21:35 lib64 -> lib

x86_64/generic/software/GPAW/23.9.1-foss-2023a:
total 14
dr-xr-xr-x 2 cvmfs cvmfs 4096 Mar 14 21:32 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 14 21:33 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 14 21:31 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Mar 14 21:32 lib64 -> lib

x86_64/intel/broadwell/software/GPAW/23.9.1-foss-2023a:
total 14
dr-xr-xr-x 2 cvmfs cvmfs 4096 Mar 14 13:40 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 14 13:40 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 14 13:39 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Mar 14 13:40 lib64 -> lib

x86_64/intel/skylake_avx512/software/GPAW/23.9.1-foss-2023a:
total 14
dr-xr-xr-x 2 cvmfs cvmfs 4096 Mar 14 21:44 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 14 21:45 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Mar 14 21:44 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Mar 14 21:44 lib64 -> lib
```
</details>

**Review by trz42 — APPROVED** [review]
All tests succeeded. Thanks @TopRichard !

**Pull request merged**
