### PR TITLE
{2023.06}[GCCcore/2023a] grpcio V1.57.0

### PR DESCRIPTION
**Pull request by TopRichard**
Required for `check_missing_installation.sh`
Lic --> Apache Software License

```
missing packages :
grpcio/1.57.0-GCCcore-12.3.0
```

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
Job fails with :
```
cat: /hostsys/fs/cgroup/memory/slurm/uid_6757/job_220165/memory.limit_in_bytes: No such file or directory
ERROR: Failed to get the memory limit in bytes from the current cgroup
```
Those modifications were added lately to the software layer, will try on another arch.

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by TopRichard** [comment]
Failure :
```
build failed (first 300 chars): cmd "sed -i 's@/usr@/cvmfs/pilot.nessi.no/versions/2023.06/compat/linux/x86_64/usr@g' setup.py && export GRPC_PYTHON_BUILD_EXT_COMPILER_JOBS=4 && export GRPC_PYTHON_CFLAGS="-fvisibility=hidden -fno-wrapv -fno-exceptions" &&GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=True GRPC_PYTHON_BUILD_SYSTEM_ZLIB=True GRPC (took 1 min 26 secs)

```

**Comment by TopRichard** [comment]
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake

**Comment by TopRichard** [comment]
Checklist before starting deployment (setting bot:deploy label):

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by TopRichard** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x]  Check if the _SPDX license identifier_ is provided 
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI for the ingested tarballs have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)

<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; 
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/grpcio/1.57.0* \
        aarch64/generic/{software,modules/all}/grpcio/1.57.0*
  ```
  **log** 
```
-rw-r--r--. 1 cvmfs cvmfs 1861 Jun 18 12:34 aarch64/generic/modules/all/grpcio/1.57.0-GCCcore-12.3.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 1861 Jun 18 13:22 x86_64/amd/zen2/modules/all/grpcio/1.57.0-GCCcore-12.3.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 1860 Jun 18 13:21 x86_64/generic/modules/all/grpcio/1.57.0-GCCcore-12.3.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 1868 Jun 18 13:46 x86_64/intel/broadwell/modules/all/grpcio/1.57.0-GCCcore-12.3.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 1873 Jun 18 13:23 x86_64/intel/skylake_avx512/modules/all/grpcio/1.57.0-GCCcore-12.3.0.lua

aarch64/generic/software/grpcio/1.57.0-GCCcore-12.3.0:
total 10
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 18 12:34 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 18 12:29 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 18 12:34 lib64 -> lib

x86_64/amd/zen2/software/grpcio/1.57.0-GCCcore-12.3.0:
total 10
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 18 13:22 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 18 13:16 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 18 13:22 lib64 -> lib

x86_64/generic/software/grpcio/1.57.0-GCCcore-12.3.0:
total 10
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 18 13:21 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 18 13:15 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 18 13:21 lib64 -> lib

x86_64/intel/broadwell/software/grpcio/1.57.0-GCCcore-12.3.0:
total 10
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 18 13:46 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 18 13:22 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 18 13:46 lib64 -> lib

x86_64/intel/skylake_avx512/software/grpcio/1.57.0-GCCcore-12.3.0:
total 10
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 18 13:23 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 18 13:18 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 18 13:23 lib64 -> lib

```
</details>

**Review by justadejavu — APPROVED** [review]
lgtm

**Pull request merged**
