### PR TITLE
Add OSU-Micro-Benchmarks/5.7.1 with GCC/10.3.0 to NESSI/2022.11

### PR DESCRIPTION
**Pull request by TopRichard**
Trying to add OSU-Micro-Benchmarks/5.7.1 with GCC/10.3.0 to NESSI/2022.11

### CODE REVIEW

**Comment by dajon** [comment]
- [x] did the builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
  - No eX3 build in last rebuild, but there are other successful zen2 builds. 
- [x] is the PR up-to-date with the target branch `nessi.no-2022.11-dev` in the repository (if not what are the differences)
- [x] are all requested changes sound (checking files changed on GitHub.com)
- [x] is/are the easyconfig/s being built included with the EB version used (if not why not)
- [x] were any changes needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Checklist for deployment
- [x] was at least one tarball for each architecture uploaded
- [x] was at least one tarball for each architecture staged
- [x] for each architecture **one and only one** tarball was approved (for `generic` the tarball built on the oldest architecture shall be ingested ... lower risk that `generic` build is not really `generic`)
  - we reject generic tarballs (https://github.com/NorESSI/staging/pull/116, https://github.com/NorESSI/staging/pull/117 and https://github.com/NorESSI/staging/pull/118)
- [ ] for each architecture **one and only one** tarball was ingested
- [ ] has the package become available via CernVM-FS for all architectures ingested
  ```
  ls /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/x86_64/{generic,amd/zen2,intel/[bsc]*}/modules/all/OSU-Micro-Benchmarks/5.7.1*
  ls /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/x86_64/{generic,amd/zen2,intel/[bsc]*}/software/OSU-Micro-Benchmarks/5.7.1*
  ```

**Review by trz42 — COMMENTED** [review]
Looks good. All architectures ingested except for generic.

~Before we can merge, the current `nessi.no-2022.11-dev` should be pulled into the PR.~

Or should we rather not update it AFTER what has been built is ingested? ... will check locally what the result of a merge would be, and if it looks ok, just merge it.

**Comment by trz42** [comment]
Locally tested merge looks good.

**Review by trz42 — APPROVED** [review]
All looking good.

**Pull request merged**
