### PR TITLE
Easyconfig that can extend EESSI

### PR DESCRIPTION
**Pull request by TopRichard**
Sync with EESSI (PR 371)

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
Changes in `EESSI-extend-2023.06-easybuild.eb` :
```
diff --git a/EESSI-extend-2023.06-easybuild.eb b/EESSI-extend-2023.06-easybuild.eb
index 76e9676..1d8362d 100644
--- a/EESSI-extend-2023.06-easybuild.eb
+++ b/EESSI-extend-2023.06-easybuild.eb
@@ -1,6 +1,6 @@
 easyblock = 'Bundle'
 
-name = 'EESSI-extend'
+name = 'NESSI-extend'
 version = '2023.06'
 # May have different ways to extend EESSI in future (manually, other tools,...)
 versionsuffix = '-easybuild'
@@ -80,55 +80,55 @@ working_dir = os.getenv("WORKING_DIR") or pathJoin("/tmp", os.getenv("USER"))
 -- Gather the EPREFIX to use as a sysroot
 sysroot = os.getenv("EESSI_EPREFIX")
 -- Use an installation prefix that we _should_ have write access to
-if (os.getenv("EESSI_CVMFS_INSTALL") ~= nil) then
+if (os.getenv("NESSI_CVMFS_INSTALL") ~= nil) then
   -- Make sure no other EESSI install environment variables are set
-  if ((os.getenv("EESSI_SITE_INSTALL") ~= nil) or (os.getenv("EESSI_PROJECT_INSTALL") ~= nil) or (os.getenv("EESSI_USER_INSTALL") ~= nil)) then
-    LmodError("You cannot use EESSI_CVMFS_INSTALL in combination with any other EESSI_*_INSTALL environment variables")
+  if ((os.getenv("NESSI_SITE_INSTALL") ~= nil) or (os.getenv("NESSI_PROJECT_INSTALL") ~= nil) or (os.getenv("NESSI_USER_INSTALL") ~= nil)) then
+    LmodError("You cannot use NESSI_CVMFS_INSTALL in combination with any other NESSI_*_INSTALL environment variables")
   end
   eessi_cvmfs_install = true
   easybuild_installpath = os.getenv("EESSI_SOFTWARE_PATH")
-elseif (os.getenv("EESSI_SITE_INSTALL") ~= nil) then
+elseif (os.getenv("NESSI_SITE_INSTALL") ~= nil) then
   -- Make sure no other EESSI install environment variables are set
-  if ((os.getenv("EESSI_PROJECT_INSTALL") ~= nil) or (os.getenv("EESSI_USER_INSTALL") ~= nil)) then
-    LmodError("You cannot use EESSI_SITE_INSTALL in combination with any other EESSI_*_INSTALL environment variables")
+  if ((os.getenv("NESSI_PROJECT_INSTALL") ~= nil) or (os.getenv("NESSI_USER_INSTALL") ~= nil)) then
+    LmodError("You cannot use NESSI_SITE_INSTALL in combination with any other NESSI_*_INSTALL environment variables")
   end
   easybuild_installpath = string.gsub(os.getenv("EESSI_SOFTWARE_PATH"), 'versions', 'host_injections')
 else
   -- Deal with user and project installs
-  project_install = os.getenv("EESSI_PROJECT_INSTALL")
+  project_install = os.getenv("NESSI_PROJECT_INSTALL")
   project_modulepath = nil
   if (project_install ~= nil) then
     -- Check the folder exists
     if not isDir(project_install) then
-      LmodError("The location of EESSI_PROJECT_INSTALL (" .. project_install .. ") does not exist or is not a folder")
+      LmodError("The location of NESSI_PROJECT_INSTALL (" .. project_install .. ") does not exist or is not a folder")
     end
     if (mode() == "load") then
-      LmodMessage("Configuring for use of EESSI_PROJECT_INSTALL under " .. project_install)
+      LmodMessage("Configuring for use of NESSI_PROJECT_INSTALL under " .. project_install)
     end
     easybuild_installpath = string.gsub(os.getenv("EESSI_SOFTWARE_PATH"), os.getenv("EESSI_CVMFS_REPO"), project_install)
     project_modulepath = pathJoin(easybuild_installpath, 'modules', 'all')
   end
-  user_install = os.getenv("EESSI_USER_INSTALL")
+  user_install = os.getenv("NESSI_USER_INSTALL")
   user_modulepath = nil
   if (user_install ~= nil) then
     -- Check the folder exists
     if not isDir(user_install) then
-      LmodError("The location of EESSI_USER_INSTALL (" .. user_install .. ") does not exist or is not a folder")
+      LmodError("The location of NESSI_USER_INSTALL (" .. user_install .. ") does not exist or is not a folder")
     end
   elseif (user_install == nil) and (project_install == nil) then
     -- No need to check for existence when we use a HOME subdir
-    user_install = pathJoin(os.getenv("HOME"), "eessi")
+    user_install = pathJoin(os.getenv("HOME"), "nessi")
   end
   if (user_install ~= nil) then
     if (mode() == "load") then
-      LmodMessage("Configuring for use of EESSI_USER_INSTALL under " .. user_install)
+      LmodMessage("Configuring for use of NESSI_USER_INSTALL under " .. user_install)
     end
     easybuild_installpath = string.gsub(os.getenv("EESSI_SOFTWARE_PATH"), os.getenv("EESSI_CVMFS_REPO"), user_install)
     user_modulepath = pathJoin(easybuild_installpath, 'modules', 'all')
   end
 end
 if (mode() == "load") then
-  LmodMessage("-- To create installations for EESSI, you _must_ have write permissions to " .. easybuild_installpath)
+  LmodMessage("-- To create installations for NESSI, you _must_ have write permissions to " .. easybuild_installpath)
   -- Advise them to reuse sources
   if (os.getenv("EASYBUILD_SOURCEPATH") == nil) then
     LmodMessage("-- You may wish to configure a sources directory for EasyBuild (for example, via setting the environment variable EASYBUILD_SOURCEPATH) to allow you to reuse existing sources for packages.")
```

**Comment by trz42** [comment]
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb10 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
Checklist before starting deployment (setting `bot:deploy` label): 

- [x]  Check if the _SPDX license identifier_ is provided 
  - all provided via repository
- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
  - provided via this repository, it is very specific to the software stack itself 
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each staged tarball was a PR for approval/rejection opened
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bs]*}/{software,modules/all}/NESSI-extend/2023.06-easybuild* \
        aarch64/generic/{software,modules/all}/NESSI-extend/2023.06-easybuild*
  ```
  **log**
```
-rw-r--r--. 1 cvmfs cvmfs 9625 May  8 20:02 aarch64/generic/modules/all/NESSI-extend/2023.06-easybuild.lua
-rw-rw-r--. 1 cvmfs cvmfs 9620 May  8 20:08 x86_64/amd/zen2/modules/all/NESSI-extend/2023.06-easybuild.lua
-rw-rw-r--. 1 cvmfs cvmfs 9619 May  8 20:08 x86_64/generic/modules/all/NESSI-extend/2023.06-easybuild.lua
-rw-rw-r--. 1 cvmfs cvmfs 9627 May  8 20:04 x86_64/intel/broadwell/modules/all/NESSI-extend/2023.06-easybuild.lua
-rw-rw-r--. 1 cvmfs cvmfs 9632 May  8 20:04 x86_64/intel/skylake_avx512/modules/all/NESSI-extend/2023.06-easybuild.lua

aarch64/generic/software/NESSI-extend/2023.06-easybuild:
total 5
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May  8 20:02 easybuild

x86_64/amd/zen2/software/NESSI-extend/2023.06-easybuild:
total 5
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May  8 20:08 easybuild

x86_64/generic/software/NESSI-extend/2023.06-easybuild:
total 5
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May  8 20:08 easybuild

x86_64/intel/broadwell/software/NESSI-extend/2023.06-easybuild:
total 5
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May  8 20:04 easybuild

x86_64/intel/skylake_avx512/software/NESSI-extend/2023.06-easybuild:
total 5
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May  8 20:04 easybuild 
```
</details>

**Review by trz42 — APPROVED** [review]
All done. Not an easy PR. Thanks @TopRichard !

**Comment by trz42** [comment]
INGEST again to undo #363 

Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [ ] at least one tarball for each architecture has been staged
- [ ] for each staged tarball was a PR for approval/rejection opened
- [ ] for each architecture **one and only one** tarball has been approved
- [ ] for each architecture **one and only one** tarball was ingested
- [ ] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [ ] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bs]*}/{software,modules/all}/NESSI-extend/2023.06-easybuild* \
        aarch64/generic/{software,modules/all}/NESSI-extend/2023.06-easybuild*
  ```
  **log**
```
 
```
</details>

**Pull request merged**
