### PR TITLE
{2023.06}[foss/2023b] CDO v2.2.2

### PR DESCRIPTION
**Pull request by trz42**
Syn NESSI with EESSI (PR 492)

SPDX license identifier: `BSD-3-Clause`

Missing packages:
```
8 out of 52 required modules missing:

* JasPer/4.0.0-GCCcore-13.2.0 (JasPer-4.0.0-GCCcore-13.2.0.eb)
* googletest/1.14.0-GCCcore-13.2.0 (googletest-1.14.0-GCCcore-13.2.0.eb)
* UDUNITS/2.2.28-GCCcore-13.2.0 (UDUNITS-2.2.28-GCCcore-13.2.0.eb)
* libaec/1.0.6-GCCcore-13.2.0 (libaec-1.0.6-GCCcore-13.2.0.eb)
* nlohmann_json/3.11.3-GCCcore-13.2.0 (nlohmann_json-3.11.3-GCCcore-13.2.0.eb)
* PROJ/9.3.1-GCCcore-13.2.0 (PROJ-9.3.1-GCCcore-13.2.0.eb)
* ecCodes/2.31.0-gompi-2023b (ecCodes-2.31.0-gompi-2023b.eb)
* CDO/2.2.2-gompi-2023b (CDO-2.2.2-gompi-2023b.eb)
```

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb10 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
Checklist before starting deployment (setting `bot:deploy` label): 

- [x]  Check if the _SPDX license identifier_ is provided 
- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each staged tarball was a PR for approval/rejection opened
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/CDO/2.2.2-gompi-2023b* \
        aarch64/generic/{software,modules/all}/CDO/2.2.2-gompi-2023b*
  ```
  **log**
```
-rw-r--r--. 1 cvmfs cvmfs 1987 Apr 15 00:42 aarch64/generic/modules/all/CDO/2.2.2-gompi-2023b.lua
-rw-rw-r--. 1 cvmfs cvmfs 1987 Apr 15 00:28 x86_64/amd/zen2/modules/all/CDO/2.2.2-gompi-2023b.lua
-rw-rw-r--. 1 cvmfs cvmfs 1986 Apr 15 00:24 x86_64/generic/modules/all/CDO/2.2.2-gompi-2023b.lua
-rw-rw-r--. 1 cvmfs cvmfs 1994 Apr 15 00:19 x86_64/intel/broadwell/modules/all/CDO/2.2.2-gompi-2023b.lua
-rw-rw-r--. 1 cvmfs cvmfs 1999 Apr 15 00:25 x86_64/intel/skylake_avx512/modules/all/CDO/2.2.2-gompi-2023b.lua

aarch64/generic/software/CDO/2.2.2-gompi-2023b:
total 19
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Apr 15 00:42 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 15 00:42 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Apr 15 00:42 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Apr 15 00:42 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 15 00:42 lib64 -> lib

x86_64/amd/zen2/software/CDO/2.2.2-gompi-2023b:
total 19
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Apr 15 00:28 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 15 00:28 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Apr 15 00:28 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Apr 15 00:28 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 15 00:28 lib64 -> lib

x86_64/generic/software/CDO/2.2.2-gompi-2023b:
total 19
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Apr 15 00:24 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 15 00:24 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Apr 15 00:24 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Apr 15 00:24 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 15 00:24 lib64 -> lib

x86_64/intel/broadwell/software/CDO/2.2.2-gompi-2023b:
total 19
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Apr 15 00:19 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 15 00:19 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Apr 15 00:19 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Apr 15 00:19 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 15 00:19 lib64 -> lib

x86_64/intel/skylake_avx512/software/CDO/2.2.2-gompi-2023b:
total 19
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Apr 15 00:25 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 15 00:26 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Apr 15 00:25 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Apr 15 00:25 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 15 00:25 lib64 -> lib 
```
</details>

**Review by poksumdo — APPROVED** [review]
+1

**Pull request merged**
