### PR TITLE
{2023.06}[system] CUDA v12.1.1

### PR DESCRIPTION
**Pull request by trz42**
Adding CUDA to NESSI. Follows EESSI PR https://github.com/EESSI/software-layer/pull/434

License: NVIDIA

Missing packages:
```
1 out of 1 required modules missing:

* CUDA/12.1.1 (CUDA-12.1.1.eb)
```

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb10 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by trz42** [comment]
Checklist before starting deployment (setting `bot:deploy` label): 

- [ ]  Check if the _SPDX license identifier_ is provided 
- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each staged tarball was a PR for approval/rejection opened
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/CUDA/12.1.1* \
        aarch64/generic/{software,modules/all}/CUDA/12.1.1*
  ```
  **log**
```
-rw-r--r--.  1 cvmfs cvmfs 2120 May  4 20:09 aarch64/generic/modules/all/CUDA/12.1.1.lua
-rw-rw-r--.  1 cvmfs cvmfs 2120 May  4 20:14 x86_64/amd/zen2/modules/all/CUDA/12.1.1.lua
-rw-rw-r--.  1 cvmfs cvmfs 2116 May  4 20:14 x86_64/generic/modules/all/CUDA/12.1.1.lua
-rw-rw-r--.  1 cvmfs cvmfs 2148 May  4 20:11 x86_64/intel/broadwell/modules/all/CUDA/12.1.1.lua
-rw-rw-r--.  1 cvmfs cvmfs 2168 May  4 20:10 x86_64/intel/skylake_avx512/modules/all/CUDA/12.1.1.lua

aarch64/generic/software/CUDA/12.1.1:
total 122
dr-xr-xr-x. 3 cvmfs cvmfs  4096 May  4 20:09 bin
dr-xr-xr-x. 4 cvmfs cvmfs  4096 May  4 20:09 compute-sanitizer
lrwxrwxrwx. 1 cvmfs cvmfs   102 May  4 20:09 DOCS -> /cvmfs/pilot.nessi.no/host_injections/2023.06/software/linux/aarch64/generic/software/CUDA/12.1.1/DOCS
dr-xr-xr-x. 3 cvmfs cvmfs  4096 May  4 20:09 easybuild
-r--r--r--. 1 cvmfs cvmfs 61498 May  4 20:09 EULA.txt
dr-xr-xr-x. 4 cvmfs cvmfs  4096 May  4 20:08 extras
lrwxrwxrwx. 1 cvmfs cvmfs    26 May  4 20:09 include -> targets/sbsa-linux/include
lrwxrwxrwx. 1 cvmfs cvmfs     5 May  4 20:09 lib -> lib64
lrwxrwxrwx. 1 cvmfs cvmfs    22 May  4 20:09 lib64 -> targets/sbsa-linux/lib
dr-xr-xr-x. 7 cvmfs cvmfs  4096 May  4 20:09 nsight-compute-2023.1.1
dr-xr-xr-x. 6 cvmfs cvmfs  4096 May  4 20:09 nsight-systems-2023.1.2
dr-xr-xr-x. 3 cvmfs cvmfs  4096 May  4 20:07 nvml
dr-xr-xr-x. 7 cvmfs cvmfs  4096 May  4 20:09 nvvm
dr-xr-xr-x. 2 cvmfs cvmfs  4096 May  4 20:09 pkgconfig
-r--r--r--. 1 cvmfs cvmfs   524 May  4 20:09 README
dr-xr-xr-x. 3 cvmfs cvmfs  4096 May  4 20:08 share
dr-xr-xr-x. 3 cvmfs cvmfs  4096 May  4 20:09 stubs
dr-xr-xr-x. 3 cvmfs cvmfs  4096 May  4 20:07 targets
dr-xr-xr-x. 2 cvmfs cvmfs  4096 May  4 20:09 tools

x86_64/amd/zen2/software/CUDA/12.1.1:
total 145
dr-xr-xr-x. 3 cvmfs cvmfs  4096 May  4 20:14 bin
dr-xr-xr-x. 5 cvmfs cvmfs  4096 May  4 20:14 compute-sanitizer
lrwxrwxrwx. 1 cvmfs cvmfs   102 May  4 20:14 DOCS -> /cvmfs/pilot.nessi.no/host_injections/2023.06/software/linux/x86_64/amd/zen2/software/CUDA/12.1.1/DOCS
dr-xr-xr-x. 3 cvmfs cvmfs  4096 May  4 20:14 easybuild
-r--r--r--. 1 cvmfs cvmfs 61498 May  4 20:14 EULA.txt
dr-xr-xr-x. 5 cvmfs cvmfs  4096 May  4 20:14 extras
dr-xr-xr-x. 6 cvmfs cvmfs  4096 May  4 20:13 gds
dr-xr-xr-x. 2 cvmfs cvmfs  4096 May  4 20:14 gds-12.1
lrwxrwxrwx. 1 cvmfs cvmfs    28 May  4 20:14 include -> targets/x86_64-linux/include
lrwxrwxrwx. 1 cvmfs cvmfs     5 May  4 20:14 lib -> lib64
lrwxrwxrwx. 1 cvmfs cvmfs    24 May  4 20:14 lib64 -> targets/x86_64-linux/lib
dr-xr-xr-x. 7 cvmfs cvmfs  4096 May  4 20:14 libnvvp
dr-xr-xr-x. 7 cvmfs cvmfs  4096 May  4 20:14 nsight-compute-2023.1.1
dr-xr-xr-x. 2 cvmfs cvmfs  4096 May  4 20:14 nsightee_plugins
dr-xr-xr-x. 6 cvmfs cvmfs  4096 May  4 20:13 nsight-systems-2023.1.2
dr-xr-xr-x. 3 cvmfs cvmfs  4096 May  4 20:13 nvml
dr-xr-xr-x. 7 cvmfs cvmfs  4096 May  4 20:14 nvvm
dr-xr-xr-x. 2 cvmfs cvmfs  4096 May  4 20:14 pkgconfig
-r--r--r--. 1 cvmfs cvmfs   524 May  4 20:14 README
dr-xr-xr-x. 3 cvmfs cvmfs  4096 May  4 20:13 share
dr-xr-xr-x. 2 cvmfs cvmfs  4096 May  4 20:14 src
dr-xr-xr-x. 3 cvmfs cvmfs  4096 May  4 20:14 stubs
dr-xr-xr-x. 3 cvmfs cvmfs  4096 May  4 20:13 targets
dr-xr-xr-x. 2 cvmfs cvmfs  4096 May  4 20:14 tools
lrwxrwxrwx. 1 cvmfs cvmfs   110 May  4 20:14 version.json -> /cvmfs/pilot.nessi.no/host_injections/2023.06/software/linux/x86_64/amd/zen2/software/CUDA/12.1.1/version.json

x86_64/generic/software/CUDA/12.1.1:
total 145
dr-xr-xr-x. 3 cvmfs cvmfs  4096 May  4 20:14 bin
dr-xr-xr-x. 5 cvmfs cvmfs  4096 May  4 20:14 compute-sanitizer
lrwxrwxrwx. 1 cvmfs cvmfs   101 May  4 20:14 DOCS -> /cvmfs/pilot.nessi.no/host_injections/2023.06/software/linux/x86_64/generic/software/CUDA/12.1.1/DOCS
dr-xr-xr-x. 3 cvmfs cvmfs  4096 May  4 20:14 easybuild
-r--r--r--. 1 cvmfs cvmfs 61498 May  4 20:14 EULA.txt
dr-xr-xr-x. 5 cvmfs cvmfs  4096 May  4 20:14 extras
dr-xr-xr-x. 6 cvmfs cvmfs  4096 May  4 20:13 gds
dr-xr-xr-x. 2 cvmfs cvmfs  4096 May  4 20:14 gds-12.1
lrwxrwxrwx. 1 cvmfs cvmfs    28 May  4 20:14 include -> targets/x86_64-linux/include
lrwxrwxrwx. 1 cvmfs cvmfs     5 May  4 20:14 lib -> lib64
lrwxrwxrwx. 1 cvmfs cvmfs    24 May  4 20:14 lib64 -> targets/x86_64-linux/lib
dr-xr-xr-x. 7 cvmfs cvmfs  4096 May  4 20:14 libnvvp
dr-xr-xr-x. 7 cvmfs cvmfs  4096 May  4 20:14 nsight-compute-2023.1.1
dr-xr-xr-x. 2 cvmfs cvmfs  4096 May  4 20:14 nsightee_plugins
dr-xr-xr-x. 6 cvmfs cvmfs  4096 May  4 20:13 nsight-systems-2023.1.2
dr-xr-xr-x. 3 cvmfs cvmfs  4096 May  4 20:12 nvml
dr-xr-xr-x. 7 cvmfs cvmfs  4096 May  4 20:14 nvvm
dr-xr-xr-x. 2 cvmfs cvmfs  4096 May  4 20:14 pkgconfig
-r--r--r--. 1 cvmfs cvmfs   524 May  4 20:14 README
dr-xr-xr-x. 3 cvmfs cvmfs  4096 May  4 20:13 share
dr-xr-xr-x. 2 cvmfs cvmfs  4096 May  4 20:14 src
dr-xr-xr-x. 3 cvmfs cvmfs  4096 May  4 20:14 stubs
dr-xr-xr-x. 3 cvmfs cvmfs  4096 May  4 20:12 targets
dr-xr-xr-x. 2 cvmfs cvmfs  4096 May  4 20:14 tools
lrwxrwxrwx. 1 cvmfs cvmfs   109 May  4 20:14 version.json -> /cvmfs/pilot.nessi.no/host_injections/2023.06/software/linux/x86_64/generic/software/CUDA/12.1.1/version.json

x86_64/intel/broadwell/software/CUDA/12.1.1:
total 145
dr-xr-xr-x. 3 cvmfs cvmfs  4096 May  4 20:11 bin
dr-xr-xr-x. 5 cvmfs cvmfs  4096 May  4 20:10 compute-sanitizer
lrwxrwxrwx. 1 cvmfs cvmfs   109 May  4 20:10 DOCS -> /cvmfs/pilot.nessi.no/host_injections/2023.06/software/linux/x86_64/intel/broadwell/software/CUDA/12.1.1/DOCS
dr-xr-xr-x. 3 cvmfs cvmfs  4096 May  4 20:11 easybuild
-r--r--r--. 1 cvmfs cvmfs 61498 May  4 20:10 EULA.txt
dr-xr-xr-x. 5 cvmfs cvmfs  4096 May  4 20:10 extras
dr-xr-xr-x. 6 cvmfs cvmfs  4096 May  4 20:09 gds
dr-xr-xr-x. 2 cvmfs cvmfs  4096 May  4 20:11 gds-12.1
lrwxrwxrwx. 1 cvmfs cvmfs    28 May  4 20:10 include -> targets/x86_64-linux/include
lrwxrwxrwx. 1 cvmfs cvmfs     5 May  4 20:10 lib -> lib64
lrwxrwxrwx. 1 cvmfs cvmfs    24 May  4 20:10 lib64 -> targets/x86_64-linux/lib
dr-xr-xr-x. 7 cvmfs cvmfs  4096 May  4 20:11 libnvvp
dr-xr-xr-x. 7 cvmfs cvmfs  4096 May  4 20:10 nsight-compute-2023.1.1
dr-xr-xr-x. 2 cvmfs cvmfs  4096 May  4 20:11 nsightee_plugins
dr-xr-xr-x. 6 cvmfs cvmfs  4096 May  4 20:10 nsight-systems-2023.1.2
dr-xr-xr-x. 3 cvmfs cvmfs  4096 May  4 20:08 nvml
dr-xr-xr-x. 7 cvmfs cvmfs  4096 May  4 20:10 nvvm
dr-xr-xr-x. 2 cvmfs cvmfs  4096 May  4 20:11 pkgconfig
-r--r--r--. 1 cvmfs cvmfs   524 May  4 20:10 README
dr-xr-xr-x. 3 cvmfs cvmfs  4096 May  4 20:10 share
dr-xr-xr-x. 2 cvmfs cvmfs  4096 May  4 20:11 src
dr-xr-xr-x. 3 cvmfs cvmfs  4096 May  4 20:10 stubs
dr-xr-xr-x. 3 cvmfs cvmfs  4096 May  4 20:08 targets
dr-xr-xr-x. 2 cvmfs cvmfs  4096 May  4 20:10 tools
lrwxrwxrwx. 1 cvmfs cvmfs   117 May  4 20:10 version.json -> /cvmfs/pilot.nessi.no/host_injections/2023.06/software/linux/x86_64/intel/broadwell/software/CUDA/12.1.1/version.json

x86_64/intel/skylake_avx512/software/CUDA/12.1.1:
total 145
dr-xr-xr-x. 3 cvmfs cvmfs  4096 May  4 20:10 bin
dr-xr-xr-x. 5 cvmfs cvmfs  4096 May  4 20:10 compute-sanitizer
lrwxrwxrwx. 1 cvmfs cvmfs   114 May  4 20:10 DOCS -> /cvmfs/pilot.nessi.no/host_injections/2023.06/software/linux/x86_64/intel/skylake_avx512/software/CUDA/12.1.1/DOCS
dr-xr-xr-x. 3 cvmfs cvmfs  4096 May  4 20:11 easybuild
-r--r--r--. 1 cvmfs cvmfs 61498 May  4 20:10 EULA.txt
dr-xr-xr-x. 5 cvmfs cvmfs  4096 May  4 20:10 extras
dr-xr-xr-x. 6 cvmfs cvmfs  4096 May  4 20:09 gds
dr-xr-xr-x. 2 cvmfs cvmfs  4096 May  4 20:10 gds-12.1
lrwxrwxrwx. 1 cvmfs cvmfs    28 May  4 20:10 include -> targets/x86_64-linux/include
lrwxrwxrwx. 1 cvmfs cvmfs     5 May  4 20:10 lib -> lib64
lrwxrwxrwx. 1 cvmfs cvmfs    24 May  4 20:10 lib64 -> targets/x86_64-linux/lib
dr-xr-xr-x. 7 cvmfs cvmfs  4096 May  4 20:10 libnvvp
dr-xr-xr-x. 7 cvmfs cvmfs  4096 May  4 20:10 nsight-compute-2023.1.1
dr-xr-xr-x. 2 cvmfs cvmfs  4096 May  4 20:10 nsightee_plugins
dr-xr-xr-x. 6 cvmfs cvmfs  4096 May  4 20:10 nsight-systems-2023.1.2
dr-xr-xr-x. 3 cvmfs cvmfs  4096 May  4 20:09 nvml
dr-xr-xr-x. 7 cvmfs cvmfs  4096 May  4 20:10 nvvm
dr-xr-xr-x. 2 cvmfs cvmfs  4096 May  4 20:10 pkgconfig
-r--r--r--. 1 cvmfs cvmfs   524 May  4 20:10 README
dr-xr-xr-x. 3 cvmfs cvmfs  4096 May  4 20:09 share
dr-xr-xr-x. 2 cvmfs cvmfs  4096 May  4 20:10 src
dr-xr-xr-x. 3 cvmfs cvmfs  4096 May  4 20:10 stubs
dr-xr-xr-x. 3 cvmfs cvmfs  4096 May  4 20:09 targets
dr-xr-xr-x. 2 cvmfs cvmfs  4096 May  4 20:10 tools
lrwxrwxrwx. 1 cvmfs cvmfs   122 May  4 20:10 version.json -> /cvmfs/pilot.nessi.no/host_injections/2023.06/software/linux/x86_64/intel/skylake_avx512/software/CUDA/12.1.1/version.json 
```
</details>

**Review by poksumdo — APPROVED** [review]
it's a start

**Pull request merged**
