### PR TITLE
{2023.06}[foss/2023b] Qt5 v5.15.13

### PR DESCRIPTION
**Pull request by trz42**
Sync NESSI with EESSI (PR 462).

SPDX license identifier: `LGPL-3.0-or-later`

Missing packages:
```
9 out of 57 required modules missing:

* re2c/3.1-GCCcore-13.2.0 (re2c-3.1-GCCcore-13.2.0.eb)
* double-conversion/3.3.0-GCCcore-13.2.0 (double-conversion-3.3.0-GCCcore-13.2.0.eb)
* graphite2/1.3.14-GCCcore-13.2.0 (graphite2-1.3.14-GCCcore-13.2.0.eb)
* snappy/1.1.10-GCCcore-13.2.0 (snappy-1.1.10-GCCcore-13.2.0.eb)
* NSPR/4.35-GCCcore-13.2.0 (NSPR-4.35-GCCcore-13.2.0.eb)
* NSS/3.94-GCCcore-13.2.0 (NSS-3.94-GCCcore-13.2.0.eb)
* nodejs/20.9.0-GCCcore-13.2.0 (nodejs-20.9.0-GCCcore-13.2.0.eb)
* libGLU/9.0.3-GCCcore-13.2.0 (libGLU-9.0.3-GCCcore-13.2.0.eb)
* Qt5/5.15.13-GCCcore-13.2.0 (Qt5-5.15.13-GCCcore-13.2.0.eb)
```

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb10 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
Just retrying with `deb11` container

bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by trz42** [comment]
Rebuild after #335 

bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb10 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
Rebuild after https://github.com/NorESSI/software-layer/pull/337 and #338

bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb10 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
Rebuild after #340

bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb10 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
Rebuild after https://github.com/NorESSI/software-layer/pull/340 and fixing merge conflict

bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb10 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by trz42** [comment]
Try building it on `AWS` instead of `eX3`...

bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by trz42** [comment]
Complete rebuild...

bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
Checklist before starting deployment (setting `bot:deploy` label): 

- [x]  Check if the _SPDX license identifier_ is provided 
- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
  - built `aarch64/generic` on AWS (instead of `eX3` where it kept failing) 
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each staged tarball was a PR for approval/rejection opened
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```bash
BASE_DIR=/cvmfs/pilot.nessi.no/versions/2023.06/software/linux \
ARCHS=() \
ARCHS+=("aarch64/generic") ; \
ARCHS+=("x86_64/generic") ; \
ARCHS+=("x86_64/amd/zen2") ; \
ARCHS+=("x86_64/intel/broadwell") ; \
ARCHS+=("x86_64/intel/skylake_avx512") ; \
for arch in "${ARCHS[@]}"; do \
ls -l \
  ${BASE_DIR}/${arch}/{software,modules/all}/Qt5/5.15.13-GCCcore-13.2.0* ; \
done ; \
ls -l \
  ${BASE_DIR}/../../init/easybuild/eb_hooks.py
  ```
  **log - BEFORE ingestion**
```bash
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/software/Qt5/5.15.13-GCCcore-13.2.0*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/modules/all/Qt5/5.15.13-GCCcore-13.2.0*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/software/Qt5/5.15.13-GCCcore-13.2.0*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/modules/all/Qt5/5.15.13-GCCcore-13.2.0*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/software/Qt5/5.15.13-GCCcore-13.2.0*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all/Qt5/5.15.13-GCCcore-13.2.0*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/software/Qt5/5.15.13-GCCcore-13.2.0*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/modules/all/Qt5/5.15.13-GCCcore-13.2.0*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/Qt5/5.15.13-GCCcore-13.2.0*': No such file or directory
ls: cannot access '/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/modules/all/Qt5/5.15.13-GCCcore-13.2.0*': No such file or directory
-rw-rw-r-- 1 cvmfs cvmfs 43825 May 30 11:45 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/../../init/easybuild/eb_hooks.py 
```
  **log - AFTER ingestion**
```bash
-rw-rw-r--  1 cvmfs cvmfs 2732 Jun  2 21:49 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/modules/all/Qt5/5.15.13-GCCcore-13.2.0.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/software/Qt5/5.15.13-GCCcore-13.2.0:
total 59
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jun  2 21:47 bin
dr-xr-xr-x  4 cvmfs cvmfs 4096 Jun  2 21:42 doc
dr-xr-xr-x  3 cvmfs cvmfs 4096 Jun  2 21:49 easybuild
dr-xr-xr-x 53 cvmfs cvmfs 4096 Jun  2 21:48 examples
dr-xr-xr-x 98 cvmfs cvmfs 4096 Jun  2 21:48 include
dr-xr-xr-x  5 cvmfs cvmfs 4096 Jun  2 21:48 lib
lrwxrwxrwx  1 cvmfs cvmfs    3 Jun  2 21:48 lib64 -> lib
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jun  2 21:47 libexec
dr-xr-xr-x 76 cvmfs cvmfs 4096 Jun  2 21:43 mkspecs
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jun  2 21:47 phrasebooks
dr-xr-xr-x 28 cvmfs cvmfs 4096 Jun  2 21:48 plugins
dr-xr-xr-x 25 cvmfs cvmfs 4096 Jun  2 21:48 qml
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jun  2 21:47 resources
dr-xr-xr-x  3 cvmfs cvmfs 4096 Jun  2 21:48 translations
-rw-rw-r--  1 cvmfs cvmfs 2731 Jun  2 22:59 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/modules/all/Qt5/5.15.13-GCCcore-13.2.0.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/software/Qt5/5.15.13-GCCcore-13.2.0:
total 59
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jun  2 22:58 bin
dr-xr-xr-x  4 cvmfs cvmfs 4096 Jun  2 22:52 doc
dr-xr-xr-x  3 cvmfs cvmfs 4096 Jun  2 23:00 easybuild
dr-xr-xr-x 53 cvmfs cvmfs 4096 Jun  2 22:58 examples
dr-xr-xr-x 98 cvmfs cvmfs 4096 Jun  2 22:58 include
dr-xr-xr-x  5 cvmfs cvmfs 4096 Jun  2 22:58 lib
lrwxrwxrwx  1 cvmfs cvmfs    3 Jun  2 22:58 lib64 -> lib
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jun  2 22:58 libexec
dr-xr-xr-x 76 cvmfs cvmfs 4096 Jun  2 22:52 mkspecs
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jun  2 22:57 phrasebooks
dr-xr-xr-x 28 cvmfs cvmfs 4096 Jun  2 22:58 plugins
dr-xr-xr-x 25 cvmfs cvmfs 4096 Jun  2 22:58 qml
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jun  2 22:58 resources
dr-xr-xr-x  3 cvmfs cvmfs 4096 Jun  2 22:58 translations
-rw-rw-r--  1 cvmfs cvmfs 2732 Jun  2 22:30 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all/Qt5/5.15.13-GCCcore-13.2.0.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/software/Qt5/5.15.13-GCCcore-13.2.0:
total 59
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jun  2 22:28 bin
dr-xr-xr-x  4 cvmfs cvmfs 4096 Jun  2 22:20 doc
dr-xr-xr-x  3 cvmfs cvmfs 4096 Jun  2 22:30 easybuild
dr-xr-xr-x 53 cvmfs cvmfs 4096 Jun  2 22:29 examples
dr-xr-xr-x 98 cvmfs cvmfs 4096 Jun  2 22:28 include
dr-xr-xr-x  5 cvmfs cvmfs 4096 Jun  2 22:28 lib
lrwxrwxrwx  1 cvmfs cvmfs    3 Jun  2 22:29 lib64 -> lib
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jun  2 22:28 libexec
dr-xr-xr-x 76 cvmfs cvmfs 4096 Jun  2 22:20 mkspecs
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jun  2 22:27 phrasebooks
dr-xr-xr-x 28 cvmfs cvmfs 4096 Jun  2 22:28 plugins
dr-xr-xr-x 25 cvmfs cvmfs 4096 Jun  2 22:28 qml
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jun  2 22:28 resources
dr-xr-xr-x  3 cvmfs cvmfs 4096 Jun  2 22:29 translations
-rw-rw-r--  1 cvmfs cvmfs 2739 Jun  2 22:46 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/modules/all/Qt5/5.15.13-GCCcore-13.2.0.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/software/Qt5/5.15.13-GCCcore-13.2.0:
total 59
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jun  2 22:45 bin
dr-xr-xr-x  4 cvmfs cvmfs 4096 Jun  2 22:40 doc
dr-xr-xr-x  3 cvmfs cvmfs 4096 Jun  2 22:47 easybuild
dr-xr-xr-x 53 cvmfs cvmfs 4096 Jun  2 22:46 examples
dr-xr-xr-x 98 cvmfs cvmfs 4096 Jun  2 22:45 include
dr-xr-xr-x  5 cvmfs cvmfs 4096 Jun  2 22:45 lib
lrwxrwxrwx  1 cvmfs cvmfs    3 Jun  2 22:46 lib64 -> lib
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jun  2 22:45 libexec
dr-xr-xr-x 76 cvmfs cvmfs 4096 Jun  2 22:40 mkspecs
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jun  2 22:45 phrasebooks
dr-xr-xr-x 28 cvmfs cvmfs 4096 Jun  2 22:45 plugins
dr-xr-xr-x 25 cvmfs cvmfs 4096 Jun  2 22:45 qml
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jun  2 22:45 resources
dr-xr-xr-x  3 cvmfs cvmfs 4096 Jun  2 22:46 translations
-rw-rw-r--  1 cvmfs cvmfs 2744 Jun  2 23:21 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/modules/all/Qt5/5.15.13-GCCcore-13.2.0.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/Qt5/5.15.13-GCCcore-13.2.0:
total 59
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jun  2 23:19 bin
dr-xr-xr-x  4 cvmfs cvmfs 4096 Jun  2 23:09 doc
dr-xr-xr-x  3 cvmfs cvmfs 4096 Jun  2 23:22 easybuild
dr-xr-xr-x 53 cvmfs cvmfs 4096 Jun  2 23:20 examples
dr-xr-xr-x 98 cvmfs cvmfs 4096 Jun  2 23:20 include
dr-xr-xr-x  5 cvmfs cvmfs 4096 Jun  2 23:20 lib
lrwxrwxrwx  1 cvmfs cvmfs    3 Jun  2 23:20 lib64 -> lib
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jun  2 23:19 libexec
dr-xr-xr-x 76 cvmfs cvmfs 4096 Jun  2 23:09 mkspecs
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jun  2 23:18 phrasebooks
dr-xr-xr-x 28 cvmfs cvmfs 4096 Jun  2 23:20 plugins
dr-xr-xr-x 25 cvmfs cvmfs 4096 Jun  2 23:20 qml
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jun  2 23:19 resources
dr-xr-xr-x  3 cvmfs cvmfs 4096 Jun  2 23:20 translations
-rw-rw-r-- 1 cvmfs cvmfs 45790 Jun  2 19:49 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/../../init/easybuild/eb_hooks.py 
```
</details>

**Comment by trz42** [comment]
Need to double-check and possibly fix contents of ingested `eb_hooks.py`. See diff below. Some changes need to be kept, some need to be dropped.
```diff
$ diff -u /cluster/projects/nn9992k/eb_hooks.py /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/../../init/easybuild/eb_hooks.py
--- /cluster/projects/nn9992k/eb_hooks.py	2024-06-02 23:56:06.000000000 +0200
+++ /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/../../init/easybuild/eb_hooks.py	2024-06-02 19:49:35.000000000 +0200
@@ -425,6 +425,29 @@
         raise EasyBuildError("OpenBLAS-specific hook triggered for non-OpenBLAS easyconfig?!")


+def pre_configure_hook_pytorch_add_cupti_libdir(self, *args, **kwargs):
+    """
+    Pre-configure hook for PyTorch: add directory $EESSI_SOFTWARE_PATH/software/CUDA/12.1.1/extras/CUPTI/lib64 to LIBRARY_PATH
+    """
+    if self.name == 'PyTorch':
+        if 'cudaver' in self.cfg.template_values and self.cfg.template_values['cudaver'] == '12.1.1':
+            _cudaver = self.cfg.template_values['cudaver']
+            print_msg("pre_configure_hook_pytorch_add_cupti_libdir: CUDA version: '%s'" % _cudaver)
+            _library_path = os.getenv('LIBRARY_PATH')
+            print_msg("pre_configure_hook_pytorch_add_cupti_libdir: library_path: '%s'", _library_path)
+            _eessi_software_path = os.getenv('EESSI_SOFTWARE_PATH')
+            print_msg("pre_configure_hook_pytorch_add_cupti_libdir: eessi_software_path: '%s'", _eessi_software_path)
+            _cupti_lib_dir = os.path.join(_eessi_software_path, 'software', 'CUDA', _cudaver, 'extras', 'CUPTI', 'lib64')
+            print_msg("pre_configure_hook_pytorch_add_cupti_libdir: cupti_lib_dir: '%s'", _cupti_lib_dir)
+            if _library_path:
+                env.setvar('LIBRARY_PATH', ':'.join([_library_path, _cupti_lib_dir]))
+            else:
+                env.setvar('LIBRARY_PATH', _cupti_lib_dir)
+            print_msg("pre_configure_hook_pytorch_add_cupti_libdir: LIBRARY_PATH: '%s'", os.getenv('LIBRARY_PATH'))
+    else:
+        raise EasyBuildError("PyTorch-specific hook triggered for non-PyTorch easyconfig?!")
+
+
 def pre_configure_hook_libfabric_disable_psm3_x86_64_generic(self, *args, **kwargs):
     """Add --disable-psm3 to libfabric configure options when building with --optarch=GENERIC on x86_64."""
     if self.name == 'libfabric':
@@ -560,6 +583,12 @@
     """
     if self.name == 'PyTorch' and self.version == '2.1.2' and get_cpu_architecture() == AARCH64:
         self.cfg['max_failed_tests'] = 10
+        if 'cudaver' in self.cfg.template_values and self.cfg.template_values['cudaver'] == '12.1.1':
+            _cudaver = self.cfg.template_values['cudaver']
+            _runtest = self.cfg['runtest']
+            self.cfg['runtest'] = _runtest.replace(
+                                      'PYTHONUNBUFFERED',
+                                      'PYTORCH_TEST_RUN_EVERYTHING_IN_SERIAL=1 PYTHONUNBUFFERED')


 def pre_single_extension_hook(ext, *args, **kwargs):
@@ -851,6 +880,7 @@
     'libfabric': pre_configure_hook_libfabric_disable_psm3_x86_64_generic,
     'MetaBAT': pre_configure_hook_metabat_filtered_zlib_dep,
     'OpenBLAS': pre_configure_hook_openblas_optarch_generic,
+    'PyTorch': pre_configure_hook_pytorch_add_cupti_libdir,
     'WRF': pre_configure_hook_wrf_aarch64,
     'at-spi2-core': pre_configure_hook_atspi2core_filter_ld_library_path,
 }
```

**Review by poksumdo — APPROVED** [review]
Finally.

**Pull request merged**
