### PR TITLE
{2023.06}[foss/2023b] Qt5 dependencies

### PR DESCRIPTION
**Pull request by trz42**
Sync NESSI with EESSI (all missing dependencies for #332)

SPDX license identifiers: just dependencies

Missing packages:
```
1 out of 10 required modules missing:

* re2c/3.1-GCCcore-13.2.0 (re2c-3.1-GCCcore-13.2.0.eb)

1 out of 7 required modules missing:

* double-conversion/3.3.0-GCCcore-13.2.0 (double-conversion-3.3.0-GCCcore-13.2.0.eb)

1 out of 7 required modules missing:

* graphite2/1.3.14-GCCcore-13.2.0 (graphite2-1.3.14-GCCcore-13.2.0.eb)

1 out of 7 required modules missing:

* snappy/1.1.10-GCCcore-13.2.0 (snappy-1.1.10-GCCcore-13.2.0.eb)

2 out of 4 required modules missing:

* NSPR/4.35-GCCcore-13.2.0 (NSPR-4.35-GCCcore-13.2.0.eb)
* NSS/3.94-GCCcore-13.2.0 (NSS-3.94-GCCcore-13.2.0.eb)

1 out of 11 required modules missing:

* nodejs/20.9.0-GCCcore-13.2.0 (nodejs-20.9.0-GCCcore-13.2.0.eb)

1 out of 37 required modules missing:

* libGLU/9.0.3-GCCcore-13.2.0 (libGLU-9.0.3-GCCcore-13.2.0.eb)
```

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb10 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by trz42** [comment]
Checklist before starting deployment (setting `bot:deploy` label): 

- [x]  Check if the _SPDX license identifier_ is provided 
- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each staged tarball was a PR for approval/rejection opened
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [ ] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
  - NOTE, just checked for one package being built (too many -> too large output) 
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/libGLU/9.0.3-GCCcore-13.2* \
        aarch64/generic/{software,modules/all}/libGLU/9.0.3-GCCcore-13.2*
  ```
  **log**
```
-rw-r--r--. 1 cvmfs cvmfs 1170 Apr 23 21:28 aarch64/generic/modules/all/libGLU/9.0.3-GCCcore-13.2.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 1170 Apr 23 21:06 x86_64/amd/zen2/modules/all/libGLU/9.0.3-GCCcore-13.2.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 1169 Apr 23 21:14 x86_64/generic/modules/all/libGLU/9.0.3-GCCcore-13.2.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 1177 Apr 23 21:09 x86_64/intel/broadwell/modules/all/libGLU/9.0.3-GCCcore-13.2.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 1182 Apr 23 21:17 x86_64/intel/skylake_avx512/modules/all/libGLU/9.0.3-GCCcore-13.2.0.lua

aarch64/generic/software/libGLU/9.0.3-GCCcore-13.2.0:
total 14
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 23 21:28 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 23 21:28 include
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 23 21:28 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 23 21:28 lib64 -> lib

x86_64/amd/zen2/software/libGLU/9.0.3-GCCcore-13.2.0:
total 14
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 23 21:06 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 23 21:06 include
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 23 21:06 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 23 21:06 lib64 -> lib

x86_64/generic/software/libGLU/9.0.3-GCCcore-13.2.0:
total 14
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 23 21:14 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 23 21:13 include
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 23 21:13 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 23 21:13 lib64 -> lib

x86_64/intel/broadwell/software/libGLU/9.0.3-GCCcore-13.2.0:
total 14
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 23 21:09 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 23 21:09 include
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 23 21:09 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 23 21:09 lib64 -> lib

x86_64/intel/skylake_avx512/software/libGLU/9.0.3-GCCcore-13.2.0:
total 14
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 23 21:17 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 23 21:17 include
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 23 21:17 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 23 21:17 lib64 -> lib 
```
</details>

**Review by poksumdo — APPROVED** [review]
CI green. Lets move on.

**Pull request merged**
