### PR TITLE
{2023.06}[gompi/2023b] Valgrind V3.23.0

### PR DESCRIPTION
**Pull request by TopRichard**
Sync with EESSI ( PR 601 )
Lic --> GPL

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by TopRichard** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by TopRichard** [comment]
Checklist before starting deployment (setting bot:deploy label):

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by TopRichard** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x]  Check if the _SPDX license identifier_ is provided 
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [ ] all tests in the CI for the ingested tarballs have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)

<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; 
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/Valgrind/3.23.0-gompi-2023b* \
        aarch64/generic/{software,modules/all}/Valgrind/3.23.0-gompi-2023b*
  ```
  **log** 
```
-rw-r--r--. 1 cvmfs cvmfs 1292 Jun 11 13:18 aarch64/generic/modules/all/Valgrind/3.23.0-gompi-2023b.lua
-rw-rw-r--. 1 cvmfs cvmfs 1292 Jun 11 13:24 x86_64/amd/zen2/modules/all/Valgrind/3.23.0-gompi-2023b.lua
-rw-rw-r--. 1 cvmfs cvmfs 1291 Jun 11 13:58 x86_64/generic/modules/all/Valgrind/3.23.0-gompi-2023b.lua
-rw-rw-r--. 1 cvmfs cvmfs 1299 Jun 13 17:39 x86_64/intel/broadwell/modules/all/Valgrind/3.23.0-gompi-2023b.lua
-rw-rw-r--. 1 cvmfs cvmfs 1304 Jun 13 13:53 x86_64/intel/skylake_avx512/modules/all/Valgrind/3.23.0-gompi-2023b.lua

aarch64/generic/software/Valgrind/3.23.0-gompi-2023b:
total 28
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 11 13:17 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 11 13:18 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 11 13:17 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 11 13:17 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 11 13:17 lib64 -> lib
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 11 13:17 libexec
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 11 13:17 share

x86_64/amd/zen2/software/Valgrind/3.23.0-gompi-2023b:
total 28
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 11 13:23 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 11 13:24 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 11 13:23 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 11 13:23 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 11 13:23 lib64 -> lib
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 11 13:23 libexec
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 11 13:23 share

x86_64/generic/software/Valgrind/3.23.0-gompi-2023b:
total 28
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 11 13:57 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 11 13:58 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 11 13:57 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 11 13:57 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 11 13:57 lib64 -> lib
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 11 13:57 libexec
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 11 13:57 share

x86_64/intel/broadwell/software/Valgrind/3.23.0-gompi-2023b:
total 28
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 13 17:38 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 13 17:39 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 13 17:38 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 13 17:38 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 13 17:38 lib64 -> lib
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 13 17:38 libexec
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 13 17:38 share

x86_64/intel/skylake_avx512/software/Valgrind/3.23.0-gompi-2023b:
total 28
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 13 13:52 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 13 13:53 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 13 13:52 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 13 13:52 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 13 13:52 lib64 -> lib
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 13 13:52 libexec
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 13 13:52 share
 

```
</details>

**Comment by TopRichard** [comment]
CI tests failing, #408 must be ingested first.

**Review by justadejavu — APPROVED** [review]
lgtm

**Pull request merged**
