### PR TITLE
{2023.06}[foss/2022a] add Boost.Python/1.79.0

### PR DESCRIPTION
**Pull request by trz42**
Will install the following packages (including dependencies):

* ICU/71.1-GCCcore-11.3.0 (ICU-71.1-GCCcore-11.3.0.eb)
* Boost/1.79.0-GCC-11.3.0 (Boost-1.79.0-GCC-11.3.0.eb)
* Boost.Python/1.79.0-GCC-11.3.0 (Boost.Python-1.79.0-GCC-11.3.0.eb)

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:AWS arch:x86_64/generic repo:nessi-2023.06-swl-deb11
bot: build inst:eX3 arch:x86_64/amd/zen2 repo:nessi-2023.06-swl-deb11
bot: build inst:eX3 arch:aarch64/generic repo:nessi-2023.06-swl-deb11
bot: build inst:Fram arch:x86_64/intel/broadwell repo:nessi-2023.06-swl-deb10
bot: build inst:AWS arch:x86_64/intel/cascadelake repo:nessi-2023.06-swl-deb11
bot: build inst:AWS arch:x86_64/intel/skylake repo:nessi-2023.06-swl-deb11

**Comment by trz42** [comment]
Build on `eX3` for `aarch64/generic` with `deb11` container failed. Retry with `deb10` container.

bot: build inst:eX3 arch:aarch64/generic repo:nessi-2023.06-swl-deb10

**Comment by trz42** [comment]
Checklist for building: 

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-intel-cascadelake`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
  - all succeeded except for `aarch64/generic`+`eessi-2023.06-eb-4.7.2-2021a.yml` due to `Yambo` not being supported on `aarch64`
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/Boost*/*11.3* \
        aarch64/generic/{software,modules/all}/Boost*/*11.3*
  ```
  **log**
```
-rw-r--r-- 1 cvmfs cvmfs 1224 Oct  6 20:43 aarch64/generic/modules/all/Boost/1.79.0-GCC-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1285 Oct  6 20:47 aarch64/generic/modules/all/Boost.Python/1.79.0-GCC-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1224 Oct  6 19:27 x86_64/amd/zen2/modules/all/Boost/1.79.0-GCC-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1285 Oct  6 19:29 x86_64/amd/zen2/modules/all/Boost.Python/1.79.0-GCC-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1222 Oct  6 19:38 x86_64/generic/modules/all/Boost/1.79.0-GCC-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1284 Oct  6 19:41 x86_64/generic/modules/all/Boost.Python/1.79.0-GCC-11.3.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 1238 Oct  6 19:35 x86_64/intel/broadwell/modules/all/Boost/1.79.0-GCC-11.3.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 1292 Oct  6 19:37 x86_64/intel/broadwell/modules/all/Boost.Python/1.79.0-GCC-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1242 Oct  6 19:37 x86_64/intel/cascadelake/modules/all/Boost/1.79.0-GCC-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1294 Oct  6 19:40 x86_64/intel/cascadelake/modules/all/Boost.Python/1.79.0-GCC-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1248 Oct  6 19:36 x86_64/intel/skylake_avx512/modules/all/Boost/1.79.0-GCC-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1297 Oct  6 19:38 x86_64/intel/skylake_avx512/modules/all/Boost.Python/1.79.0-GCC-11.3.0.lua

aarch64/generic/software/Boost/1.79.0-GCC-11.3.0:
total 14
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 20:43 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 20:41 include
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 20:42 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  6 20:42 lib64 -> lib

aarch64/generic/software/Boost.Python/1.79.0-GCC-11.3.0:
total 14
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 20:47 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 20:46 include
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 20:47 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  6 20:47 lib64 -> lib

x86_64/amd/zen2/software/Boost/1.79.0-GCC-11.3.0:
total 14
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 19:27 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 19:27 include
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 19:27 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  6 19:27 lib64 -> lib

x86_64/amd/zen2/software/Boost.Python/1.79.0-GCC-11.3.0:
total 14
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 19:29 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 19:29 include
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 19:29 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  6 19:29 lib64 -> lib

x86_64/generic/software/Boost/1.79.0-GCC-11.3.0:
total 14
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 19:39 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 19:38 include
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 19:38 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  6 19:38 lib64 -> lib

x86_64/generic/software/Boost.Python/1.79.0-GCC-11.3.0:
total 14
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 19:42 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 19:41 include
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 19:41 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  6 19:41 lib64 -> lib

x86_64/intel/broadwell/software/Boost/1.79.0-GCC-11.3.0:
total 14
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 19:35 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 19:34 include
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 19:34 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  6 19:34 lib64 -> lib

x86_64/intel/broadwell/software/Boost.Python/1.79.0-GCC-11.3.0:
total 14
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 19:38 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 19:37 include
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 19:37 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  6 19:37 lib64 -> lib

x86_64/intel/cascadelake/software/Boost/1.79.0-GCC-11.3.0:
total 14
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 19:38 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 19:37 include
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 19:37 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  6 19:37 lib64 -> lib

x86_64/intel/cascadelake/software/Boost.Python/1.79.0-GCC-11.3.0:
total 14
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 19:40 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 19:40 include
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 19:40 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  6 19:40 lib64 -> lib

x86_64/intel/skylake_avx512/software/Boost/1.79.0-GCC-11.3.0:
total 14
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 19:36 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 19:36 include
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 19:36 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  6 19:36 lib64 -> lib

x86_64/intel/skylake_avx512/software/Boost.Python/1.79.0-GCC-11.3.0:
total 14
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 19:39 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 19:38 include
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  6 19:38 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  6 19:38 lib64 -> lib 
```
</details>

**Review by poksumdo — APPROVED** [review]
A Boost for NESSI.

**Pull request merged**
