### PR TITLE
Adding CMake/3.20.1, Perl/5.32.1 and OpenMPI/4.1.1 with GCC/10.3.0 to NESSI/2023.04

### PR DESCRIPTION
**Pull request by TopRichard**

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:AWS arch:x86_64/generic repo:nessi.no-2023.04
bot: build inst:AWS arch:x86_64/intel/cascadelake repo:nessi.no-2023.04
bot: build inst:AWS arch:x86_64/intel/skylake repo:nessi.no-2023.04
bot: build inst:Fram-NESSI arch:x86_64/intel/broadwell repo:nessi.no-2023.04
bot: build inst:eX3 arch:zen2 repo:nessi.no-2023.04
bot: build inst:eX3 arch:aarch64/generic repo:nessi.no-2023.04
- received bot command `build inst:AWS arch:x86_64/generic repo:nessi.no-2023.04` from `TopRichard` (expanded command format: `build instance:AWS architecture:x86_64/generic repository:nessi.no-2023.04`)
- received bot command `build inst:AWS arch:x86_64/intel/cascadelake repo:nessi.no-2023.04` from `TopRichard` (expanded command format: `build instance:AWS architecture:x86_64/intel/cascadelake repository:nessi.no-2023.04`)
- received bot command `build inst:AWS arch:x86_64/intel/skylake repo:nessi.no-2023.04` from `TopRichard` (expanded command format: `build instance:AWS architecture:x86_64/intel/skylake repository:nessi.no-2023.04`)
- received bot command `build inst:Fram-NESSI arch:x86_64/intel/broadwell repo:nessi.no-2023.04` from `TopRichard` (expanded command format: `build instance:Fram-NESSI architecture:x86_64/intel/broadwell repository:nessi.no-2023.04`)
- received bot command `build inst:eX3 arch:zen2 repo:nessi.no-2023.04` from `TopRichard` (expanded command format: `build instance:eX3 architecture:zen2 repository:nessi.no-2023.04`)
- received bot command `build inst:eX3 arch:aarch64/generic repo:nessi.no-2023.04` from `TopRichard` (expanded command format: `build instance:eX3 architecture:aarch64/generic repository:nessi.no-2023.04`)

**Comment by trz42** [comment]
Checklist for building: 

- [x]  did the builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  is the PR up-to-date with the target branch nessi.no-2023.04-dev in the repository (if not what are the differences)
  - almost. PR #103 isn't included but should not have any impact on this one. Checked result manually on all bot instances & jobs.
- [x]  are all requested changes sound (checking files changed on GitHub.com)
- [x]  is/are the easyconfig/s being built included with the EB version used (if not why not)
- [x]  were any changes needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Checklist for deployment/ingestion

- [x] at least one tarball for each architecture has been uploaded
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512`
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] at least one tarball for each architecture has been staged
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512`
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] for each architecture **one and only one** tarball has been approved
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512`
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] for each architecture **one and only one** tarball was ingested
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512` 
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
  **command**
  ```
  ls -l /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/{CMake,Perl,OpenMPI}/*
  ls -l /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/aarch64/generic/{software,modules/all}/{CMake,Perl,OpenMPI}/*
  ```
  **log**
```
-rw-r--r--. 1 cvmfs cvmfs  1287 Apr 25 07:18 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/amd/zen2/modules/all/CMake/3.20.1-GCCcore-10.3.0.lua
-rw-r--r--. 1 cvmfs cvmfs  1643 Apr 25 08:16 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/amd/zen2/modules/all/OpenMPI/4.1.1-GCC-10.3.0.lua
-rw-r--r--. 1 cvmfs cvmfs 29916 Apr 25 07:40 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/amd/zen2/modules/all/Perl/5.32.1-GCCcore-10.3.0.lua
-rw-r--r--. 1 cvmfs cvmfs  1286 Apr 25 07:24 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/generic/modules/all/CMake/3.20.1-GCCcore-10.3.0.lua
-rw-r--r--. 1 cvmfs cvmfs  1642 Apr 25 08:13 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/generic/modules/all/OpenMPI/4.1.1-GCC-10.3.0.lua
-rw-r--r--. 1 cvmfs cvmfs 29915 Apr 25 07:43 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/generic/modules/all/Perl/5.32.1-GCCcore-10.3.0.lua
-rw-rw-r--. 1 cvmfs cvmfs  1294 Apr 25 07:26 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/broadwell/modules/all/CMake/3.20.1-GCCcore-10.3.0.lua
-rw-rw-r--. 1 cvmfs cvmfs  1650 Apr 25 08:37 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/broadwell/modules/all/OpenMPI/4.1.1-GCC-10.3.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 29923 Apr 25 07:52 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/broadwell/modules/all/Perl/5.32.1-GCCcore-10.3.0.lua
-rw-r--r--. 1 cvmfs cvmfs  1296 Apr 25 07:21 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/cascadelake/modules/all/CMake/3.20.1-GCCcore-10.3.0.lua
-rw-r--r--. 1 cvmfs cvmfs  1652 Apr 25 07:54 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/cascadelake/modules/all/OpenMPI/4.1.1-GCC-10.3.0.lua
-rw-r--r--. 1 cvmfs cvmfs 29925 Apr 25 07:34 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/cascadelake/modules/all/Perl/5.32.1-GCCcore-10.3.0.lua
-rw-r--r--. 1 cvmfs cvmfs  1299 Apr 25 07:22 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/skylake_avx512/modules/all/CMake/3.20.1-GCCcore-10.3.0.lua
-rw-r--r--. 1 cvmfs cvmfs  1655 Apr 25 08:01 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/skylake_avx512/modules/all/OpenMPI/4.1.1-GCC-10.3.0.lua
-rw-r--r--. 1 cvmfs cvmfs 29928 Apr 25 07:37 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/skylake_avx512/modules/all/Perl/5.32.1-GCCcore-10.3.0.lua

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/amd/zen2/software/CMake/3.20.1-GCCcore-10.3.0:
total 18
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 25 07:18 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 25 07:18 doc
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 25 07:18 easybuild
drwxr-xr-x. 7 cvmfs cvmfs 4096 Apr 25 07:18 share

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/amd/zen2/software/OpenMPI/4.1.1-GCC-10.3.0:
total 28
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 25 08:15 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 25 08:16 easybuild
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 25 08:14 etc
drwxr-xr-x. 5 cvmfs cvmfs 4096 Apr 25 08:15 include
drwxr-xr-x. 4 cvmfs cvmfs 4096 Apr 25 08:15 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 25 08:15 lib64 -> lib
drwxr-xr-x. 4 cvmfs cvmfs 4096 Apr 25 08:13 share

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/amd/zen2/software/Perl/5.32.1-GCCcore-10.3.0:
total 19
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 25 07:39 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 25 07:40 easybuild
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 25 07:31 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 25 07:39 lib64 -> lib
drwxr-xr-x. 4 cvmfs cvmfs 4096 Apr 25 07:31 man

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/generic/software/CMake/3.20.1-GCCcore-10.3.0:
total 18
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 25 07:24 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 25 07:24 doc
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 25 07:24 easybuild
drwxr-xr-x. 7 cvmfs cvmfs 4096 Apr 25 07:24 share

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/generic/software/OpenMPI/4.1.1-GCC-10.3.0:
total 28
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 25 08:12 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 25 08:13 easybuild
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 25 08:12 etc
drwxr-xr-x. 5 cvmfs cvmfs 4096 Apr 25 08:12 include
drwxr-xr-x. 4 cvmfs cvmfs 4096 Apr 25 08:12 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 25 08:13 lib64 -> lib
drwxr-xr-x. 4 cvmfs cvmfs 4096 Apr 25 08:11 share

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/generic/software/Perl/5.32.1-GCCcore-10.3.0:
total 19
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 25 07:42 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 25 07:44 easybuild
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 25 07:34 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 25 07:42 lib64 -> lib
drwxr-xr-x. 4 cvmfs cvmfs 4096 Apr 25 07:34 man

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/broadwell/software/CMake/3.20.1-GCCcore-10.3.0:
total 18
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 25 07:26 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 25 07:26 doc
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 25 07:26 easybuild
drwxr-xr-x. 7 cvmfs cvmfs 4096 Apr 25 07:26 share

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/broadwell/software/OpenMPI/4.1.1-GCC-10.3.0:
total 28
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 25 08:36 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 25 08:37 easybuild
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 25 08:35 etc
drwxr-xr-x. 5 cvmfs cvmfs 4096 Apr 25 08:36 include
drwxr-xr-x. 4 cvmfs cvmfs 4096 Apr 25 08:36 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 25 08:36 lib64 -> lib
drwxr-xr-x. 4 cvmfs cvmfs 4096 Apr 25 08:33 share

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/broadwell/software/Perl/5.32.1-GCCcore-10.3.0:
total 19
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 25 07:51 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 25 07:53 easybuild
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 25 07:40 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 25 07:51 lib64 -> lib
drwxr-xr-x. 4 cvmfs cvmfs 4096 Apr 25 07:40 man

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/cascadelake/software/CMake/3.20.1-GCCcore-10.3.0:
total 18
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 25 07:21 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 25 07:21 doc
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 25 07:21 easybuild
drwxr-xr-x. 7 cvmfs cvmfs 4096 Apr 25 07:21 share

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/cascadelake/software/OpenMPI/4.1.1-GCC-10.3.0:
total 28
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 25 07:54 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 25 07:54 easybuild
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 25 07:53 etc
drwxr-xr-x. 5 cvmfs cvmfs 4096 Apr 25 07:54 include
drwxr-xr-x. 4 cvmfs cvmfs 4096 Apr 25 07:54 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 25 07:54 lib64 -> lib
drwxr-xr-x. 4 cvmfs cvmfs 4096 Apr 25 07:52 share

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/cascadelake/software/Perl/5.32.1-GCCcore-10.3.0:
total 19
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 25 07:33 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 25 07:34 easybuild
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 25 07:28 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 25 07:33 lib64 -> lib
drwxr-xr-x. 4 cvmfs cvmfs 4096 Apr 25 07:28 man

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/skylake_avx512/software/CMake/3.20.1-GCCcore-10.3.0:
total 18
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 25 07:22 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 25 07:22 doc
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 25 07:22 easybuild
drwxr-xr-x. 7 cvmfs cvmfs 4096 Apr 25 07:22 share

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/skylake_avx512/software/OpenMPI/4.1.1-GCC-10.3.0:
total 28
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 25 08:01 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 25 08:01 easybuild
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 25 08:00 etc
drwxr-xr-x. 5 cvmfs cvmfs 4096 Apr 25 08:01 include
drwxr-xr-x. 4 cvmfs cvmfs 4096 Apr 25 08:01 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 25 08:01 lib64 -> lib
drwxr-xr-x. 4 cvmfs cvmfs 4096 Apr 25 08:00 share

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/x86_64/intel/skylake_avx512/software/Perl/5.32.1-GCCcore-10.3.0:
total 19
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 25 07:36 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 25 07:38 easybuild
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 25 07:30 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 25 07:37 lib64 -> lib
drwxr-xr-x. 4 cvmfs cvmfs 4096 Apr 25 07:30 man

-rw-r--r--. 1 cvmfs cvmfs  1287 Apr 25 07:23 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/aarch64/generic/modules/all/CMake/3.20.1-GCCcore-10.3.0.lua
-rw-r--r--. 1 cvmfs cvmfs  1643 Apr 25 09:15 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/aarch64/generic/modules/all/OpenMPI/4.1.1-GCC-10.3.0.lua
-rw-r--r--. 1 cvmfs cvmfs 29916 Apr 25 08:04 /cvmfs/pilot.nessi.no/versions/2023.04/software/linux/aarch64/generic/modules/all/Perl/5.32.1-GCCcore-10.3.0.lua

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/aarch64/generic/software/CMake/3.20.1-GCCcore-10.3.0:
total 18
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 25 07:23 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 25 07:23 doc
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 25 07:23 easybuild
drwxr-xr-x. 7 cvmfs cvmfs 4096 Apr 25 07:23 share

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/aarch64/generic/software/OpenMPI/4.1.1-GCC-10.3.0:
total 28
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 25 09:14 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 25 09:15 easybuild
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 25 09:12 etc
drwxr-xr-x. 5 cvmfs cvmfs 4096 Apr 25 09:14 include
drwxr-xr-x. 4 cvmfs cvmfs 4096 Apr 25 09:14 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 25 09:14 lib64 -> lib
drwxr-xr-x. 4 cvmfs cvmfs 4096 Apr 25 09:09 share

/cvmfs/pilot.nessi.no/versions/2023.04/software/linux/aarch64/generic/software/Perl/5.32.1-GCCcore-10.3.0:
total 19
drwxr-xr-x. 2 cvmfs cvmfs 4096 Apr 25 08:02 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 25 08:06 easybuild
drwxr-xr-x. 3 cvmfs cvmfs 4096 Apr 25 07:45 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 25 08:03 lib64 -> lib
drwxr-xr-x. 4 cvmfs cvmfs 4096 Apr 25 07:45 man 
```

**Review by trz42 — APPROVED** [review]
Looks good, everything ingested and available from a client.

We try to merge this despite it not being up-to-date with the branch `nessi.no-2023.04-dev`. Should be fine because the only commit that is missing, is changing different code.

**Pull request merged**
