### PR TITLE
{2023.06}[foss/2022a] Pango/1.50.7

### PR DESCRIPTION
**Pull request by trz42**
Done separately to prepare for R.

Will install the following packages:

* FriBidi/1.0.12-GCCcore-11.3.0 (FriBidi-1.0.12-GCCcore-11.3.0.eb)
* GLib/2.72.1-GCCcore-11.3.0 (GLib-2.72.1-GCCcore-11.3.0.eb)
* cairo/1.17.4-GCCcore-11.3.0 (cairo-1.17.4-GCCcore-11.3.0.eb)
* GObject-Introspection/1.72.0-GCCcore-11.3.0 (GObject-Introspection-1.72.0-GCCcore-11.3.0.eb)
* HarfBuzz/4.2.1-GCCcore-11.3.0 (HarfBuzz-4.2.1-GCCcore-11.3.0.eb)
* Pango/1.50.7-GCCcore-11.3.0 (Pango-1.50.7-GCCcore-11.3.0.eb)

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:AWS arch:x86_64/generic repo:nessi-2023.06-swl-deb11
bot: build inst:AWS arch:x86_64/amd/zen2 repo:nessi-2023.06-swl-deb11
bot: build inst:eX3 arch:aarch64/generic repo:nessi-2023.06-swl-deb10
bot: build inst:Fram arch:x86_64/intel/broadwell repo:nessi-2023.06-swl-deb10
bot: build inst:AWS arch:x86_64/intel/cascadelake repo:nessi-2023.06-swl-deb11
bot: build inst:AWS arch:x86_64/intel/skylake repo:nessi-2023.06-swl-deb11

**Comment by trz42** [comment]
Checklist for building: 

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-intel-cascadelake`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/Pango/* \
        aarch64/generic/{software,modules/all}/Pango/*
  ```
  **log**
```
-rw-r--r-- 1 cvmfs cvmfs 2217 Oct  8 19:24 aarch64/generic/modules/all/Pango/1.50.7-GCCcore-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 2217 Oct  8 19:06 x86_64/amd/zen2/modules/all/Pango/1.50.7-GCCcore-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 2216 Oct  8 19:06 x86_64/generic/modules/all/Pango/1.50.7-GCCcore-11.3.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 2224 Oct  8 18:57 x86_64/intel/broadwell/modules/all/Pango/1.50.7-GCCcore-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 2226 Oct  8 19:16 x86_64/intel/cascadelake/modules/all/Pango/1.50.7-GCCcore-11.3.0.lua
-rw-r--r-- 1 cvmfs cvmfs 2229 Oct  8 19:04 x86_64/intel/skylake_avx512/modules/all/Pango/1.50.7-GCCcore-11.3.0.lua

aarch64/generic/software/Pango/1.50.7-GCCcore-11.3.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  8 19:24 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  8 19:24 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  8 19:24 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  8 19:24 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  8 19:24 lib64 -> lib
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  8 19:24 share

x86_64/amd/zen2/software/Pango/1.50.7-GCCcore-11.3.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  8 19:06 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  8 19:06 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  8 19:06 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  8 19:06 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  8 19:06 lib64 -> lib
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  8 19:06 share

x86_64/generic/software/Pango/1.50.7-GCCcore-11.3.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  8 19:06 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  8 19:06 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  8 19:06 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  8 19:06 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  8 19:06 lib64 -> lib
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  8 19:06 share

x86_64/intel/broadwell/software/Pango/1.50.7-GCCcore-11.3.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  8 18:57 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  8 18:57 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  8 18:57 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  8 18:57 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  8 18:57 lib64 -> lib
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  8 18:57 share

x86_64/intel/cascadelake/software/Pango/1.50.7-GCCcore-11.3.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  8 19:16 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  8 19:16 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  8 19:16 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  8 19:16 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  8 19:16 lib64 -> lib
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  8 19:16 share

x86_64/intel/skylake_avx512/software/Pango/1.50.7-GCCcore-11.3.0:
total 23
dr-xr-xr-x 2 cvmfs cvmfs 4096 Oct  8 19:04 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  8 19:04 easybuild
dr-xr-xr-x 3 cvmfs cvmfs 4096 Oct  8 19:04 include
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  8 19:04 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Oct  8 19:04 lib64 -> lib
dr-xr-xr-x 4 cvmfs cvmfs 4096 Oct  8 19:04 share 
```
</details>

**Review by poksumdo — APPROVED** [review]
Looks good.

**Pull request merged**
