### PR TITLE
{2023.06}[system] EasyBuild v4.9.2

### PR DESCRIPTION
**Pull request by TopRichard**
Lic --> GPL

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
Checklist before starting deployment (setting bot:deploy label):

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by TopRichard** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x]  Check if the _SPDX license identifier_ is provided 
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [ ] all tests in the CI for the ingested tarballs have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)

<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; 
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/EasyBuild/4.9.2* \
        aarch64/generic/{software,modules/all}/EasyBuild/4.9.2*
  ```
  **log** 
```
-rw-r--r--. 1 cvmfs cvmfs 1223 Jun 17 12:01 aarch64/generic/modules/all/EasyBuild/4.9.2.lua
-rw-rw-r--. 1 cvmfs cvmfs 1222 Jun 17 12:06 x86_64/amd/zen2/modules/all/EasyBuild/4.9.2.lua
-rw-rw-r--. 1 cvmfs cvmfs 1221 Jun 17 11:20 x86_64/generic/modules/all/EasyBuild/4.9.2.lua
-rw-rw-r--. 1 cvmfs cvmfs 1229 Jun 17 12:09 x86_64/intel/broadwell/modules/all/EasyBuild/4.9.2.lua
-rw-rw-r--. 1 cvmfs cvmfs 1234 Jun 17 12:06 x86_64/intel/skylake_avx512/modules/all/EasyBuild/4.9.2.lua

aarch64/generic/software/EasyBuild/4.9.2:
total 23
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 17 12:00 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 17 12:00 contrib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jun 17 12:03 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 17 12:00 etc
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 17 11:59 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 17 12:01 lib64 -> lib

x86_64/amd/zen2/software/EasyBuild/4.9.2:
total 23
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 17 12:06 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 17 12:06 contrib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jun 17 12:07 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 17 12:06 etc
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 17 12:05 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 17 12:06 lib64 -> lib

x86_64/generic/software/EasyBuild/4.9.2:
total 23
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 17 11:19 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 17 11:19 contrib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jun 17 11:21 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 17 11:19 etc
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 17 11:19 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 17 11:20 lib64 -> lib

x86_64/intel/broadwell/software/EasyBuild/4.9.2:
total 23
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 17 12:08 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 17 12:08 contrib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jun 17 12:11 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 17 12:08 etc
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 17 12:08 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 17 12:09 lib64 -> lib

x86_64/intel/skylake_avx512/software/EasyBuild/4.9.2:
total 23
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 17 12:05 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 17 12:05 contrib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jun 17 12:07 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 17 12:05 etc
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 17 12:04 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 17 12:05 lib64 -> lib

```
</details>

**Comment by TopRichard** [comment]
CI test fail with 
```
1 out of 46 required modules missing:

* grpcio/1.57.0-GCCcore-12.3.0 (grpcio-1.57.0-GCCcore-12.3.0.eb)
```
#408

**Review by justadejavu — APPROVED** [review]
Okay

**Pull request merged**
