### PR TITLE
{2023.06}[foss/2022b] GLib/2.75.0

### PR DESCRIPTION
**Pull request by trz42**
Failed previously on `eX3 / aarch64/generic`. Try on `eX3` and `AWS`.

Modules to be installed:

```
4 out of 25 required modules missing:

* Ninja/1.11.1-GCCcore-12.2.0 (Ninja-1.11.1-GCCcore-12.2.0.eb)
* PCRE2/10.40-GCCcore-12.2.0 (PCRE2-10.40-GCCcore-12.2.0.eb)
* Meson/0.64.0-GCCcore-12.2.0 (Meson-0.64.0-GCCcore-12.2.0.eb)
* GLib/2.75.0-GCCcore-12.2.0 (GLib-2.75.0-GCCcore-12.2.0.eb)
```

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:aarch64/generic
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic
bot: build inst:eX3 repo:nessi-2023.06-swl-deb10 arch:aarch64/generic

**Comment by trz42** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/generic
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:zen2

**Comment by trz42** [comment]
Checklist before setting deploy label: 

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
  - be aware of two builds for `aarch64/generic` (one from `AWS` on `neoverse_n1` and one from `eX3` on `ThunderX2`)
  - the one from `eX3` shall be ingested
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)
  - Note, it failed using the `*-deb11` repo (which uses a `deb11` container). It worked using a `deb10` container.

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - ~`x86_64-intel-cascadelake`~
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/GLib/2.75.0* \
        aarch64/generic/{software,modules/all}/GLib/2.75.0*
  ```
  **log**
```
-rw-r--r-- 1 cvmfs cvmfs 1420 Jan 27 22:56 aarch64/generic/modules/all/GLib/2.75.0-GCCcore-12.2.0.lua
-rw-r--r-- 1 cvmfs cvmfs 1420 Jan 27 23:13 x86_64/amd/zen2/modules/all/GLib/2.75.0-GCCcore-12.2.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 1419 Jan 27 23:26 x86_64/generic/modules/all/GLib/2.75.0-GCCcore-12.2.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 1427 Jan 27 23:20 x86_64/intel/broadwell/modules/all/GLib/2.75.0-GCCcore-12.2.0.lua
-rw-rw-r-- 1 cvmfs cvmfs 1432 Jan 27 23:18 x86_64/intel/skylake_avx512/modules/all/GLib/2.75.0-GCCcore-12.2.0.lua

aarch64/generic/software/GLib/2.75.0-GCCcore-12.2.0:
total 28
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 27 22:56 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 27 22:56 easybuild
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jan 27 22:56 include
dr-xr-xr-x 5 cvmfs cvmfs 4096 Jan 27 22:56 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jan 27 22:56 lib64 -> lib
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 27 22:56 libexec
dr-xr-xr-x 9 cvmfs cvmfs 4096 Jan 27 22:56 share

x86_64/amd/zen2/software/GLib/2.75.0-GCCcore-12.2.0:
total 28
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 27 23:13 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 27 23:13 easybuild
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jan 27 23:13 include
dr-xr-xr-x 5 cvmfs cvmfs 4096 Jan 27 23:13 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jan 27 23:13 lib64 -> lib
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 27 23:13 libexec
dr-xr-xr-x 9 cvmfs cvmfs 4096 Jan 27 23:13 share

x86_64/generic/software/GLib/2.75.0-GCCcore-12.2.0:
total 28
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 27 23:26 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 27 23:26 easybuild
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jan 27 23:26 include
dr-xr-xr-x 5 cvmfs cvmfs 4096 Jan 27 23:26 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jan 27 23:26 lib64 -> lib
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 27 23:26 libexec
dr-xr-xr-x 9 cvmfs cvmfs 4096 Jan 27 23:26 share

x86_64/intel/broadwell/software/GLib/2.75.0-GCCcore-12.2.0:
total 28
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 27 23:20 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 27 23:20 easybuild
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jan 27 23:20 include
dr-xr-xr-x 5 cvmfs cvmfs 4096 Jan 27 23:20 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jan 27 23:20 lib64 -> lib
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 27 23:20 libexec
dr-xr-xr-x 9 cvmfs cvmfs 4096 Jan 27 23:20 share

x86_64/intel/skylake_avx512/software/GLib/2.75.0-GCCcore-12.2.0:
total 28
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 27 23:18 bin
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jan 27 23:18 easybuild
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jan 27 23:18 include
dr-xr-xr-x 5 cvmfs cvmfs 4096 Jan 27 23:18 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jan 27 23:18 lib64 -> lib
dr-xr-xr-x 2 cvmfs cvmfs 4096 Jan 27 23:18 libexec
dr-xr-xr-x 9 cvmfs cvmfs 4096 Jan 27 23:18 share 
```
</details>

**Review by poksumdo — APPROVED** [review]
All CI green.

Includes update to actions' version to address Node.js warning.

**Pull request merged**
