### PR TITLE
{2023.06}[foss/2023a] CUDA samples v12.1

### PR DESCRIPTION
**Pull request by trz42**
Adding CUDA samples to NESSI. Follows EESSI PR https://github.com/EESSI/software-layer/pull/434

License: NVIDIA

Missing packages:
```
1 out of 4 required modules missing:

* CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1 (CUDA-Samples-12.1-GCC-12.3.0-CUDA-12.1.1.eb)
```

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb10 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
- Checking the errors indicates that we first need #352

**Comment by trz42** [comment]
Rebuilding after #352

bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb10 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by trz42** [comment]
Checklist before starting deployment (setting `bot:deploy` label): 

- [ ]  Check if the _SPDX license identifier_ is provided 
- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each staged tarball was a PR for approval/rejection opened
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1* \
        aarch64/generic/{software,modules/all}/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1*
  ```
  **log**
```
-rw-r--r--. 1 cvmfs cvmfs 1042 May  5 09:58 aarch64/generic/modules/all/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1.lua
-rw-rw-r--. 1 cvmfs cvmfs 1042 May  5 09:57 x86_64/amd/zen2/modules/all/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1.lua
-rw-rw-r--. 1 cvmfs cvmfs 1041 May  5 09:57 x86_64/generic/modules/all/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1.lua
-rw-rw-r--. 1 cvmfs cvmfs 1049 May  5 11:46 x86_64/intel/broadwell/modules/all/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1.lua
-rw-rw-r--. 1 cvmfs cvmfs 1054 May  5 09:55 x86_64/intel/skylake_avx512/modules/all/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1.lua

aarch64/generic/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1:
total 11
dr-xr-xr-x. 2 cvmfs cvmfs 4096 May  5 09:58 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May  5 09:58 easybuild
-r--r--r--. 1 cvmfs cvmfs 1601 May 31  2023 LICENSE

x86_64/amd/zen2/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1:
total 11
dr-xr-xr-x. 4 cvmfs cvmfs 4096 May  5 09:57 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May  5 09:57 easybuild
-r--r--r--. 1 cvmfs cvmfs 1601 May 31  2023 LICENSE

x86_64/generic/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1:
total 11
dr-xr-xr-x. 4 cvmfs cvmfs 4096 May  5 09:57 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May  5 09:57 easybuild
-r--r--r--. 1 cvmfs cvmfs 1601 May 31  2023 LICENSE

x86_64/intel/broadwell/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1:
total 11
dr-xr-xr-x. 4 cvmfs cvmfs 4096 May  5 11:46 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May  5 11:46 easybuild
-r--r--r--. 1 cvmfs cvmfs 1601 May 31  2023 LICENSE

x86_64/intel/skylake_avx512/software/CUDA-Samples/12.1-GCC-12.3.0-CUDA-12.1.1:
total 11
dr-xr-xr-x. 4 cvmfs cvmfs 4096 May  5 09:55 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May  5 09:55 easybuild
-r--r--r--. 1 cvmfs cvmfs 1601 May 31  2023 LICENSE 
```
</details>

**Review by poksumdo — APPROVED** [review]
nice

**Pull request merged**
