### PR TITLE
Addig OpenSSL/1.1-GCC/10.3.0 to NESSI/2023.06

### PR DESCRIPTION
**Pull request by TopRichard**
Trying to add OpenSSL/1.1 and GCC/10.3.0 to NESSI/2023.06

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi.no-2023.06-software arch:generic
bot: build inst:AWS repo:nessi.no-2023.06-software arch:x86_64/intel/cascadelake 
bot: build inst:AWS repo:nessi.no-2023.06-software arch:x86_64/intel/skylake 
bot: build inst:Fram-NESSI repo:nessi.no-2023.06-software arch:x86_64/intel/broadwell
bot: build inst:eX3 repo:nessi.no-2023.06-software arch:zen2
bot: build inst:eX3 repo:nessi.no-2023.06-software arch:aarch64/generic
bot: build inst:Saga-NESSI repo:nessi.no-2023.06-software arch:x86_64/generic
bot: build inst:Saga-NESSI repo:nessi.no-2023.06-software arch:x86_64/intel/cascadelake
bot: build inst:Saga-NESSI repo:nessi.no-2023.06-software arch:x86_64/intel/skylake

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi.no-2023.06-software arch:generic
bot: build inst:AWS repo:nessi.no-2023.06-software arch:x86_64/intel/cascadelake 
bot: build inst:AWS repo:nessi.no-2023.06-software arch:x86_64/intel/skylake 
bot: build inst:Fram-NESSI repo:nessi.no-2023.06-software arch:x86_64/intel/broadwell
bot: build inst:eX3 repo:nessi.no-2023.06-software arch:zen2
bot: build inst:eX3 repo:nessi.no-2023.06-software arch:aarch64/generic
bot: build inst:Saga-NESSI repo:nessi.no-2023.06-software arch:x86_64/generic
bot: build inst:Saga-NESSI repo:nessi.no-2023.06-software arch:x86_64/intel/cascadelake
bot: build inst:Saga-NESSI repo:nessi.no-2023.06-software arch:x86_64/intel/skylake

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi.no-2023.06-software arch:generic
bot: build inst:AWS repo:nessi.no-2023.06-software arch:x86_64/intel/cascadelake 
bot: build inst:AWS repo:nessi.no-2023.06-software arch:x86_64/intel/skylake 
bot: build inst:Fram-NESSI repo:nessi.no-2023.06-software arch:x86_64/intel/broadwell
bot: build inst:eX3 repo:nessi.no-2023.06-software arch:zen2
bot: build inst:eX3 repo:nessi.no-2023.06-software arch:aarch64/generic
bot: build inst:Saga-NESSI repo:nessi.no-2023.06-software arch:x86_64/generic
bot: build inst:Saga-NESSI repo:nessi.no-2023.06-software arch:x86_64/intel/cascadelake
bot: build inst:Saga-NESSI repo:nessi.no-2023.06-software arch:x86_64/intel/skylake

**Comment by TopRichard** [comment]
Checklist for building:

- [x] did the builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x] is the PR up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x] are all requested changes sound (checking files changed on GitHub.com)
- [x] is/are the easyconfig/s being built included with the EB version used (if not why not)
- [x] were any changes needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Checklist for deployment/ingestion

- [x] at least one tarball for each architecture has been uploaded
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512`
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] at least one tarball for each architecture has been staged
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512`
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] for each architecture **one and only one** tarball has been approved
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512`
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] for each architecture **one and only one** tarball was ingested
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512` 
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
  **command**
  ```
  ls -l /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/{GCC,GCCcore,OpenSSL,pkgconf}/*
  ls -l /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/{software,modules/all}/{GCC,GCCcore,OpenSSL,pkgconf}/*
  ```
  **log**
```
-rw-r--r--.  1 cvmfs cvmfs 1121 Jun 19 10:48 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all/GCC/10.3.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1231 Jun 19 10:48 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all/GCCcore/10.3.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1487 Jun 19 09:37 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all/OpenSSL/1.1.lua
-rw-r--r--.  1 cvmfs cvmfs 1410 Jun 19 09:37 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all/pkgconf/1.8.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1119 Jun 19 11:36 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/modules/all/GCC/10.3.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1230 Jun 19 11:35 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/modules/all/GCCcore/10.3.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1486 Jun 19 09:41 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/modules/all/OpenSSL/1.1.lua
-rw-r--r--.  1 cvmfs cvmfs 1409 Jun 19 09:40 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/modules/all/pkgconf/1.8.0.lua
-rw-rw-r--.  1 cvmfs cvmfs 1135 Jun 19 10:42 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/modules/all/GCC/10.3.0.lua
-rw-rw-r--.  1 cvmfs cvmfs 1238 Jun 19 10:42 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/modules/all/GCCcore/10.3.0.lua
-rw-rw-r--.  1 cvmfs cvmfs 1494 Jun 19 09:39 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/modules/all/OpenSSL/1.1.lua
-rw-rw-r--.  1 cvmfs cvmfs 1417 Jun 19 09:39 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/modules/all/pkgconf/1.8.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1139 Jun 19 10:52 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/modules/all/GCC/10.3.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1240 Jun 19 10:52 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/modules/all/GCCcore/10.3.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1496 Jun 19 09:38 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/modules/all/OpenSSL/1.1.lua
-rw-r--r--.  1 cvmfs cvmfs 1419 Jun 19 09:37 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/modules/all/pkgconf/1.8.0.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/software/GCC/10.3.0:
total 5
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 10:48 easybuild

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/software/GCCcore/10.3.0:
total 36
drwxr-xr-x. 2 cvmfs cvmfs 4096 Jun 19 10:48 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 10:48 easybuild
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 10:36 include
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 10:36 lib
drwxr-xr-x. 2 cvmfs cvmfs 4096 Jun 19 10:48 lib64
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 10:36 libexec
drwxr-xr-x. 5 cvmfs cvmfs 4096 Jun 19 10:48 nvptx-none
drwxr-xr-x. 6 cvmfs cvmfs 4096 Jun 19 10:36 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/software/OpenSSL/1.1:
total 19
drwxr-xr-x. 2 cvmfs cvmfs 4096 Jun 19 09:37 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 09:37 easybuild
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 09:37 include
lrwxrwxrwx. 1 cvmfs cvmfs    5 Jun 19 09:37 lib -> lib64
drwxr-xr-x. 4 cvmfs cvmfs 4096 Jun 19 09:37 lib64

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/software/pkgconf/1.8.0:
total 23
drwxr-xr-x. 2 cvmfs cvmfs 4096 Jun 19 09:37 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 09:37 easybuild
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 09:37 include
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 09:37 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 19 09:37 lib64 -> lib
drwxr-xr-x. 5 cvmfs cvmfs 4096 Jun 19 09:37 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/software/GCC/10.3.0:
total 5
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 11:36 easybuild

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/software/GCCcore/10.3.0:
total 36
drwxr-xr-x. 2 cvmfs cvmfs 4096 Jun 19 11:35 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 11:36 easybuild
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 11:14 include
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 11:14 lib
drwxr-xr-x. 2 cvmfs cvmfs 4096 Jun 19 11:35 lib64
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 11:14 libexec
drwxr-xr-x. 5 cvmfs cvmfs 4096 Jun 19 11:35 nvptx-none
drwxr-xr-x. 6 cvmfs cvmfs 4096 Jun 19 11:15 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/software/OpenSSL/1.1:
total 19
drwxr-xr-x. 2 cvmfs cvmfs 4096 Jun 19 09:40 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 09:41 easybuild
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 09:40 include
lrwxrwxrwx. 1 cvmfs cvmfs    5 Jun 19 09:41 lib -> lib64
drwxr-xr-x. 4 cvmfs cvmfs 4096 Jun 19 09:40 lib64

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/software/pkgconf/1.8.0:
total 23
drwxr-xr-x. 2 cvmfs cvmfs 4096 Jun 19 09:40 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 09:40 easybuild
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 09:40 include
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 09:40 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 19 09:40 lib64 -> lib
drwxr-xr-x. 5 cvmfs cvmfs 4096 Jun 19 09:40 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/software/GCC/10.3.0:
total 5
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 10:42 easybuild

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/software/GCCcore/10.3.0:
total 36
drwxr-xr-x. 2 cvmfs cvmfs 4096 Jun 19 10:42 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 10:42 easybuild
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 10:30 include
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 10:29 lib
drwxr-xr-x. 2 cvmfs cvmfs 4096 Jun 19 10:42 lib64
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 10:29 libexec
drwxr-xr-x. 5 cvmfs cvmfs 4096 Jun 19 10:42 nvptx-none
drwxr-xr-x. 6 cvmfs cvmfs 4096 Jun 19 10:30 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/software/OpenSSL/1.1:
total 19
drwxr-xr-x. 2 cvmfs cvmfs 4096 Jun 19 09:39 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 09:39 easybuild
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 09:39 include
lrwxrwxrwx. 1 cvmfs cvmfs    5 Jun 19 09:39 lib -> lib64
drwxr-xr-x. 4 cvmfs cvmfs 4096 Jun 19 09:39 lib64

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/software/pkgconf/1.8.0:
total 23
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 19 09:39 lib64 -> lib
drwxr-xr-x. 5 cvmfs cvmfs 4096 Jun 19 09:39 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/software/GCC/10.3.0:
total 5
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 10:52 easybuild

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/software/GCCcore/10.3.0:
total 36
drwxr-xr-x. 2 cvmfs cvmfs 4096 Jun 19 10:52 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 10:52 easybuild
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 10:39 include
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 10:39 lib
drwxr-xr-x. 2 cvmfs cvmfs 4096 Jun 19 10:52 lib64
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 10:39 libexec
drwxr-xr-x. 5 cvmfs cvmfs 4096 Jun 19 10:52 nvptx-none
drwxr-xr-x. 6 cvmfs cvmfs 4096 Jun 19 10:39 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/software/OpenSSL/1.1:
total 19
drwxr-xr-x. 2 cvmfs cvmfs 4096 Jun 19 09:37 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 09:38 easybuild
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 09:37 include
lrwxrwxrwx. 1 cvmfs cvmfs    5 Jun 19 09:38 lib -> lib64
drwxr-xr-x. 4 cvmfs cvmfs 4096 Jun 19 09:37 lib64

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/software/pkgconf/1.8.0:
total 23
drwxr-xr-x. 2 cvmfs cvmfs 4096 Jun 19 09:37 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 09:37 easybuild
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 09:37 include
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 09:37 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 19 09:37 lib64 -> lib

-rw-r--r--.  1 cvmfs cvmfs 1121 Jun 19 11:21 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/modules/all/GCC/10.3.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1231 Jun 19 11:20 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/modules/all/GCCcore/10.3.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1487 Jun 19 09:35 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/modules/all/OpenSSL/1.1.lua
-rw-r--r--.  1 cvmfs cvmfs 1410 Jun 19 09:35 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/modules/all/pkgconf/1.8.0.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/software/GCC/10.3.0:
total 5
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 11:21 easybuild

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/software/GCCcore/10.3.0:
total 36
drwxr-xr-x. 2 cvmfs cvmfs 4096 Jun 19 11:20 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 11:21 easybuild
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 10:59 include
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 10:59 lib
drwxr-xr-x. 2 cvmfs cvmfs 4096 Jun 19 11:19 lib64
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 10:59 libexec
drwxr-xr-x. 5 cvmfs cvmfs 4096 Jun 19 11:20 nvptx-none
drwxr-xr-x. 6 cvmfs cvmfs 4096 Jun 19 11:00 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/software/OpenSSL/1.1:
total 19
drwxr-xr-x. 2 cvmfs cvmfs 4096 Jun 19 09:35 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 09:35 easybuild
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 09:35 include
lrwxrwxrwx. 1 cvmfs cvmfs    5 Jun 19 09:35 lib -> lib64
drwxr-xr-x. 4 cvmfs cvmfs 4096 Jun 19 09:35 lib64

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/software/pkgconf/1.8.0:
total 23
drwxr-xr-x. 2 cvmfs cvmfs 4096 Jun 19 09:35 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 09:35 easybuild
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 09:35 include
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 09:35 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 19 09:35 lib64 -> lib
drwxr-xr-x. 5 cvmfs cvmfs 4096 Jun 19 09:35 share 
```

**Review by trz42 — APPROVED** [review]
Looks good. All built and ingested.

The OpenSSL package we could have probably parked in some common easystack file. But no reason to block this PR.

**Pull request merged**
