### PR TITLE
added comment to create PR for testing bots

### PR DESCRIPTION
**Pull request by trz42**
Testing bot updates on June 27th, 2023.

### CODE REVIEW

**Comment by trz42** [comment]
bot: build repo:nessi.no-2023.06-software arch:generic

**Comment by trz42** [comment]
Scancelled all jobs. Seems the easystack files for foss/2021b and foss/2022a included packages that were missing. However, we don't want to build them here. Will update the PR and rebuild.

**Comment by trz42** [comment]
bot: build repo:nessi.no-2023.06-software arch:generic

**Comment by trz42** [comment]
En gang til.

**Comment by trz42** [comment]
bot: build repo:nessi.no-2023.06-software arch:generic

**Comment by trz42** [comment]
Everything looks good. Will remove comment from foss/2021a easystack file, then merge this PR so that the other easystack files are updated in the nessi.no-2023.06 branch.

**Review by poksumdo — APPROVED** [review]
Looks good.

**Pull request merged**
