### PR TITLE
Add WRF/3.9.1.1 with GCC/9.3.0 to NESSI/2022.11

### PR DESCRIPTION
**Pull request by TopRichard**
Trying to add WRF/3.9.1.1-foss-2020a-dmpar to NESSI/2022.11

### CODE REVIEW

**Comment by dajon** [comment]
- [x] did the builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
  -  Wonder why there is no saga bot instance, at the top? But saga build later.
- [x] is the PR up-to-date with the target branch `nessi.no-2022.11-dev` in the repository (if not what are the differences)
- [x] are all requested changes sound (checking files changed on GitHub.com)
- [x] is/are the easyconfig/s being built included with the EB version used (if not why not)
- [x] were any changes needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
- [x] the builds for all required architectures succeeded (SUCCESS message + reasonably sized tarball)
  - builds for `generic` are ignored
  - [x] `intel-broadwell`
  - [x] `intel-skylake_avx512`
  - [x] `intel-cascadelake`
  - [x] `and-zen2`
- [x] the PR is up-to-date with the target branch `nessi.no-2022.11-dev` in the repository (if not what are the differences)
- [x] all changes are sound (checking files changed on GitHub.com)
- [x] the easyconfig/s being built is/are included with the EB version used (if not why not)
- [x] no changes were needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Checklist for deployment

_Note, we do not ingest any potential build for `generic`. See separate PRs to branch `nessi.no-2022.11-generic-rebuild`._

- [x] at least one tarball for each architecture has been uploaded
  - builds for `generic` are ignored
  - [x] `intel-broadwell`
  - [x] `intel-skylake_avx512`
  - [x] `intel-cascadelake`
  - [x] `amd-zen2`
- [x] at least one tarball for each architecture has been staged
  - builds for `generic` are ignored
  - [x] `intel-broadwell`
  - [x] `intel-skylake_avx512`
  - [x] `intel-cascadelake`
  - [x] `amd-zen2`
- [x] for each architecture **one and only one** tarball has been approved
  - builds for `generic` are ignored
  - [x] `intel-broadwell`
  - [x] `intel-skylake_avx512`
  - [x] `intel-cascadelake`
  - [x] `amd-zen2`
- [x] for each architecture **one and only one** tarball was ingested
  - builds for `generic` are ignored
  - [x] `intel-broadwell`
  - [x] `intel-skylake_avx512`
  - [x] `intel-cascadelake`
  - [x] `amd-zen2`
- [ ] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
  **command**
  ```
  ls -l /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/x86_64/{amd/zen2,intel/[bsc]*}/{software,modules/all}/WRF*
  ```
  **log**
  ```
  /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/x86_64/amd/zen2/modules/all/WRF:
  total 2
  -rw-r--r--. 1 cvmfs cvmfs 1874 Mar 23 11:25 3.9.1.1-foss-2020a-dmpar.lua

  /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/x86_64/amd/zen2/software/WRF:
  total 5
  drwxr-xr-x. 4 cvmfs cvmfs 4096 Mar 24 18:14 3.9.1.1-foss-2020a-dmpar

  /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/x86_64/intel/broadwell/modules/all/WRF:
  total 2
  -rw-rw-r--. 1 cvmfs cvmfs 1895 Mar 23 12:15 3.9.1.1-foss-2020a-dmpar.lua

  /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/x86_64/intel/broadwell/software/WRF:
  total 5
  drwxr-xr-x. 4 cvmfs cvmfs 4096 Mar 24 18:20 3.9.1.1-foss-2020a-dmpar

  /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/x86_64/intel/cascadelake/modules/all/WRF:
  total 2
  -rw-rw-r--. 1 cvmfs cvmfs 1901 Mar 23 14:34 3.9.1.1-foss-2020a-dmpar.lua

  /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/x86_64/intel/cascadelake/software/WRF:
  total 5
  drwxr-xr-x. 4 cvmfs cvmfs 4096 Mar 24 18:24 3.9.1.1-foss-2020a-dmpar

  /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/x86_64/intel/skylake_avx512/modules/all/WRF:
  total 2
  -rw-rw-r--. 1 cvmfs cvmfs 1910 Mar 23 12:34 3.9.1.1-foss-2020a-dmpar.lua

  /cvmfs/pilot.nessi.no/versions/2022.11/software/linux/x86_64/intel/skylake_avx512/software/WRF:
  total 5
  drwxr-xr-x. 4 cvmfs cvmfs 4096 Mar 24 18:29 3.9.1.1-foss-2020a-dmpar
  ```

**Review by trz42 — APPROVED** [review]
Everything done. Awesome!

:100:

**Pull request merged**
