### PR TITLE
{23.06} GCC/11.2.0

### PR DESCRIPTION
**Pull request by trz42**
- only add GCC/11.2.0 to NESSI/2023.06

### CODE REVIEW

**Comment by trz42** [comment]
bot: build repo:nessi.no-2023.06-software inst:eX3 arch:aarch64/generic
bot: build repo:nessi.no-2023.06-software inst:eX3 arch:zen2
bot: build repo:nessi.no-2023.06-software inst:Fram arch:broadwell
bot: build repo:nessi.no-2023.06-software inst:AWS arch:x86_64/generic
bot: build repo:nessi.no-2023.06-software inst:AWS arch:cascade
bot: build repo:nessi.no-2023.06-software inst:AWS arch:skylake

**Comment by trz42** [comment]
bot: build repo:nessi.no-2023.06-software inst:AWS arch:zen2

**Comment by trz42** [comment]
Checklist for building: 

- [x]  did the builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  is the PR up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  are all requested changes sound (checking files changed on GitHub.com)
- [x]  is/are the easyconfig/s being built included with the EB version used (if not why not)
- [x]  were any changes needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Checklist for deployment/ingestion

- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
  **command**
  ```
  ls -l /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/{GCC,GCCcore}/11.2.0*
  ls -l /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/{software,modules/all}/{GCC,GCCcore}/11.2.0*
  ```
  **log**
```
$ ls -l /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/{GCC,GCCcore}/11.2.0*
-rw-r--r--.  1 cvmfs cvmfs 1121 Jun 27 21:50 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all/GCC/11.2.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1231 Jun 27 21:50 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all/GCCcore/11.2.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1119 Jun 27 19:44 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/modules/all/GCC/11.2.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1230 Jun 27 19:44 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/modules/all/GCCcore/11.2.0.lua
-rw-rw-r--.  1 cvmfs cvmfs 1135 Jun 27 18:40 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/modules/all/GCC/11.2.0.lua
-rw-rw-r--.  1 cvmfs cvmfs 1238 Jun 27 18:40 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/modules/all/GCCcore/11.2.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1139 Jun 27 18:59 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/modules/all/GCC/11.2.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1240 Jun 27 18:59 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/modules/all/GCCcore/11.2.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1145 Jun 27 19:17 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/modules/all/GCC/11.2.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1243 Jun 27 19:17 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/modules/all/GCCcore/11.2.0.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/software/GCC/11.2.0:
total 5
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 21:50 easybuild

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/software/GCCcore/11.2.0:
total 36
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 27 21:50 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 21:50 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 21:32 include
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 21:32 lib
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 27 21:50 lib64
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 21:32 libexec
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jun 27 21:50 nvptx-none
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jun 27 21:32 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/software/GCC/11.2.0:
total 5
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 19:44 easybuild

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/software/GCCcore/11.2.0:
total 36
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 27 19:43 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 19:44 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 19:22 include
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 19:21 lib
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 27 19:43 lib64
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 19:21 libexec
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jun 27 19:43 nvptx-none
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jun 27 19:22 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/software/GCC/11.2.0:
total 5
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 18:40 easybuild

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/software/GCCcore/11.2.0:
total 36
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 27 18:39 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 18:40 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 18:27 include
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 18:27 lib
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 27 18:39 lib64
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 18:27 libexec
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jun 27 18:39 nvptx-none
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jun 27 18:27 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/software/GCC/11.2.0:
total 5
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 18:59 easybuild

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/software/GCCcore/11.2.0:
total 36
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 27 18:58 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 18:59 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 18:44 include
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 18:44 lib
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 27 18:58 lib64
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 18:44 libexec
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jun 27 18:58 nvptx-none
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jun 27 18:44 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/GCC/11.2.0:
total 5
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 19:17 easybuild

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/GCCcore/11.2.0:
total 36
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 27 19:17 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 19:17 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 19:00 include
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 19:00 lib
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 27 19:16 lib64
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 19:00 libexec
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jun 27 19:16 nvptx-none
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jun 27 19:00 share

-rw-r--r--.  1 cvmfs cvmfs 1121 Jun 27 19:32 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/modules/all/GCC/11.2.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1231 Jun 27 19:31 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/modules/all/GCCcore/11.2.0.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/software/GCC/11.2.0:
total 5
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 19:32 easybuild

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/software/GCCcore/11.2.0:
total 36
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 27 19:31 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 19:32 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 19:08 include
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 19:08 lib
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 27 19:30 lib64
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 27 19:08 libexec
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jun 27 19:31 nvptx-none
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jun 27 19:09 share 
```

**Review by poksumdo — APPROVED** [review]
lgtm

**Pull request merged**
