### PR TITLE
{2023.06}[foss/2023a] ipympl v0.9.3

### PR DESCRIPTION
**Pull request by trz42**
Sync NESSI with EESSI (PR 505)

SPDX license identifier: `BSD-3-Clause`

Missing packages:
```
1 out of 97 required modules missing:

* ipympl/0.9.3-foss-2023a (ipympl-0.9.3-foss-2023a.eb)
```

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3-NESSI repo:nessi-2023.06-swl-deb10 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
Checklist before starting deployment (setting `bot:deploy` label): 

- [x]  Check if the _SPDX license identifier_ is provided 
- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each staged tarball was a PR for approval/rejection opened
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/ipympl/0.9.3* \
        aarch64/generic/{software,modules/all}/ipympl/0.9.3*
  ```
  **log**
```
-rw-r--r--. 1 cvmfs cvmfs 2237 Apr 17 13:04 aarch64/generic/modules/all/ipympl/0.9.3-foss-2023a.lua
-rw-rw-r--. 1 cvmfs cvmfs 2237 Apr 17 13:09 x86_64/amd/zen2/modules/all/ipympl/0.9.3-foss-2023a.lua
-rw-rw-r--. 1 cvmfs cvmfs 2236 Apr 17 13:15 x86_64/generic/modules/all/ipympl/0.9.3-foss-2023a.lua
-rw-rw-r--. 1 cvmfs cvmfs 2244 Apr 17 13:05 x86_64/intel/broadwell/modules/all/ipympl/0.9.3-foss-2023a.lua
-rw-rw-r--. 1 cvmfs cvmfs 2249 Apr 17 13:05 x86_64/intel/skylake_avx512/modules/all/ipympl/0.9.3-foss-2023a.lua

aarch64/generic/software/ipympl/0.9.3-foss-2023a:
total 19
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 17 13:04 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 17 13:04 etc
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 17 13:03 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 17 13:04 lib64 -> lib
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 17 13:04 share

x86_64/amd/zen2/software/ipympl/0.9.3-foss-2023a:
total 19
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 17 13:09 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 17 13:08 etc
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 17 13:07 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 17 13:08 lib64 -> lib
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 17 13:08 share

x86_64/generic/software/ipympl/0.9.3-foss-2023a:
total 19
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 17 13:16 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 17 13:15 etc
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 17 13:14 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 17 13:15 lib64 -> lib
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 17 13:15 share

x86_64/intel/broadwell/software/ipympl/0.9.3-foss-2023a:
total 19
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 17 13:05 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 17 13:05 etc
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 17 13:04 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 17 13:05 lib64 -> lib
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 17 13:05 share

x86_64/intel/skylake_avx512/software/ipympl/0.9.3-foss-2023a:
total 19
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 17 13:06 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 17 13:05 etc
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 17 13:04 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Apr 17 13:05 lib64 -> lib
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Apr 17 13:05 share 
```
</details>

**Review by poksumdo — APPROVED** [review]
One package at a time.

**Pull request merged**
