### PR TITLE
Use readlink -f instead of realpath (CentOS6)1

### PR DESCRIPTION
**Pull request by TopRichard**
We have to build this for an environment

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
Code change.

**Review by justadejavu — APPROVED** [review]
Okay

**Pull request merged**
