### PR TITLE
{23.06}[foss/2021b] add missing packages for foss/2021b

### PR DESCRIPTION
**Pull request by trz42**
Should build

- OpenBLAS/0.3.18
- FlexiBLAS/3.0.4
- ScaLAPACK/2.1.0

### CODE REVIEW

**Comment by trz42** [comment]
bot: build repo:nessi.no-2023.06-software inst:eX3 arch:aarch64/generic
bot: build repo:nessi.no-2023.06-software inst:eX3 arch:zen2
bot: build repo:nessi.no-2023.06-software inst:Fram arch:broadwell
bot: build repo:nessi.no-2023.06-software inst:AWS arch:x86_64/generic
bot: build repo:nessi.no-2023.06-software inst:AWS arch:cascade
bot: build repo:nessi.no-2023.06-software inst:AWS arch:skylake

**Comment by trz42** [comment]
Rebuilding for aarch64/generic after changing value type to int in added parse_hook

bot: build repo:nessi.no-2023.06-software inst:eX3 arch:aarch64/generic

**Comment by trz42** [comment]
Checklist for building: 

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)
  - max number of failed LAPACK numerical tests needed to be increased to 302

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-intel-cascadelake`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)

<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/ScaLAPACK/2.1.0* \
        aarch64/generic/{software,modules/all}/ScaLAPACK/2.1.0*
  ```
  **log**
```
-rw-r--r-- 1 cvmfs cvmfs 1334 Jun 21 04:47 aarch64/generic/modules/all/ScaLAPACK/2.1.0-gompi-2021a-fb.lua
-rw-r--r-- 1 cvmfs cvmfs 1334 Jun 30 13:51 aarch64/generic/modules/all/ScaLAPACK/2.1.0-gompi-2021b-fb.lua
-rw-r--r-- 1 cvmfs cvmfs 1334 Jun 21 01:58 x86_64/amd/zen2/modules/all/ScaLAPACK/2.1.0-gompi-2021a-fb.lua
-rw-r--r-- 1 cvmfs cvmfs 1334 Jun 30 08:31 x86_64/amd/zen2/modules/all/ScaLAPACK/2.1.0-gompi-2021b-fb.lua
-rw-r--r-- 1 cvmfs cvmfs 1333 Jun 21 04:34 x86_64/generic/modules/all/ScaLAPACK/2.1.0-gompi-2021a-fb.lua
-rw-r--r-- 1 cvmfs cvmfs 1333 Jun 30 09:14 x86_64/generic/modules/all/ScaLAPACK/2.1.0-gompi-2021b-fb.lua
-rw-rw-r-- 1 cvmfs cvmfs 1341 Jun 21 02:09 x86_64/intel/broadwell/modules/all/ScaLAPACK/2.1.0-gompi-2021a-fb.lua
-rw-rw-r-- 1 cvmfs cvmfs 1341 Jun 30 08:44 x86_64/intel/broadwell/modules/all/ScaLAPACK/2.1.0-gompi-2021b-fb.lua
-rw-r--r-- 1 cvmfs cvmfs 1343 Jun 21 05:06 x86_64/intel/cascadelake/modules/all/ScaLAPACK/2.1.0-gompi-2021a-fb.lua
-rw-r--r-- 1 cvmfs cvmfs 1343 Jun 30 08:34 x86_64/intel/cascadelake/modules/all/ScaLAPACK/2.1.0-gompi-2021b-fb.lua
-rw-r--r-- 1 cvmfs cvmfs 1346 Jun 21 04:17 x86_64/intel/skylake_avx512/modules/all/ScaLAPACK/2.1.0-gompi-2021a-fb.lua
-rw-r--r-- 1 cvmfs cvmfs 1346 Jun 30 08:40 x86_64/intel/skylake_avx512/modules/all/ScaLAPACK/2.1.0-gompi-2021b-fb.lua

aarch64/generic/software/ScaLAPACK/2.1.0-gompi-2021a-fb:
total 10
drwxr-xr-x 3 cvmfs cvmfs 4096 Jun 21 04:47 easybuild
drwxr-xr-x 4 cvmfs cvmfs 4096 Jun 21 04:47 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 21 04:47 lib64 -> lib

aarch64/generic/software/ScaLAPACK/2.1.0-gompi-2021b-fb:
total 10
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 30 13:51 easybuild
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 30 13:51 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 30 13:51 lib64 -> lib

x86_64/amd/zen2/software/ScaLAPACK/2.1.0-gompi-2021a-fb:
total 10
drwxr-xr-x 3 cvmfs cvmfs 4096 Jun 21 01:58 easybuild
drwxr-xr-x 4 cvmfs cvmfs 4096 Jun 21 01:58 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 21 01:58 lib64 -> lib

x86_64/amd/zen2/software/ScaLAPACK/2.1.0-gompi-2021b-fb:
total 10
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 30 08:32 easybuild
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 30 08:31 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 30 08:31 lib64 -> lib

x86_64/generic/software/ScaLAPACK/2.1.0-gompi-2021a-fb:
total 10
drwxr-xr-x 3 cvmfs cvmfs 4096 Jun 21 04:34 easybuild
drwxr-xr-x 4 cvmfs cvmfs 4096 Jun 21 04:34 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 21 04:34 lib64 -> lib

x86_64/generic/software/ScaLAPACK/2.1.0-gompi-2021b-fb:
total 10
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 30 09:14 easybuild
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 30 09:14 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 30 09:14 lib64 -> lib

x86_64/intel/broadwell/software/ScaLAPACK/2.1.0-gompi-2021a-fb:
total 10
drwxr-xr-x 3 cvmfs cvmfs 4096 Jun 21 02:09 easybuild
drwxr-xr-x 4 cvmfs cvmfs 4096 Jun 21 02:09 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 21 02:09 lib64 -> lib

x86_64/intel/broadwell/software/ScaLAPACK/2.1.0-gompi-2021b-fb:
total 10
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 30 08:44 easybuild
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 30 08:44 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 30 08:44 lib64 -> lib

x86_64/intel/cascadelake/software/ScaLAPACK/2.1.0-gompi-2021a-fb:
total 10
drwxr-xr-x 3 cvmfs cvmfs 4096 Jun 21 05:06 easybuild
drwxr-xr-x 4 cvmfs cvmfs 4096 Jun 21 05:06 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 21 05:06 lib64 -> lib

x86_64/intel/cascadelake/software/ScaLAPACK/2.1.0-gompi-2021b-fb:
total 10
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 30 08:34 easybuild
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 30 08:34 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 30 08:34 lib64 -> lib

x86_64/intel/skylake_avx512/software/ScaLAPACK/2.1.0-gompi-2021a-fb:
total 10
drwxr-xr-x 3 cvmfs cvmfs 4096 Jun 21 04:17 easybuild
drwxr-xr-x 4 cvmfs cvmfs 4096 Jun 21 04:17 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 21 04:17 lib64 -> lib

x86_64/intel/skylake_avx512/software/ScaLAPACK/2.1.0-gompi-2021b-fb:
total 10
dr-xr-xr-x 3 cvmfs cvmfs 4096 Jun 30 08:41 easybuild
dr-xr-xr-x 4 cvmfs cvmfs 4096 Jun 30 08:40 lib
lrwxrwxrwx 1 cvmfs cvmfs    3 Jun 30 08:40 lib64 -> lib 
```
</details>

**Review by poksumdo — APPROVED** [review]
All good. :tada:

**Pull request merged**
