### PR TITLE
init stack NESSI/2023.06

### PR DESCRIPTION
**Pull request by trz42**
- sync'ed with EESSI/2023.06 branch
- should build EasyBuild

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:AWS repo:nessi.no-2023.06-software arch:generic
- received bot command `build inst:AWS repo:nessi.no-2023.06-software arch:generic` from `trz42` (expanded command format: `build instance:AWS repository:nessi.no-2023.06-software architecture:generic`)

**Comment by trz42** [comment]
bot: build inst:AWS repo:nessi.no-2023.06-software arch:aarch64/generic
- received bot command `build inst:AWS repo:nessi.no-2023.06-software arch:aarch64/generic` from `trz42` (expanded command format: `build instance:AWS repository:nessi.no-2023.06-software architecture:aarch64/generic`)

**Comment by trz42** [comment]
bot: build inst:AWS repo:nessi.no-2023.06-software arch:aarch64/generic

- received bot command `build inst:AWS repo:nessi.no-2023.06-software arch:aarch64/generic` from `trz42` (expanded command format: `build instance:AWS repository:nessi.no-2023.06-software architecture:aarch64/generic`)

**Comment by trz42** [comment]
bot: build inst:AWS repo:nessi.no-2023.06-software arch:aarch64/generic

- received bot command `build inst:AWS repo:nessi.no-2023.06-software arch:aarch64/generic` from `trz42` (expanded command format: `build instance:AWS repository:nessi.no-2023.06-software architecture:aarch64/generic`)

**Comment by trz42** [comment]
bot: build inst:AWS repo:nessi.no-2023.06-software arch:aarch64/generic

**Comment by trz42** [comment]
bot: build inst:AWS repo:nessi.no-2023.06-software arch:aarch64/generic

**Comment by trz42** [comment]
bot: build inst:AWS repo:nessi.no-2023.06-software arch:aarch64/generic

**Comment by trz42** [comment]
bot: build inst:AWS repo:nessi.no-2023.06-software arch:x86_64
bot: build inst:Fram repo:nessi.no-2023.06-software arch:x86_64/intel/broadwell
bot: build inst:eX3 repo:nessi.no-2023.06-software

**Comment by trz42** [comment]
Checklist for building: 

- [x]  did the builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  is the PR up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  are all requested changes sound (checking files changed on GitHub.com)
  - lots of changes to sync with [EESSI/software-layer](https://github.com/EESSI/software-layer)
  - it also includes a fully functional `bot/check-result.sh` with bot instances running https://github.com/EESSI/eessi-bot-software-layer/pull/174 or newer
- [x]  is/are the easyconfig/s being built included with the EB version used (if not why not)
- [x]  were any changes needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Checklist for deployment/ingestion

- [x] at least one tarball for each architecture has been uploaded
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512`
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] at least one tarball for each architecture has been staged
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512`
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] for each architecture at least one approval PR has been opened
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512`
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] for each architecture **one and only one** tarball has been approved
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512`
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] for each architecture **one and only one** tarball was ingested
  - [x] `x86_64-intel-broadwell`
  - [x] `x86_64-intel-skylake_avx512` 
  - [x] `x86_64-intel-cascadelake`
  - [x] `x86_64-amd-zen2`
  - [x] `x86_64-generic`
  - [x] `aarch64-generic`
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
  **command**
  ```
  ls -l /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/EasyBuild/*
  ls -l /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/{software,modules/all}/EasyBuild/*
  ```
  **log**
```
 ls -l /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/EasyBuild/*
-rw-r--r--. 1 cvmfs cvmfs 1320 Jun 18 03:54 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all/EasyBuild/4.7.2.lua
-rw-r--r--. 1 cvmfs cvmfs 1319 Jun 18 03:59 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/modules/all/EasyBuild/4.7.2.lua
-rw-rw-r--. 1 cvmfs cvmfs 1327 Jun 18 03:56 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/modules/all/EasyBuild/4.7.2.lua
-rw-r--r--. 1 cvmfs cvmfs 1332 Jun 18 03:59 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/modules/all/EasyBuild/4.7.2.lua
-rw-r--r--. 1 cvmfs cvmfs 1329 Jun 18 03:59 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/modules/all/EasyBuild/4.7.2.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/software/EasyBuild/4.7.2:
total 23
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 18 03:53 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 18 03:53 contrib
drwxr-xr-x. 5 cvmfs cvmfs 4096 Jun 18 03:54 easybuild
drwxr-xr-x. 2 cvmfs cvmfs 4096 Jun 18 03:53 etc
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 18 03:53 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 18 03:54 lib64 -> lib

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/software/EasyBuild/4.7.2:
total 23
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 18 03:58 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 18 03:58 contrib
drwxr-xr-x. 5 cvmfs cvmfs 4096 Jun 18 04:00 easybuild
drwxr-xr-x. 2 cvmfs cvmfs 4096 Jun 18 03:58 etc
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 18 03:58 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 18 03:59 lib64 -> lib

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/software/EasyBuild/4.7.2:
total 23
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 18 03:56 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 18 03:56 contrib
drwxr-xr-x. 5 cvmfs cvmfs 4096 Jun 18 03:57 easybuild
drwxr-xr-x. 2 cvmfs cvmfs 4096 Jun 18 03:56 etc
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 18 03:55 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 18 03:56 lib64 -> lib

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/EasyBuild/4.7.2:
total 23
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 18 03:58 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 18 03:58 contrib
drwxr-xr-x. 5 cvmfs cvmfs 4096 Jun 18 03:59 easybuild
drwxr-xr-x. 2 cvmfs cvmfs 4096 Jun 18 03:58 etc
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 18 03:58 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 18 03:58 lib64 -> lib

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/software/EasyBuild/4.7.2:
total 23
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 18 03:58 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 18 03:58 contrib
drwxr-xr-x. 5 cvmfs cvmfs 4096 Jun 18 03:59 easybuild
drwxr-xr-x. 2 cvmfs cvmfs 4096 Jun 18 03:58 etc
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 18 03:58 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 18 03:58 lib64 -> lib

-rw-r--r--. 1 cvmfs cvmfs 1321 Jun 18 03:53 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/modules/all/EasyBuild/4.7.2.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/software/EasyBuild/4.7.2:
total 23
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 18 03:52 bin
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 18 03:52 contrib
drwxr-xr-x. 5 cvmfs cvmfs 4096 Jun 18 03:54 easybuild
drwxr-xr-x. 2 cvmfs cvmfs 4096 Jun 18 03:52 etc
drwxr-xr-x. 3 cvmfs cvmfs 4096 Jun 18 03:52 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 18 03:53 lib64 -> lib 
```

**Review by poksumdo — APPROVED** [review]
Looks good.

**Pull request merged**
