### PR TITLE
{23.06}[foss/2021b] CMake + OpenMPI + FFTW + BLIS

### PR DESCRIPTION
**Pull request by trz42**
Add several components of foss/2021b (not OpenBLAS and packages depending on it):

- `CMake/3.21.1` with easyblock PR 2248
- `OpenMPI/4.1.1`
- `FFTW/3.3.10`
- `BLIS/0.8.1`

### CODE REVIEW

**Comment by trz42** [comment]
bot: build repo:nessi.no-2023.06-software inst:eX3 arch:aarch64/generic
bot: build repo:nessi.no-2023.06-software inst:eX3 arch:zen2
bot: build repo:nessi.no-2023.06-software inst:Fram arch:broadwell
bot: build repo:nessi.no-2023.06-software inst:AWS arch:x86_64/generic
bot: build repo:nessi.no-2023.06-software inst:AWS arch:cascade
bot: build repo:nessi.no-2023.06-software inst:AWS arch:skylake

**Comment by trz42** [comment]
Checklist for building: 

- [x]  did the builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  is the PR up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  are all requested changes sound (checking files changed on GitHub.com)
- [x]  is/are the easyconfig/s being built included with the EB version used (if not why not)
- [x]  were any changes needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Checklist for deployment/ingestion

- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
  **command**
  ```
  ls -l /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/CMake/3.21.1*
  ls -l /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/{software,modules/all}/CMake/3.21.1*
  ls -l /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/BLIS/0.8.1*
  ls -l /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/{software,modules/all}/BLIS/0.8.1*
  ls -l /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/FFTW/3.3.10*
  ls -l /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/{software,modules/all}/FFTW/3.3.10*
  ls -l /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/OpenMPI/4.1.1*
  ls -l /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/{software,modules/all}/OpenMPI/4.1.1*
  ```
  **log**
```
-rw-r--r--. 1 cvmfs cvmfs 1385 Jun 28 18:55 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all/CMake/3.21.1-GCCcore-11.2.0.lua
-rw-r--r--. 1 cvmfs cvmfs 1384 Jun 28 19:06 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/modules/all/CMake/3.21.1-GCCcore-11.2.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 1392 Jun 28 18:58 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/modules/all/CMake/3.21.1-GCCcore-11.2.0.lua
-rw-r--r--. 1 cvmfs cvmfs 1394 Jun 28 19:01 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/modules/all/CMake/3.21.1-GCCcore-11.2.0.lua
-rw-r--r--. 1 cvmfs cvmfs 1397 Jun 28 19:02 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/modules/all/CMake/3.21.1-GCCcore-11.2.0.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/software/CMake/3.21.1-GCCcore-11.2.0:
total 18
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 18:55 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 18:55 doc
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 18:55 easybuild
dr-xr-xr-x. 7 cvmfs cvmfs 4096 Jun 28 18:55 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/software/CMake/3.21.1-GCCcore-11.2.0:
total 18
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 19:06 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 19:06 doc
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 19:06 easybuild
dr-xr-xr-x. 7 cvmfs cvmfs 4096 Jun 28 19:06 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/software/CMake/3.21.1-GCCcore-11.2.0:
total 18
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 18:58 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 18:58 doc
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 18:58 easybuild
dr-xr-xr-x. 7 cvmfs cvmfs 4096 Jun 28 18:58 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/software/CMake/3.21.1-GCCcore-11.2.0:
total 18
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 19:01 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 19:01 doc
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 19:01 easybuild
dr-xr-xr-x. 7 cvmfs cvmfs 4096 Jun 28 19:01 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/CMake/3.21.1-GCCcore-11.2.0:
total 18
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 19:02 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 19:02 doc
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 19:02 easybuild
dr-xr-xr-x. 7 cvmfs cvmfs 4096 Jun 28 19:02 share

-rw-r--r--. 1 cvmfs cvmfs 1385 Jun 28 18:56 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/modules/all/CMake/3.21.1-GCCcore-11.2.0.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/software/CMake/3.21.1-GCCcore-11.2.0:
total 18
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 18:56 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 18:56 doc
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 18:57 easybuild
dr-xr-xr-x. 7 cvmfs cvmfs 4096 Jun 28 18:56 share

-rw-r--r--. 1 cvmfs cvmfs 1296 Jun 28 23:04 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all/BLIS/0.8.1-GCC-11.2.0.lua
-rw-r--r--. 1 cvmfs cvmfs 1295 Jun 29 00:30 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/modules/all/BLIS/0.8.1-GCC-11.2.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 1303 Jun 28 23:26 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/modules/all/BLIS/0.8.1-GCC-11.2.0.lua
-rw-r--r--. 1 cvmfs cvmfs 1305 Jun 28 22:56 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/modules/all/BLIS/0.8.1-GCC-11.2.0.lua
-rw-r--r--. 1 cvmfs cvmfs 1308 Jun 28 23:45 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/modules/all/BLIS/0.8.1-GCC-11.2.0.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/software/BLIS/0.8.1-GCC-11.2.0:
total 19
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 23:04 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 23:04 include
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 23:04 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 28 23:04 lib64 -> lib
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 23:04 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/software/BLIS/0.8.1-GCC-11.2.0:
total 19
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 29 00:30 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 29 00:30 include
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 29 00:30 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 29 00:30 lib64 -> lib
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 29 00:30 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/software/BLIS/0.8.1-GCC-11.2.0:
total 19
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 23:27 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 23:26 include
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 23:26 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 28 23:26 lib64 -> lib
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 23:26 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/software/BLIS/0.8.1-GCC-11.2.0:
total 19
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 22:56 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 22:56 include
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 22:56 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 28 22:56 lib64 -> lib
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 22:56 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/BLIS/0.8.1-GCC-11.2.0:
total 19
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 23:45 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 23:45 include
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 23:45 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 28 23:45 lib64 -> lib
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 23:45 share

-rw-r--r--. 1 cvmfs cvmfs 1296 Jun 29 00:57 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/modules/all/BLIS/0.8.1-GCC-11.2.0.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/software/BLIS/0.8.1-GCC-11.2.0:
total 19
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 29 00:57 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 29 00:57 include
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 29 00:57 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 29 00:57 lib64 -> lib
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 29 00:57 share

-rw-r--r--. 1 cvmfs cvmfs 1422 Jun 28 20:46 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all/FFTW/3.3.10-gompi-2021b.lua
-rw-r--r--. 1 cvmfs cvmfs 1421 Jun 28 21:22 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/modules/all/FFTW/3.3.10-gompi-2021b.lua
-rw-rw-r--. 1 cvmfs cvmfs 1429 Jun 28 21:29 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/modules/all/FFTW/3.3.10-gompi-2021b.lua
-rw-r--r--. 1 cvmfs cvmfs 1431 Jun 28 20:48 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/modules/all/FFTW/3.3.10-gompi-2021b.lua
-rw-r--r--. 1 cvmfs cvmfs 1434 Jun 28 21:13 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/modules/all/FFTW/3.3.10-gompi-2021b.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/software/FFTW/3.3.10-gompi-2021b:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 20:46 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 20:46 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 20:46 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 20:46 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 28 20:46 lib64 -> lib
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 20:05 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/software/FFTW/3.3.10-gompi-2021b:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 21:22 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 21:22 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 21:22 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 21:22 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 28 21:22 lib64 -> lib
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 20:51 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/software/FFTW/3.3.10-gompi-2021b:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 21:29 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 21:29 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 21:29 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 21:29 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 28 21:29 lib64 -> lib
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 20:22 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/software/FFTW/3.3.10-gompi-2021b:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 20:48 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 20:48 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 20:48 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 20:48 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 28 20:48 lib64 -> lib
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 20:07 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/FFTW/3.3.10-gompi-2021b:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 21:13 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 21:13 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 21:13 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 21:13 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 28 21:13 lib64 -> lib
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 20:28 share

-rw-r--r--. 1 cvmfs cvmfs 1422 Jun 28 21:38 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/modules/all/FFTW/3.3.10-gompi-2021b.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/software/FFTW/3.3.10-gompi-2021b:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 21:38 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 21:38 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 21:38 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 21:38 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 28 21:38 lib64 -> lib
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 21:07 share

-rw-r--r--. 1 cvmfs cvmfs 1741 Jun 28 19:54 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all/OpenMPI/4.1.1-GCC-11.2.0.lua
-rw-r--r--. 1 cvmfs cvmfs 1740 Jun 28 20:43 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/modules/all/OpenMPI/4.1.1-GCC-11.2.0.lua
-rw-rw-r--. 1 cvmfs cvmfs 1748 Jun 28 20:10 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/modules/all/OpenMPI/4.1.1-GCC-11.2.0.lua
-rw-r--r--. 1 cvmfs cvmfs 1750 Jun 28 19:59 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/modules/all/OpenMPI/4.1.1-GCC-11.2.0.lua
-rw-r--r--. 1 cvmfs cvmfs 1753 Jun 28 20:18 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/modules/all/OpenMPI/4.1.1-GCC-11.2.0.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/software/OpenMPI/4.1.1-GCC-11.2.0:
total 28
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 19:54 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 19:54 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 19:53 etc
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jun 28 19:53 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 19:53 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 28 19:54 lib64 -> lib
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 19:51 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/software/OpenMPI/4.1.1-GCC-11.2.0:
total 28
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 20:43 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 20:43 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 20:41 etc
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jun 28 20:42 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 20:42 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 28 20:43 lib64 -> lib
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 20:39 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/software/OpenMPI/4.1.1-GCC-11.2.0:
total 28
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 20:09 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 20:10 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 20:08 etc
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jun 28 20:09 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 20:09 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 28 20:09 lib64 -> lib
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 20:06 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/software/OpenMPI/4.1.1-GCC-11.2.0:
total 28
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 19:59 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 20:00 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 19:58 etc
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jun 28 19:59 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 19:59 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 28 19:59 lib64 -> lib
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 19:57 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/OpenMPI/4.1.1-GCC-11.2.0:
total 28
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 20:17 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 20:18 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 20:16 etc
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jun 28 20:17 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 20:17 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 28 20:17 lib64 -> lib
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 20:14 share

-rw-r--r--. 1 cvmfs cvmfs 1741 Jun 28 20:59 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/modules/all/OpenMPI/4.1.1-GCC-11.2.0.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/software/OpenMPI/4.1.1-GCC-11.2.0:
total 28
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 20:58 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 20:59 easybuild
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 20:56 etc
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jun 28 20:58 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 20:58 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 28 20:58 lib64 -> lib
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 28 20:53 share 
```

**Review by poksumdo — APPROVED** [review]
Everything built and ingested. CI turned green.

**Pull request merged**
