### PR TITLE
{2023.06}[foss/2022a] ParaView-mpi V5.10.1

### PR DESCRIPTION
**Pull request by TopRichard**
Trying to build ParaView_mpi-foss/2022a as a step forward for getting closer to the current available HPC software stack.
license: https://spdx.org/licenses/BSD-3-Clause.html 
Will install the following packages:

```
* Python/2.7.18-GCCcore-11.3.0-bare (Python-2.7.18-GCCcore-11.3.0-bare.eb)
* ffnvcodec/11.1.5.2 (ffnvcodec-11.1.5.2.eb)
* re2c/2.2-GCCcore-11.3.0 (re2c-2.2-GCCcore-11.3.0.eb)
* double-conversion/3.2.0-GCCcore-11.3.0 (double-conversion-3.2.0-GCCcore-11.3.0.eb)
* x264/20220620-GCCcore-11.3.0 (x264-20220620-GCCcore-11.3.0.eb)
* Yasm/1.3.0-GCCcore-11.3.0 (Yasm-1.3.0-GCCcore-11.3.0.eb)
* x265/3.5-GCCcore-11.3.0 (x265-3.5-GCCcore-11.3.0.eb)
* FFmpeg/4.4.2-GCCcore-11.3.0 (FFmpeg-4.4.2-GCCcore-11.3.0.eb)
* graphite2/1.3.14-GCCcore-11.3.0 (graphite2-1.3.14-GCCcore-11.3.0.eb)
* snappy/1.1.9-GCCcore-11.3.0 (snappy-1.1.9-GCCcore-11.3.0.eb)
* NSPR/4.34-GCCcore-11.3.0 (NSPR-4.34-GCCcore-11.3.0.eb)
* NSS/3.79-GCCcore-11.3.0 (NSS-3.79-GCCcore-11.3.0.eb)
* Qt5/5.15.5-GCCcore-11.3.0 (Qt5-5.15.5-GCCcore-11.3.0.eb)
* ParaView/5.10.1-foss-2022a-mpi (ParaView-5.10.1-foss-2022a-mpi.eb)
```

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb10 arch:x86_64/intel/broadwell
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/cascadelake
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake

**Comment by TopRichard** [comment]
bot: build inst:eX3 repo:nessi-2023.06-swl-deb10 arch:zen2

**Comment by TopRichard** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by trz42** [comment]
bot: show_config

**Comment by TopRichard** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by TopRichard** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic
bot: build inst:AWS-MC-NESSIrepo:nessi-2023.06-swl-deb10 arch:zen2

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb10 arch:zen2

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2

**Comment by TopRichard** [comment]
Checklist for building ParaView-mpi V5.10.1 : 

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- []  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)
       - Excluded aarch64 and Cascadelake regardless of the build status.

**Comment by TopRichard** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [] encountered issues in the ingestion, likely related to troubles interacting with GitHub via PyGithub … 
- [x] all tests in the CI for the ingested tarballs have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] the PR has a license info for the ingested software
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)

<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; 
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/ParaView/5.10.1-foss-2022a-mpi* \
        aarch64/generic/{software,modules/all}/ParaView/5.10.1-foss-2022a-mpi*


 -rw-rw-r--. 1 cvmfs cvmfs 2071 Oct 17 23:51 x86_64/amd/zen2/modules/all/ParaView/5.10.1-foss-2022a-mpi.lua
-rw-rw-r--. 1 cvmfs cvmfs 2070 Oct 17 12:20 x86_64/generic/modules/all/ParaView/5.10.1-foss-2022a-mpi.lua
-rw-rw-r--. 1 cvmfs cvmfs 2078 Oct 17 11:17 x86_64/intel/broadwell/modules/all/ParaView/5.10.1-foss-2022a-mpi.lua
-rw-rw-r--. 1 cvmfs cvmfs 2083 Oct 12 16:40 x86_64/intel/skylake_avx512/modules/all/ParaView/5.10.1-foss-2022a-mpi.lua

x86_64/amd/zen2/software/ParaView/5.10.1-foss-2022a-mpi:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct 17 23:49 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 17 23:52 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 17 23:49 include
dr-xr-xr-x. 7 cvmfs cvmfs 4096 Oct 17 23:49 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct 17 23:49 lib64 -> lib
dr-xr-xr-x. 8 cvmfs cvmfs 4096 Oct 17 23:49 share

x86_64/generic/software/ParaView/5.10.1-foss-2022a-mpi:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct 17 12:18 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 17 12:20 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 17 12:17 include
dr-xr-xr-x. 7 cvmfs cvmfs 4096 Oct 17 12:18 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct 17 12:18 lib64 -> lib
dr-xr-xr-x. 8 cvmfs cvmfs 4096 Oct 17 12:18 share

x86_64/intel/broadwell/software/ParaView/5.10.1-foss-2022a-mpi:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct 17 11:16 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 17 11:18 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 17 11:15 include
dr-xr-xr-x. 7 cvmfs cvmfs 4096 Oct 17 11:16 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct 17 11:16 lib64 -> lib
dr-xr-xr-x. 8 cvmfs cvmfs 4096 Oct 17 11:16 share

x86_64/intel/skylake_avx512/software/ParaView/5.10.1-foss-2022a-mpi:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Oct 12 16:37 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 12 16:41 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Oct 12 16:36 include
dr-xr-xr-x. 7 cvmfs cvmfs 4096 Oct 12 16:37 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Oct 12 16:37 lib64 -> lib
dr-xr-xr-x. 8 cvmfs cvmfs 4096 Oct 12 16:37 share


```
</details>

**Review by justadejavu — APPROVED** [review]
Okay

**Pull request merged**
