### PR TITLE
{23.06} GCC/12.2.0

### PR DESCRIPTION
**Pull request by trz42**
Adds GCC/12.2.0 to NESSI/2023.06

### CODE REVIEW

**Comment by trz42** [comment]
bot: build repo:nessi.no-2023.06-software inst:eX3 arch:aarch64/generic
bot: build repo:nessi.no-2023.06-software inst:eX3 arch:zen2
bot: build repo:nessi.no-2023.06-software inst:Fram arch:broadwell
bot: build repo:nessi.no-2023.06-software inst:AWS arch:x86_64/generic
bot: build repo:nessi.no-2023.06-software inst:AWS arch:cascade
bot: build repo:nessi.no-2023.06-software inst:AWS arch:skylake

**Comment by trz42** [comment]
Checklist for building: 

- [x]  did the builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  is the PR up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  are all requested changes sound (checking files changed on GitHub.com)
- [x]  is/are the easyconfig/s being built included with the EB version used (if not why not)
- [x]  were any changes needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Checklist for deployment/ingestion

- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
  **command**
  ```
  ls -l /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/{GCC,GCCcore}/12.2.0*
  ls -l /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/{software,modules/all}/{GCC,GCCcore}/12.2.0*
  ```
  **log**
```
-rw-r--r--.  1 cvmfs cvmfs 1121 Jun 28 15:49 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all/GCC/12.2.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1231 Jun 28 15:48 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/modules/all/GCCcore/12.2.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1119 Jun 28 16:42 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/modules/all/GCC/12.2.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1230 Jun 28 16:42 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/modules/all/GCCcore/12.2.0.lua
-rw-rw-r--.  1 cvmfs cvmfs 1135 Jun 28 15:42 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/modules/all/GCC/12.2.0.lua
-rw-rw-r--.  1 cvmfs cvmfs 1238 Jun 28 15:42 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/modules/all/GCCcore/12.2.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1139 Jun 28 15:50 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/modules/all/GCC/12.2.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1240 Jun 28 15:50 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/modules/all/GCCcore/12.2.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1145 Jun 28 16:11 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/modules/all/GCC/12.2.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1243 Jun 28 16:11 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/modules/all/GCCcore/12.2.0.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/software/GCC/12.2.0:
total 5
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 15:49 easybuild

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/amd/zen2/software/GCCcore/12.2.0:
total 36
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 15:48 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 15:49 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 15:32 include
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 15:32 lib
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 15:48 lib64
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 15:32 libexec
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jun 28 15:48 nvptx-none
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jun 28 15:32 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/software/GCC/12.2.0:
total 5
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 16:42 easybuild

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/generic/software/GCCcore/12.2.0:
total 36
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 16:42 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 16:42 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 16:14 include
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 16:14 lib
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 16:41 lib64
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 16:14 libexec
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jun 28 16:41 nvptx-none
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jun 28 16:15 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/software/GCC/12.2.0:
total 5
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 15:42 easybuild

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/broadwell/software/GCCcore/12.2.0:
total 36
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 15:42 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 15:42 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 15:23 include
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 15:23 lib
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 15:41 lib64
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 15:23 libexec
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jun 28 15:41 nvptx-none
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jun 28 15:23 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/software/GCC/12.2.0:
total 5
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 15:50 easybuild

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/cascadelake/software/GCCcore/12.2.0:
total 36
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 15:50 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 15:50 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 15:33 include
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 15:33 lib
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 15:49 lib64
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 15:33 libexec
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jun 28 15:50 nvptx-none
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jun 28 15:33 share

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/GCC/12.2.0:
total 5
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 16:11 easybuild

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/x86_64/intel/skylake_avx512/software/GCCcore/12.2.0:
total 36
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 16:11 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 16:11 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 15:48 include
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 15:48 lib
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 16:10 lib64
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 15:48 libexec
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jun 28 16:10 nvptx-none
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jun 28 15:48 share

-rw-r--r--.  1 cvmfs cvmfs 1121 Jun 28 16:28 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/modules/all/GCC/12.2.0.lua
-rw-r--r--.  1 cvmfs cvmfs 1231 Jun 28 16:28 /cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/modules/all/GCCcore/12.2.0.lua

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/software/GCC/12.2.0:
total 5
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 16:28 easybuild

/cvmfs/pilot.nessi.no/versions/2023.06/software/linux/aarch64/generic/software/GCCcore/12.2.0:
total 36
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 16:27 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 16:28 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 15:59 include
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 15:58 lib
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 28 16:27 lib64
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 28 15:58 libexec
dr-xr-xr-x. 5 cvmfs cvmfs 4096 Jun 28 16:27 nvptx-none
dr-xr-xr-x. 6 cvmfs cvmfs 4096 Jun 28 15:59 share 
```

**Review by poksumdo — APPROVED** [review]
lgtm 👍

**Pull request merged**
