### PR TITLE
{2023.06}[gfbf/2023b] pystencils V1.3.4

### PR DESCRIPTION
**Pull request by TopRichard**
Sync with EESSI ( PR 641)
Lic --> AGPLv3+

```
missing packages :

gmpy2/2.1.5-GCC-13.2.0
libyaml/0.2.5-GCCcore-13.2.0
pystencils/1.3.4-gfbf-2023b
PyYAML/6.0.1-GCCcore-13.2.0
sympy/1.12-gfbf-2023b

```

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
Checklist before starting deployment (setting bot:deploy label):

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by TopRichard** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x]  Check if the _SPDX license identifier_ is provided 
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI for the ingested tarballs have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)

<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; 
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/pystencils/1.3.4-gfbf-2023b* \
        aarch64/generic/{software,modules/all}/pystencils/1.3.4-gfbf-2023b*
  ```
  **log**
```
-rw-rw-r--. 1 cvmfs cvmfs 1766 Jul 17 08:18 aarch64/generic/modules/all/pystencils/1.3.4-gfbf-2023b.lua
-rw-rw-r--. 1 cvmfs cvmfs 1766 Jul 17 08:14 x86_64/amd/zen2/modules/all/pystencils/1.3.4-gfbf-2023b.lua
-rw-rw-r--. 1 cvmfs cvmfs 1765 Jul 17 08:05 x86_64/generic/modules/all/pystencils/1.3.4-gfbf-2023b.lua
-rw-rw-r--. 1 cvmfs cvmfs 1773 Jul 17 09:06 x86_64/intel/broadwell/modules/all/pystencils/1.3.4-gfbf-2023b.lua
-rw-rw-r--. 1 cvmfs cvmfs 1778 Jul 17 08:55 x86_64/intel/skylake_avx512/modules/all/pystencils/1.3.4-gfbf-2023b.lua

aarch64/generic/software/pystencils/1.3.4-gfbf-2023b:
total 10
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 17 08:18 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 17 08:17 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 17 08:18 lib64 -> lib

x86_64/amd/zen2/software/pystencils/1.3.4-gfbf-2023b:
total 10
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 17 08:14 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 17 08:13 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 17 08:14 lib64 -> lib

x86_64/generic/software/pystencils/1.3.4-gfbf-2023b:
total 10
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 17 08:05 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 17 08:04 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 17 08:05 lib64 -> lib

x86_64/intel/broadwell/software/pystencils/1.3.4-gfbf-2023b:
total 10
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 17 09:06 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 17 09:06 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 17 09:06 lib64 -> lib

x86_64/intel/skylake_avx512/software/pystencils/1.3.4-gfbf-2023b:
total 10
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 17 08:55 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jul 17 08:55 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jul 17 08:55 lib64 -> lib

```
</details>

**Review by justadejavu — APPROVED** [review]
Okay

**Pull request merged**
