### PR TITLE
{2023.06}[foss/2023b] GROMACS V2024.1

### PR DESCRIPTION
**Pull request by TopRichard**
Adding GROMACS 2024.1
Lic : https://spdx.org/licenses/LGPL-2.1-only.html
Sync with EESSI (PR499) 
```
3 out of 59 required modules missing:

* networkx/3.2.1-gfbf-2023b (networkx-3.2.1-gfbf-2023b.eb)
* mpi4py/3.1.5-gompi-2023b (mpi4py-3.1.5-gompi-2023b.eb)
* GROMACS/2024.1-foss-2023b (GROMACS-2024.1-foss-2023b.eb)
```

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:eX3 repo:nessi-2023.06-swl-deb10 arch:aarch64/generic

**Comment by TopRichard** [comment]
Checklist before starting deployment (setting bot:deploy label):

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by TopRichard** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x]  Check if the _SPDX license identifier_ is provided 
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI for the ingested tarballs have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)

<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; 
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/GROMACS/2024.1-foss-2023b* \
        aarch64/generic/{software,modules/all}/GROMACS/2024.1-foss-2023b*
  ```
  **log** 
```
-rw-r--r--. 1 cvmfs cvmfs 2430 May  2 11:31 aarch64/generic/modules/all/GROMACS/2024.1-foss-2023b.lua
-rw-rw-r--. 1 cvmfs cvmfs 2430 May  2 09:05 x86_64/amd/zen2/modules/all/GROMACS/2024.1-foss-2023b.lua
-rw-rw-r--. 1 cvmfs cvmfs 2429 May  2 09:05 x86_64/generic/modules/all/GROMACS/2024.1-foss-2023b.lua
-rw-rw-r--. 1 cvmfs cvmfs 2437 May  2 09:06 x86_64/intel/broadwell/modules/all/GROMACS/2024.1-foss-2023b.lua
-rw-rw-r--. 1 cvmfs cvmfs 2442 May  2 09:14 x86_64/intel/skylake_avx512/modules/all/GROMACS/2024.1-foss-2023b.lua

aarch64/generic/software/GROMACS/2024.1-foss-2023b:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 May  2 11:29 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May  2 11:32 easybuild
dr-xr-xr-x. 5 cvmfs cvmfs 4096 May  2 10:02 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 May  2 11:29 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 May  2 11:31 lib64 -> lib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 May  2 10:02 share

x86_64/amd/zen2/software/GROMACS/2024.1-foss-2023b:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 May  2 09:04 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May  2 09:05 easybuild
dr-xr-xr-x. 5 cvmfs cvmfs 4096 May  2 08:29 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 May  2 09:04 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 May  2 09:05 lib64 -> lib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 May  2 08:29 share

x86_64/generic/software/GROMACS/2024.1-foss-2023b:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 May  2 09:04 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May  2 09:05 easybuild
dr-xr-xr-x. 5 cvmfs cvmfs 4096 May  2 08:31 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 May  2 09:04 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 May  2 09:05 lib64 -> lib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 May  2 08:31 share

x86_64/intel/broadwell/software/GROMACS/2024.1-foss-2023b:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 May  2 09:04 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May  2 09:06 easybuild
dr-xr-xr-x. 5 cvmfs cvmfs 4096 May  2 08:25 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 May  2 09:04 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 May  2 09:06 lib64 -> lib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 May  2 08:25 share

x86_64/intel/skylake_avx512/software/GROMACS/2024.1-foss-2023b:
total 23
dr-xr-xr-x. 2 cvmfs cvmfs 4096 May  2 09:12 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 May  2 09:14 easybuild
dr-xr-xr-x. 5 cvmfs cvmfs 4096 May  2 08:26 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 May  2 09:12 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 May  2 09:13 lib64 -> lib
dr-xr-xr-x. 5 cvmfs cvmfs 4096 May  2 08:26 share

```
</details>

**Review by justadejavu — APPROVED** [review]
lgtm

**Pull request merged**
