### PR TITLE
use NESSI_SITE_INSTALL when it is set

### PR DESCRIPTION
**Pull request by trz42**
Apparently the `extend` module wasn't using it yet.

### CODE REVIEW

**Comment by trz42** [comment]
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
Need to rebuild module...

bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
Rebuild filename must conform to certain structure...

Need to rebuild module...

bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
Debug permission issue...

bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2

**Comment by trz42** [comment]
Debug permission issue (2)...

bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2

**Comment by trz42** [comment]
Debug permission issue (3)...

bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2

**Comment by trz42** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb10 arch:zen2

**Comment by trz42** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2

**Comment by trz42** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2

**Comment by trz42** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2

**Comment by trz42** [comment]
Gave up on fixing the permission issue. Will first remove module from S0, then "rebuild" and ingest.

**Comment by trz42** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2

**Comment by trz42** [comment]
Build for other architectures too...

bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:aarch64/generic
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by trz42** [comment]
Checklist before starting deployment (setting `bot:deploy` label): 

- [x]  Check if the _SPDX license identifier_ is provided 
  - just rebuilding NESSI-extend module 
- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
  - builds continued to fail until software package was removed from S0 
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each staged tarball was a PR for approval/rejection opened
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/NESSI-extend/* \
        aarch64/generic/{software,modules/all}/NESSI-extend/*
  ```
  **log**
```
-rw-rw-r-- 1 cvmfs cvmfs 10137 May 19 23:53 aarch64/generic/modules/all/NESSI-extend/2023.06-easybuild.lua
-rw-rw-r-- 1 cvmfs cvmfs 10132 May 19 23:32 x86_64/amd/zen2/modules/all/NESSI-extend/2023.06-easybuild.lua
-rw-rw-r-- 1 cvmfs cvmfs 10131 May 19 23:53 x86_64/generic/modules/all/NESSI-extend/2023.06-easybuild.lua
-rw-rw-r-- 1 cvmfs cvmfs 10139 May 19 23:46 x86_64/intel/broadwell/modules/all/NESSI-extend/2023.06-easybuild.lua
-rw-rw-r-- 1 cvmfs cvmfs 10144 May 19 23:50 x86_64/intel/skylake_avx512/modules/all/NESSI-extend/2023.06-easybuild.lua

aarch64/generic/software/NESSI-extend/2023.06-easybuild:
total 5
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 19 23:53 easybuild

x86_64/amd/zen2/software/NESSI-extend/2023.06-easybuild:
total 5
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 19 23:32 easybuild

x86_64/generic/software/NESSI-extend/2023.06-easybuild:
total 5
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 19 23:53 easybuild

x86_64/intel/broadwell/software/NESSI-extend/2023.06-easybuild:
total 5
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 19 23:46 easybuild

x86_64/intel/skylake_avx512/software/NESSI-extend/2023.06-easybuild:
total 5
dr-xr-xr-x 3 cvmfs cvmfs 4096 May 19 23:50 easybuild 
```
</details>

**Review by poksumdo — APPROVED** [review]
done. let's see if it works.

**Comment by poksumdo** [comment]
Apparently, one should use NESSI_PROJECT_INSTALL if one wants to install under a specific path which is neither under `/cvmfs` nor under `.../host_injections`.

Need to "undo" the ingestion (delete modules+software on S0 and ingest newly builds from #364).

**Pull request merged**
