### PR TITLE
{2023.06}[gompi/2023a] Valgrind V3.21.0

### PR DESCRIPTION
**Pull request by TopRichard**
Sync with EESSI ( PR 601 )
Lic --> GPL

```
missing packages:
Valgrind/3.21.0-gompi-2023a
```

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
Checklist before starting deployment (setting bot:deploy label):

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)

**Comment by TopRichard** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x]  Check if the _SPDX license identifier_ is provided 
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI for the ingested tarballs have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)

<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; 
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/Valgrind/3.21.0-gompi-2023a* \
        aarch64/generic/{software,modules/all}/Valgrind/3.21.0-gompi-2023a*
  ```
  **log** 
```
-rw-r--r--. 1 cvmfs cvmfs 1090 Jun 19 06:53 aarch64/generic/modules/all/Valgrind/3.21.0-gompi-2023a.lua
-rw-rw-r--. 1 cvmfs cvmfs 1090 Jun 19 07:00 x86_64/amd/zen2/modules/all/Valgrind/3.21.0-gompi-2023a.lua
-rw-rw-r--. 1 cvmfs cvmfs 1089 Jun 19 07:00 x86_64/generic/modules/all/Valgrind/3.21.0-gompi-2023a.lua
-rw-rw-r--. 1 cvmfs cvmfs 1097 Jun 19 07:06 x86_64/intel/broadwell/modules/all/Valgrind/3.21.0-gompi-2023a.lua
-rw-rw-r--. 1 cvmfs cvmfs 1102 Jun 19 07:01 x86_64/intel/skylake_avx512/modules/all/Valgrind/3.21.0-gompi-2023a.lua

aarch64/generic/software/Valgrind/3.21.0-gompi-2023a:
total 28
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 19 06:53 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 06:53 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 06:53 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 19 06:53 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 19 06:53 lib64 -> lib
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 06:53 libexec
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 19 06:53 share

x86_64/amd/zen2/software/Valgrind/3.21.0-gompi-2023a:
total 28
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 19 07:00 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 07:00 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 07:00 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 19 07:00 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 19 07:00 lib64 -> lib
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 07:00 libexec
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 19 07:00 share

x86_64/generic/software/Valgrind/3.21.0-gompi-2023a:
total 28
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 19 07:00 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 07:00 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 07:00 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 19 07:00 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 19 07:00 lib64 -> lib
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 07:00 libexec
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 19 07:00 share

x86_64/intel/broadwell/software/Valgrind/3.21.0-gompi-2023a:
total 28
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 19 07:06 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 07:06 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 07:06 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 19 07:06 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 19 07:06 lib64 -> lib
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 07:06 libexec
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 19 07:06 share

x86_64/intel/skylake_avx512/software/Valgrind/3.21.0-gompi-2023a:
total 28
dr-xr-xr-x. 2 cvmfs cvmfs 4096 Jun 19 07:01 bin
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 07:01 easybuild
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 07:01 include
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 19 07:01 lib
lrwxrwxrwx. 1 cvmfs cvmfs    3 Jun 19 07:01 lib64 -> lib
dr-xr-xr-x. 3 cvmfs cvmfs 4096 Jun 19 07:01 libexec
dr-xr-xr-x. 4 cvmfs cvmfs 4096 Jun 19 07:01 share

```
</details>

**Review by justadejavu — APPROVED** [review]
Okay

**Pull request merged**
