### PR TITLE
{2023.06}[foss/2022b] Qt5 V5.15.7

### PR DESCRIPTION
**Pull request by TopRichard**
Trying to add Qt5 V5.15.7/foss2022b 

Modules to be installed:
```
35 out of 63 required modules missing:

* Bison/3.8.2-GCCcore-12.2.0 (Bison-3.8.2-GCCcore-12.2.0.eb)
* re2c/3.0-GCCcore-12.2.0 (re2c-3.0-GCCcore-12.2.0.eb)
* Python/2.7.18-GCCcore-12.2.0-bare (Python-2.7.18-GCCcore-12.2.0-bare.eb)
* libpng/1.6.38-GCCcore-12.2.0 (libpng-1.6.38-GCCcore-12.2.0.eb)
* double-conversion/3.2.1-GCCcore-12.2.0 (double-conversion-3.2.1-GCCcore-12.2.0.eb)
* graphite2/1.3.14-GCCcore-12.2.0 (graphite2-1.3.14-GCCcore-12.2.0.eb)
* ICU/72.1-GCCcore-12.2.0 (ICU-72.1-GCCcore-12.2.0.eb)
* pixman/0.42.2-GCCcore-12.2.0 (pixman-0.42.2-GCCcore-12.2.0.eb)
* Brotli/1.0.9-GCCcore-12.2.0 (Brotli-1.0.9-GCCcore-12.2.0.eb)
* libiconv/1.17-GCCcore-12.2.0 (libiconv-1.17-GCCcore-12.2.0.eb)
* freetype/2.12.1-GCCcore-12.2.0 (freetype-2.12.1-GCCcore-12.2.0.eb)
* Doxygen/1.9.5-GCCcore-12.2.0 (Doxygen-1.9.5-GCCcore-12.2.0.eb)
* fontconfig/2.14.1-GCCcore-12.2.0 (fontconfig-2.14.1-GCCcore-12.2.0.eb)
* X11/20221110-GCCcore-12.2.0 (X11-20221110-GCCcore-12.2.0.eb)
* cairo/1.17.4-GCCcore-12.2.0 (cairo-1.17.4-GCCcore-12.2.0.eb)
* GObject-Introspection/1.74.0-GCCcore-12.2.0 (GObject-Introspection-1.74.0-GCCcore-12.2.0.eb)
* HarfBuzz/5.3.1-GCCcore-12.2.0 (HarfBuzz-5.3.1-GCCcore-12.2.0.eb)
* NASM/2.15.05-GCCcore-12.2.0 (NASM-2.15.05-GCCcore-12.2.0.eb)
* Mako/1.2.4-GCCcore-12.2.0 (Mako-1.2.4-GCCcore-12.2.0.eb)
* libjpeg-turbo/2.1.4-GCCcore-12.2.0 (libjpeg-turbo-2.1.4-GCCcore-12.2.0.eb)
* snappy/1.1.9-GCCcore-12.2.0 (snappy-1.1.9-GCCcore-12.2.0.eb)
* NSPR/4.35-GCCcore-12.2.0 (NSPR-4.35-GCCcore-12.2.0.eb)
* NSS/3.85-GCCcore-12.2.0 (NSS-3.85-GCCcore-12.2.0.eb)
* JasPer/4.0.0-GCCcore-12.2.0 (JasPer-4.0.0-GCCcore-12.2.0.eb)
* libdrm/2.4.114-GCCcore-12.2.0 (libdrm-2.4.114-GCCcore-12.2.0.eb)
* gzip/1.12-GCCcore-12.2.0 (gzip-1.12-GCCcore-12.2.0.eb)
* nodejs/18.12.1-GCCcore-12.2.0 (nodejs-18.12.1-GCCcore-12.2.0.eb)
* libglvnd/1.6.0-GCCcore-12.2.0 (libglvnd-1.6.0-GCCcore-12.2.0.eb)
* lz4/1.9.4-GCCcore-12.2.0 (lz4-1.9.4-GCCcore-12.2.0.eb)
* zstd/1.5.2-GCCcore-12.2.0 (zstd-1.5.2-GCCcore-12.2.0.eb)
* libunwind/1.6.2-GCCcore-12.2.0 (libunwind-1.6.2-GCCcore-12.2.0.eb)
* LLVM/15.0.5-GCCcore-12.2.0 (LLVM-15.0.5-GCCcore-12.2.0.eb)
* Mesa/22.2.4-GCCcore-12.2.0 (Mesa-22.2.4-GCCcore-12.2.0.eb)
* libGLU/9.0.2-GCCcore-12.2.0 (libGLU-9.0.2-GCCcore-12.2.0.eb)
* Qt5/5.15.7-GCCcore-12.2.0 (Qt5-5.15.7-GCCcore-12.2.0.eb)
```

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake

**Comment by TopRichard** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake

**Comment by TopRichard** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake

**Comment by TopRichard** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by TopRichard** [comment]
bot: show_config

**Comment by TopRichard** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb10 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2

**Comment by TopRichard** [comment]
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by TopRichard** [comment]
@trz42 For the https://github.com/NorESSI/software-layer/pull/215#issuecomment-1882544549, Saga bot_job_manager log last event at: **[20240109-T13:53:43]**

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/generic 
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb10 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake

**Comment by TopRichard** [comment]
bot: build inst:AWS-MC-NESSI repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by trz42** [comment]
Rebuilding after #258 has been ingested. Additionally some CI workflows and eb_hooks.py have been updated. Note, deliberately choosing `deb10` container for building for `aarch64/generic` on `eX3` as builds using `deb11` failed.

bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/skylake
bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:x86_64/generic
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:eX3 repo:nessi-2023.06-swl-deb10 arch:aarch64/generic

**Comment by trz42** [comment]
Build for `zen2` on `eX3` with `deb11` container failed. Repeating it with `deb10` container and launching a build on `AWS`.

bot: build inst:AWS repo:nessi-2023.06-swl-deb11 arch:zen2
bot: build inst:eX3 repo:nessi-2023.06-swl-deb10 arch:zen2

**Comment by trz42** [comment]
Last job for `zen2` on `eX3` failed because of full disk. Cleaned up disk usage and excluded node for new jobs. Repeating builds for `zen2` on `eX3`.

bot: build inst:eX3 repo:nessi-2023.06-swl-deb10 arch:zen2
bot: build inst:eX3 repo:nessi-2023.06-swl-deb11 arch:zen2

**Comment by trz42** [comment]
Broadwell job didn't seem to progress. Running it again after adjusting time limit and requested memory. Launching two build jobs one with each container version.

bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb10 arch:x86_64/intel/broadwell
bot: build inst:Saga-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by trz42** [comment]
Also try building on Fram.

bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb10 arch:x86_64/intel/broadwell
bot: build inst:Fram-NESSI repo:nessi-2023.06-swl-deb11 arch:x86_64/intel/broadwell

**Comment by trz42** [comment]
Checklist before starting deployment: 

- [x]  Check whether builds for all required architectures succeed (SUCCESS message + reasonably sized tarball)
- [x]  Check if the PR is up-to-date with the target branch nessi.no-2023.06 in the repository (if not what are the differences)
- [x]  Assess if all requested changes are sound (checking files changed on GitHub.com)
- [x]  Verify that all easyconfig/s being built are included with the EB version used (if not why not)
- [x]  Review changes (if any) needed to get the build(s) succeed (common changes for all architectures, changes for a single architecture, changes because of build environment specifics, etc.)
  - Still not clear when to use deb10/deb11 container

**Comment by trz42** [comment]
Target architectures
  - `x86_64-intel-broadwell`
  - `x86_64-intel-skylake_avx512`
  - ~`x86_64-intel-cascadelake`~
  - `x86_64-amd-zen2`
  - `x86_64-generic`
  - `aarch64-generic`

Checklist for deployment/ingestion
- [x] at least one tarball for each architecture has been uploaded
- [x] at least one tarball for each architecture has been staged
- [x] for each architecture **one and only one** tarball has been approved
- [x] for each architecture **one and only one** tarball was ingested
- [x] all tests in the CI have succeeded (rerun failed tests ~ 10 mins after last ingest)
- [x] has the package become available via CernVM-FS for all architectures ingested (for lmod cache updates pay attention to timestamp of files)
<details><summary>command & log</summary>

  **command**
  ```
  cd /cvmfs/pilot.nessi.no/versions/2023.06/software/linux ; \
  ls -l \
        x86_64/{generic,amd/zen2,intel/[bsc]*}/{software,modules/all}/Qt5/5.15.7* \
        aarch64/generic/{software,modules/all}/Qt5/5.15.7*
  ```
  **log**
```
-rw-r--r--  1 cvmfs cvmfs 2729 Jan 28 09:26 aarch64/generic/modules/all/Qt5/5.15.7-GCCcore-12.2.0.lua
-rw-rw-r--  1 cvmfs cvmfs 2729 Jan 28 12:29 x86_64/amd/zen2/modules/all/Qt5/5.15.7-GCCcore-12.2.0.lua
-rw-rw-r--  1 cvmfs cvmfs 2728 Jan 28 05:52 x86_64/generic/modules/all/Qt5/5.15.7-GCCcore-12.2.0.lua
-rw-rw-r--  1 cvmfs cvmfs 2736 Jan 28 19:54 x86_64/intel/broadwell/modules/all/Qt5/5.15.7-GCCcore-12.2.0.lua
-rw-rw-r--  1 cvmfs cvmfs 2741 Jan 28 06:49 x86_64/intel/skylake_avx512/modules/all/Qt5/5.15.7-GCCcore-12.2.0.lua

aarch64/generic/software/Qt5/5.15.7-GCCcore-12.2.0:
total 59
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jan 28 09:23 bin
dr-xr-xr-x  4 cvmfs cvmfs 4096 Jan 28 09:14 doc
dr-xr-xr-x  3 cvmfs cvmfs 4096 Jan 28 09:27 easybuild
dr-xr-xr-x 53 cvmfs cvmfs 4096 Jan 28 09:24 examples
dr-xr-xr-x 98 cvmfs cvmfs 4096 Jan 28 09:24 include
dr-xr-xr-x  5 cvmfs cvmfs 4096 Jan 28 09:24 lib
lrwxrwxrwx  1 cvmfs cvmfs    3 Jan 28 09:24 lib64 -> lib
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jan 28 09:23 libexec
dr-xr-xr-x 76 cvmfs cvmfs 4096 Jan 28 09:14 mkspecs
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jan 28 09:22 phrasebooks
dr-xr-xr-x 28 cvmfs cvmfs 4096 Jan 28 09:24 plugins
dr-xr-xr-x 25 cvmfs cvmfs 4096 Jan 28 09:24 qml
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jan 28 09:23 resources
dr-xr-xr-x  3 cvmfs cvmfs 4096 Jan 28 09:24 translations

x86_64/amd/zen2/software/Qt5/5.15.7-GCCcore-12.2.0:
total 59
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jan 28 12:27 bin
dr-xr-xr-x  4 cvmfs cvmfs 4096 Jan 28 12:22 doc
dr-xr-xr-x  3 cvmfs cvmfs 4096 Jan 28 12:29 easybuild
dr-xr-xr-x 53 cvmfs cvmfs 4096 Jan 28 12:28 examples
dr-xr-xr-x 98 cvmfs cvmfs 4096 Jan 28 12:28 include
dr-xr-xr-x  5 cvmfs cvmfs 4096 Jan 28 12:28 lib
lrwxrwxrwx  1 cvmfs cvmfs    3 Jan 28 12:28 lib64 -> lib
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jan 28 12:27 libexec
dr-xr-xr-x 76 cvmfs cvmfs 4096 Jan 28 12:22 mkspecs
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jan 28 12:27 phrasebooks
dr-xr-xr-x 28 cvmfs cvmfs 4096 Jan 28 12:28 plugins
dr-xr-xr-x 25 cvmfs cvmfs 4096 Jan 28 12:28 qml
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jan 28 12:27 resources
dr-xr-xr-x  3 cvmfs cvmfs 4096 Jan 28 12:28 translations

x86_64/generic/software/Qt5/5.15.7-GCCcore-12.2.0:
total 59
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jan 28 05:50 bin
dr-xr-xr-x  4 cvmfs cvmfs 4096 Jan 28 05:45 doc
dr-xr-xr-x  3 cvmfs cvmfs 4096 Jan 28 05:52 easybuild
dr-xr-xr-x 53 cvmfs cvmfs 4096 Jan 28 05:51 examples
dr-xr-xr-x 98 cvmfs cvmfs 4096 Jan 28 05:51 include
dr-xr-xr-x  5 cvmfs cvmfs 4096 Jan 28 05:51 lib
lrwxrwxrwx  1 cvmfs cvmfs    3 Jan 28 05:51 lib64 -> lib
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jan 28 05:50 libexec
dr-xr-xr-x 76 cvmfs cvmfs 4096 Jan 28 05:45 mkspecs
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jan 28 05:50 phrasebooks
dr-xr-xr-x 28 cvmfs cvmfs 4096 Jan 28 05:51 plugins
dr-xr-xr-x 25 cvmfs cvmfs 4096 Jan 28 05:51 qml
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jan 28 05:50 resources
dr-xr-xr-x  3 cvmfs cvmfs 4096 Jan 28 05:51 translations

x86_64/intel/broadwell/software/Qt5/5.15.7-GCCcore-12.2.0:
total 59
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jan 28 19:52 bin
dr-xr-xr-x  4 cvmfs cvmfs 4096 Jan 28 19:43 doc
dr-xr-xr-x  3 cvmfs cvmfs 4096 Jan 28 19:55 easybuild
dr-xr-xr-x 53 cvmfs cvmfs 4096 Jan 28 19:53 examples
dr-xr-xr-x 98 cvmfs cvmfs 4096 Jan 28 19:52 include
dr-xr-xr-x  5 cvmfs cvmfs 4096 Jan 28 19:52 lib
lrwxrwxrwx  1 cvmfs cvmfs    3 Jan 28 19:53 lib64 -> lib
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jan 28 19:52 libexec
dr-xr-xr-x 76 cvmfs cvmfs 4096 Jan 28 19:44 mkspecs
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jan 28 19:51 phrasebooks
dr-xr-xr-x 28 cvmfs cvmfs 4096 Jan 28 19:52 plugins
dr-xr-xr-x 25 cvmfs cvmfs 4096 Jan 28 19:52 qml
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jan 28 19:52 resources
dr-xr-xr-x  3 cvmfs cvmfs 4096 Jan 28 19:53 translations

x86_64/intel/skylake_avx512/software/Qt5/5.15.7-GCCcore-12.2.0:
total 59
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jan 28 06:47 bin
dr-xr-xr-x  4 cvmfs cvmfs 4096 Jan 28 06:40 doc
dr-xr-xr-x  3 cvmfs cvmfs 4096 Jan 28 06:50 easybuild
dr-xr-xr-x 53 cvmfs cvmfs 4096 Jan 28 06:48 examples
dr-xr-xr-x 98 cvmfs cvmfs 4096 Jan 28 06:48 include
dr-xr-xr-x  5 cvmfs cvmfs 4096 Jan 28 06:48 lib
lrwxrwxrwx  1 cvmfs cvmfs    3 Jan 28 06:48 lib64 -> lib
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jan 28 06:47 libexec
dr-xr-xr-x 76 cvmfs cvmfs 4096 Jan 28 06:40 mkspecs
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jan 28 06:47 phrasebooks
dr-xr-xr-x 28 cvmfs cvmfs 4096 Jan 28 06:48 plugins
dr-xr-xr-x 25 cvmfs cvmfs 4096 Jan 28 06:48 qml
dr-xr-xr-x  2 cvmfs cvmfs 4096 Jan 28 06:47 resources
dr-xr-xr-x  3 cvmfs cvmfs 4096 Jan 28 06:48 translations

```
</details>

**Review by trz42 — APPROVED** [review]
Great! :100:

**Pull request merged**
