### PR TITLE
{2023.06}[foss/2022a] QuantumESPRESSO V7.1

### PR DESCRIPTION
**Pull request by TopRichard**

### CODE REVIEW

**Comment by TopRichard** [comment]
bot: build inst:AWS repo:nessi.no-2023.06-software arch:x86_64/generic 
bot: build inst:AWS repo:nessi.no-2023.06-software arch:x86_64/intel/cascadelake 
bot: build inst:AWS repo:nessi.no-2023.06-software arch:x86_64/intel/skylake 
bot: build inst:Fram-NESSI repo:nessi.no-2023.06-software arch:x86_64/intel/broadwell
bot: build inst:eX3 repo:nessi.no-2023.06-software arch:zen2
bot: build inst:eX3 repo:nessi.no-2023.06-software arch:aarch64/generic

**Comment by trz42** [comment]
bot: show_config

**Comment by TopRichard** [comment]
bot: build inst:eX3 repo:nessi.no-2023.06-software arch:zen2
bot: build inst:eX3 repo:nessi.no-2023.06-software arch:aarch64/generic

**Comment by TopRichard** [comment]
bot: build inst:eX3 repo:nessi.no-2023.06-software arch:aarch64/generic

**Comment by trz42** [comment]
Needs to be rebuilt because some dependencies were ingested in the meantime.

**Pull request closed without merging**
